
test_root_search: test_root_search.cpp include/ext/root_search.h include/ext/root_search.tcc test_function.h test_function.tcc
	$(HOME)/bin/bin/g++ -std=c++17 -g -Wall -Wextra -Wno-psabi -Iinclude -I../include -I../polynomial/include -I../quadrature/include -I../cxx_fp_utils/include -o test_root_search test_root_search.cpp -lquadmath
