#!/bin/bash

mkdir -f output

../../build/debug/bin/test_anger_weber > output/test_anger_weber.txt
../../build/debug/bin/test_appell_f1 > output/test_appell_f1.txt
../../build/debug/bin/test_bell > output/test_bell.txt
../../build/debug/bin/test_bernoulli > output/test_bernoulli.txt
../../build/debug/bin/test_bessel > output/test_bessel.txt
../../build/debug/bin/test_bessel_asymp > output/test_bessel_asymp.txt
../../build/debug/bin/test_bessel_iter > output/test_bessel_iter.txt
../../build/debug/bin/test_beta > output/test_beta.txt
../../build/debug/bin/test_beta_inc > output/test_beta_inc.txt
../../build/debug/bin/test_binet > output/test_binet.txt
../../build/debug/bin/test_binet_float > output/test_binet_float.txt
../../build/debug/bin/test_bose_einstein > output/test_bose_einstein.txt
../../build/debug/bin/test_charlier > output/test_charlier.txt
../../build/debug/bin/test_chebyshev > output/test_chebyshev.txt
../../build/debug/bin/test_chebyshev_trig > output/test_chebyshev_trig.txt
../../build/debug/bin/test_chebyshev_trig_pi > output/test_chebyshev_trig_pi.txt
../../build/debug/bin/test_clausen > output/test_clausen.txt
../../build/debug/bin/test_cmath > output/test_cmath.txt
../../build/debug/bin/test_comp_ellint_1 > output/test_comp_ellint_1.txt
../../build/debug/bin/test_complex128 > output/test_complex128.txt
../../build/debug/bin/test_complex_gamma > output/test_complex_gamma.txt
../../build/debug/bin/test_conf_hyperg_limit > output/test_conf_hyperg_limit.txt
../../build/debug/bin/test_const > output/test_const.txt
../../build/debug/bin/test_continued_fraction > output/test_continued_fraction.txt
../../build/debug/bin/test_continuous_dual_hahn > output/test_continuous_dual_hahn.txt
../../build/debug/bin/test_continuous_hahn > output/test_continuous_hahn.txt
../../build/debug/bin/test_coulomb > output/test_coulomb.txt
../../build/debug/bin/test_csint > output/test_csint.txt
../../build/debug/bin/test_cyl_hankel > output/test_cyl_hankel.txt
../../build/debug/bin/test_dawson > output/test_dawson.txt
../../build/debug/bin/test_debye > output/test_debye.txt
../../build/debug/bin/test_digamma > output/test_digamma.txt
../../build/debug/bin/test_dilog > output/test_dilog.txt
../../build/debug/bin/test_dirichlet_eta > output/test_dirichlet_eta.txt
../../build/debug/bin/test_dual_hahn > output/test_dual_hahn.txt
../../build/debug/bin/test_erfc > output/test_erfc.txt
../../build/debug/bin/test_experfc > output/test_experfc.txt
../../build/debug/bin/test_expint > output/test_expint.txt
../../build/debug/bin/test_factorial > output/test_factorial.txt
../../build/debug/bin/test_faddeeva > output/test_faddeeva.txt
../../build/debug/bin/test_falling_factorial > output/test_falling_factorial.txt
../../build/debug/bin/test_fermi_dirac > output/test_fermi_dirac.txt
../../build/debug/bin/test_fibonacci > output/test_fibonacci.txt
../../build/debug/bin/test_float128 > output/test_float128.txt
../../build/debug/bin/test_fresnel > output/test_fresnel.txt
../../build/debug/bin/test_gamma > output/test_gamma.txt
../../build/debug/bin/test_gamma_ratio > output/test_gamma_ratio.txt
../../build/debug/bin/test_gamma_reciprocal > output/test_gamma_reciprocal.txt
../../build/debug/bin/test_gegenbauer > output/test_gegenbauer.txt
../../build/debug/bin/test_gudermannian > output/test_gudermannian.txt
../../build/debug/bin/test_hahn > output/test_hahn.txt
../../build/debug/bin/test_hankel > output/test_hankel.txt
../../build/debug/bin/test_hankel_real_arg > output/test_hankel_real_arg.txt
../../build/debug/bin/test_hermite > output/test_hermite.txt
../../build/debug/bin/test_heuman_lambda > output/test_heuman_lambda.txt
../../build/debug/bin/test_hurwitz_zeta > output/test_hurwitz_zeta.txt
../../build/debug/bin/test_hurwitz_zeta_new > output/test_hurwitz_zeta_new.txt
../../build/debug/bin/test_hyperg > output/test_hyperg.txt
../../build/debug/bin/test_hypot > output/test_hypot.txt
../../build/debug/bin/test_inv_erf > output/test_inv_erf.txt
../../build/debug/bin/test_inv_gamma.py*
../../build/debug/bin/test_inv_ibeta > output/test_inv_ibeta.txt
../../build/debug/bin/test_jacobi > output/test_jacobi.txt
../../build/debug/bin/test_jacobi_ellint > output/test_jacobi_ellint.txt
../../build/debug/bin/test_jacobi_inv > output/test_jacobi_inv.txt
../../build/debug/bin/test_jacobi_theta > output/test_jacobi_theta.txt
../../build/debug/bin/test_jacobi_zeta > output/test_jacobi_zeta.txt
../../build/debug/bin/test_kelvin > output/test_kelvin.txt
../../build/debug/bin/test_krawtchouk > output/test_krawtchouk.txt
../../build/debug/bin/test_laguerre > output/test_laguerre.txt
../../build/debug/bin/test_lah > output/test_lah.txt
../../build/debug/bin/test_large_order_bessel > output/test_large_order_bessel.txt
../../build/debug/bin/test_legendre > output/test_legendre.txt
../../build/debug/bin/test_legendre_ellint > output/test_legendre_ellint.txt
../../build/debug/bin/test_lentz_continued_fraction > output/test_lentz_continued_fraction.txt
../../build/debug/bin/test_lerch > output/test_lerch.txt
../../build/debug/bin/test_limits > output/test_limits.txt
../../build/debug/bin/test_little_airy > output/test_little_airy.txt
../../build/debug/bin/test_lobatto > output/test_lobatto.txt
../../build/debug/bin/test_lommel > output/test_lommel.txt
../../build/debug/bin/test_marcum_q > output/test_marcum_q.txt
../../build/debug/bin/test_math_h > output/test_math_h.txt
../../build/debug/bin/test_meixner > output/test_meixner.txt
../../build/debug/bin/test_meixner_pollaczek > output/test_meixner_pollaczek.txt
../../build/debug/bin/test_maxint > output/test_maxint.txt
../../build/debug/bin/test_mittag_leffler > output/test_mittag_leffler.txt
../../build/debug/bin/test_mpreal > output/test_mpreal.txt
../../build/debug/bin/test_notsospecfun > output/test_notsospecfun.txt
../../build/debug/bin/test_nric_bessel > output/test_nric_bessel.txt
../../build/debug/bin/test_numeric_limits > output/test_numeric_limits.txt
../../build/debug/bin/test_owens_t > output/test_owens_t.txt
../../build/debug/bin/test_parab_cyl > output/test_parab_cyl.txt
../../build/debug/bin/test_polygamma > output/test_polygamma.txt
../../build/debug/bin/test_polylog > output/test_polylog.txt
../../build/debug/bin/test_pow_bits > output/test_pow_bits.txt
../../build/debug/bin/test_power_mean > output/test_power_mean.txt
../../build/debug/bin/test_power_norm > output/test_power_norm.txt
../../build/debug/bin/test_racah > output/test_racah.txt
../../build/debug/bin/test_rational > output/test_rational.txt
../../build/debug/bin/test_recursion > output/test_recursion.txt
../../build/debug/bin/test_reperiodized_hyper > output/test_reperiodized_hyper.txt
../../build/debug/bin/test_reperiodized_trig > output/test_reperiodized_trig.txt
../../build/debug/bin/test_riemann_zeta > output/test_riemann_zeta.txt
../../build/debug/bin/test_rising_factorial > output/test_rising_factorial.txt
../../build/debug/bin/test_root_finding > output/test_root_finding.txt
../../build/debug/bin/test_sincos > output/test_sincos.txt
../../build/debug/bin/test_sinus_cardinal > output/test_sinus_cardinal.txt
../../build/debug/bin/test_sph_bessel > output/test_sph_bessel.txt
../../build/debug/bin/test_sph_hankel > output/test_sph_hankel.txt
../../build/debug/bin/test_steed_continued_fraction > output/test_steed_continued_fraction.txt
../../build/debug/bin/test_struve > output/test_struve.txt
../../build/debug/bin/test_struve_old > output/test_struve_old.txt
../../build/debug/bin/test_summation > output/test_summation.txt
../../build/debug/bin/test_theta > output/test_theta.txt
../../build/debug/bin/test_tricomi_u > output/test_tricomi_u.txt
../../build/debug/bin/test_weierstrass_ellint > output/test_weierstrass_ellint.txt
../../build/debug/bin/test_trig > output/test_trig.txt
../../build/debug/bin/test_wilson > output/test_wilson.txt
../../build/debug/bin/test_wright_omega > output/test_wright_omega.txt
../../build/debug/bin/test_zeta_trig > output/test_zeta_trig.txt
