// { dg-do run { target c++11 } }
// { dg-options "-D__STDCPP_WANT_MATH_SPEC_FUNCS__" }
//
// Copyright (C) 2016 Free Software Foundation, Inc.
//
// This file is part of the GNU ISO C++ Library.  This library is free
// software; you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the
// Free Software Foundation; either version 3, or (at your option)
// any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this library; see the file COPYING3.  If not see
// <http://www.gnu.org/licenses/>.

//  comp_ellint_d

//  Compare against values generated by the GNU Scientific Library.
//  The GSL can be found on the web: http://www.gnu.org/software/gsl/
#include <limits>
#include <cmath>
#if defined(__TEST_DEBUG)
#  include <iostream>
#  define VERIFY(A) \
  if (!(A)) \
    { \
      std::cout << "line " << __LINE__ \
	<< "  max_abs_frac = " << max_abs_frac \
	<< std::endl; \
    }
#else
#  include <testsuite_hooks.h>
#endif
#include <specfun_testcase.h>

// Test data.
// max(|f - f_Boost|): 2.2204460492503131e-16
// max(|f - f_Boost| / |f_Boost|): 2.7843193611279334e-16
// mean(f - f_Boost): 9.3492465231592125e-17
// variance(f - f_Boost): 5.1258018532879257e-34
// stddev(f - f_Boost): 2.2640233773722228e-17
const testcase_comp_ellint_d<double>
data001[19] =
{
  { 1.3689531921495754, -0.90000000000000002 },
  { 1.1233638038981610, -0.80000000000000004 },
  { 1.0000670669444245, -0.69999999999999996 },
  { 0.92408446796396748, -0.59999999999999998 },
  { 0.87315258189267553, -0.50000000000000000 },
  { 0.83786408440294280, -0.39999999999999991 },
  { 0.81350172230293061, -0.29999999999999993 },
  { 0.79748253029092386, -0.19999999999999996 },
  { 0.78836194956876615, -0.099999999999999978 },
  { 0.78539816339744828, 0.0000000000000000 },
  { 0.78836194956876615, 0.10000000000000009 },
  { 0.79748253029092386, 0.20000000000000018 },
  { 0.81350172230293072, 0.30000000000000004 },
  { 0.83786408440294291, 0.40000000000000013 },
  { 0.87315258189267553, 0.50000000000000000 },
  { 0.92408446796396759, 0.60000000000000009 },
  { 1.0000670669444247, 0.70000000000000018 },
  { 1.1233638038981610, 0.80000000000000004 },
  { 1.3689531921495759, 0.90000000000000013 },
};
const double toler001 = 2.5000000000000020e-13;

template<typename Ret, unsigned int Num>
  void
  test(const testcase_comp_ellint_d<Ret> (&data)[Num], Ret toler)
  {
    bool test __attribute__((unused)) = true;
    const Ret eps = std::numeric_limits<Ret>::epsilon();
    Ret max_abs_diff = -Ret(1);
    Ret max_abs_frac = -Ret(1);
    unsigned int num_datum = Num;
    for (unsigned int i = 0; i < num_datum; ++i)
      {
	const Ret f = __gnu_cxx::comp_ellint_d(data[i].k);
	const Ret f0 = data[i].f0;
	const Ret diff = f - f0;
	if (std::abs(diff) > max_abs_diff)
	  max_abs_diff = std::abs(diff);
	if (std::abs(f0) > Ret(10) * eps
	 && std::abs(f) > Ret(10) * eps)
	  {
	    const Ret frac = diff / f0;
	    if (std::abs(frac) > max_abs_frac)
	      max_abs_frac = std::abs(frac);
	  }
      }
    VERIFY(max_abs_frac < toler);
  }

int
main()
{
  test(data001, toler001);
  return 0;
}
