
all: \
 amath.o \
 amcmplx.o \
 amtools.o \
 memh.o \
 sfbasic.o \
 sfbessel.o \
 sfellint.o \
 sferf.o \
 sfexpint.o \
 sfgamma2.o \
 sfgamma.o \
 sfhyperg.o \
 sfmisc.o \
 sfpoly.o \
 sfsdist.o \
 sfzeta2.o \
 sfzeta.o \
 specfun.o \
 specfunx.o

amath.o: amath.pas
	fpc amath

amcmplx.o: amcmplx.pas
	fpc amcmplx

amtools.o: amtools.pas
	fpc amtools

memh.o: memh.pas
	fpc memh

sfbasic.o: sfbasic.pas
	fpc sfbasic

sfbessel.o: sfbessel.pas
	fpc sfbessel

sfellint.o: sfellint.pas
	fpc sfellint

sferf.o: sferf.pas
	fpc sferf

sfexpint.o: sfexpint.pas
	fpc sfexpint

sfgamma2.o: sfgamma2.pas
	fpc sfgamma2

sfgamma.o: sfgamma.pas
	fpc sfgamma

sfhyperg.o: sfhyperg.pas
	fpc sfhyperg

sfmisc.o: sfmisc.pas
	fpc sfmisc

sfpoly.o: sfpoly.pas
	fpc sfpoly

sfsdist.o: sfsdist.pas
	fpc sfsdist

sfzeta2.o: sfzeta2.pas
	fpc sfzeta2

sfzeta.o: sfzeta.pas
	fpc sfzeta

specfun.o: specfun.pas
	fpc specfun

specfunx.o: specfunx.pas
	fpc specfunx

