C++ Special Math Functions: GNU Extended Mathematical Special Functions
GNU Extended Mathematical Special Functions
C++ Mathematical Special Functions
Functions
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::airy_ai (_Tp __x)
template<typename _Tp >
std::complex< __gnu_cxx::fp_promote_t< _Tp > > __gnu_cxx::airy_ai (std::complex< _Tp > __x)
float __gnu_cxx::airy_aif (float __x)
long double __gnu_cxx::airy_ail (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::airy_bi (_Tp __x)
template<typename _Tp >
std::complex< __gnu_cxx::fp_promote_t< _Tp > > __gnu_cxx::airy_bi (std::complex< _Tp > __x)
float __gnu_cxx::airy_bif (float __x)
long double __gnu_cxx::airy_bil (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::bernoulli (unsigned int __n)
template<typename _Tp >
_Tp __gnu_cxx::bernoulli (unsigned int __n, _Tp __x)
float __gnu_cxx::bernoullif (unsigned int __n)
long double __gnu_cxx::bernoullil (unsigned int __n)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::binomial (unsigned int __n, unsigned int __k)
Return the binomial coefficient as a real number. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::binomial_p (_Tp __p, unsigned int __n, unsigned int __k)
Return the binomial cumulative distribution function.
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::binomial_pdf (_Tp __p, unsigned int __n, unsigned int __k)
Return the binomial probability mass function.
float __gnu_cxx::binomialf (unsigned int __n, unsigned int __k)
long double __gnu_cxx::binomiall (unsigned int __n, unsigned int __k)
template<typename _Tps , typename _Tp >
__gnu_cxx::fp_promote_t< _Tps, _Tp > __gnu_cxx::bose_einstein (_Tps __s, _Tp __x)
float __gnu_cxx::bose_einsteinf (float __s, float __x)
long double __gnu_cxx::bose_einsteinl (long double __s, long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::chebyshev_t (unsigned int __n, _Tp __x)
float __gnu_cxx::chebyshev_tf (unsigned int __n, float __x)
long double __gnu_cxx::chebyshev_tl (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::chebyshev_u (unsigned int __n, _Tp __x)
float __gnu_cxx::chebyshev_uf (unsigned int __n, float __x)
long double __gnu_cxx::chebyshev_ul (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::chebyshev_v (unsigned int __n, _Tp __x)
float __gnu_cxx::chebyshev_vf (unsigned int __n, float __x)
long double __gnu_cxx::chebyshev_vl (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::chebyshev_w (unsigned int __n, _Tp __x)
float __gnu_cxx::chebyshev_wf (unsigned int __n, float __x)
long double __gnu_cxx::chebyshev_wl (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::clausen (unsigned int __m, _Tp __x)
template<typename _Tp >
std::complex< __gnu_cxx::fp_promote_t< _Tp > > __gnu_cxx::clausen (unsigned int __m, std::complex< _Tp > __z)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::clausen_cl (unsigned int __m, _Tp __x)
float __gnu_cxx::clausen_clf (unsigned int __m, float __x)
long double __gnu_cxx::clausen_cll (unsigned int __m, long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::clausen_sl (unsigned int __m, _Tp __x)
float __gnu_cxx::clausen_slf (unsigned int __m, float __x)
long double __gnu_cxx::clausen_sll (unsigned int __m, long double __x)
float __gnu_cxx::clausenf (unsigned int __m, float __x)
std::complex< float > __gnu_cxx::clausenf (unsigned int __m, std::complex< float > __z)
long double __gnu_cxx::clausenl (unsigned int __m, long double __x)
std::complex< long double > __gnu_cxx::clausenl (unsigned int __m, std::complex< long double > __z)
template<typename _Tk >
__gnu_cxx::fp_promote_t< _Tk > __gnu_cxx::comp_ellint_d (_Tk __k)
float __gnu_cxx::comp_ellint_df (float __k)
long double __gnu_cxx::comp_ellint_dl (long double __k)
float __gnu_cxx::comp_ellint_rf (float __x, float __y)
long double __gnu_cxx::comp_ellint_rf (long double __x, long double __y)
template<typename _Tx , typename _Ty >
__gnu_cxx::fp_promote_t< _Tx, _Ty > __gnu_cxx::comp_ellint_rf (_Tx __x, _Ty __y)
float __gnu_cxx::comp_ellint_rg (float __x, float __y)
long double __gnu_cxx::comp_ellint_rg (long double __x, long double __y)
template<typename _Tx , typename _Ty >
__gnu_cxx::fp_promote_t< _Tx, _Ty > __gnu_cxx::comp_ellint_rg (_Tx __x, _Ty __y)
template<typename _Tpa , typename _Tpc , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpa, _Tpc, _Tp > __gnu_cxx::conf_hyperg (_Tpa __a, _Tpc __c, _Tp __x)
template<typename _Tpc , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpc, _Tp > __gnu_cxx::conf_hyperg_lim (_Tpc __c, _Tp __x)
float __gnu_cxx::conf_hyperg_limf (float __c, float __x)
long double __gnu_cxx::conf_hyperg_liml (long double __c, long double __x)
float __gnu_cxx::conf_hypergf (float __a, float __c, float __x)
long double __gnu_cxx::conf_hypergl (long double __a, long double __c, long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::cos_pi (_Tp __x)
float __gnu_cxx::cos_pif (float __x)
long double __gnu_cxx::cos_pil (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::cosh_pi (_Tp __x)
float __gnu_cxx::cosh_pif (float __x)
long double __gnu_cxx::cosh_pil (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::coshint (_Tp __x)
float __gnu_cxx::coshintf (float __x)
long double __gnu_cxx::coshintl (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::cosint (_Tp __x)
float __gnu_cxx::cosintf (float __x)
long double __gnu_cxx::cosintl (long double __x)
template<typename _Tpnu , typename _Tp >
std::complex< __gnu_cxx::fp_promote_t< _Tpnu, _Tp > > __gnu_cxx::cyl_hankel_1 (_Tpnu __nu, _Tp __z)
template<typename _Tpnu , typename _Tp >
std::complex< __gnu_cxx::fp_promote_t< _Tpnu, _Tp > > __gnu_cxx::cyl_hankel_1 (std::complex< _Tpnu > __nu, std::complex< _Tp > __x)
std::complex< float > __gnu_cxx::cyl_hankel_1f (float __nu, float __z)
std::complex< float > __gnu_cxx::cyl_hankel_1f (std::complex< float > __nu, std::complex< float > __x)
std::complex< long double > __gnu_cxx::cyl_hankel_1l (long double __nu, long double __z)
std::complex< long double > __gnu_cxx::cyl_hankel_1l (std::complex< long double > __nu, std::complex< long double > __x)
template<typename _Tpnu , typename _Tp >
std::complex< __gnu_cxx::fp_promote_t< _Tpnu, _Tp > > __gnu_cxx::cyl_hankel_2 (_Tpnu __nu, _Tp __z)
template<typename _Tpnu , typename _Tp >
std::complex< __gnu_cxx::fp_promote_t< _Tpnu, _Tp > > __gnu_cxx::cyl_hankel_2 (std::complex< _Tpnu > __nu, std::complex< _Tp > __x)
std::complex< float > __gnu_cxx::cyl_hankel_2f (float __nu, float __z)
std::complex< float > __gnu_cxx::cyl_hankel_2f (std::complex< float > __nu, std::complex< float > __x)
std::complex< long double > __gnu_cxx::cyl_hankel_2l (long double __nu, long double __z)
std::complex< long double > __gnu_cxx::cyl_hankel_2l (std::complex< long double > __nu, std::complex< long double > __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::dawson (_Tp __x)
float __gnu_cxx::dawsonf (float __x)
long double __gnu_cxx::dawsonl (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::debye (unsigned int __n, _Tp __x)
float __gnu_cxx::debyef (unsigned int __n, float __x)
long double __gnu_cxx::debyel (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::digamma (_Tp __x)
float __gnu_cxx::digammaf (float __x)
long double __gnu_cxx::digammal (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::dilog (_Tp __x)
float __gnu_cxx::dilogf (float __x)
long double __gnu_cxx::dilogl (long double __x)
template<typename _Tp >
_Tp __gnu_cxx::dirichlet_beta (_Tp __s)
float __gnu_cxx::dirichlet_betaf (float __s)
long double __gnu_cxx::dirichlet_betal (long double __s)
template<typename _Tp >
_Tp __gnu_cxx::dirichlet_eta (_Tp __s)
float __gnu_cxx::dirichlet_etaf (float __s)
long double __gnu_cxx::dirichlet_etal (long double __s)
template<typename _Tp >
_Tp __gnu_cxx::dirichlet_lambda (_Tp __s)
float __gnu_cxx::dirichlet_lambdaf (float __s)
long double __gnu_cxx::dirichlet_lambdal (long double __s)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::double_factorial (int __n)
Return the double factorial of the argument as a real number.
for even and
for odd .
float __gnu_cxx::double_factorialf (int __n)
long double __gnu_cxx::double_factoriall (int __n)
template<typename _Tk , typename _Tp , typename _Ta , typename _Tb >
__gnu_cxx::fp_promote_t< _Tk, _Tp, _Ta, _Tb > __gnu_cxx::ellint_cel (_Tk __k_c, _Tp __p, _Ta __a, _Tb __b)
float __gnu_cxx::ellint_celf (float __k_c, float __p, float __a, float __b)
long double __gnu_cxx::ellint_cell (long double __k_c, long double __p, long double __a, long double __b)
template<typename _Tk , typename _Tphi >
__gnu_cxx::fp_promote_t< _Tk, _Tphi > __gnu_cxx::ellint_d (_Tk __k, _Tphi __phi)
float __gnu_cxx::ellint_df (float __k, float __phi)
long double __gnu_cxx::ellint_dl (long double __k, long double __phi)
template<typename _Tp , typename _Tk >
__gnu_cxx::fp_promote_t< _Tp, _Tk > __gnu_cxx::ellint_el1 (_Tp __x, _Tk __k_c)
float __gnu_cxx::ellint_el1f (float __x, float __k_c)
long double __gnu_cxx::ellint_el1l (long double __x, long double __k_c)
template<typename _Tp , typename _Tk , typename _Ta , typename _Tb >
__gnu_cxx::fp_promote_t< _Tp, _Tk, _Ta, _Tb > __gnu_cxx::ellint_el2 (_Tp __x, _Tk __k_c, _Ta __a, _Tb __b)
float __gnu_cxx::ellint_el2f (float __x, float __k_c, float __a, float __b)
long double __gnu_cxx::ellint_el2l (long double __x, long double __k_c, long double __a, long double __b)
template<typename _Tx , typename _Tk , typename _Tp >
__gnu_cxx::fp_promote_t< _Tx, _Tk, _Tp > __gnu_cxx::ellint_el3 (_Tx __x, _Tk __k_c, _Tp __p)
float __gnu_cxx::ellint_el3f (float __x, float __k_c, float __p)
long double __gnu_cxx::ellint_el3l (long double __x, long double __k_c, long double __p)
template<typename _Tp , typename _Up >
__gnu_cxx::fp_promote_t< _Tp, _Up > __gnu_cxx::ellint_rc (_Tp __x, _Up __y)
float __gnu_cxx::ellint_rcf (float __x, float __y)
long double __gnu_cxx::ellint_rcl (long double __x, long double __y)
template<typename _Tp , typename _Up , typename _Vp >
__gnu_cxx::fp_promote_t< _Tp, _Up, _Vp > __gnu_cxx::ellint_rd (_Tp __x, _Up __y, _Vp __z)
float __gnu_cxx::ellint_rdf (float __x, float __y, float __z)
long double __gnu_cxx::ellint_rdl (long double __x, long double __y, long double __z)
template<typename _Tp , typename _Up , typename _Vp >
__gnu_cxx::fp_promote_t< _Tp, _Up, _Vp > __gnu_cxx::ellint_rf (_Tp __x, _Up __y, _Vp __z)
float __gnu_cxx::ellint_rff (float __x, float __y, float __z)
long double __gnu_cxx::ellint_rfl (long double __x, long double __y, long double __z)
template<typename _Tp , typename _Up , typename _Vp >
__gnu_cxx::fp_promote_t< _Tp, _Up, _Vp > __gnu_cxx::ellint_rg (_Tp __x, _Up __y, _Vp __z)
float __gnu_cxx::ellint_rgf (float __x, float __y, float __z)
long double __gnu_cxx::ellint_rgl (long double __x, long double __y, long double __z)
template<typename _Tp , typename _Up , typename _Vp , typename _Wp >
__gnu_cxx::fp_promote_t< _Tp, _Up, _Vp, _Wp > __gnu_cxx::ellint_rj (_Tp __x, _Up __y, _Vp __z, _Wp __p)
float __gnu_cxx::ellint_rjf (float __x, float __y, float __z, float __p)
long double __gnu_cxx::ellint_rjl (long double __x, long double __y, long double __z, long double __p)
template<typename _Tp >
_Tp __gnu_cxx::ellnome (_Tp __k)
float __gnu_cxx::ellnomef (float __k)
long double __gnu_cxx::ellnomel (long double __k)
template<typename _Tp >
_Tp __gnu_cxx::euler (unsigned int __n)
This returns Euler number .
template<typename _Tp >
_Tp __gnu_cxx::eulerian_1 (unsigned int __n, unsigned int __m)
template<typename _Tp >
_Tp __gnu_cxx::eulerian_2 (unsigned int __n, unsigned int __m)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::expint (unsigned int __n, _Tp __x)
float __gnu_cxx::expintf (unsigned int __n, float __x)
long double __gnu_cxx::expintl (unsigned int __n, long double __x)
template<typename _Tlam , typename _Tp >
__gnu_cxx::fp_promote_t< _Tlam, _Tp > __gnu_cxx::exponential_p (_Tlam __lambda, _Tp __x)
Return the exponential cumulative probability density function.
template<typename _Tlam , typename _Tp >
__gnu_cxx::fp_promote_t< _Tlam, _Tp > __gnu_cxx::exponential_pdf (_Tlam __lambda, _Tp __x)
Return the exponential probability density function.
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::factorial (unsigned int __n)
Return the factorial of the argument as a real number.
.
float __gnu_cxx::factorialf (unsigned int __n)
long double __gnu_cxx::factoriall (unsigned int __n)
template<typename _Tp , typename _Tnu >
__gnu_cxx::fp_promote_t< _Tp, _Tnu > __gnu_cxx::falling_factorial (_Tp __a, _Tnu __nu)
Return the falling factorial function or the lower Pochhammer symbol for real argument and integral order . The falling factorial function is defined by
In particular, .
float __gnu_cxx::falling_factorialf (float __a, float __nu)
long double __gnu_cxx::falling_factoriall (long double __a, long double __nu)
template<typename _Tps , typename _Tp >
__gnu_cxx::fp_promote_t< _Tps, _Tp > __gnu_cxx::fermi_dirac (_Tps __s, _Tp __x)
float __gnu_cxx::fermi_diracf (float __s, float __x)
long double __gnu_cxx::fermi_diracl (long double __s, long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::fisher_f_p (_Tp __F, unsigned int __nu1, unsigned int __nu2)
Return the F-distribution propability function. This returns the probability that the observed chi-square for a correct model exceeds the value .
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::fisher_f_pdf (_Tp __F, unsigned int __nu1, unsigned int __nu2)
Return the F-distribution propability function. This returns the probability that the observed chi-square for a correct model exceeds the value .
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::fresnel_c (_Tp __x)
float __gnu_cxx::fresnel_cf (float __x)
long double __gnu_cxx::fresnel_cl (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::fresnel_s (_Tp __x)
float __gnu_cxx::fresnel_sf (float __x)
long double __gnu_cxx::fresnel_sl (long double __x)
template<typename _Ta , typename _Tp >
__gnu_cxx::fp_promote_t< _Ta, _Tp > __gnu_cxx::gamma_p (_Ta __a, _Tp __x)
Return the gamma cumulative propability distribution function or the regularized lower incomplete gamma function.
template<typename _Ta , typename _Tb , typename _Tp >
__gnu_cxx::fp_promote_t< _Ta, _Tb, _Tp > __gnu_cxx::gamma_pdf (_Ta __alpha, _Tb __beta, _Tp __x)
Return the gamma propability distribution function.
float __gnu_cxx::gamma_pf (float __a, float __x)
long double __gnu_cxx::gamma_pl (long double __a, long double __x)
template<typename _Ta , typename _Tp >
__gnu_cxx::fp_promote_t< _Ta, _Tp > __gnu_cxx::gamma_q (_Ta __a, _Tp __x)
Return the gamma complementary cumulative propability distribution (or survival) function or the regularized upper incomplete gamma function.
float __gnu_cxx::gamma_qf (float __a, float __x)
long double __gnu_cxx::gamma_ql (long double __a, long double __x)
template<typename _Ta >
__gnu_cxx::fp_promote_t< _Ta > __gnu_cxx::gamma_reciprocal (_Ta __a)
float __gnu_cxx::gamma_reciprocalf (float __a)
long double __gnu_cxx::gamma_reciprocall (long double __a)
template<typename _Tlam , typename _Tp >
__gnu_cxx::fp_promote_t< _Tlam, _Tp > __gnu_cxx::gegenbauer (unsigned int __n, _Tlam __lambda, _Tp __x)
float __gnu_cxx::gegenbauerf (unsigned int __n, float __lambda, float __x)
long double __gnu_cxx::gegenbauerl (unsigned int __n, long double __lambda, long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::harmonic (unsigned int __n)
template<typename _Tk , typename _Tphi >
__gnu_cxx::fp_promote_t< _Tk, _Tphi > __gnu_cxx::heuman_lambda (_Tk __k, _Tphi __phi)
float __gnu_cxx::heuman_lambdaf (float __k, float __phi)
long double __gnu_cxx::heuman_lambdal (long double __k, long double __phi)
template<typename _Tp , typename _Up >
__gnu_cxx::fp_promote_t< _Tp, _Up > __gnu_cxx::hurwitz_zeta (_Tp __s, _Up __a)
template<typename _Tp , typename _Up >
std::complex< _Tp > __gnu_cxx::hurwitz_zeta (_Tp __s, std::complex< _Up > __a)
float __gnu_cxx::hurwitz_zetaf (float __s, float __a)
long double __gnu_cxx::hurwitz_zetal (long double __s, long double __a)
template<typename _Tpa , typename _Tpb , typename _Tpc , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpa, _Tpb, _Tpc, _Tp > __gnu_cxx::hyperg (_Tpa __a, _Tpb __b, _Tpc __c, _Tp __x)
float __gnu_cxx::hypergf (float __a, float __b, float __c, float __x)
long double __gnu_cxx::hypergl (long double __a, long double __b, long double __c, long double __x)
template<typename _Ta , typename _Tb , typename _Tp >
__gnu_cxx::fp_promote_t< _Ta, _Tb, _Tp > __gnu_cxx::ibeta (_Ta __a, _Tb __b, _Tp __x)
template<typename _Ta , typename _Tb , typename _Tp >
__gnu_cxx::fp_promote_t< _Ta, _Tb, _Tp > __gnu_cxx::ibetac (_Ta __a, _Tb __b, _Tp __x)
float __gnu_cxx::ibetacf (float __a, float __b, float __x)
long double __gnu_cxx::ibetacl (long double __a, long double __b, long double __x)
float __gnu_cxx::ibetaf (float __a, float __b, float __x)
long double __gnu_cxx::ibetal (long double __a, long double __b, long double __x)
template<typename _Talpha , typename _Tbeta , typename _Tp >
__gnu_cxx::fp_promote_t< _Talpha, _Tbeta, _Tp > __gnu_cxx::jacobi (unsigned __n, _Talpha __alpha, _Tbeta __beta, _Tp __x)
template<typename _Kp , typename _Up >
__gnu_cxx::fp_promote_t< _Kp, _Up > __gnu_cxx::jacobi_cn (_Kp __k, _Up __u)
float __gnu_cxx::jacobi_cnf (float __k, float __u)
long double __gnu_cxx::jacobi_cnl (long double __k, long double __u)
template<typename _Kp , typename _Up >
__gnu_cxx::fp_promote_t< _Kp, _Up > __gnu_cxx::jacobi_dn (_Kp __k, _Up __u)
float __gnu_cxx::jacobi_dnf (float __k, float __u)
long double __gnu_cxx::jacobi_dnl (long double __k, long double __u)
template<typename _Kp , typename _Up >
__gnu_cxx::fp_promote_t< _Kp, _Up > __gnu_cxx::jacobi_sn (_Kp __k, _Up __u)
float __gnu_cxx::jacobi_snf (float __k, float __u)
long double __gnu_cxx::jacobi_snl (long double __k, long double __u)
template<typename _Tpq , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpq, _Tp > __gnu_cxx::jacobi_theta_1 (_Tpq __q, _Tp __x)
float __gnu_cxx::jacobi_theta_1f (float __q, float __x)
long double __gnu_cxx::jacobi_theta_1l (long double __q, long double __x)
template<typename _Tpq , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpq, _Tp > __gnu_cxx::jacobi_theta_2 (_Tpq __q, _Tp __x)
float __gnu_cxx::jacobi_theta_2f (float __q, float __x)
long double __gnu_cxx::jacobi_theta_2l (long double __q, long double __x)
template<typename _Tpq , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpq, _Tp > __gnu_cxx::jacobi_theta_3 (_Tpq __q, _Tp __x)
float __gnu_cxx::jacobi_theta_3f (float __q, float __x)
long double __gnu_cxx::jacobi_theta_3l (long double __q, long double __x)
template<typename _Tpq , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpq, _Tp > __gnu_cxx::jacobi_theta_4 (_Tpq __q, _Tp __x)
float __gnu_cxx::jacobi_theta_4f (float __q, float __x)
long double __gnu_cxx::jacobi_theta_4l (long double __q, long double __x)
template<typename _Tk , typename _Tphi >
__gnu_cxx::fp_promote_t< _Tk, _Tphi > __gnu_cxx::jacobi_zeta (_Tk __k, _Tphi __phi)
float __gnu_cxx::jacobi_zetaf (float __k, float __phi)
long double __gnu_cxx::jacobi_zetal (long double __k, long double __phi)
float __gnu_cxx::jacobif (unsigned __n, float __alpha, float __beta, float __x)
long double __gnu_cxx::jacobil (unsigned __n, long double __alpha, long double __beta, long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::lbinomial (unsigned int __n, unsigned int __k)
Return the logarithm of the binomial coefficient as a real number. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
float __gnu_cxx::lbinomialf (unsigned int __n, unsigned int __k)
long double __gnu_cxx::lbinomiall (unsigned int __n, unsigned int __k)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::ldouble_factorial (int __n)
Return the logarithm of the double factorial of the argument as a real number.
for even and
for odd .
float __gnu_cxx::ldouble_factorialf (int __n)
long double __gnu_cxx::ldouble_factoriall (int __n)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::legendre_q (unsigned int __l, _Tp __x)
float __gnu_cxx::legendre_qf (unsigned int __l, float __x)
long double __gnu_cxx::legendre_ql (unsigned int __l, long double __x)
template<typename _Tp , typename _Ts , typename _Ta >
__gnu_cxx::fp_promote_t< _Tp, _Ts, _Ta > __gnu_cxx::lerch_phi (_Tp __z, _Ts __s, _Ta __a)
float __gnu_cxx::lerch_phif (float __z, float __s, float __a)
long double __gnu_cxx::lerch_phil (long double __z, long double __s, long double __a)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::lfactorial (unsigned int __n)
Return the logarithm of the factorial of the argument as a real number.
.
float __gnu_cxx::lfactorialf (unsigned int __n)
long double __gnu_cxx::lfactoriall (unsigned int __n)
template<typename _Tp , typename _Tnu >
__gnu_cxx::fp_promote_t< _Tp, _Tnu > __gnu_cxx::lfalling_factorial (_Tp __a, _Tnu __nu)
Return the logarithm of the falling factorial function or the lower Pochhammer symbol. The falling factorial function is defined by
In particular, . Thus this function returns
Many notations exist for this function: ,
, and others.
float __gnu_cxx::lfalling_factorialf (float __a, float __nu)
long double __gnu_cxx::lfalling_factoriall (long double __a, long double __nu)
template<typename _Ta >
__gnu_cxx::fp_promote_t< _Ta > __gnu_cxx::lgamma (_Ta __a)
template<typename _Ta >
std::complex< __gnu_cxx::fp_promote_t< _Ta > > __gnu_cxx::lgamma (std::complex< _Ta > __a)
float __gnu_cxx::lgammaf (float __a)
std::complex< float > __gnu_cxx::lgammaf (std::complex< float > __a)
long double __gnu_cxx::lgammal (long double __a)
std::complex< long double > __gnu_cxx::lgammal (std::complex< long double > __a)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::logint (_Tp __x)
float __gnu_cxx::logintf (float __x)
long double __gnu_cxx::logintl (long double __x)
template<typename _Ta , typename _Tb , typename _Tp >
__gnu_cxx::fp_promote_t< _Ta, _Tb, _Tp > __gnu_cxx::logistic_p (_Ta __a, _Tb __b, _Tp __x)
Return the logistic cumulative distribution function.
template<typename _Ta , typename _Tb , typename _Tp >
__gnu_cxx::fp_promote_t< _Ta, _Tb, _Tp > __gnu_cxx::logistic_pdf (_Ta __a, _Tb __b, _Tp __x)
Return the logistic probability density function.
template<typename _Tmu , typename _Tsig , typename _Tp >
__gnu_cxx::fp_promote_t< _Tmu, _Tsig, _Tp > __gnu_cxx::lognormal_p (_Tmu __mu, _Tsig __sigma, _Tp __x)
Return the lognormal cumulative probability density function.
template<typename _Tmu , typename _Tsig , typename _Tp >
__gnu_cxx::fp_promote_t< _Tmu, _Tsig, _Tp > __gnu_cxx::lognormal_pdf (_Tmu __mu, _Tsig __sigma, _Tp __x)
Return the lognormal probability density function.
template<typename _Tp , typename _Tnu >
__gnu_cxx::fp_promote_t< _Tp, _Tnu > __gnu_cxx::lrising_factorial (_Tp __a, _Tnu __nu)
Return the logarithm of the rising factorial function or the (upper) Pochhammer symbol. The rising factorial function is defined for integer order by
Thus this function returns
Many notations exist for this function: (especially in the literature of special functions),
, and others.
float __gnu_cxx::lrising_factorialf (float __a, float __nu)
long double __gnu_cxx::lrising_factoriall (long double __a, long double __nu)
template<typename _Tmu , typename _Tsig , typename _Tp >
__gnu_cxx::fp_promote_t< _Tmu, _Tsig, _Tp > __gnu_cxx::normal_p (_Tmu __mu, _Tsig __sigma, _Tp __x)
Return the normal cumulative probability density function.
template<typename _Tmu , typename _Tsig , typename _Tp >
__gnu_cxx::fp_promote_t< _Tmu, _Tsig, _Tp > __gnu_cxx::normal_pdf (_Tmu __mu, _Tsig __sigma, _Tp __x)
Return the gamma cumulative propability distribution function.
template<typename _Tph , typename _Tpa >
__gnu_cxx::fp_promote_t< _Tph, _Tpa > __gnu_cxx::owens_t (_Tph __h, _Tpa __a)
float __gnu_cxx::owens_tf (float __h, float __a)
long double __gnu_cxx::owens_tl (long double __h, long double __a)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::polygamma (unsigned int __m, _Tp __x)
float __gnu_cxx::polygammaf (unsigned int __m, float __x)
long double __gnu_cxx::polygammal (unsigned int __m, long double __x)
template<typename _Tp , typename _Wp >
__gnu_cxx::fp_promote_t< _Tp, _Wp > __gnu_cxx::polylog (_Tp __s, _Wp __w)
template<typename _Tp , typename _Wp >
std::complex< __gnu_cxx::fp_promote_t< _Tp, _Wp > > __gnu_cxx::polylog (_Tp __s, std::complex< _Tp > __w)
float __gnu_cxx::polylogf (float __s, float __w)
std::complex< float > __gnu_cxx::polylogf (float __s, std::complex< float > __w)
long double __gnu_cxx::polylogl (long double __s, long double __w)
std::complex< long double > __gnu_cxx::polylogl (long double __s, std::complex< long double > __w)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::radpoly (unsigned int __n, unsigned int __m, _Tp __rho)
float __gnu_cxx::radpolyf (unsigned int __n, unsigned int __m, float __rho)
long double __gnu_cxx::radpolyl (unsigned int __n, unsigned int __m, long double __rho)
template<typename _Tp , typename _Tnu >
__gnu_cxx::fp_promote_t< _Tp, _Tnu > __gnu_cxx::rising_factorial (_Tp __a, _Tnu __nu)
Return the rising factorial function or the (upper) Pochhammer function. The rising factorial function is defined by
Many notations exist for this function: , (especially in the literature of special functions),
, and others.
float __gnu_cxx::rising_factorialf (float __a, float __nu)
long double __gnu_cxx::rising_factoriall (long double __a, long double __nu)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::sin_pi (_Tp __x)
float __gnu_cxx::sin_pif (float __x)
long double __gnu_cxx::sin_pil (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::sinc (_Tp __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::sinc_pi (_Tp __x)
float __gnu_cxx::sinc_pif (float __x)
long double __gnu_cxx::sinc_pil (long double __x)
float __gnu_cxx::sincf (float __x)
long double __gnu_cxx::sincl (long double __x)
__gnu_cxx::__sincos_t< double > __gnu_cxx::sincos (double __x)
template<typename _Tp >
__gnu_cxx::__sincos_t< __gnu_cxx::fp_promote_t< _Tp > > __gnu_cxx::sincos (_Tp __x)
template<typename _Tp >
__gnu_cxx::__sincos_t< __gnu_cxx::fp_promote_t< _Tp > > __gnu_cxx::sincos_pi (_Tp __x)
__gnu_cxx::__sincos_t< float > __gnu_cxx::sincos_pif (float __x)
__gnu_cxx::__sincos_t< long double > __gnu_cxx::sincos_pil (long double __x)
__gnu_cxx::__sincos_t< float > __gnu_cxx::sincosf (float __x)
__gnu_cxx::__sincos_t< long double > __gnu_cxx::sincosl (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::sinh_pi (_Tp __x)
float __gnu_cxx::sinh_pif (float __x)
long double __gnu_cxx::sinh_pil (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::sinhc (_Tp __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::sinhc_pi (_Tp __x)
float __gnu_cxx::sinhc_pif (float __x)
long double __gnu_cxx::sinhc_pil (long double __x)
float __gnu_cxx::sinhcf (float __x)
long double __gnu_cxx::sinhcl (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::sinhint (_Tp __x)
float __gnu_cxx::sinhintf (float __x)
long double __gnu_cxx::sinhintl (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::sinint (_Tp __x)
float __gnu_cxx::sinintf (float __x)
long double __gnu_cxx::sinintl (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::sph_bessel_i (unsigned int __n, _Tp __x)
float __gnu_cxx::sph_bessel_if (unsigned int __n, float __x)
long double __gnu_cxx::sph_bessel_il (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::sph_bessel_k (unsigned int __n, _Tp __x)
float __gnu_cxx::sph_bessel_kf (unsigned int __n, float __x)
long double __gnu_cxx::sph_bessel_kl (unsigned int __n, long double __x)
template<typename _Tp >
std::complex< __gnu_cxx::fp_promote_t< _Tp > > __gnu_cxx::sph_hankel_1 (unsigned int __n, _Tp __z)
template<typename _Tp >
std::complex< __gnu_cxx::fp_promote_t< _Tp > > __gnu_cxx::sph_hankel_1 (unsigned int __n, std::complex< _Tp > __x)
std::complex< float > __gnu_cxx::sph_hankel_1f (unsigned int __n, float __z)
std::complex< float > __gnu_cxx::sph_hankel_1f (unsigned int __n, std::complex< float > __x)
std::complex< long double > __gnu_cxx::sph_hankel_1l (unsigned int __n, long double __z)
std::complex< long double > __gnu_cxx::sph_hankel_1l (unsigned int __n, std::complex< long double > __x)
template<typename _Tp >
std::complex< __gnu_cxx::fp_promote_t< _Tp > > __gnu_cxx::sph_hankel_2 (unsigned int __n, _Tp __z)
template<typename _Tp >
std::complex< __gnu_cxx::fp_promote_t< _Tp > > __gnu_cxx::sph_hankel_2 (unsigned int __n, std::complex< _Tp > __x)
std::complex< float > __gnu_cxx::sph_hankel_2f (unsigned int __n, float __z)
std::complex< float > __gnu_cxx::sph_hankel_2f (unsigned int __n, std::complex< float > __x)
std::complex< long double > __gnu_cxx::sph_hankel_2l (unsigned int __n, long double __z)
std::complex< long double > __gnu_cxx::sph_hankel_2l (unsigned int __n, std::complex< long double > __x)
template<typename _Ttheta , typename _Tphi >
std::complex< __gnu_cxx::fp_promote_t< _Ttheta, _Tphi > > __gnu_cxx::sph_harmonic (unsigned int __l, int __m, _Ttheta __theta, _Tphi __phi)
std::complex< float > __gnu_cxx::sph_harmonicf (unsigned int __l, int __m, float __theta, float __phi)
std::complex< long double > __gnu_cxx::sph_harmonicl (unsigned int __l, int __m, long double __theta, long double __phi)
template<typename _Tp >
_Tp __gnu_cxx::stirling_1 (unsigned int __n, unsigned int __m)
template<typename _Tp >
_Tp __gnu_cxx::stirling_2 (unsigned int __n, unsigned int __m)
template<typename _Tt , typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::student_t_p (_Tt __t, unsigned int __nu)
Return the Students T probability function.
template<typename _Tt , typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::student_t_pdf (_Tt __t, unsigned int __nu)
Return the complement of the Students T probability function.
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::tan_pi (_Tp __x)
float __gnu_cxx::tan_pif (float __x)
long double __gnu_cxx::tan_pil (long double __x)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __gnu_cxx::tanh_pi (_Tp __x)
float __gnu_cxx::tanh_pif (float __x)
long double __gnu_cxx::tanh_pil (long double __x)
template<typename _Ta >
__gnu_cxx::fp_promote_t< _Ta > __gnu_cxx::tgamma (_Ta __a)
template<typename _Ta >
std::complex< __gnu_cxx::fp_promote_t< _Ta > > __gnu_cxx::tgamma (std::complex< _Ta > __a)
template<typename _Ta , typename _Tp >
__gnu_cxx::fp_promote_t< _Ta, _Tp > __gnu_cxx::tgamma (_Ta __a, _Tp __x)
template<typename _Ta , typename _Tp >
__gnu_cxx::fp_promote_t< _Ta, _Tp > __gnu_cxx::tgamma_lower (_Ta __a, _Tp __x)
float __gnu_cxx::tgamma_lowerf (float __a, float __x)
long double __gnu_cxx::tgamma_lowerl (long double __a, long double __x)
float __gnu_cxx::tgammaf (float __a)
std::complex< float > __gnu_cxx::tgammaf (std::complex< float > __a)
float __gnu_cxx::tgammaf (float __a, float __x)
long double __gnu_cxx::tgammal (long double __a)
std::complex< long double > __gnu_cxx::tgammal (std::complex< long double > __a)
long double __gnu_cxx::tgammal (long double __a, long double __x)
template<typename _Tpnu , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpnu, _Tp > __gnu_cxx::theta_1 (_Tpnu __nu, _Tp __x)
float __gnu_cxx::theta_1f (float __nu, float __x)
long double __gnu_cxx::theta_1l (long double __nu, long double __x)
template<typename _Tpnu , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpnu, _Tp > __gnu_cxx::theta_2 (_Tpnu __nu, _Tp __x)
float __gnu_cxx::theta_2f (float __nu, float __x)
long double __gnu_cxx::theta_2l (long double __nu, long double __x)
template<typename _Tpnu , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpnu, _Tp > __gnu_cxx::theta_3 (_Tpnu __nu, _Tp __x)
float __gnu_cxx::theta_3f (float __nu, float __x)
long double __gnu_cxx::theta_3l (long double __nu, long double __x)
template<typename _Tpnu , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpnu, _Tp > __gnu_cxx::theta_4 (_Tpnu __nu, _Tp __x)
float __gnu_cxx::theta_4f (float __nu, float __x)
long double __gnu_cxx::theta_4l (long double __nu, long double __x)
template<typename _Tpk , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpk, _Tp > __gnu_cxx::theta_c (_Tpk __k, _Tp __x)
float __gnu_cxx::theta_cf (float __k, float __x)
long double __gnu_cxx::theta_cl (long double __k, long double __x)
template<typename _Tpk , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpk, _Tp > __gnu_cxx::theta_d (_Tpk __k, _Tp __x)
float __gnu_cxx::theta_df (float __k, float __x)
long double __gnu_cxx::theta_dl (long double __k, long double __x)
template<typename _Tpk , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpk, _Tp > __gnu_cxx::theta_n (_Tpk __k, _Tp __x)
float __gnu_cxx::theta_nf (float __k, float __x)
long double __gnu_cxx::theta_nl (long double __k, long double __x)
template<typename _Tpk , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpk, _Tp > __gnu_cxx::theta_s (_Tpk __k, _Tp __x)
float __gnu_cxx::theta_sf (float __k, float __x)
long double __gnu_cxx::theta_sl (long double __k, long double __x)
template<typename _Tpa , typename _Tpc , typename _Tp >
__gnu_cxx::fp_promote_t< _Tpa, _Tpc, _Tp > __gnu_cxx::tricomi_u (_Tpa __a, _Tpc __c, _Tp __x)
float __gnu_cxx::tricomi_uf (float __a, float __c, float __x)
long double __gnu_cxx::tricomi_ul (long double __a, long double __c, long double __x)
template<typename _Ta , typename _Tb , typename _Tp >
__gnu_cxx::fp_promote_t< _Ta, _Tb, _Tp > __gnu_cxx::weibull_p (_Ta __a, _Tb __b, _Tp __x)
Return the Weibull cumulative probability density function.
template<typename _Ta , typename _Tb , typename _Tp >
__gnu_cxx::fp_promote_t< _Ta, _Tb, _Tp > __gnu_cxx::weibull_pdf (_Ta __a, _Tb __b, _Tp __x)
Return the Weibull probability density function.
template<typename _Trho , typename _Tphi >
__gnu_cxx::fp_promote_t< _Trho, _Tphi > __gnu_cxx::zernike (unsigned int __n, int __m, _Trho __rho, _Tphi __phi)
float __gnu_cxx::zernikef (unsigned int __n, int __m, float __rho, float __phi)
long double __gnu_cxx::zernikel (unsigned int __n, int __m, long double __rho, long double __phi)
Detailed Description
An extended collection of advanced mathematical special functions for GNU.
Function Documentation
airy_ai() [1/2]
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::airy_ai (_Tp __x) inline
Return the Airy function of real argument .
The Airy function is defined by:
Template Parameters
_Tp The real type of the argument
Parameters
__x The argument
Definition at line 2821 of file specfun.h.
airy_ai() [2/2]
template<typename _Tp > std::complex<__gnu_cxx::fp_promote_t<_Tp> > __gnu_cxx::airy_ai (std::complex< _Tp > __x) inline
Return the Airy function of complex argument .
The Airy function is defined by:
Template Parameters
_Tp The real type of the argument
Parameters
__x The complex argument
Definition at line 2841 of file specfun.h.
airy_aif()
float __gnu_cxx::airy_aif (float __x) inline
Return the Airy function for float argument .
See also
airy_ai for details.
Definition at line 2794 of file specfun.h.
airy_ail()
long double __gnu_cxx::airy_ail (long double __x) inline
Return the Airy function for long double argument .
See also
airy_ai for details.
Definition at line 2804 of file specfun.h.
airy_bi() [1/2]
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::airy_bi (_Tp __x) inline
Return the Airy function of real argument .
The Airy function is defined by:
Template Parameters
_Tp The real type of the argument
Parameters
__x The argument
Definition at line 2883 of file specfun.h.
airy_bi() [2/2]
template<typename _Tp > std::complex<__gnu_cxx::fp_promote_t<_Tp> > __gnu_cxx::airy_bi (std::complex< _Tp > __x) inline
Return the Airy function of complex argument .
The Airy function is defined by:
Template Parameters
_Tp The real type of the argument
Parameters
__x The complex argument
Definition at line 2904 of file specfun.h.
airy_bif()
float __gnu_cxx::airy_bif (float __x) inline
Return the Airy function for float argument .
See also
airy_bi for details.
Definition at line 2855 of file specfun.h.
airy_bil()
long double __gnu_cxx::airy_bil (long double __x) inline
Return the Airy function for long double argument .
See also
airy_bi for details.
Definition at line 2865 of file specfun.h.
bernoulli() [1/2]
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::bernoulli (unsigned int __n) inline
Return the Bernoulli number of integer order .
The Bernoulli numbers are defined by
All odd Bernoulli numbers except are zero.
Parameters
__n The order.
Definition at line 4318 of file specfun.h.
bernoulli() [2/2]
template<typename _Tp > _Tp __gnu_cxx::bernoulli (unsigned int __n, _Tp __x) inline
Return the Bernoulli polynomial of order n at argument x.
The values at 0 and 1 are equal to the corresponding Bernoulli number:
The derivative is proportional to the previous polynomial:
The series expansion for the Bernoulli polynomials is:
A useful argument promotion is:
Definition at line 6880 of file specfun.h.
References std::__detail::__bernoulli().
bernoullif()
float __gnu_cxx::bernoullif (unsigned int __n) inline
Return the Bernoulli number of integer order as a float.
See also
bernoulli for details.
Definition at line 4291 of file specfun.h.
bernoullil()
long double __gnu_cxx::bernoullil (unsigned int __n) inline
Return the Bernoulli number of integer order as a long double.
See also
bernoulli for details.
Definition at line 4301 of file specfun.h.
binomial()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::binomial (unsigned int __n, unsigned int __k) inline
Return the binomial coefficient as a real number. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
Parameters
__n The first argument of the binomial coefficient.
__k The second argument of the binomial coefficient.
Returns
The binomial coefficient.
Definition at line 4234 of file specfun.h.
binomial_p()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::binomial_p (_Tp __p, unsigned int __n, unsigned int __k)
Return the binomial cumulative distribution function.
The binomial cumulative distribution function is related to the incomplete beta function:
Parameters
__p
__n
__k
Definition at line 6733 of file specfun.h.
binomial_pdf()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::binomial_pdf (_Tp __p, unsigned int __n, unsigned int __k)
Return the binomial probability mass function.
The binomial cumulative distribution function is related to the incomplete beta function:
Parameters
__p
__n
__k
Definition at line 6712 of file specfun.h.
binomialf()
float __gnu_cxx::binomialf (unsigned int __n, unsigned int __k) inline
Return the binomial coefficient as a float.
See also
binomial for details.
Definition at line 4205 of file specfun.h.
binomiall()
long double __gnu_cxx::binomiall (unsigned int __n, unsigned int __k) inline
Return the binomial coefficient as a long double.
See also
binomial for details.
Definition at line 4214 of file specfun.h.
bose_einstein()
template<typename _Tps , typename _Tp > __gnu_cxx::fp_promote_t<_Tps, _Tp> __gnu_cxx::bose_einstein (_Tps __s, _Tp __x) inline
Return the Bose-Einstein integral of integer or real order s and real argument x.
See also
https://en.wikipedia.org/wiki/Clausen_function
http://dlmf.nist.gov/25.12.16
Parameters
__s The order s >= 0.
__x The real argument.
Returns
The real Bose-Einstein integral G_s(x),
Definition at line 6111 of file specfun.h.
bose_einsteinf()
float __gnu_cxx::bose_einsteinf (float __s, float __x) inline
Return the Bose-Einstein integral of float order s and argument x.
See also
bose_einstein for details.
Definition at line 6081 of file specfun.h.
bose_einsteinl()
long double __gnu_cxx::bose_einsteinl (long double __s, long double __x) inline
Return the Bose-Einstein integral of long double order s and argument x.
See also
bose_einstein for details.
Definition at line 6091 of file specfun.h.
chebyshev_t()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::chebyshev_t (unsigned int __n, _Tp __x) inline
Return the Chebyshev polynomial of the first kind of non-negative order and real argument .
The Chebyshev polynomial of the first kind is defined by:
where , .
Template Parameters
_Tp The real type of the argument
Parameters
__n The non-negative integral order
__x The real argument
Definition at line 2052 of file specfun.h.
chebyshev_tf()
float __gnu_cxx::chebyshev_tf (unsigned int __n, float __x) inline
Return the Chebyshev polynomials of the first kind of non-negative order and float argument .
See also
chebyshev_t for details.
Definition at line 2023 of file specfun.h.
chebyshev_tl()
long double __gnu_cxx::chebyshev_tl (unsigned int __n, long double __x) inline
Return the Chebyshev polynomials of the first kind of non-negative order and real argument .
See also
chebyshev_t for details.
Definition at line 2033 of file specfun.h.
chebyshev_u()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::chebyshev_u (unsigned int __n, _Tp __x) inline
Return the Chebyshev polynomial of the second kind of non-negative order and real argument .
The Chebyshev polynomial of the second kind is defined by:
where , .
Template Parameters
_Tp The real type of the argument
Parameters
__n The non-negative integral order
__x The real argument
Definition at line 2096 of file specfun.h.
chebyshev_uf()
float __gnu_cxx::chebyshev_uf (unsigned int __n, float __x) inline
Return the Chebyshev polynomials of the second kind of non-negative order and float argument .
See also
chebyshev_u for details.
Definition at line 2067 of file specfun.h.
chebyshev_ul()
long double __gnu_cxx::chebyshev_ul (unsigned int __n, long double __x) inline
Return the Chebyshev polynomials of the second kind of non-negative order and real argument .
See also
chebyshev_u for details.
Definition at line 2077 of file specfun.h.
chebyshev_v()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::chebyshev_v (unsigned int __n, _Tp __x) inline
Return the Chebyshev polynomial of the third kind of non-negative order and real argument .
The Chebyshev polynomial of the third kind is defined by:
where , .
Template Parameters
_Tp The real type of the argument
Parameters
__n The non-negative integral order
__x The real argument
Definition at line 2141 of file specfun.h.
chebyshev_vf()
float __gnu_cxx::chebyshev_vf (unsigned int __n, float __x) inline
Return the Chebyshev polynomials of the third kind of non-negative order and float argument .
See also
chebyshev_v for details.
Definition at line 2111 of file specfun.h.
chebyshev_vl()
long double __gnu_cxx::chebyshev_vl (unsigned int __n, long double __x) inline
Return the Chebyshev polynomials of the third kind of non-negative order and real argument .
See also
chebyshev_v for details.
Definition at line 2121 of file specfun.h.
chebyshev_w()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::chebyshev_w (unsigned int __n, _Tp __x) inline
Return the Chebyshev polynomial of the fourth kind of non-negative order and real argument .
The Chebyshev polynomial of the fourth kind is defined by:
where , .
Template Parameters
_Tp The real type of the argument
Parameters
__n The non-negative integral order
__x The real argument
Definition at line 2186 of file specfun.h.
chebyshev_wf()
float __gnu_cxx::chebyshev_wf (unsigned int __n, float __x) inline
Return the Chebyshev polynomials of the fourth kind of non-negative order and float argument .
See also
chebyshev_w for details.
Definition at line 2156 of file specfun.h.
chebyshev_wl()
long double __gnu_cxx::chebyshev_wl (unsigned int __n, long double __x) inline
Return the Chebyshev polynomials of the fourth kind of non-negative order and real argument .
See also
chebyshev_w for details.
Definition at line 2166 of file specfun.h.
clausen() [1/2]
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::clausen (unsigned int __m, _Tp __x) inline
Return the Clausen function of integer order and real argument .
The Clausen function is defined by
Template Parameters
_Tp The real type of the argument
Parameters
__m The integral order
__x The real argument
Definition at line 5362 of file specfun.h.
clausen() [2/2]
template<typename _Tp > std::complex<__gnu_cxx::fp_promote_t<_Tp> > __gnu_cxx::clausen (unsigned int __m, std::complex< _Tp > __z) inline
Return the Clausen function of integer order and complex argument .
The Clausen function is defined by
Template Parameters
_Tp The real type of the complex components
Parameters
__m The integral order
__z The complex argument
Definition at line 5406 of file specfun.h.
clausen_cl()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::clausen_cl (unsigned int __m, _Tp __x) inline
Return the Clausen cosine function of order and real argument .
The Clausen cosine function is defined by
Template Parameters
_Tp The real type of the argument
Parameters
__m The unsigned integer order
__x The real argument
Definition at line 5317 of file specfun.h.
clausen_clf()
float __gnu_cxx::clausen_clf (unsigned int __m, float __x) inline
Return the Clausen cosine function of order and float argument .
See also
clausen_cl for details.
Definition at line 5289 of file specfun.h.
clausen_cll()
long double __gnu_cxx::clausen_cll (unsigned int __m, long double __x) inline
Return the Clausen cosine function of order and long double argument .
See also
clausen_cl for details.
Definition at line 5299 of file specfun.h.
clausen_sl()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::clausen_sl (unsigned int __m, _Tp __x) inline
Return the Clausen sine function of order and real argument .
The Clausen sine function is defined by
Template Parameters
_Tp The real type of the argument
Parameters
__m The unsigned integer order
__x The real argument
Definition at line 5274 of file specfun.h.
clausen_slf()
float __gnu_cxx::clausen_slf (unsigned int __m, float __x) inline
Return the Clausen sine function of order and float argument .
See also
clausen_sl for details.
Definition at line 5246 of file specfun.h.
clausen_sll()
long double __gnu_cxx::clausen_sll (unsigned int __m, long double __x) inline
Return the Clausen sine function of order and long double argument .
See also
clausen_sl for details.
Definition at line 5256 of file specfun.h.
clausenf() [1/2]
float __gnu_cxx::clausenf (unsigned int __m, float __x) inline
Return the Clausen function of integer order and float argument .
See also
clausen for details.
Definition at line 5332 of file specfun.h.
clausenf() [2/2]
std::complex<float> __gnu_cxx::clausenf (unsigned int __m, std::complex< float > __z) inline
Return the Clausen function of integer order and std::complex<float> argument .
See also
clausen for details.
Definition at line 5377 of file specfun.h.
clausenl() [1/2]
long double __gnu_cxx::clausenl (unsigned int __m, long double __x) inline
Return the Clausen function of integer order and long double argument .
See also
clausen for details.
Definition at line 5342 of file specfun.h.
clausenl() [2/2]
std::complex<long double> __gnu_cxx::clausenl (unsigned int __m, std::complex< long double > __z) inline
Return the Clausen function of integer order and std::complex<long double> argument .
See also
clausen for details.
Definition at line 5387 of file specfun.h.
comp_ellint_d()
template<typename _Tk > __gnu_cxx::fp_promote_t<_Tk> __gnu_cxx::comp_ellint_d (_Tk __k) inline
Return the complete Legendre elliptic integral of real modulus .
The complete Legendre elliptic integral D is defined by
Template Parameters
_Tk The type of the modulus k
Parameters
__k The modulus -1 <= __k <= +1
Definition at line 4534 of file specfun.h.
comp_ellint_df()
float __gnu_cxx::comp_ellint_df (float __k) inline
Return the complete Legendre elliptic integral of float modulus .
See also
comp_ellint_d for details.
Definition at line 4507 of file specfun.h.
comp_ellint_dl()
long double __gnu_cxx::comp_ellint_dl (long double __k) inline
Return the complete Legendre elliptic integral of long double modulus .
See also
comp_ellint_d for details.
Definition at line 4517 of file specfun.h.
comp_ellint_rf() [1/3]
float __gnu_cxx::comp_ellint_rf (float __x, float __y) inline
Return the complete Carlson elliptic function for float arguments.
See also
comp_ellint_rf for details.
Definition at line 3164 of file specfun.h.
comp_ellint_rf() [2/3]
long double __gnu_cxx::comp_ellint_rf (long double __x, long double __y) inline
Return the complete Carlson elliptic function for long double arguments.
See also
comp_ellint_rf for details.
Definition at line 3174 of file specfun.h.
comp_ellint_rf() [3/3]
template<typename _Tx , typename _Ty > __gnu_cxx::fp_promote_t<_Tx, _Ty> __gnu_cxx::comp_ellint_rf (_Tx __x, _Ty __y) inline
Return the complete Carlson elliptic function for real arguments.
The complete Carlson elliptic function of the first kind is defined by:
Parameters
__x The first argument.
__y The second argument.
Definition at line 3192 of file specfun.h.
comp_ellint_rg() [1/3]
float __gnu_cxx::comp_ellint_rg (float __x, float __y) inline
Return the Carlson complementary elliptic function .
See also
comp_ellint_rg for details.
Definition at line 3397 of file specfun.h.
comp_ellint_rg() [2/3]
long double __gnu_cxx::comp_ellint_rg (long double __x, long double __y) inline
Return the Carlson complementary elliptic function .
See also
comp_ellint_rg for details.
Definition at line 3406 of file specfun.h.
comp_ellint_rg() [3/3]
template<typename _Tx , typename _Ty > __gnu_cxx::fp_promote_t<_Tx, _Ty> __gnu_cxx::comp_ellint_rg (_Tx __x, _Ty __y) inline
Return the complete Carlson elliptic function for real arguments.
The complete Carlson elliptic function is defined by:
Parameters
__x The first argument.
__y The second argument.
Definition at line 3425 of file specfun.h.
conf_hyperg()
template<typename _Tpa , typename _Tpc , typename _Tp > __gnu_cxx::fp_promote_t<_Tpa, _Tpc, _Tp> __gnu_cxx::conf_hyperg (_Tpa __a, _Tpc __c, _Tp __x) inline
Return the confluent hypergeometric function of real numerator parameter , denominator parameter , and argument .
The confluent hypergeometric function is defined by
where the Pochhammer symbol is ,
Parameters
__a The numerator parameter
__c The denominator parameter
__x The argument
Definition at line 1431 of file specfun.h.
conf_hyperg_lim()
template<typename _Tpc , typename _Tp > __gnu_cxx::fp_promote_t<_Tpc, _Tp> __gnu_cxx::conf_hyperg_lim (_Tpc __c, _Tp __x) inline
Return the confluent hypergeometric limit function of real numerator parameter and argument .
The confluent hypergeometric limit function is defined by
where the Pochhammer symbol is ,
Parameters
__c The denominator parameter
__x The argument
Definition at line 1576 of file specfun.h.
conf_hyperg_limf()
float __gnu_cxx::conf_hyperg_limf (float __c, float __x) inline
Return the confluent hypergeometric limit function of float numerator parameter and argument .
See also
conf_hyperg_lim for details.
Definition at line 1547 of file specfun.h.
conf_hyperg_liml()
long double __gnu_cxx::conf_hyperg_liml (long double __c, long double __x) inline
Return the confluent hypergeometric limit function of long double numerator parameter and argument .
See also
conf_hyperg_lim for details.
Definition at line 1557 of file specfun.h.
conf_hypergf()
float __gnu_cxx::conf_hypergf (float __a, float __c, float __x) inline
Return the confluent hypergeometric function of float numerator parameter , denominator parameter , and argument .
See also
conf_hyperg for details.
Definition at line 1399 of file specfun.h.
conf_hypergl()
long double __gnu_cxx::conf_hypergl (long double __a, long double __c, long double __x) inline
Return the confluent hypergeometric function of long double numerator parameter , denominator parameter , and argument .
See also
conf_hyperg for details.
Definition at line 1410 of file specfun.h.
cos_pi()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::cos_pi (_Tp __x) inline
Return the reperiodized cosine function for real argument .
The reperiodized cosine function is defined by:
Template Parameters
_Tp The floating-point type of the argument __x.
Parameters
__x The argument
Definition at line 6237 of file specfun.h.
cos_pif()
float __gnu_cxx::cos_pif (float __x) inline
Return the reperiodized cosine function for float argument .
See also
cos_pi for more details.
Definition at line 6210 of file specfun.h.
cos_pil()
long double __gnu_cxx::cos_pil (long double __x) inline
Return the reperiodized cosine function for long double argument .
See also
cos_pi for more details.
Definition at line 6220 of file specfun.h.
cosh_pi()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::cosh_pi (_Tp __x) inline
Return the reperiodized hyperbolic cosine function for real argument .
The reperiodized hyperbolic cosine function is defined by:
Template Parameters
_Tp The floating-point type of the argument __x.
Parameters
__x The argument
Definition at line 6279 of file specfun.h.
cosh_pif()
float __gnu_cxx::cosh_pif (float __x) inline
Return the reperiodized hyperbolic cosine function for float argument .
See also
cosh_pi for more details.
Definition at line 6252 of file specfun.h.
cosh_pil()
long double __gnu_cxx::cosh_pil (long double __x) inline
Return the reperiodized hyperbolic cosine function for long double argument .
See also
cosh_pi for more details.
Definition at line 6262 of file specfun.h.
coshint()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::coshint (_Tp __x) inline
Return the hyperbolic cosine integral of real argument .
The hyperbolic cosine integral is defined by
Template Parameters
_Tp The type of the real argument
Parameters
__x The real argument
Definition at line 1858 of file specfun.h.
coshintf()
float __gnu_cxx::coshintf (float __x) inline
Return the hyperbolic cosine integral of float argument .
See also
coshint for details.
Definition at line 1830 of file specfun.h.
coshintl()
long double __gnu_cxx::coshintl (long double __x) inline
Return the hyperbolic cosine integral of long double argument .
See also
coshint for details.
Definition at line 1840 of file specfun.h.
cosint()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::cosint (_Tp __x) inline
Return the cosine integral of real argument .
The cosine integral is defined by
Parameters
__x The real upper integration limit
Definition at line 1775 of file specfun.h.
cosintf()
float __gnu_cxx::cosintf (float __x) inline
Return the cosine integral of float argument .
See also
cosint for details.
Definition at line 1749 of file specfun.h.
cosintl()
long double __gnu_cxx::cosintl (long double __x) inline
Return the cosine integral of long double argument .
See also
cosint for details.
Definition at line 1759 of file specfun.h.
cyl_hankel_1() [1/2]
template<typename _Tpnu , typename _Tp > std::complex<__gnu_cxx::fp_promote_t<_Tpnu, _Tp> > __gnu_cxx::cyl_hankel_1 (_Tpnu __nu, _Tp __z) inline
Return the cylindrical Hankel function of the first kind of real order and argument .
The spherical Hankel function of the first kind is defined by:
where and are the cylindrical Bessel and Neumann functions respectively (
See also
cyl_bessel and cyl_neumann).
Template Parameters
_Tp The real type of the argument
Parameters
__nu The real order
__z The real argument
Definition at line 2548 of file specfun.h.
cyl_hankel_1() [2/2]
template<typename _Tpnu , typename _Tp > std::complex<__gnu_cxx::fp_promote_t<_Tpnu, _Tp> > __gnu_cxx::cyl_hankel_1 (std::complex< _Tpnu > __nu, std::complex< _Tp > __x) inline
Return the complex cylindrical Hankel function of the first kind of complex order and argument .
The cylindrical Hankel function of the first kind is defined by
Template Parameters
_Tpnu The complex type of the order
_Tp The complex type of the argument
Parameters
__nu The complex order
__x The complex argument
Definition at line 4811 of file specfun.h.
cyl_hankel_1f() [1/2]
std::complex<float> __gnu_cxx::cyl_hankel_1f (float __nu, float __z) inline
Return the cylindrical Hankel function of the first kind of float order and argument .
See also
cyl_hankel_1 for details.
Definition at line 2516 of file specfun.h.
cyl_hankel_1f() [2/2]
std::complex<float> __gnu_cxx::cyl_hankel_1f (std::complex< float > __nu, std::complex< float > __x) inline
Return the complex cylindrical Hankel function of the first kind of std::complex<float> order and argument .
See also
cyl_hankel_1 for more details.
Definition at line 4780 of file specfun.h.
cyl_hankel_1l() [1/2]
std::complex<long double> __gnu_cxx::cyl_hankel_1l (long double __nu, long double __z) inline
Return the cylindrical Hankel function of the first kind of long double order and argument .
See also
cyl_hankel_1 for details.
Definition at line 2527 of file specfun.h.
cyl_hankel_1l() [2/2]
std::complex<long double> __gnu_cxx::cyl_hankel_1l (std::complex< long double > __nu, std::complex< long double > __x) inline
Return the complex cylindrical Hankel function of the first kind of std::complex<long double> order and argument .
See also
cyl_hankel_1 for more details.
Definition at line 4791 of file specfun.h.
cyl_hankel_2() [1/2]
template<typename _Tpnu , typename _Tp > std::complex<__gnu_cxx::fp_promote_t<_Tpnu, _Tp> > __gnu_cxx::cyl_hankel_2 (_Tpnu __nu, _Tp __z) inline
Return the cylindrical Hankel function of the second kind of real order and argument .
The cylindrical Hankel function of the second kind is defined by:
where and are the cylindrical Bessel and Neumann functions respectively (
See also
cyl_bessel and cyl_neumann).
Template Parameters
_Tp The real type of the argument
Parameters
__nu The real order
__z The real argument
Definition at line 2596 of file specfun.h.
cyl_hankel_2() [2/2]
template<typename _Tpnu , typename _Tp > std::complex<__gnu_cxx::fp_promote_t<_Tpnu, _Tp> > __gnu_cxx::cyl_hankel_2 (std::complex< _Tpnu > __nu, std::complex< _Tp > __x) inline
Return the complex cylindrical Hankel function of the second kind of complex order and argument .
The cylindrical Hankel function of the second kind is defined by
Template Parameters
_Tpnu The complex type of the order
_Tp The complex type of the argument
Parameters
__nu The complex order
__x The complex argument
Definition at line 4858 of file specfun.h.
cyl_hankel_2f() [1/2]
std::complex<float> __gnu_cxx::cyl_hankel_2f (float __nu, float __z) inline
Return the cylindrical Hankel function of the second kind of float order and argument .
See also
cyl_hankel_2 for details.
Definition at line 2564 of file specfun.h.
cyl_hankel_2f() [2/2]
std::complex<float> __gnu_cxx::cyl_hankel_2f (std::complex< float > __nu, std::complex< float > __x) inline
Return the complex cylindrical Hankel function of the second kind of std::complex<float> order and argument .
See also
cyl_hankel_2 for more details.
Definition at line 4827 of file specfun.h.
cyl_hankel_2l() [1/2]
std::complex<long double> __gnu_cxx::cyl_hankel_2l (long double __nu, long double __z) inline
Return the cylindrical Hankel function of the second kind of long double order and argument .
See also
cyl_hankel_2 for details.
Definition at line 2575 of file specfun.h.
cyl_hankel_2l() [2/2]
std::complex<long double> __gnu_cxx::cyl_hankel_2l (std::complex< long double > __nu, std::complex< long double > __x) inline
Return the complex cylindrical Hankel function of the second kind of std::complex<long double> order and argument .
See also
cyl_hankel_2 for more details.
Definition at line 4838 of file specfun.h.
dawson()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::dawson (_Tp __x) inline
Return the Dawson integral, , for real argument .
The Dawson integral is defined by:
and it's derivative is:
Parameters
__x The argument .
Definition at line 3808 of file specfun.h.
dawsonf()
float __gnu_cxx::dawsonf (float __x) inline
Return the Dawson integral, , for float argument .
See also
dawson for details.
Definition at line 3779 of file specfun.h.
dawsonl()
long double __gnu_cxx::dawsonl (long double __x) inline
Return the Dawson integral, , for long double argument .
See also
dawson for details.
Definition at line 3789 of file specfun.h.
debye()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::debye (unsigned int __n, _Tp __x) inline
Return the Debye function of positive order and real argument .
The Debye function is defined by:
Template Parameters
_Tp The real type of the argument
Parameters
__n The positive integral order
__x The real argument
Definition at line 6849 of file specfun.h.
debyef()
float __gnu_cxx::debyef (unsigned int __n, float __x) inline
Return the Debye function of positive order and float argument .
See also
debye for details.
Definition at line 6821 of file specfun.h.
debyel()
long double __gnu_cxx::debyel (unsigned int __n, long double __x) inline
Return the Debye function of positive order and real argument .
See also
debye for details.
Definition at line 6831 of file specfun.h.
digamma()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::digamma (_Tp __x) inline
Return the digamma or psi function of argument .
The the digamma or psi function is defined by
the logarithmic derivative of the gamma function.
Parameters
__x The parameter
Definition at line 3571 of file specfun.h.
digammaf()
float __gnu_cxx::digammaf (float __x) inline
Return the digamma or psi function of float argument .
See also
digamma for details.
Definition at line 3544 of file specfun.h.
digammal()
long double __gnu_cxx::digammal (long double __x) inline
Return the digamma or psi function of long double argument .
See also
digamma for details.
Definition at line 3554 of file specfun.h.
dilog()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::dilog (_Tp __x) inline
Return the dilogarithm function for real argument.
The dilogarithm is defined by:
Parameters
__x The argument.
Definition at line 3149 of file specfun.h.
dilogf()
float __gnu_cxx::dilogf (float __x) inline
Return the dilogarithm function for float argument.
See also
dilog for details.
Definition at line 3123 of file specfun.h.
dilogl()
long double __gnu_cxx::dilogl (long double __x) inline
Return the dilogarithm function for long double argument.
See also
dilog for details.
Definition at line 3133 of file specfun.h.
dirichlet_beta()
template<typename _Tp > _Tp __gnu_cxx::dirichlet_beta (_Tp __s) inline
Return the Dirichlet beta function of real argument .
The Dirichlet beta function is defined by:
An important reflection formula is:
The Dirichlet beta function, in terms of the polylogarithm, is
Parameters
__s
Definition at line 5188 of file specfun.h.
dirichlet_betaf()
float __gnu_cxx::dirichlet_betaf (float __s) inline
Return the Dirichlet beta function of real argument .
See also
dirichlet_beta for details.
Definition at line 5153 of file specfun.h.
dirichlet_betal()
long double __gnu_cxx::dirichlet_betal (long double __s) inline
Return the Dirichlet beta function of real argument .
See also
dirichlet_beta for details.
Definition at line 5162 of file specfun.h.
dirichlet_eta()
template<typename _Tp > _Tp __gnu_cxx::dirichlet_eta (_Tp __s) inline
Return the Dirichlet eta function of real argument .
The Dirichlet eta function is defined by
An important reflection formula is:
The Dirichlet eta function, in terms of the polylogarithm, is
Parameters
__s
Definition at line 5139 of file specfun.h.
dirichlet_etaf()
float __gnu_cxx::dirichlet_etaf (float __s) inline
Return the Dirichlet eta function of real argument .
See also
dirichlet_eta for details.
Definition at line 5103 of file specfun.h.
dirichlet_etal()
long double __gnu_cxx::dirichlet_etal (long double __s) inline
Return the Dirichlet eta function of real argument .
See also
dirichlet_eta for details.
Definition at line 5112 of file specfun.h.
dirichlet_lambda()
template<typename _Tp > _Tp __gnu_cxx::dirichlet_lambda (_Tp __s) inline
Return the Dirichlet lambda function of real argument .
The Dirichlet lambda function is defined by
In terms of the Riemann zeta and the Dirichlet eta functions
Parameters
__s
Definition at line 5231 of file specfun.h.
dirichlet_lambdaf()
float __gnu_cxx::dirichlet_lambdaf (float __s) inline
Return the Dirichlet lambda function of real argument .
See also
dirichlet_lambda for details.
Definition at line 5202 of file specfun.h.
dirichlet_lambdal()
long double __gnu_cxx::dirichlet_lambdal (long double __s) inline
Return the Dirichlet lambda function of real argument .
See also
dirichlet_lambda for details.
Definition at line 5211 of file specfun.h.
double_factorial()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::double_factorial (int __n) inline
Return the double factorial of the argument as a real number.
for even and
for odd .
Definition at line 4112 of file specfun.h.
double_factorialf()
float __gnu_cxx::double_factorialf (int __n) inline
Return the double factorial of the argument as a float.
See also
double_factorial for more details
Definition at line 4085 of file specfun.h.
double_factoriall()
long double __gnu_cxx::double_factoriall (int __n) inline
Return the double factorial of the argument as a long double .
See also
double_factorial for more details
Definition at line 4095 of file specfun.h.
ellint_cel()
template<typename _Tk , typename _Tp , typename _Ta , typename _Tb > __gnu_cxx::fp_promote_t<_Tk, _Tp, _Ta, _Tb> __gnu_cxx::ellint_cel (_Tk __k_c, _Tp __p, _Ta __a, _Tb __b) inline
Return the Bulirsch complete elliptic integral of real complementary modulus , and parameters , , and .
The Bulirsch complete elliptic integral is defined by
Parameters
__k_c The complementary modulus
__p The parameter
__a The parameter
__b The parameter
Definition at line 4764 of file specfun.h.
ellint_celf()
float __gnu_cxx::ellint_celf (float __k_c, float __p, float __a, float __b) inline
Return the Bulirsch complete elliptic integral of real complementary modulus , and parameters , , and .
See also
ellint_cel for details.
Definition at line 4732 of file specfun.h.
ellint_cell()
long double __gnu_cxx::ellint_cell (long double __k_c, long double __p, long double __a, long double __b) inline
Return the Bulirsch complete elliptic integral .
See also
ellint_cel for details.
Definition at line 4741 of file specfun.h.
ellint_d()
template<typename _Tk , typename _Tphi > __gnu_cxx::fp_promote_t<_Tk, _Tphi> __gnu_cxx::ellint_d (_Tk __k, _Tphi __phi) inline
Return the incomplete Legendre elliptic integral of real modulus and angular limit .
The Legendre elliptic integral D is defined by
Parameters
__k The modulus -1 <= __k <= +1
__phi The angle
Definition at line 4577 of file specfun.h.
ellint_df()
float __gnu_cxx::ellint_df (float __k, float __phi) inline
Return the incomplete Legendre elliptic integral of float modulus and angular limit .
See also
ellint_d for details.
Definition at line 4549 of file specfun.h.
ellint_dl()
long double __gnu_cxx::ellint_dl (long double __k, long double __phi) inline
Return the incomplete Legendre elliptic integral of long double modulus and angular limit .
See also
ellint_d for details.
Definition at line 4559 of file specfun.h.
ellint_el1()
template<typename _Tp , typename _Tk > __gnu_cxx::fp_promote_t<_Tp, _Tk> __gnu_cxx::ellint_el1 (_Tp __x, _Tk __k_c) inline
Return the Bulirsch elliptic integral of the first kind of real tangent limit and complementary modulus .
The Bulirsch elliptic integral of the first kind is defined by
Parameters
__x The tangent of the angular integration limit
__k_c The complementary modulus
Definition at line 4623 of file specfun.h.
ellint_el1f()
float __gnu_cxx::ellint_el1f (float __x, float __k_c) inline
Return the Bulirsch elliptic integral of the first kind of float tangent limit and complementary modulus .
See also
ellint_el1 for details.
Definition at line 4593 of file specfun.h.
ellint_el1l()
long double __gnu_cxx::ellint_el1l (long double __x, long double __k_c) inline
Return the Bulirsch elliptic integral of the first kind of real tangent limit and complementary modulus .
See also
ellint_el1 for details.
Definition at line 4604 of file specfun.h.
ellint_el2()
template<typename _Tp , typename _Tk , typename _Ta , typename _Tb > __gnu_cxx::fp_promote_t<_Tp, _Tk, _Ta, _Tb> __gnu_cxx::ellint_el2 (_Tp __x, _Tk __k_c, _Ta __a, _Tb __b) inline
Return the Bulirsch elliptic integral of the second kind .
The Bulirsch elliptic integral of the second kind is defined by
Parameters
__x The tangent of the angular integration limit
__k_c The complementary modulus
__a The parameter
__b The parameter
Definition at line 4669 of file specfun.h.
ellint_el2f()
float __gnu_cxx::ellint_el2f (float __x, float __k_c, float __a, float __b) inline
Return the Bulirsch elliptic integral of the second kind .
See also
ellint_el2 for details.
Definition at line 4638 of file specfun.h.
ellint_el2l()
long double __gnu_cxx::ellint_el2l (long double __x, long double __k_c, long double __a, long double __b) inline
Return the Bulirsch elliptic integral of the second kind .
See also
ellint_el2 for details.
Definition at line 4648 of file specfun.h.
ellint_el3()
template<typename _Tx , typename _Tk , typename _Tp > __gnu_cxx::fp_promote_t<_Tx, _Tk, _Tp> __gnu_cxx::ellint_el3 (_Tx __x, _Tk __k_c, _Tp __p) inline
Return the Bulirsch elliptic integral of the third kind of real tangent limit , complementary modulus , and parameter .
The Bulirsch elliptic integral of the third kind is defined by
Parameters
__x The tangent of the angular integration limit
__k_c The complementary modulus
__p The paramenter
Definition at line 4716 of file specfun.h.
ellint_el3f()
float __gnu_cxx::ellint_el3f (float __x, float __k_c, float __p) inline
Return the Bulirsch elliptic integral of the third kind of float tangent limit , complementary modulus , and parameter .
See also
ellint_el3 for details.
Definition at line 4685 of file specfun.h.
ellint_el3l()
long double __gnu_cxx::ellint_el3l (long double __x, long double __k_c, long double __p) inline
Return the Bulirsch elliptic integral of the third kind of long double tangent limit , complementary modulus , and parameter .
See also
ellint_el3 for details.
Definition at line 4696 of file specfun.h.
ellint_rc()
template<typename _Tp , typename _Up > __gnu_cxx::fp_promote_t<_Tp, _Up> __gnu_cxx::ellint_rc (_Tp __x, _Up __y) inline
Return the Carlson elliptic function where is the Carlson elliptic function of the first kind.
The Carlson elliptic function is defined by:
Based on Carlson's algorithms:
B. C. Carlson Numer. Math. 33, 1 (1979)
B. C. Carlson, Special Functions of Applied Mathematics (1977)
Numerical Recipes in C, 2nd ed, pp. 261-269, by Press, Teukolsky, Vetterling, Flannery (1992)
Parameters
__x The first argument.
__y The second argument.
Definition at line 3284 of file specfun.h.
ellint_rcf()
float __gnu_cxx::ellint_rcf (float __x, float __y) inline
Return the Carlson elliptic function .
See also
ellint_rc for details.
Definition at line 3250 of file specfun.h.
ellint_rcl()
long double __gnu_cxx::ellint_rcl (long double __x, long double __y) inline
Return the Carlson elliptic function .
See also
ellint_rc for details.
Definition at line 3259 of file specfun.h.
ellint_rd()
template<typename _Tp , typename _Up , typename _Vp > __gnu_cxx::fp_promote_t<_Tp, _Up, _Vp> __gnu_cxx::ellint_rd (_Tp __x, _Up __y, _Vp __z) inline
Return the Carlson elliptic function of the second kind where is the Carlson elliptic function of the third kind.
The Carlson elliptic function of the second kind is defined by:
Based on Carlson's algorithms:
B. C. Carlson Numer. Math. 33, 1 (1979)
B. C. Carlson, Special Functions of Applied Mathematics (1977)
Numerical Recipes in C, 2nd ed, pp. 261-269, by Press, Teukolsky, Vetterling, Flannery (1992)
Parameters
__x The first of two symmetric arguments.
__y The second of two symmetric arguments.
__z The third argument.
Definition at line 3383 of file specfun.h.
ellint_rdf()
float __gnu_cxx::ellint_rdf (float __x, float __y, float __z) inline
Return the Carlson elliptic function .
See also
ellint_rd for details.
Definition at line 3347 of file specfun.h.
ellint_rdl()
long double __gnu_cxx::ellint_rdl (long double __x, long double __y, long double __z) inline
Return the Carlson elliptic function .
See also
ellint_rd for details.
Definition at line 3356 of file specfun.h.
ellint_rf()
template<typename _Tp , typename _Up , typename _Vp > __gnu_cxx::fp_promote_t<_Tp, _Up, _Vp> __gnu_cxx::ellint_rf (_Tp __x, _Up __y, _Vp __z) inline
Return the Carlson elliptic function of the first kind for real arguments.
The Carlson elliptic function of the first kind is defined by:
Parameters
__x The first of three symmetric arguments.
__y The second of three symmetric arguments.
__z The third of three symmetric arguments.
Definition at line 3236 of file specfun.h.
ellint_rff()
float __gnu_cxx::ellint_rff (float __x, float __y, float __z) inline
Return the Carlson elliptic function of the first kind for float arguments.
See also
ellint_rf for details.
Definition at line 3207 of file specfun.h.
ellint_rfl()
long double __gnu_cxx::ellint_rfl (long double __x, long double __y, long double __z) inline
Return the Carlson elliptic function of the first kind for long double arguments.
See also
ellint_rf for details.
Definition at line 3217 of file specfun.h.
ellint_rg()
template<typename _Tp , typename _Up , typename _Vp > __gnu_cxx::fp_promote_t<_Tp, _Up, _Vp> __gnu_cxx::ellint_rg (_Tp __x, _Up __y, _Vp __z) inline
Return the symmetric Carlson elliptic function of the second kind .
The Carlson symmetric elliptic function of the second kind is defined by:
Based on Carlson's algorithms:
B. C. Carlson Numer. Math. 33, 1 (1979)
B. C. Carlson, Special Functions of Applied Mathematics (1977)
Numerical Recipes in C, 2nd ed, pp. 261-269, by Press, Teukolsky, Vetterling, Flannery (1992)
Parameters
__x The first of three symmetric arguments.
__y The second of three symmetric arguments.
__z The third of three symmetric arguments.
Definition at line 3474 of file specfun.h.
ellint_rgf()
float __gnu_cxx::ellint_rgf (float __x, float __y, float __z) inline
Return the Carlson elliptic function .
See also
ellint_rg for details.
Definition at line 3439 of file specfun.h.
ellint_rgl()
long double __gnu_cxx::ellint_rgl (long double __x, long double __y, long double __z) inline
Return the Carlson elliptic function .
See also
ellint_rg for details.
Definition at line 3448 of file specfun.h.
ellint_rj()
template<typename _Tp , typename _Up , typename _Vp , typename _Wp > __gnu_cxx::fp_promote_t<_Tp, _Up, _Vp, _Wp> __gnu_cxx::ellint_rj (_Tp __x, _Up __y, _Vp __z, _Wp __p) inline
Return the Carlson elliptic function of the third kind.
The Carlson elliptic function of the third kind is defined by:
Based on Carlson's algorithms:
B. C. Carlson Numer. Math. 33, 1 (1979)
B. C. Carlson, Special Functions of Applied Mathematics (1977)
Numerical Recipes in C, 2nd ed, pp. 261-269, by Press, Teukolsky, Vetterling, Flannery (1992)
Parameters
__x The first of three symmetric arguments.
__y The second of three symmetric arguments.
__z The third of three symmetric arguments.
__p The fourth argument.
Definition at line 3333 of file specfun.h.
ellint_rjf()
float __gnu_cxx::ellint_rjf (float __x, float __y, float __z, float __p) inline
Return the Carlson elliptic function .
See also
ellint_rj for details.
Definition at line 3298 of file specfun.h.
ellint_rjl()
long double __gnu_cxx::ellint_rjl (long double __x, long double __y, long double __z, long double __p) inline
Return the Carlson elliptic function .
See also
ellint_rj for details.
Definition at line 3307 of file specfun.h.
ellnome()
template<typename _Tp > _Tp __gnu_cxx::ellnome (_Tp __k) inline
Return the elliptic nome function of modulus .
The elliptic nome function is defined by
where is the complete elliptic function of the first kind.
Template Parameters
_Tp The real type of the modulus
Parameters
__k The modulus
Definition at line 5620 of file specfun.h.
ellnomef()
float __gnu_cxx::ellnomef (float __k) inline
Return the elliptic nome function of modulus .
See also
ellnome for details.
Definition at line 5593 of file specfun.h.
ellnomel()
long double __gnu_cxx::ellnomel (long double __k) inline
Return the elliptic nome function of long double modulus .
See also
ellnome for details.
Definition at line 5603 of file specfun.h.
euler()
template<typename _Tp > _Tp __gnu_cxx::euler (unsigned int __n) inline
This returns Euler number .
Parameters
__n the order n of the Euler number.
Returns
The Euler number of order n.
Definition at line 6891 of file specfun.h.
eulerian_1()
template<typename _Tp > _Tp __gnu_cxx::eulerian_1 (unsigned int __n, unsigned int __m) inline
Return the Eulerian number of the first kind. The Eulerian numbers of the first kind are defined by recursion:
Note that is a common older notation.
Todo:
Develop an iterator model for Eulerian numbers of the first kind.
Definition at line 6909 of file specfun.h.
eulerian_2()
template<typename _Tp > _Tp __gnu_cxx::eulerian_2 (unsigned int __n, unsigned int __m) inline
Return the Eulerian number of the second kind. The Eulerian numbers of the second kind are defined by recursion:
Todo:
Develop an iterator model for Eulerian numbers of the second kind.
Definition at line 6927 of file specfun.h.
expint()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::expint (unsigned int __n, _Tp __x) inline
Return the exponential integral of integral order and real argument . The exponential integral is defined by:
In particular
Template Parameters
_Tp The real type of the argument
Parameters
__n The integral order
__x The real argument
Definition at line 3854 of file specfun.h.
expintf()
float __gnu_cxx::expintf (unsigned int __n, float __x) inline
Return the exponential integral for integral order and float argument .
See also
expint for details.
Definition at line 3823 of file specfun.h.
expintl()
long double __gnu_cxx::expintl (unsigned int __n, long double __x) inline
Return the exponential integral for integral order and long double argument .
See also
expint for details.
Definition at line 3833 of file specfun.h.
exponential_p()
template<typename _Tlam , typename _Tp > __gnu_cxx::fp_promote_t<_Tlam, _Tp> __gnu_cxx::exponential_p (_Tlam __lambda, _Tp __x) inline
Return the exponential cumulative probability density function.
The formula for the exponential cumulative probability density function is
Definition at line 6568 of file specfun.h.
exponential_pdf()
template<typename _Tlam , typename _Tp > __gnu_cxx::fp_promote_t<_Tlam, _Tp> __gnu_cxx::exponential_pdf (_Tlam __lambda, _Tp __x) inline
Return the exponential probability density function.
The formula for the exponential probability density function is
Definition at line 6552 of file specfun.h.
factorial()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::factorial (unsigned int __n) inline
Return the factorial of the argument as a real number.
.
Definition at line 4071 of file specfun.h.
factorialf()
float __gnu_cxx::factorialf (unsigned int __n) inline
Return the factorial of the argument as a float.
See also
factorial for more details
Definition at line 4051 of file specfun.h.
factoriall()
long double __gnu_cxx::factoriall (unsigned int __n) inline
Return the factorial of the argument as a long double.
See also
factorial for more details
Definition at line 4060 of file specfun.h.
falling_factorial()
template<typename _Tp , typename _Tnu > __gnu_cxx::fp_promote_t<_Tp, _Tnu> __gnu_cxx::falling_factorial (_Tp __a, _Tnu __nu) inline
Return the falling factorial function or the lower Pochhammer symbol for real argument and integral order . The falling factorial function is defined by
In particular, .
Definition at line 4037 of file specfun.h.
falling_factorialf()
float __gnu_cxx::falling_factorialf (float __a, float __nu) inline
Return the falling factorial for float arguments.
See also
falling_factorial for details.
Definition at line 4011 of file specfun.h.
falling_factoriall()
long double __gnu_cxx::falling_factoriall (long double __a, long double __nu) inline
Return the falling factorial for long double arguments.
See also
falling_factorial for details.
Definition at line 4021 of file specfun.h.
fermi_dirac()
template<typename _Tps , typename _Tp > __gnu_cxx::fp_promote_t<_Tps, _Tp> __gnu_cxx::fermi_dirac (_Tps __s, _Tp __x) inline
Return the Fermi-Dirac integral of integer or real order s and real argument x.
See also
https://en.wikipedia.org/wiki/Clausen_function
http://dlmf.nist.gov/25.12.16
Parameters
__s The order s > -1.
__x The real argument.
Returns
The real Fermi-Dirac integral F_s(x),
Definition at line 6067 of file specfun.h.
fermi_diracf()
float __gnu_cxx::fermi_diracf (float __s, float __x) inline
Return the Fermi-Dirac integral of float order s and argument x.
See also
fermi_dirac for details.
Definition at line 6037 of file specfun.h.
fermi_diracl()
long double __gnu_cxx::fermi_diracl (long double __s, long double __x) inline
Return the Fermi-Dirac integral of long double order s and argument x.
See also
fermi_dirac for details.
Definition at line 6047 of file specfun.h.
fisher_f_p()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::fisher_f_p (_Tp __F, unsigned int __nu1, unsigned int __nu2)
Return the F-distribution propability function. This returns the probability that the observed chi-square for a correct model exceeds the value .
The f-distribution propability function is related to the incomplete beta function:
Parameters
__nu1 The number of degrees of freedom of sample 1
__nu2 The number of degrees of freedom of sample 2
__F The F statistic
Definition at line 6666 of file specfun.h.
fisher_f_pdf()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::fisher_f_pdf (_Tp __F, unsigned int __nu1, unsigned int __nu2)
Return the F-distribution propability function. This returns the probability that the observed chi-square for a correct model exceeds the value .
The f-distribution propability function is related to the incomplete beta function:
Parameters
__F
__nu1
__nu2
Definition at line 6691 of file specfun.h.
fresnel_c()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::fresnel_c (_Tp __x) inline
Return the Fresnel cosine integral of argument .
The Fresnel cosine integral is defined by
Parameters
__x The argument
Definition at line 3765 of file specfun.h.
fresnel_cf()
float __gnu_cxx::fresnel_cf (float __x) inline
Definition at line 3746 of file specfun.h.
fresnel_cl()
long double __gnu_cxx::fresnel_cl (long double __x) inline
Definition at line 3750 of file specfun.h.
fresnel_s()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::fresnel_s (_Tp __x) inline
Return the Fresnel sine integral of argument .
The Fresnel sine integral is defined by
Parameters
__x The argument
Definition at line 3737 of file specfun.h.
fresnel_sf()
float __gnu_cxx::fresnel_sf (float __x) inline
Definition at line 3718 of file specfun.h.
fresnel_sl()
long double __gnu_cxx::fresnel_sl (long double __x) inline
Definition at line 3722 of file specfun.h.
gamma_p()
template<typename _Ta , typename _Tp > __gnu_cxx::fp_promote_t<_Ta, _Tp> __gnu_cxx::gamma_p (_Ta __a, _Tp __x) inline
Return the gamma cumulative propability distribution function or the regularized lower incomplete gamma function.
The formula for the gamma probability density function is:
Definition at line 4395 of file specfun.h.
gamma_pdf()
template<typename _Ta , typename _Tb , typename _Tp > __gnu_cxx::fp_promote_t<_Ta, _Tb, _Tp> __gnu_cxx::gamma_pdf (_Ta __alpha, _Tb __beta, _Tp __x) inline
Return the gamma propability distribution function.
The formula for the gamma probability density function is:
Definition at line 6453 of file specfun.h.
References std::__detail::__beta().
gamma_pf()
float __gnu_cxx::gamma_pf (float __a, float __x) inline
Definition at line 4376 of file specfun.h.
gamma_pl()
long double __gnu_cxx::gamma_pl (long double __a, long double __x) inline
Definition at line 4380 of file specfun.h.
gamma_q()
template<typename _Ta , typename _Tp > __gnu_cxx::fp_promote_t<_Ta, _Tp> __gnu_cxx::gamma_q (_Ta __a, _Tp __x) inline
Return the gamma complementary cumulative propability distribution (or survival) function or the regularized upper incomplete gamma function.
The formula for the gamma probability density function is:
Definition at line 4423 of file specfun.h.
gamma_qf()
float __gnu_cxx::gamma_qf (float __a, float __x) inline
Definition at line 4404 of file specfun.h.
gamma_ql()
long double __gnu_cxx::gamma_ql (long double __a, long double __x) inline
Definition at line 4408 of file specfun.h.
gamma_reciprocal()
template<typename _Ta > __gnu_cxx::fp_promote_t<_Ta> __gnu_cxx::gamma_reciprocal (_Ta __a) inline
Return the reciprocal gamma function for real argument.
The reciprocal of the Gamma function is what you'd expect:
But unlike the Gamma function this function has no singularities and is exponentially decreasing for increasing argument.
Definition at line 6806 of file specfun.h.
gamma_reciprocalf()
float __gnu_cxx::gamma_reciprocalf (float __a) inline
Return the reciprocal gamma function for float argument.
See also
gamma_reciprocal for details.
Definition at line 6781 of file specfun.h.
gamma_reciprocall()
long double __gnu_cxx::gamma_reciprocall (long double __a) inline
Return the reciprocal gamma function for long double argument.
See also
gamma_reciprocal for details.
Definition at line 6791 of file specfun.h.
gegenbauer()
template<typename _Tlam , typename _Tp > __gnu_cxx::fp_promote_t<_Tlam, _Tp> __gnu_cxx::gegenbauer (unsigned int __n, _Tlam __lambda, _Tp __x) inline
Return the Gegenbauer polynomial of degree n and real order and argument .
The Gegenbauer polynomial is generated by a three-term recursion relation:
and , .
Template Parameters
_Tlam The real type of the order
_Tp The real type of the argument
Parameters
__n The non-negative integral degree
__lambda The real order
__x The real argument
Definition at line 2307 of file specfun.h.
gegenbauerf()
float __gnu_cxx::gegenbauerf (unsigned int __n, float __lambda, float __x) inline
Return the Gegenbauer polynomial of degree n and float order and argument .
See also
gegenbauer for details.
Definition at line 2270 of file specfun.h.
gegenbauerl()
long double __gnu_cxx::gegenbauerl (unsigned int __n, long double __lambda, long double __x) inline
Return the Gegenbauer polynomial of degree n and long double order and argument .
See also
gegenbauer for details.
Definition at line 2281 of file specfun.h.
harmonic()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::harmonic (unsigned int __n) inline
Return the harmonic number .
The the harmonic number is defined by
Parameters
__n The parameter
Definition at line 3629 of file specfun.h.
heuman_lambda()
template<typename _Tk , typename _Tphi > __gnu_cxx::fp_promote_t<_Tk, _Tphi> __gnu_cxx::heuman_lambda (_Tk __k, _Tphi __phi) inline
Return the Heuman lambda function of modulus and angular limit .
The complete Heuman lambda function is defined by
where , is the complete elliptic function of the first kind, and is the Jacobi zeta function.
Template Parameters
_Tk the floating-point type of the modulus
_Tphi the floating-point type of the angular limit argument
Parameters
__k The modulus
__phi The angle
Definition at line 4492 of file specfun.h.
heuman_lambdaf()
float __gnu_cxx::heuman_lambdaf (float __k, float __phi) inline
Definition at line 4466 of file specfun.h.
heuman_lambdal()
long double __gnu_cxx::heuman_lambdal (long double __k, long double __phi) inline
Definition at line 4470 of file specfun.h.
hurwitz_zeta() [1/2]
template<typename _Tp , typename _Up > __gnu_cxx::fp_promote_t<_Tp, _Up> __gnu_cxx::hurwitz_zeta (_Tp __s, _Up __a) inline
Return the Hurwitz zeta function of real argument , and parameter .
The the Hurwitz zeta function is defined by
Parameters
__s The argument
__a The parameter
Definition at line 3516 of file specfun.h.
hurwitz_zeta() [2/2]
template<typename _Tp , typename _Up > std::complex<_Tp> __gnu_cxx::hurwitz_zeta (_Tp __s, std::complex< _Up > __a)
Return the Hurwitz zeta function of real argument , and complex parameter .
See also
hurwitz_zeta for details.
Definition at line 3530 of file specfun.h.
hurwitz_zetaf()
float __gnu_cxx::hurwitz_zetaf (float __s, float __a) inline
Return the Hurwitz zeta function of float argument , and parameter .
See also
hurwitz_zeta for details.
Definition at line 3489 of file specfun.h.
hurwitz_zetal()
long double __gnu_cxx::hurwitz_zetal (long double __s, long double __a) inline
Return the Hurwitz zeta function of long double argument , and parameter .
See also
hurwitz_zeta for details.
Definition at line 3499 of file specfun.h.
hyperg()
template<typename _Tpa , typename _Tpb , typename _Tpc , typename _Tp > __gnu_cxx::fp_promote_t<_Tpa, _Tpb, _Tpc, _Tp> __gnu_cxx::hyperg (_Tpa __a, _Tpb __b, _Tpc __c, _Tp __x) inline
Return the hypergeometric function of real numerator parameters and , denominator parameter , and argument .
The hypergeometric function is defined by
where the Pochhammer symbol is ,
Parameters
__a The first numerator parameter
__b The second numerator parameter
__c The denominator parameter
__x The argument
Definition at line 1530 of file specfun.h.
hypergf()
float __gnu_cxx::hypergf (float __a, float __b, float __c, float __x) inline
Return the hypergeometric function of @ float numerator parameters and , denominator parameter , and argument .
See also
hyperg for details.
Definition at line 1497 of file specfun.h.
hypergl()
long double __gnu_cxx::hypergl (long double __a, long double __b, long double __c, long double __x) inline
Return the hypergeometric function of long double numerator parameters and , denominator parameter , and argument .
See also
hyperg for details.
Definition at line 1508 of file specfun.h.
ibeta()
template<typename _Ta , typename _Tb , typename _Tp > __gnu_cxx::fp_promote_t<_Ta, _Tb, _Tp> __gnu_cxx::ibeta (_Ta __a, _Tb __b, _Tp __x) inline
Return the regularized incomplete beta function of parameters , , and argument .
The regularized incomplete beta function is defined by
where
is the non-regularized incomplete beta function and is the usual beta function.
Parameters
__a The first parameter
__b The second parameter
__x The argument
Definition at line 3678 of file specfun.h.
ibetac()
template<typename _Ta , typename _Tb , typename _Tp > __gnu_cxx::fp_promote_t<_Ta, _Tb, _Tp> __gnu_cxx::ibetac (_Ta __a, _Tb __b, _Tp __x) inline
Return the regularized complementary incomplete beta function of parameters , , and argument .
The regularized complementary incomplete beta function is defined by
Parameters
__a The parameter
__b The parameter
__x The argument
Definition at line 3709 of file specfun.h.
ibetacf()
float __gnu_cxx::ibetacf (float __a, float __b, float __x) inline
Definition at line 3687 of file specfun.h.
References __gnu_cxx::ibetaf().
ibetacl()
long double __gnu_cxx::ibetacl (long double __a, long double __b, long double __x) inline
Definition at line 3691 of file specfun.h.
References __gnu_cxx::ibetal().
ibetaf()
float __gnu_cxx::ibetaf (float __a, float __b, float __x) inline
Return the regularized incomplete beta function of parameters , , and argument .
See ibeta for details.
Definition at line 3644 of file specfun.h.
Referenced by __gnu_cxx::ibetacf().
ibetal()
long double __gnu_cxx::ibetal (long double __a, long double __b, long double __x) inline
Return the regularized incomplete beta function of parameters , , and argument .
See ibeta for details.
Definition at line 3654 of file specfun.h.
Referenced by __gnu_cxx::ibetacl().
jacobi()
template<typename _Talpha , typename _Tbeta , typename _Tp > __gnu_cxx::fp_promote_t<_Talpha, _Tbeta, _Tp> __gnu_cxx::jacobi (unsigned __n, _Talpha __alpha, _Tbeta __beta, _Tp __x) inline
Return the Jacobi polynomial of degree and float orders and argument .
The Jacobi polynomials are generated by a three-term recursion relation:
where and .
Template Parameters
_Talpha The real type of the order
_Tbeta The real type of the order
_Tp The real type of the argument
Parameters
__n The non-negative integral degree
__alpha The real order
__beta The real order
__x The real argument
Definition at line 2253 of file specfun.h.
References std::__detail::__beta().
jacobi_cn()
template<typename _Kp , typename _Up > __gnu_cxx::fp_promote_t<_Kp, _Up> __gnu_cxx::jacobi_cn (_Kp __k, _Up __u) inline
Return the Jacobi elliptic cosine amplitude function of real modulus and argument .
The Jacobi elliptic cn integral is defined by
where is the Legendre elliptic integral of the first kind (
See also
ellint_1).
Template Parameters
_Kp The type of the real modulus
_Up The type of the real argument
Parameters
__k The real modulus
__u The real argument
Definition at line 1958 of file specfun.h.
jacobi_cnf()
float __gnu_cxx::jacobi_cnf (float __k, float __u) inline
Return the Jacobi elliptic cosine amplitude function of float modulus and argument .
See also
jacobi_cn for details.
Definition at line 1923 of file specfun.h.
jacobi_cnl()
long double __gnu_cxx::jacobi_cnl (long double __k, long double __u) inline
Return the Jacobi elliptic cosine amplitude function of long double modulus and argument .
See also
jacobi_cn for details.
Definition at line 1935 of file specfun.h.
jacobi_dn()
template<typename _Kp , typename _Up > __gnu_cxx::fp_promote_t<_Kp, _Up> __gnu_cxx::jacobi_dn (_Kp __k, _Up __u) inline
Return the Jacobi elliptic delta amplitude function of real modulus and argument .
The Jacobi elliptic dn integral is defined by
where is the Legendre elliptic integral of the first kind (
See also
ellint_1).
Template Parameters
_Kp The type of the real modulus
_Up The type of the real argument
Parameters
__k The real modulus
__u The real argument
Definition at line 2008 of file specfun.h.
jacobi_dnf()
float __gnu_cxx::jacobi_dnf (float __k, float __u) inline
Return the Jacobi elliptic delta amplitude function of float modulus and argument .
See also
jacobi_dn for details.
Definition at line 1973 of file specfun.h.
jacobi_dnl()
long double __gnu_cxx::jacobi_dnl (long double __k, long double __u) inline
Return the Jacobi elliptic delta amplitude function of long double modulus and argument .
See also
jacobi_dn for details.
Definition at line 1985 of file specfun.h.
jacobi_sn()
template<typename _Kp , typename _Up > __gnu_cxx::fp_promote_t<_Kp, _Up> __gnu_cxx::jacobi_sn (_Kp __k, _Up __u) inline
Return the Jacobi elliptic sine amplitude function of real modulus and argument .
The Jacobi elliptic sn integral is defined by
where is the Legendre elliptic integral of the first kind (
See also
ellint_1).
Template Parameters
_Kp The type of the real modulus
_Up The type of the real argument
Parameters
__k The real modulus
__u The real argument
Definition at line 1908 of file specfun.h.
jacobi_snf()
float __gnu_cxx::jacobi_snf (float __k, float __u) inline
Return the Jacobi elliptic sine amplitude function of float modulus and argument .
See also
jacobi_sn for details.
Definition at line 1873 of file specfun.h.
jacobi_snl()
long double __gnu_cxx::jacobi_snl (long double __k, long double __u) inline
Return the Jacobi elliptic sine amplitude function of long double modulus and argument .
See also
jacobi_sn for details.
Definition at line 1885 of file specfun.h.
jacobi_theta_1()
template<typename _Tpq , typename _Tp > __gnu_cxx::fp_promote_t<_Tpq, _Tp> __gnu_cxx::jacobi_theta_1 (_Tpq __q, _Tp __x) inline
Return the Jacobi theta-1 function of nome and argument .
The Jacobi theta-1 function is defined by
Parameters
__q The periodic (period = 2) argument
__x The argument
Definition at line 5851 of file specfun.h.
jacobi_theta_1f()
float __gnu_cxx::jacobi_theta_1f (float __q, float __x) inline
Return the Jacobi theta-1 function of nome and argument .
See also
jacobi_theta_1 for details.
Definition at line 5823 of file specfun.h.
jacobi_theta_1l()
long double __gnu_cxx::jacobi_theta_1l (long double __q, long double __x) inline
Return the Jacobi theta-1 function of nome and argument .
See also
jacobi_theta_1 for details.
Definition at line 5833 of file specfun.h.
jacobi_theta_2()
template<typename _Tpq , typename _Tp > __gnu_cxx::fp_promote_t<_Tpq, _Tp> __gnu_cxx::jacobi_theta_2 (_Tpq __q, _Tp __x) inline
Return the Jacobi theta-2 function of nome and argument .
The Jacobi theta-2 function is defined by
Parameters
__q The periodic (period = 2) argument
__x The argument
Definition at line 5894 of file specfun.h.
jacobi_theta_2f()
float __gnu_cxx::jacobi_theta_2f (float __q, float __x) inline
Return the Jacobi theta-2 function of nome and argument .
See also
jacobi_theta_2 for details.
Definition at line 5866 of file specfun.h.
jacobi_theta_2l()
long double __gnu_cxx::jacobi_theta_2l (long double __q, long double __x) inline
Return the Jacobi theta-2 function of nome and argument .
See also
jacobi_theta_2 for details.
Definition at line 5876 of file specfun.h.
jacobi_theta_3()
template<typename _Tpq , typename _Tp > __gnu_cxx::fp_promote_t<_Tpq, _Tp> __gnu_cxx::jacobi_theta_3 (_Tpq __q, _Tp __x) inline
Return the Jacobi theta-3 function of nome and argument .
The Jacobi theta-3 function is defined by
Parameters
__q The elliptic nome
__x The argument
Definition at line 5937 of file specfun.h.
jacobi_theta_3f()
float __gnu_cxx::jacobi_theta_3f (float __q, float __x) inline
Return the Jacobi theta-3 function of nome and argument .
See also
jacobi_theta_3 for details.
Definition at line 5909 of file specfun.h.
jacobi_theta_3l()
long double __gnu_cxx::jacobi_theta_3l (long double __q, long double __x) inline
Return the Jacobi theta-3 function of nome and argument .
See also
jacobi_theta_3 for details.
Definition at line 5919 of file specfun.h.
jacobi_theta_4()
template<typename _Tpq , typename _Tp > __gnu_cxx::fp_promote_t<_Tpq, _Tp> __gnu_cxx::jacobi_theta_4 (_Tpq __q, _Tp __x) inline
Return the Jacobi theta-4 function of nome and argument .
The Jacobi theta-4 function is defined by
Parameters
__q The elliptic nome
__x The argument
Definition at line 5980 of file specfun.h.
jacobi_theta_4f()
float __gnu_cxx::jacobi_theta_4f (float __q, float __x) inline
Return the Jacobi theta-4 function of nome and argument .
See also
jacobi_theta_4 for details.
Definition at line 5952 of file specfun.h.
jacobi_theta_4l()
long double __gnu_cxx::jacobi_theta_4l (long double __q, long double __x) inline
Return the Jacobi theta-4 function of nome and argument .
See also
jacobi_theta_4 for details.
Definition at line 5962 of file specfun.h.
jacobi_zeta()
template<typename _Tk , typename _Tphi > __gnu_cxx::fp_promote_t<_Tk, _Tphi> __gnu_cxx::jacobi_zeta (_Tk __k, _Tphi __phi) inline
Return the Jacobi zeta function of and .
The Jacobi zeta function is defined by
where is the elliptic function of the second kind, is the complete ellitic function of the second kind, and is the elliptic function of the first kind.
Template Parameters
_Tk the real type of the modulus
_Tphi the real type of the angle limit
Parameters
__k The modulus
__phi The angle
Definition at line 4457 of file specfun.h.
jacobi_zetaf()
float __gnu_cxx::jacobi_zetaf (float __k, float __phi) inline
Definition at line 4432 of file specfun.h.
jacobi_zetal()
long double __gnu_cxx::jacobi_zetal (long double __k, long double __phi) inline
Definition at line 4436 of file specfun.h.
jacobif()
float __gnu_cxx::jacobif (unsigned __n, float __alpha, float __beta, float __x) inline
Return the Jacobi polynomial of degree and float orders and argument .
See also
jacobi for details.
Definition at line 2202 of file specfun.h.
References std::__detail::__beta().
jacobil()
long double __gnu_cxx::jacobil (unsigned __n, long double __alpha, long double __beta, long double __x) inline
Return the Jacobi polynomial of degree and long double orders and argument .
See also
jacobi for details.
Definition at line 2216 of file specfun.h.
References std::__detail::__beta().
lbinomial()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::lbinomial (unsigned int __n, unsigned int __k) inline
Return the logarithm of the binomial coefficient as a real number. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
Parameters
__n The first argument of the binomial coefficient.
__k The second argument of the binomial coefficient.
Returns
The logarithm of the binomial coefficient.
Definition at line 4277 of file specfun.h.
lbinomialf()
float __gnu_cxx::lbinomialf (unsigned int __n, unsigned int __k) inline
Return the logarithm of the binomial coefficient as a float.
See also
lbinomial for details.
Definition at line 4248 of file specfun.h.
lbinomiall()
long double __gnu_cxx::lbinomiall (unsigned int __n, unsigned int __k) inline
Return the logarithm of the binomial coefficient as a long double.
See also
lbinomial for details.
Definition at line 4257 of file specfun.h.
ldouble_factorial()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::ldouble_factorial (int __n) inline
Return the logarithm of the double factorial of the argument as a real number.
for even and
for odd .
Definition at line 4191 of file specfun.h.
ldouble_factorialf()
float __gnu_cxx::ldouble_factorialf (int __n) inline
Return the logarithm of the double factorial of the argument as a float.
See also
ldouble_factorial for more details
Definition at line 4164 of file specfun.h.
ldouble_factoriall()
long double __gnu_cxx::ldouble_factoriall (int __n) inline
Return the logarithm of the double factorial of the argument as a long double .
See also
double_factorial for more details
Definition at line 4174 of file specfun.h.
legendre_q()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::legendre_q (unsigned int __l, _Tp __x) inline
Return the Legendre function of the second kind of nonnegative degree and real argument .
The Legendre function of the second kind of order and argument , , is defined by:
where is the Legendre polynomial of degree and is the digamma or psi function.
Template Parameters
_Tp The floating-point type of the argument __x.
Parameters
__l The degree
__x The argument abs(__x) <= 1
Exceptions
std::domain_error if abs(__x) > 1
Definition at line 4367 of file specfun.h.
legendre_qf()
float __gnu_cxx::legendre_qf (unsigned int __l, float __x) inline
Return the Legendre function of the second kind of nonnegative degree and float argument.
See also
legendre_q for details.
Definition at line 4333 of file specfun.h.
legendre_ql()
long double __gnu_cxx::legendre_ql (unsigned int __l, long double __x) inline
Return the Legendre function of the second kind of nonnegative degree and long double argument.
See also
legendre_q for details.
Definition at line 4343 of file specfun.h.
lerch_phi()
template<typename _Tp , typename _Ts , typename _Ta > __gnu_cxx::fp_promote_t<_Tp, _Ts, _Ta> __gnu_cxx::lerch_phi (_Tp __z, _Ts __s, _Ta __a) inline
Return the Lerch transcendent .
The series is:
Definition at line 7018 of file specfun.h.
lerch_phif()
float __gnu_cxx::lerch_phif (float __z, float __s, float __a) inline
Return the Lerch transcendent for float arguments.
See also
lerch_phi for details.
Definition at line 6995 of file specfun.h.
lerch_phil()
long double __gnu_cxx::lerch_phil (long double __z, long double __s, long double __a) inline
Return the Lerch transcendent for long double arguments.
See also
lerch_phi for details.
Definition at line 7005 of file specfun.h.
lfactorial()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::lfactorial (unsigned int __n) inline
Return the logarithm of the factorial of the argument as a real number.
.
Definition at line 4149 of file specfun.h.
lfactorialf()
float __gnu_cxx::lfactorialf (unsigned int __n) inline
Return the logarithm of the factorial of the argument as a float.
See also
lfactorial for more details
Definition at line 4127 of file specfun.h.
lfactoriall()
long double __gnu_cxx::lfactoriall (unsigned int __n) inline
Return the logarithm of the factorial of the argument as a long double.
See also
lfactorial for more details
Definition at line 4137 of file specfun.h.
lfalling_factorial()
template<typename _Tp , typename _Tnu > __gnu_cxx::fp_promote_t<_Tp, _Tnu> __gnu_cxx::lfalling_factorial (_Tp __a, _Tnu __nu) inline
Return the logarithm of the falling factorial function or the lower Pochhammer symbol. The falling factorial function is defined by
In particular, . Thus this function returns
Many notations exist for this function: ,
, and others.
Definition at line 3953 of file specfun.h.
lfalling_factorialf()
float __gnu_cxx::lfalling_factorialf (float __a, float __nu) inline
Return the logarithm of the falling factorial for float arguments.
See also
lfalling_factorial for details.
Definition at line 3918 of file specfun.h.
lfalling_factoriall()
long double __gnu_cxx::lfalling_factoriall (long double __a, long double __nu) inline
Return the logarithm of the falling factorial for float arguments.
See also
lfalling_factorial for details.
Definition at line 3928 of file specfun.h.
lgamma() [1/2]
template<typename _Ta > __gnu_cxx::fp_promote_t<_Ta> __gnu_cxx::lgamma (_Ta __a) inline
Return the logarithm of the gamma function for real argument.
Definition at line 2937 of file specfun.h.
Referenced by std::__detail::__gegenbauer_zeros(), std::__detail::__jacobi_zeros(), and std::__detail::__laguerre_zeros().
lgamma() [2/2]
template<typename _Ta > std::complex<__gnu_cxx::fp_promote_t<_Ta> > __gnu_cxx::lgamma (std::complex< _Ta > __a) inline
Return the logarithm of the gamma function for complex argument.
Definition at line 2970 of file specfun.h.
lgammaf() [1/2]
float __gnu_cxx::lgammaf (float __a) inline
Return the logarithm of the gamma function for float argument.
See also
lgamma for details.
Definition at line 2919 of file specfun.h.
lgammaf() [2/2]
std::complex<float> __gnu_cxx::lgammaf (std::complex< float > __a) inline
Return the logarithm of the gamma function for std::complex<float> argument.
See also
lgamma for details.
Definition at line 2952 of file specfun.h.
lgammal() [1/2]
long double __gnu_cxx::lgammal (long double __a) inline
Return the logarithm of the gamma function for long double argument.
See also
lgamma for details.
Definition at line 2929 of file specfun.h.
lgammal() [2/2]
std::complex<long double> __gnu_cxx::lgammal (std::complex< long double > __a) inline
Return the logarithm of the gamma function for std::complex<long double> argument.
See also
lgamma for details.
Definition at line 2962 of file specfun.h.
logint()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::logint (_Tp __x) inline
Return the logarithmic integral of argument .
The logarithmic integral is defined by
Parameters
__x The real upper integration limit
Definition at line 1696 of file specfun.h.
logintf()
float __gnu_cxx::logintf (float __x) inline
Return the logarithmic integral of argument .
See also
logint for details.
Definition at line 1672 of file specfun.h.
logintl()
long double __gnu_cxx::logintl (long double __x) inline
Return the logarithmic integral of argument .
See also
logint for details.
Definition at line 1681 of file specfun.h.
logistic_p()
template<typename _Ta , typename _Tb , typename _Tp > __gnu_cxx::fp_promote_t<_Ta, _Tb, _Tp> __gnu_cxx::logistic_p (_Ta __a, _Tb __b, _Tp __x) inline
Return the logistic cumulative distribution function.
The formula for the logistic probability function is
where .
Definition at line 6767 of file specfun.h.
logistic_pdf()
template<typename _Ta , typename _Tb , typename _Tp > __gnu_cxx::fp_promote_t<_Ta, _Tb, _Tp> __gnu_cxx::logistic_pdf (_Ta __a, _Tb __b, _Tp __x) inline
Return the logistic probability density function.
The formula for the logistic probability density function is
where .
Definition at line 6750 of file specfun.h.
lognormal_p()
template<typename _Tmu , typename _Tsig , typename _Tp > __gnu_cxx::fp_promote_t<_Tmu, _Tsig, _Tp> __gnu_cxx::lognormal_p (_Tmu __mu, _Tsig __sigma, _Tp __x) inline
Return the lognormal cumulative probability density function.
The formula for the lognormal cumulative probability density function is
Definition at line 6536 of file specfun.h.
lognormal_pdf()
template<typename _Tmu , typename _Tsig , typename _Tp > __gnu_cxx::fp_promote_t<_Tmu, _Tsig, _Tp> __gnu_cxx::lognormal_pdf (_Tmu __mu, _Tsig __sigma, _Tp __x) inline
Return the lognormal probability density function.
The formula for the lognormal probability density function is
Definition at line 6519 of file specfun.h.
lrising_factorial()
template<typename _Tp , typename _Tnu > __gnu_cxx::fp_promote_t<_Tp, _Tnu> __gnu_cxx::lrising_factorial (_Tp __a, _Tnu __nu) inline
Return the logarithm of the rising factorial function or the (upper) Pochhammer symbol. The rising factorial function is defined for integer order by
Thus this function returns
Many notations exist for this function: (especially in the literature of special functions),
, and others.
Definition at line 3903 of file specfun.h.
lrising_factorialf()
float __gnu_cxx::lrising_factorialf (float __a, float __nu) inline
Return the logarithm of the rising factorial for float arguments.
See also
lrising_factorial for details.
Definition at line 3869 of file specfun.h.
lrising_factoriall()
long double __gnu_cxx::lrising_factoriall (long double __a, long double __nu) inline
Return the logarithm of the rising factorial for long double arguments.
See also
lrising_factorial for details.
Definition at line 3879 of file specfun.h.
normal_p()
template<typename _Tmu , typename _Tsig , typename _Tp > __gnu_cxx::fp_promote_t<_Tmu, _Tsig, _Tp> __gnu_cxx::normal_p (_Tmu __mu, _Tsig __sigma, _Tp __x) inline
Return the normal cumulative probability density function.
The formula for the normal cumulative probability density function is
Definition at line 6503 of file specfun.h.
normal_pdf()
template<typename _Tmu , typename _Tsig , typename _Tp > __gnu_cxx::fp_promote_t<_Tmu, _Tsig, _Tp> __gnu_cxx::normal_pdf (_Tmu __mu, _Tsig __sigma, _Tp __x) inline
Return the gamma cumulative propability distribution function.
The formula for the gamma probability density function is:
template<typename _Ta, typename _Tb, typename _Tp> inline __gnu_cxx::fp_promote_t<_Ta, _Tb, _Tp> gamma_p(_Ta __alpha, _Tb __beta, _Tp __x) { using __type = __gnu_cxx::fp_promote_t<_Ta, _Tb, _Tp>; return std::__detail::__gamma_p<__type>(__alpha, __beta, __x); } Return the normal probability density function.
The formula for the normal probability density function is
Definition at line 6486 of file specfun.h.
owens_t()
template<typename _Tph , typename _Tpa > __gnu_cxx::fp_promote_t<_Tph, _Tpa> __gnu_cxx::owens_t (_Tph __h, _Tpa __a) inline
Return the Owens T function of shape factor and integration limit .
The Owens T function is defined by
Parameters
__h The shape factor
__a The integration limit
Definition at line 6023 of file specfun.h.
owens_tf()
float __gnu_cxx::owens_tf (float __h, float __a) inline
Return the Owens T function of shape factor and integration limit .
See also
owens_t for details.
Definition at line 5995 of file specfun.h.
owens_tl()
long double __gnu_cxx::owens_tl (long double __h, long double __a) inline
Return the Owens T function of long double shape factor and integration limit .
See also
owens_t for details.
Definition at line 6005 of file specfun.h.
polygamma()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::polygamma (unsigned int __m, _Tp __x) inline
Return the polygamma function of argument .
The the polygamma or digamma function is defined by
Parameters
__x The parameter
Definition at line 3611 of file specfun.h.
polygammaf()
float __gnu_cxx::polygammaf (unsigned int __m, float __x) inline
Return the polygamma function of float argument .
See also
polygamma for details.
Definition at line 3585 of file specfun.h.
polygammal()
long double __gnu_cxx::polygammal (unsigned int __m, long double __x) inline
Return the polygamma function of long double argument .
See also
polygamma for details.
Definition at line 3595 of file specfun.h.
polylog() [1/2]
template<typename _Tp , typename _Wp > __gnu_cxx::fp_promote_t<_Tp, _Wp> __gnu_cxx::polylog (_Tp __s, _Wp __w) inline
Return the polylogarithm function of real order and real argument .
The polylogarithm function is defined by
Parameters
__s Order.
__w Argument.
Definition at line 5049 of file specfun.h.
polylog() [2/2]
template<typename _Tp , typename _Wp > std::complex<__gnu_cxx::fp_promote_t<_Tp, _Wp> > __gnu_cxx::polylog (_Tp __s, std::complex< _Tp > __w) inline
Return the complex polylogarithm function of real order and complex argument .
The polylogarithm function is defined by
Parameters
__s Order.
__w Argument.
Definition at line 5089 of file specfun.h.
polylogf() [1/2]
float __gnu_cxx::polylogf (float __s, float __w) inline
Return the real polylogarithm function of real order and real argument .
See also
polylog for details.
Definition at line 5022 of file specfun.h.
polylogf() [2/2]
std::complex<float> __gnu_cxx::polylogf (float __s, std::complex< float > __w) inline
Return the complex polylogarithm function of real order and complex argument .
See also
polylog for details.
Definition at line 5062 of file specfun.h.
polylogl() [1/2]
long double __gnu_cxx::polylogl (long double __s, long double __w) inline
Return the complex polylogarithm function of real order and argument .
See also
polylog for details.
Definition at line 5032 of file specfun.h.
polylogl() [2/2]
std::complex<long double> __gnu_cxx::polylogl (long double __s, std::complex< long double > __w) inline
Return the complex polylogarithm function of real order and complex argument .
See also
polylog for details.
Definition at line 5072 of file specfun.h.
radpoly()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::radpoly (unsigned int __n, unsigned int __m, _Tp __rho) inline
Return the radial polynomial for non-negative degree , order , and real radial argument .
The radial polynomials are defined by
for even and identically 0 for odd. The radial polynomials can be related to the Jacobi polynomials:
See also
jacobi for details on the Jacobi polynomials.
Template Parameters
_Tp The real type of the radial coordinate
Parameters
__n The non-negative degree.
__m The non-negative azimuthal order
__rho The radial argument
Definition at line 2418 of file specfun.h.
radpolyf()
float __gnu_cxx::radpolyf (unsigned int __n, unsigned int __m, float __rho) inline
Return the radial polynomial for non-negative degree , order , and float radial argument .
See also
radpoly for details.
Definition at line 2379 of file specfun.h.
References std::__detail::__radial_jacobi().
radpolyl()
long double __gnu_cxx::radpolyl (unsigned int __n, unsigned int __m, long double __rho) inline
Return the radial polynomial for non-negative degree , order , and long double radial argument .
See also
radpoly for details.
Definition at line 2390 of file specfun.h.
References std::__detail::__radial_jacobi().
rising_factorial()
template<typename _Tp , typename _Tnu > __gnu_cxx::fp_promote_t<_Tp, _Tnu> __gnu_cxx::rising_factorial (_Tp __a, _Tnu __nu) inline
Return the rising factorial function or the (upper) Pochhammer function. The rising factorial function is defined by
Many notations exist for this function: , (especially in the literature of special functions),
, and others.
Definition at line 3996 of file specfun.h.
rising_factorialf()
float __gnu_cxx::rising_factorialf (float __a, float __nu) inline
Return the rising factorial for float arguments.
See also
rising_factorial for details.
Definition at line 3968 of file specfun.h.
rising_factoriall()
long double __gnu_cxx::rising_factoriall (long double __a, long double __nu) inline
Return the rising factorial for long double arguments.
See also
rising_factorial for details.
Definition at line 3978 of file specfun.h.
sin_pi()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::sin_pi (_Tp __x) inline
Return the reperiodized sine function for real argument .
The reperiodized sine function is defined by:
Template Parameters
_Tp The floating-point type of the argument __x.
Parameters
__x The argument
Definition at line 6153 of file specfun.h.
sin_pif()
float __gnu_cxx::sin_pif (float __x) inline
Return the reperiodized sine function for float argument .
See also
sin_pi for more details.
Definition at line 6126 of file specfun.h.
sin_pil()
long double __gnu_cxx::sin_pil (long double __x) inline
Return the reperiodized sine function for long double argument .
See also
sin_pi for more details.
Definition at line 6136 of file specfun.h.
sinc()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::sinc (_Tp __x) inline
Return the sinus cardinal function for real argument __x. The sinus cardinal function is defined by:
Template Parameters
_Tp The real type of the argument
Parameters
__x The argument
Definition at line 1617 of file specfun.h.
sinc_pi()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::sinc_pi (_Tp __x) inline
Return the reperiodized sinus cardinal function for real argument __x. The normalized sinus cardinal function is defined by:
Template Parameters
_Tp The real type of the argument
Parameters
__x The argument
Definition at line 1658 of file specfun.h.
sinc_pif()
float __gnu_cxx::sinc_pif (float __x) inline
Return the reperiodized sinus cardinal function for float argument __x.
See also
sinc for details.
Definition at line 1632 of file specfun.h.
sinc_pil()
long double __gnu_cxx::sinc_pil (long double __x) inline
Return the reperiodized sinus cardinal function for long double argument __x.
See also
sinc for details.
Definition at line 1642 of file specfun.h.
sincf()
float __gnu_cxx::sincf (float __x) inline
Return the sinus cardinal function for float argument __x.
See also
sinc_pi for details.
Definition at line 1591 of file specfun.h.
sincl()
long double __gnu_cxx::sincl (long double __x) inline
Return the sinus cardinal function for long double argument __x.
See also
sinc_pi for details.
Definition at line 1601 of file specfun.h.
sincos() [1/2]
__gnu_cxx::__sincos_t<double> __gnu_cxx::sincos (double __x) inline
Return both the sine and the cosine of a double argument.
See also
sincos for details.
Definition at line 6391 of file specfun.h.
sincos() [2/2]
template<typename _Tp > __gnu_cxx::__sincos_t<__gnu_cxx::fp_promote_t<_Tp> > __gnu_cxx::sincos (_Tp __x) inline
Return both the sine and the cosine of a reperiodized argument.
Definition at line 6402 of file specfun.h.
sincos_pi()
template<typename _Tp > __gnu_cxx::__sincos_t<__gnu_cxx::fp_promote_t<_Tp> > __gnu_cxx::sincos_pi (_Tp __x) inline
Return both the sine and the cosine of a reperiodized real argument.
Definition at line 6436 of file specfun.h.
sincos_pif()
__gnu_cxx::__sincos_t<float> __gnu_cxx::sincos_pif (float __x) inline
Return both the sine and the cosine of a reperiodized float argument.
See also
sincos_pi for details.
Definition at line 6414 of file specfun.h.
sincos_pil()
__gnu_cxx::__sincos_t<long double> __gnu_cxx::sincos_pil (long double __x) inline
Return both the sine and the cosine of a reperiodized long double argument.
See also
sincos_pi for details.
Definition at line 6424 of file specfun.h.
sincosf()
__gnu_cxx::__sincos_t<float> __gnu_cxx::sincosf (float __x) inline
Return both the sine and the cosine of a float argument.
Definition at line 6373 of file specfun.h.
sincosl()
__gnu_cxx::__sincos_t<long double> __gnu_cxx::sincosl (long double __x) inline
Return both the sine and the cosine of a long double argument.
See also
sincos for details.
Definition at line 6382 of file specfun.h.
sinh_pi()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::sinh_pi (_Tp __x) inline
Return the reperiodized hyperbolic sine function for real argument .
The reperiodized hyperbolic sine function is defined by:
Template Parameters
_Tp The floating-point type of the argument __x.
Parameters
__x The argument
Definition at line 6195 of file specfun.h.
sinh_pif()
float __gnu_cxx::sinh_pif (float __x) inline
Return the reperiodized hyperbolic sine function for float argument .
See also
sinh_pi for more details.
Definition at line 6168 of file specfun.h.
sinh_pil()
long double __gnu_cxx::sinh_pil (long double __x) inline
Return the reperiodized hyperbolic sine function for long double argument .
See also
sinh_pi for more details.
Definition at line 6178 of file specfun.h.
sinhc()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::sinhc (_Tp __x) inline
Return the normalized hyperbolic sinus cardinal function for real argument __x. The normalized hyperbolic sinus cardinal function is defined by:
Template Parameters
_Tp The real type of the argument
Parameters
__x The argument
Definition at line 2500 of file specfun.h.
sinhc_pi()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::sinhc_pi (_Tp __x) inline
Return the hyperbolic sinus cardinal function for real argument __x. The sinus cardinal function is defined by:
Template Parameters
_Tp The real type of the argument
Parameters
__x The argument
Definition at line 2459 of file specfun.h.
sinhc_pif()
float __gnu_cxx::sinhc_pif (float __x) inline
Return the hyperbolic sinus cardinal function for float argument __x.
See also
sinhc_pi for details.
Definition at line 2433 of file specfun.h.
sinhc_pil()
long double __gnu_cxx::sinhc_pil (long double __x) inline
Return the hyperbolic sinus cardinal function for long double argument __x.
See also
sinhc_pi for details.
Definition at line 2443 of file specfun.h.
sinhcf()
float __gnu_cxx::sinhcf (float __x) inline
Return the normalized hyperbolic sinus cardinal function for float argument __x.
See also
sinhc for details.
Definition at line 2474 of file specfun.h.
sinhcl()
long double __gnu_cxx::sinhcl (long double __x) inline
Return the normalized hyperbolic sinus cardinal function for long double argument __x.
See also
sinhc for details.
Definition at line 2484 of file specfun.h.
sinhint()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::sinhint (_Tp __x) inline
Return the hyperbolic sine integral of real argument .
The hyperbolic sine integral is defined by
Template Parameters
_Tp The type of the real argument
Parameters
__x The argument
Definition at line 1816 of file specfun.h.
sinhintf()
float __gnu_cxx::sinhintf (float __x) inline
Return the hyperbolic sine integral of float argument .
See also
sinhint for details.
Definition at line 1789 of file specfun.h.
sinhintl()
long double __gnu_cxx::sinhintl (long double __x) inline
Return the hyperbolic sine integral of long double argument .
See also
sinhint for details.
Definition at line 1799 of file specfun.h.
sinint()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::sinint (_Tp __x) inline
Return the sine integral of real argument .
The sine integral is defined by
Parameters
__x The real upper integration limit
Definition at line 1735 of file specfun.h.
sinintf()
float __gnu_cxx::sinintf (float __x) inline
Return the sine integral of float argument .
See also
sinint for details.
Definition at line 1710 of file specfun.h.
sinintl()
long double __gnu_cxx::sinintl (long double __x) inline
Return the sine integral of long double argument .
See also
sinint for details.
Definition at line 1720 of file specfun.h.
sph_bessel_i()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::sph_bessel_i (unsigned int __n, _Tp __x) inline
Return the regular modified spherical Bessel function of nonnegative order n and real argument .
The spherical Bessel function is defined by:
Template Parameters
_Tp The floating-point type of the argument __x.
Parameters
__n The integral order n >= 0
__x The real argument x >= 0
Exceptions
std::domain_error if __x < 0 .
Definition at line 2736 of file specfun.h.
sph_bessel_if()
float __gnu_cxx::sph_bessel_if (unsigned int __n, float __x) inline
Return the regular modified spherical Bessel function of nonnegative order n and float argument .
See also
sph_bessel_i for details.
Definition at line 2707 of file specfun.h.
sph_bessel_il()
long double __gnu_cxx::sph_bessel_il (unsigned int __n, long double __x) inline
Return the regular modified spherical Bessel function of nonnegative order n and long double argument .
See also
sph_bessel_i for details.
Definition at line 2717 of file specfun.h.
sph_bessel_k()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::sph_bessel_k (unsigned int __n, _Tp __x) inline
Return the irregular modified spherical Bessel function of nonnegative order n and real argument .
The spherical Bessel function is defined by:
Template Parameters
_Tp The floating-point type of the argument __x.
Parameters
__n The integral order n >= 0
__x The real argument x >= 0
Exceptions
std::domain_error if __x < 0 .
Definition at line 2780 of file specfun.h.
sph_bessel_kf()
float __gnu_cxx::sph_bessel_kf (unsigned int __n, float __x) inline
Return the irregular modified spherical Bessel function of nonnegative order n and float argument .
See also
sph_bessel_k for more details.
Definition at line 2751 of file specfun.h.
sph_bessel_kl()
long double __gnu_cxx::sph_bessel_kl (unsigned int __n, long double __x) inline
Return the irregular modified spherical Bessel function of nonnegative order n and long double argument .
See also
sph_bessel_k for more details.
Definition at line 2761 of file specfun.h.
sph_hankel_1() [1/2]
template<typename _Tp > std::complex<__gnu_cxx::fp_promote_t<_Tp> > __gnu_cxx::sph_hankel_1 (unsigned int __n, _Tp __z) inline
Return the spherical Hankel function of the first kind of nonnegative order and real argument .
The spherical Hankel function of the first kind is defined by:
or in terms of the cylindrical Bessel and Neumann functions by:
Template Parameters
_Tp The real type of the argument
Parameters
__n The non-negative order
__z The real argument
Definition at line 2644 of file specfun.h.
sph_hankel_1() [2/2]
template<typename _Tp > std::complex<__gnu_cxx::fp_promote_t<_Tp> > __gnu_cxx::sph_hankel_1 (unsigned int __n, std::complex< _Tp > __x) inline
Return the complex spherical Hankel function of the first kind of non-negative integral and complex argument .
The spherical Hankel function of the first kind is defined by
where and are the spherical Bessel and Neumann functions respectively.
Parameters
__n The integral order >= 0
__x The complex argument
Definition at line 4906 of file specfun.h.
sph_hankel_1f() [1/2]
std::complex<float> __gnu_cxx::sph_hankel_1f (unsigned int __n, float __z) inline
Return the spherical Hankel function of the first kind of nonnegative order n and float argument .
See also
sph_hankel_1 for details.
Definition at line 2611 of file specfun.h.
sph_hankel_1f() [2/2]
std::complex<float> __gnu_cxx::sph_hankel_1f (unsigned int __n, std::complex< float > __x) inline
Return the complex spherical Hankel function of the first kind of non-negative integral and std::complex<float> argument .
See also
sph_hankel_1 for more details.
Definition at line 4874 of file specfun.h.
sph_hankel_1l() [1/2]
std::complex<long double> __gnu_cxx::sph_hankel_1l (unsigned int __n, long double __z) inline
Return the spherical Hankel function of the first kind of nonnegative order n and long double argument .
See also
sph_hankel_1 for details.
Definition at line 2621 of file specfun.h.
sph_hankel_1l() [2/2]
std::complex<long double> __gnu_cxx::sph_hankel_1l (unsigned int __n, std::complex< long double > __x) inline
Return the complex spherical Hankel function of the first kind of non-negative integral and std::complex<long double> argument .
See also
sph_hankel_1 for more details.
Definition at line 4885 of file specfun.h.
sph_hankel_2() [1/2]
template<typename _Tp > std::complex<__gnu_cxx::fp_promote_t<_Tp> > __gnu_cxx::sph_hankel_2 (unsigned int __n, _Tp __z) inline
Return the spherical Hankel function of the second kind of nonnegative order and real argument .
The spherical Hankel function of the second kind is defined by:
or in terms of the cylindrical Bessel and Neumann functions by:
Template Parameters
_Tp The real type of the argument
Parameters
__n The non-negative order
__z The real argument
Definition at line 2692 of file specfun.h.
sph_hankel_2() [2/2]
template<typename _Tp > std::complex<__gnu_cxx::fp_promote_t<_Tp> > __gnu_cxx::sph_hankel_2 (unsigned int __n, std::complex< _Tp > __x) inline
Return the complex spherical Hankel function of the second kind of nonnegative order and complex argument .
The spherical Hankel function of the second kind is defined by
where and are the spherical Bessel and Neumann functions respectively.
Parameters
__n The integral order >= 0
__x The complex argument
Definition at line 4954 of file specfun.h.
sph_hankel_2f() [1/2]
std::complex<float> __gnu_cxx::sph_hankel_2f (unsigned int __n, float __z) inline
Return the spherical Hankel function of the second kind of nonnegative order n and float argument .
See also
sph_hankel_2 for details.
Definition at line 2659 of file specfun.h.
sph_hankel_2f() [2/2]
std::complex<float> __gnu_cxx::sph_hankel_2f (unsigned int __n, std::complex< float > __x) inline
Return the complex spherical Hankel function of the second kind of non-negative integral and std::complex<float> argument .
See also
sph_hankel_2 for more details.
Definition at line 4922 of file specfun.h.
sph_hankel_2l() [1/2]
std::complex<long double> __gnu_cxx::sph_hankel_2l (unsigned int __n, long double __z) inline
Return the spherical Hankel function of the second kind of nonnegative order n and long double argument .
See also
sph_hankel_2 for details.
Definition at line 2669 of file specfun.h.
sph_hankel_2l() [2/2]
std::complex<long double> __gnu_cxx::sph_hankel_2l (unsigned int __n, std::complex< long double > __x) inline
Return the complex spherical Hankel function of the second kind of non-negative integral and std::complex<long double> argument .
See also
sph_hankel_2 for more details.
Definition at line 4933 of file specfun.h.
sph_harmonic()
template<typename _Ttheta , typename _Tphi > std::complex<__gnu_cxx::fp_promote_t<_Ttheta, _Tphi> > __gnu_cxx::sph_harmonic (unsigned int __l, int __m, _Ttheta __theta, _Tphi __phi) inline
Return the complex spherical harmonic function of degree , order , and real zenith angle , and azimuth angle .
The spherical harmonic function is defined by:
Note
if .
Parameters
__l The order
__m The degree
__theta The zenith angle in radians
__phi The azimuth angle in radians
Definition at line 5007 of file specfun.h.
sph_harmonicf()
std::complex<float> __gnu_cxx::sph_harmonicf (unsigned int __l, int __m, float __theta, float __phi) inline
Return the complex spherical harmonic function of degree , order , and float zenith angle , and azimuth angle .
See also
sph_harmonic for details.
Definition at line 4970 of file specfun.h.
sph_harmonicl()
std::complex<long double> __gnu_cxx::sph_harmonicl (unsigned int __l, int __m, long double __theta, long double __phi) inline
Return the complex spherical harmonic function of degree , order , and long double zenith angle , and azimuth angle .
See also
sph_harmonic for details.
Definition at line 4982 of file specfun.h.
stirling_1()
template<typename _Tp > _Tp __gnu_cxx::stirling_1 (unsigned int __n, unsigned int __m) inline
Return the Stirling number of the first kind.
The Stirling numbers of the first kind are the coefficients of the Pocchammer polynomials or the rising factorials:
The recursion is
with starting values
and
The Stirling number of the first kind is denoted by other symbols in the literature, usually .
Todo:
Develop an iterator model for Stirling numbers of the first kind.
Definition at line 6963 of file specfun.h.
stirling_2()
template<typename _Tp > _Tp __gnu_cxx::stirling_2 (unsigned int __n, unsigned int __m) inline
Return the Stirling number of the second kind by series expansion or by recursion.
The series is:
The Stirling number of the second kind is denoted by other symbols in the literature: , and others.
Todo:
Develop an iterator model for Stirling numbers of the second kind.
Definition at line 6986 of file specfun.h.
student_t_p()
template<typename _Tt , typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::student_t_p (_Tt __t, unsigned int __nu)
Return the Students T probability function.
The students T propability function is related to the incomplete beta function:
Parameters
__t
__nu
Definition at line 6623 of file specfun.h.
student_t_pdf()
template<typename _Tt , typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::student_t_pdf (_Tt __t, unsigned int __nu)
Return the complement of the Students T probability function.
The complement of the students T propability function is:
Parameters
__t
__nu
Definition at line 6643 of file specfun.h.
tan_pi()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::tan_pi (_Tp __x) inline
Return the reperiodized tangent function for real argument .
The reperiodized tangent function is defined by:
Template Parameters
_Tp The floating-point type of the argument __x.
Parameters
__x The argument
Definition at line 6321 of file specfun.h.
tan_pif()
float __gnu_cxx::tan_pif (float __x) inline
Return the reperiodized tangent function for float argument .
See also
tan_pi for more details.
Definition at line 6294 of file specfun.h.
tan_pil()
long double __gnu_cxx::tan_pil (long double __x) inline
Return the reperiodized tangent function for long double argument .
See also
tan_pi for more details.
Definition at line 6304 of file specfun.h.
tanh_pi()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> __gnu_cxx::tanh_pi (_Tp __x) inline
Return the reperiodized hyperbolic tangent function for real argument .
The reperiodized hyperbolic tangent function is defined by:
Template Parameters
_Tp The floating-point type of the argument __x.
Parameters
__x The argument
Definition at line 6363 of file specfun.h.
tanh_pif()
float __gnu_cxx::tanh_pif (float __x) inline
Return the reperiodized hyperbolic tangent function for float argument .
See also
tanh_pi for more details.
Definition at line 6336 of file specfun.h.
tanh_pil()
long double __gnu_cxx::tanh_pil (long double __x) inline
Return the reperiodized hyperbolic tangent function for long double argument .
See also
tanh_pi for more details.
Definition at line 6346 of file specfun.h.
tgamma() [1/3]
template<typename _Ta > __gnu_cxx::fp_promote_t<_Ta> __gnu_cxx::tgamma (_Ta __a) inline
Return the gamma function for real argument.
Definition at line 3002 of file specfun.h.
Referenced by std::__detail::__tricomi_u_naive().
tgamma() [2/3]
template<typename _Ta > std::complex<__gnu_cxx::fp_promote_t<_Ta> > __gnu_cxx::tgamma (std::complex< _Ta > __a) inline
Return the gamma function for complex argument.
Definition at line 3034 of file specfun.h.
tgamma() [3/3]
template<typename _Ta , typename _Tp > __gnu_cxx::fp_promote_t<_Ta, _Tp> __gnu_cxx::tgamma (_Ta __a, _Tp __x) inline
Return the upper incomplete gamma function . The (upper) incomplete gamma function is defined by
Definition at line 3071 of file specfun.h.
tgamma_lower()
template<typename _Ta , typename _Tp > __gnu_cxx::fp_promote_t<_Ta, _Tp> __gnu_cxx::tgamma_lower (_Ta __a, _Tp __x) inline
Return the lower incomplete gamma function . The lower incomplete gamma function is defined by
Definition at line 3108 of file specfun.h.
tgamma_lowerf()
float __gnu_cxx::tgamma_lowerf (float __a, float __x) inline
Return the lower incomplete gamma function for float argument.
See also
tgamma_lower for details.
Definition at line 3086 of file specfun.h.
tgamma_lowerl()
long double __gnu_cxx::tgamma_lowerl (long double __a, long double __x) inline
Return the lower incomplete gamma function for long double argument.
See also
tgamma_lower for details.
Definition at line 3096 of file specfun.h.
tgammaf() [1/3]
float __gnu_cxx::tgammaf (float __a) inline
Return the gamma function for float argument.
See also
lgamma for details.
Definition at line 2984 of file specfun.h.
tgammaf() [2/3]
std::complex<float> __gnu_cxx::tgammaf (std::complex< float > __a) inline
Return the gamma function for std::complex<float> argument.
See also
lgamma for details.
Definition at line 3016 of file specfun.h.
tgammaf() [3/3]
float __gnu_cxx::tgammaf (float __a, float __x) inline
Return the upper incomplete gamma function for float argument.
See also
tgamma for details.
Definition at line 3049 of file specfun.h.
tgammal() [1/3]
long double __gnu_cxx::tgammal (long double __a) inline
Return the gamma function for long double argument.
See also
lgamma for details.
Definition at line 2994 of file specfun.h.
tgammal() [2/3]
std::complex<long double> __gnu_cxx::tgammal (std::complex< long double > __a) inline
Return the gamma function for std::complex<long double> argument.
See also
lgamma for details.
Definition at line 3026 of file specfun.h.
tgammal() [3/3]
long double __gnu_cxx::tgammal (long double __a, long double __x) inline
Return the upper incomplete gamma function for long double argument.
See also
tgamma for details.
Definition at line 3059 of file specfun.h.
theta_1()
template<typename _Tpnu , typename _Tp > __gnu_cxx::fp_promote_t<_Tpnu, _Tp> __gnu_cxx::theta_1 (_Tpnu __nu, _Tp __x) inline
Return the exponential theta-1 function of period and argument .
The exponential theta-1 function is defined by
Parameters
__nu The periodic (period = 2) argument
__x The argument
Definition at line 5449 of file specfun.h.
theta_1f()
float __gnu_cxx::theta_1f (float __nu, float __x) inline
Return the exponential theta-1 function of period and argument .
See also
theta_1 for details.
Definition at line 5421 of file specfun.h.
theta_1l()
long double __gnu_cxx::theta_1l (long double __nu, long double __x) inline
Return the exponential theta-1 function of period and argument .
See also
theta_1 for details.
Definition at line 5431 of file specfun.h.
theta_2()
template<typename _Tpnu , typename _Tp > __gnu_cxx::fp_promote_t<_Tpnu, _Tp> __gnu_cxx::theta_2 (_Tpnu __nu, _Tp __x) inline
Return the exponential theta-2 function of period and argument .
The exponential theta-2 function is defined by
Parameters
__nu The periodic (period = 2) argument
__x The argument
Definition at line 5492 of file specfun.h.
theta_2f()
float __gnu_cxx::theta_2f (float __nu, float __x) inline
Return the exponential theta-2 function of period and argument .
See also
theta_2 for details.
Definition at line 5464 of file specfun.h.
theta_2l()
long double __gnu_cxx::theta_2l (long double __nu, long double __x) inline
Return the exponential theta-2 function of period and argument .
See also
theta_2 for details.
Definition at line 5474 of file specfun.h.
theta_3()
template<typename _Tpnu , typename _Tp > __gnu_cxx::fp_promote_t<_Tpnu, _Tp> __gnu_cxx::theta_3 (_Tpnu __nu, _Tp __x) inline
Return the exponential theta-3 function of period and argument .
The exponential theta-3 function is defined by
Parameters
__nu The periodic (period = 1) argument
__x The argument
Definition at line 5535 of file specfun.h.
theta_3f()
float __gnu_cxx::theta_3f (float __nu, float __x) inline
Return the exponential theta-3 function of period and argument .
See also
theta_3 for details.
Definition at line 5507 of file specfun.h.
theta_3l()
long double __gnu_cxx::theta_3l (long double __nu, long double __x) inline
Return the exponential theta-3 function of period and argument .
See also
theta_3 for details.
Definition at line 5517 of file specfun.h.
theta_4()
template<typename _Tpnu , typename _Tp > __gnu_cxx::fp_promote_t<_Tpnu, _Tp> __gnu_cxx::theta_4 (_Tpnu __nu, _Tp __x) inline
Return the exponential theta-4 function of period and argument .
The exponential theta-4 function is defined by
Parameters
__nu The periodic (period = 1) argument
__x The argument
Definition at line 5578 of file specfun.h.
theta_4f()
float __gnu_cxx::theta_4f (float __nu, float __x) inline
Return the exponential theta-4 function of period and argument .
See also
theta_4 for details.
Definition at line 5550 of file specfun.h.
theta_4l()
long double __gnu_cxx::theta_4l (long double __nu, long double __x) inline
Return the exponential theta-4 function of period and argument .
See also
theta_4 for details.
Definition at line 5560 of file specfun.h.
theta_c()
template<typename _Tpk , typename _Tp > __gnu_cxx::fp_promote_t<_Tpk, _Tp> __gnu_cxx::theta_c (_Tpk __k, _Tp __x) inline
Return the Neville theta-c function of modulus and argument .
The Neville theta-c function is defined by
where is the elliptic nome, is the complete Legendre elliptic integral of the first kind, and is the exponential theta-1 function.
See also
ellnome, std::comp_ellint_1, and theta_1 for details.
Parameters
__k The modulus
__x The argument
Definition at line 5714 of file specfun.h.
theta_cf()
float __gnu_cxx::theta_cf (float __k, float __x) inline
Return the Neville theta-c function of modulus and argument .
See also
theta_c for details.
Definition at line 5682 of file specfun.h.
theta_cl()
long double __gnu_cxx::theta_cl (long double __k, long double __x) inline
Return the Neville theta-c function of long double modulus and argument .
See also
theta_c for details.
Definition at line 5692 of file specfun.h.
theta_d()
template<typename _Tpk , typename _Tp > __gnu_cxx::fp_promote_t<_Tpk, _Tp> __gnu_cxx::theta_d (_Tpk __k, _Tp __x) inline
Return the Neville theta-d function of modulus and argument .
The Neville theta-d function is defined by
where is the elliptic nome, is the complete Legendre elliptic integral of the first kind, and is the exponential theta-3 function.
See also
ellnome, std::comp_ellint_1, and theta_3 for details.
Parameters
__k The modulus
__x The argument
Definition at line 5761 of file specfun.h.
theta_df()
float __gnu_cxx::theta_df (float __k, float __x) inline
Return the Neville theta-d function of modulus and argument .
See also
theta_d for details.
Definition at line 5729 of file specfun.h.
theta_dl()
long double __gnu_cxx::theta_dl (long double __k, long double __x) inline
Return the Neville theta-d function of long double modulus and argument .
See also
theta_d for details.
Definition at line 5739 of file specfun.h.
theta_n()
template<typename _Tpk , typename _Tp > __gnu_cxx::fp_promote_t<_Tpk, _Tp> __gnu_cxx::theta_n (_Tpk __k, _Tp __x) inline
Return the Neville theta-n function of modulus and argument .
The Neville theta-n function is defined by
where is the elliptic nome, is the complete Legendre elliptic integral of the first kind, and is the exponential theta-4 function.
See also
ellnome, std::comp_ellint_1, and theta_4 for details.
Parameters
__k The modulus
__x The argument
Definition at line 5808 of file specfun.h.
theta_nf()
float __gnu_cxx::theta_nf (float __k, float __x) inline
Return the Neville theta-n function of modulus and argument .
See also
theta_n for details.
Definition at line 5776 of file specfun.h.
theta_nl()
long double __gnu_cxx::theta_nl (long double __k, long double __x) inline
Return the Neville theta-n function of long double modulus and argument .
See also
theta_n for details.
Definition at line 5786 of file specfun.h.
theta_s()
template<typename _Tpk , typename _Tp > __gnu_cxx::fp_promote_t<_Tpk, _Tp> __gnu_cxx::theta_s (_Tpk __k, _Tp __x) inline
Return the Neville theta-s function of modulus and argument .
The Neville theta-s function is defined by
where is the elliptic nome, is the complete Legendre elliptic integral of the first kind, and is the exponential theta-1 function.
See also
ellnome, std::comp_ellint_1, and theta_1 for details.
Parameters
__k The modulus
__x The argument
Definition at line 5667 of file specfun.h.
theta_sf()
float __gnu_cxx::theta_sf (float __k, float __x) inline
Return the Neville theta-s function of modulus and argument .
See also
theta_s for details.
Definition at line 5635 of file specfun.h.
theta_sl()
long double __gnu_cxx::theta_sl (long double __k, long double __x) inline
Return the Neville theta-s function of long double modulus and argument .
See also
theta_s for details.
Definition at line 5645 of file specfun.h.
tricomi_u()
template<typename _Tpa , typename _Tpc , typename _Tp > __gnu_cxx::fp_promote_t<_Tpa, _Tpc, _Tp> __gnu_cxx::tricomi_u (_Tpa __a, _Tpc __c, _Tp __x) inline
Return the Tricomi confluent hypergeometric function of real numerator parameter , denominator parameter , and argument .
The Tricomi confluent hypergeometric function is defined by
where if the confluent hypergeometric function.
See also
conf_hyperg.
Parameters
__a The numerator parameter
__c The denominator parameter
__x The argument
Definition at line 1481 of file specfun.h.
tricomi_uf()
float __gnu_cxx::tricomi_uf (float __a, float __c, float __x) inline
Return the Tricomi confluent hypergeometric function of float numerator parameter , denominator parameter , and argument .
See also
tricomi_u for details.
Definition at line 1447 of file specfun.h.
tricomi_ul()
long double __gnu_cxx::tricomi_ul (long double __a, long double __c, long double __x) inline
Return the Tricomi confluent hypergeometric function of long double numerator parameter , denominator parameter , and argument .
See also
tricomi_u for details.
Definition at line 1458 of file specfun.h.
weibull_p()
template<typename _Ta , typename _Tb , typename _Tp > __gnu_cxx::fp_promote_t<_Ta, _Tb, _Tp> __gnu_cxx::weibull_p (_Ta __a, _Tb __b, _Tp __x) inline
Return the Weibull cumulative probability density function.
The formula for the Weibull cumulative probability density function is
Definition at line 6603 of file specfun.h.
weibull_pdf()
template<typename _Ta , typename _Tb , typename _Tp > __gnu_cxx::fp_promote_t<_Ta, _Tb, _Tp> __gnu_cxx::weibull_pdf (_Ta __a, _Tb __b, _Tp __x) inline
Return the Weibull probability density function.
The formula for the Weibull probability density function is
Definition at line 6587 of file specfun.h.
zernike()
template<typename _Trho , typename _Tphi > __gnu_cxx::fp_promote_t<_Trho, _Tphi> __gnu_cxx::zernike (unsigned int __n, int __m, _Trho __rho, _Tphi __phi) inline
Return the Zernicke polynomial for non-negative degree , signed order , and real radial argument and azimuthal angle .
The even Zernicke polynomials are defined by:
and the odd Zernicke polynomials are defined by:
for non-negative degree and and where is the radial polynomial (
See also
radpoly).
Template Parameters
_Trho The real type of the radial coordinate
_Tphi The real type of the azimuthal angle
Parameters
__n The non-negative degree.
__m The (signed) azimuthal order
__rho The radial coordinate
__phi The azimuthal angle
Definition at line 2363 of file specfun.h.
zernikef()
float __gnu_cxx::zernikef (unsigned int __n, int __m, float __rho, float __phi) inline
Return the Zernicke polynomial for non-negative degree , signed order , and real radial argument and azimuthal angle .
See also
zernike for details.
Definition at line 2324 of file specfun.h.
zernikel()
long double __gnu_cxx::zernikel (unsigned int __n, int __m, long double __rho, long double __phi) inline
Return the Zernicke polynomial for non-negative degree , signed order , and real radial argument and azimuthal angle .
See also
zernike for details.
Definition at line 2335 of file specfun.h.