C++ Special Math Functions: std::__detail Namespace Reference
std::__detail Namespace Reference
Implementation-space details.
Classes
struct __gamma_lanczos_data
struct __gamma_lanczos_data< double >
struct __gamma_lanczos_data< float >
struct __gamma_lanczos_data< long double >
struct __gamma_spouge_data
struct __gamma_spouge_data< double >
struct __gamma_spouge_data< float >
struct __gamma_spouge_data< long double >
struct __jacobi_lattice_t
struct __jacobi_theta_0_t
struct __weierstrass_invariants_t
struct __weierstrass_roots_t
class _Airy
class _Airy_asymp
struct _Airy_asymp_data
struct _Airy_asymp_data< double >
struct _Airy_asymp_data< float >
struct _Airy_asymp_data< long double >
class _Airy_asymp_series
struct _Airy_default_radii
struct _Airy_default_radii< double >
struct _Airy_default_radii< float >
struct _Airy_default_radii< long double >
class _Airy_series
struct _AiryAuxilliaryState
struct _AiryState
class _AsympTerminator
struct _Factorial_table
class _Terminator
Functions
template<typename _Tp >
__gnu_cxx::__airy_t< _Tp, _Tp > __airy (_Tp __z)
Compute the Airy functions and and their first derivatives and respectively.
template<typename _Tp >
std::complex< _Tp > __airy_ai (std::complex< _Tp > __z)
Return the complex Airy Ai function.
template<typename _Tp >
void __airy_arg (std::complex< _Tp > __num2d3, std::complex< _Tp > __zeta, std::complex< _Tp > &__argp, std::complex< _Tp > &__argm)
Compute the arguments for the Airy function evaluations carefully to prevent premature overflow. Note that the major work here is in safe_div. A faster, but less safe implementation can be obtained without use of safe_div.
template<typename _Tp >
std::complex< _Tp > __airy_bi (std::complex< _Tp > __z)
Return the complex Airy Bi function.
template<typename _Tpa , typename _Tp >
_Tp __assoc_laguerre (unsigned int __n, _Tpa __alpha, _Tp __x)
This routine returns the associated Laguerre polynomial of degree n, order m: .
template<typename _Tp >
__gnu_cxx::__assoc_legendre_p_t< _Tp > __assoc_legendre_p (unsigned int __l, unsigned int __m, _Tp __x, _Tp __phase=_Tp{+1})
Return the associated Legendre function by recursion on and downward recursion on m.
template<typename _Tp >
__gnu_cxx::__assoc_legendre_q_t< _Tp > __assoc_legendre_q (unsigned int __l, unsigned int __m, _Tp __x, _Tp __phase=_Tp{+1})
template<typename _Tp >
std::vector< _Tp > __bell (unsigned int __n)
template<typename _Tp , typename _Up >
_Up __bell (unsigned int __n, _Up __x)
template<typename _Tp >
std::vector< _Tp > __bell_series (unsigned int __n)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __bernoulli (unsigned int __n)
This returns Bernoulli number .
template<typename _Tp >
_Tp __bernoulli (unsigned int __n, _Tp __x)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __bernoulli_2n (unsigned int __n)
This returns Bernoulli number at even integer arguments .
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __bernoulli_series (unsigned int __n)
This returns Bernoulli numbers from a table or by summation for larger values.
.
template<typename _Tp >
_Tp __beta (_Tp __a, _Tp __b)
Return the beta function .
template<typename _Tp >
_Tp __beta_gamma (_Tp __a, _Tp __b)
Return the beta function: .
template<typename _Tp >
_Tp __beta_inc (_Tp __a, _Tp __b, _Tp __x)
template<typename _Tp >
_Tp __beta_lgamma (_Tp __a, _Tp __b)
Return the beta function using the log gamma functions.
template<typename _Tp >
_Tp __beta_p (_Tp __a, _Tp __b, _Tp __x)
template<typename _Tp >
_Tp __beta_product (_Tp __a, _Tp __b)
Return the beta function using the product form.
template<typename _Tp >
_Tp __binomial (unsigned int __n, unsigned int __k)
Return the binomial coefficient. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
template<typename _Tp >
_Tp __binomial (_Tp __nu, unsigned int __k)
Return the binomial coefficient for non-integral degree. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
template<typename _Tp >
_Tp __binomial_p (_Tp __p, unsigned int __n, unsigned int __k)
Return the binomial cumulative distribution function.
template<typename _Tp >
_Tp __binomial_pdf (_Tp __p, unsigned int __n, unsigned int __k)
Return the binomial probability mass function.
template<typename _Tp >
_Tp __binomial_q (_Tp __p, unsigned int __n, unsigned int __k)
Return the complementary binomial cumulative distribution function.
template<typename _Sp , typename _Tp >
_Tp __bose_einstein (_Sp __s, _Tp __x)
template<typename _Tp >
_Tp __cauchy_p (_Tp __a, _Tp __b, _Tp __x)
template<typename _Tp >
std::tuple< _Tp, _Tp, _Tp > __chebyshev_recur (unsigned int __n, _Tp __x, _Tp _C0, _Tp _C1)
template<typename _Tp >
__gnu_cxx::__chebyshev_t_t< _Tp > __chebyshev_t (unsigned int __n, _Tp __x)
template<typename _Tp >
__gnu_cxx::__chebyshev_u_t< _Tp > __chebyshev_u (unsigned int __n, _Tp __x)
template<typename _Tp >
__gnu_cxx::__chebyshev_v_t< _Tp > __chebyshev_v (unsigned int __n, _Tp __x)
template<typename _Tp >
__gnu_cxx::__chebyshev_w_t< _Tp > __chebyshev_w (unsigned int __n, _Tp __x)
template<typename _Tp >
_Tp __chi_squared_pdf (_Tp __chi2, unsigned int __nu)
Return the chi-squared propability function. This returns the probability that the observed chi-squared for a correct model is less than the value .
template<typename _Tp >
_Tp __chi_squared_pdfc (_Tp __chi2, unsigned int __nu)
Return the complementary chi-squared propability function. This returns the probability that the observed chi-squared for a correct model is greater than the value .
template<typename _Tp >
std::pair< _Tp, _Tp > __chshint (_Tp __x, _Tp &_Chi, _Tp &_Shi)
This function returns the hyperbolic cosine and hyperbolic sine integrals as a pair.
template<typename _Tp >
void __chshint_cont_frac (_Tp __t, _Tp &_Chi, _Tp &_Shi)
This function computes the hyperbolic cosine and hyperbolic sine integrals by continued fraction for positive argument.
template<typename _Tp >
void __chshint_series (_Tp __t, _Tp &_Chi, _Tp &_Shi)
This function computes the hyperbolic cosine and hyperbolic sine integrals by series summation for positive argument.
template<typename _Tp >
std::complex< _Tp > __clamp_0_m2pi (std::complex< _Tp > __z)
template<typename _Tp >
std::complex< _Tp > __clamp_pi (std::complex< _Tp > __z)
template<typename _Tp >
std::complex< _Tp > __clausen (unsigned int __m, std::complex< _Tp > __z)
template<typename _Tp >
_Tp __clausen (unsigned int __m, _Tp __x)
template<typename _Tp >
_Tp __clausen_cl (unsigned int __m, std::complex< _Tp > __z)
template<typename _Tp >
_Tp __clausen_cl (unsigned int __m, _Tp __x)
template<typename _Tp >
_Tp __clausen_sl (unsigned int __m, std::complex< _Tp > __z)
template<typename _Tp >
_Tp __clausen_sl (unsigned int __m, _Tp __x)
template<typename _Tp >
_Tp __comp_ellint_1 (_Tp __k)
Return the complete elliptic integral of the first kind using the Carlson formulation.
template<typename _Tp >
_Tp __comp_ellint_2 (_Tp __k)
Return the complete elliptic integral of the second kind using the Carlson formulation.
template<typename _Tp >
_Tp __comp_ellint_3 (_Tp __k, _Tp __nu)
Return the complete elliptic integral of the third kind using the Carlson formulation.
template<typename _Tp >
_Tp __comp_ellint_d (_Tp __k)
template<typename _Tp >
_Tp __comp_ellint_rf (_Tp __x, _Tp __y)
template<typename _Tp >
_Tp __comp_ellint_rg (_Tp __x, _Tp __y)
template<typename _Tp >
_Tp __conf_hyperg (_Tp __a, _Tp __c, _Tp __x)
Return the confluent hypergeometric function .
template<typename _Tp >
_Tp __conf_hyperg_lim (_Tp __c, _Tp __x)
Return the confluent hypergeometric limit function .
template<typename _Tp >
_Tp __conf_hyperg_lim_series (_Tp __c, _Tp __x)
This routine returns the confluent hypergeometric limit function by series expansion.
template<typename _Tp >
_Tp __conf_hyperg_luke (_Tp __a, _Tp __c, _Tp __xin)
Return the hypergeometric function by an iterative procedure described in Luke, Algorithms for the Computation of Mathematical Functions.
template<typename _Tp >
_Tp __conf_hyperg_series (_Tp __a, _Tp __c, _Tp __x)
This routine returns the confluent hypergeometric function by series expansion.
template<typename _Tp >
_Tp __cos_pi (_Tp __x)
template<typename _Tp >
std::complex< _Tp > __cos_pi (std::complex< _Tp > __z)
template<typename _Tp >
_Tp __cosh_pi (_Tp __x)
template<typename _Tp >
std::complex< _Tp > __cosh_pi (std::complex< _Tp > __z)
template<typename _Tp >
_Tp __coshint (const _Tp __x)
Return the hyperbolic cosine integral .
template<typename _Tp >
std::pair< _Tp, _Tp > __coulomb_CF1 (unsigned int __l, _Tp __eta, _Tp __x)
template<typename _Tp >
std::complex< _Tp > __coulomb_CF2 (unsigned int __l, _Tp __eta, _Tp __x)
template<typename _Tp >
std::pair< _Tp, _Tp > __coulomb_f_recur (unsigned int __l_min, unsigned int __k_max, _Tp __eta, _Tp __x, _Tp _F_l_max, _Tp _Fp_l_max)
template<typename _Tp >
std::pair< _Tp, _Tp > __coulomb_g_recur (unsigned int __l_min, unsigned int __k_max, _Tp __eta, _Tp __x, _Tp _G_l_min, _Tp _Gp_l_min)
template<typename _Tp >
_Tp __coulomb_norm (unsigned int __l, _Tp __eta)
template<typename _Tp >
std::complex< _Tp > __cyl_bessel (std::complex< _Tp > __nu, std::complex< _Tp > __z)
Return the complex cylindrical Bessel function.
template<typename _Tp >
_Tp __cyl_bessel_i (_Tp __nu, _Tp __x)
Return the regular modified Bessel function of order : .
template<typename _Tp >
_Tp __cyl_bessel_ij_series (_Tp __nu, _Tp __x, _Tp __sgn, unsigned int __max_iter)
This routine returns the cylindrical Bessel functions of order : or by series expansion.
template<typename _Tp >
__gnu_cxx::__cyl_mod_bessel_t< _Tp, _Tp, _Tp > __cyl_bessel_ik (_Tp __nu, _Tp __x)
Return the modified cylindrical Bessel functions and their derivatives of order by various means.
template<typename _Tp >
__gnu_cxx::__cyl_mod_bessel_t< _Tp, _Tp, _Tp > __cyl_bessel_ik_asymp (_Tp __nu, _Tp __x)
This routine computes the asymptotic modified cylindrical Bessel and functions of order nu: , . Use this for .
template<typename _Tp >
__gnu_cxx::__cyl_mod_bessel_t< _Tp, _Tp, _Tp > __cyl_bessel_ik_steed (_Tp __nu, _Tp __x)
Compute the modified Bessel functions and and their first derivatives and respectively. These four functions are computed together for numerical stability.
template<typename _Tp >
_Tp __cyl_bessel_j (_Tp __nu, _Tp __x)
Return the Bessel function of order : .
template<typename _Tp >
__gnu_cxx::__cyl_bessel_t< _Tp, _Tp, _Tp > __cyl_bessel_jn (_Tp __nu, _Tp __x)
Return the cylindrical Bessel functions and their derivatives of order by various means.
template<typename _Tp >
__gnu_cxx::__cyl_bessel_t< _Tp, _Tp, _Tp > __cyl_bessel_jn_asymp (_Tp __nu, _Tp __x)
This routine computes the asymptotic cylindrical Bessel and Neumann functions of order nu: , . Use this for .
template<typename _Tp >
__gnu_cxx::__cyl_bessel_t< _Tp, _Tp, std::complex< _Tp > > __cyl_bessel_jn_neg_arg (_Tp __nu, _Tp __x)
Return the cylindrical Bessel functions and their derivatives of order and argument .
template<typename _Tp >
__gnu_cxx::__cyl_bessel_t< _Tp, _Tp, _Tp > __cyl_bessel_jn_steed (_Tp __nu, _Tp __x)
Compute the Bessel and Neumann functions and their first derivatives and respectively. These four functions are computed together for numerical stability.
template<typename _Tp >
_Tp __cyl_bessel_k (_Tp __nu, _Tp __x)
Return the irregular modified Bessel function of order .
template<typename _Tp >
std::complex< _Tp > __cyl_hankel_1 (_Tp __nu, _Tp __x)
Return the cylindrical Hankel function of the first kind .
template<typename _Tp >
std::complex< _Tp > __cyl_hankel_1 (std::complex< _Tp > __nu, std::complex< _Tp > __z)
Return the complex cylindrical Hankel function of the first kind.
template<typename _Tp >
std::complex< _Tp > __cyl_hankel_2 (_Tp __nu, _Tp __x)
Return the cylindrical Hankel function of the second kind .
template<typename _Tp >
std::complex< _Tp > __cyl_hankel_2 (std::complex< _Tp > __nu, std::complex< _Tp > __z)
Return the complex cylindrical Hankel function of the second kind.
template<typename _Tp >
std::complex< _Tp > __cyl_neumann (std::complex< _Tp > __nu, std::complex< _Tp > __z)
Return the complex cylindrical Neumann function.
template<typename _Tp >
_Tp __cyl_neumann_n (_Tp __nu, _Tp __x)
Return the Neumann function of order : .
template<typename _Tp >
_Tp __dawson (_Tp __x)
Return the Dawson integral, , for real argument x.
template<typename _Tp >
_Tp __dawson_cont_frac (_Tp __x)
Compute the Dawson integral using a sampling theorem representation.
template<typename _Tp >
_Tp __dawson_series (_Tp __x)
Compute the Dawson integral using the series expansion.
template<typename _Tp >
_Tp __debye (unsigned int __n, _Tp __x)
template<typename _Tp >
void __debye_region (std::complex< _Tp > __alpha, int &__indexr, char &__aorb)
template<typename _Tp >
_Tp __digamma (unsigned int __n)
Return the digamma function of integral argument. The digamma or function is defined as the logarithmic derivative of the gamma function:
The digamma series for integral argument is given by:
The latter sum is called the harmonic number, .
template<typename _Tp >
_Tp __digamma (_Tp __x)
Return the digamma function. The digamma or function is defined by
For negative argument the reflection formula is used:
.
template<typename _Tp >
_Tp __digamma_asymp (_Tp __x)
Return the digamma function for large argument. The digamma or function is defined by
.
template<typename _Tp >
_Tp __digamma_series (_Tp __x)
Return the digamma function by series expansion. The digamma or function is defined by
.
template<typename _Tp >
_Tp __dilog (_Tp __x)
Compute the dilogarithm function by summation for x <= 1.
template<typename _Tp >
_Tp __dirichlet_beta (std::complex< _Tp > __s)
template<typename _Tp >
_Tp __dirichlet_beta (_Tp __s)
template<typename _Tp >
std::complex< _Tp > __dirichlet_eta (std::complex< _Tp > __s)
template<typename _Tp >
_Tp __dirichlet_eta (_Tp __s)
template<typename _Tp >
_Tp __dirichlet_lambda (_Tp __s)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __double_factorial (int __n)
Return the double factorial of the integer n.
template<typename _Tp >
_Tp __ellint_1 (_Tp __k, _Tp __phi)
Return the incomplete elliptic integral of the first kind using the Carlson formulation.
template<typename _Tp >
_Tp __ellint_2 (_Tp __k, _Tp __phi)
Return the incomplete elliptic integral of the second kind using the Carlson formulation.
template<typename _Tp >
_Tp __ellint_3 (_Tp __k, _Tp __nu, _Tp __phi)
Return the incomplete elliptic integral of the third kind using the Carlson formulation.
template<typename _Tp >
_Tp __ellint_cel (_Tp __k_c, _Tp __p, _Tp __a, _Tp __b)
template<typename _Tp >
_Tp __ellint_d (_Tp __k, _Tp __phi)
template<typename _Tp >
_Tp __ellint_el1 (_Tp __x, _Tp __k_c)
template<typename _Tp >
_Tp __ellint_el2 (_Tp __x, _Tp __k_c, _Tp __a, _Tp __b)
template<typename _Tp >
_Tp __ellint_el3 (_Tp __x, _Tp __k_c, _Tp __p)
template<typename _Tp >
_Tp __ellint_rc (_Tp __x, _Tp __y)
Return the Carlson elliptic function where is the Carlson elliptic function of the first kind.
template<typename _Tp >
_Tp __ellint_rd (_Tp __x, _Tp __y, _Tp __z)
Return the Carlson elliptic function of the second kind where is the Carlson elliptic function of the third kind.
template<typename _Tp >
_Tp __ellint_rf (_Tp __x, _Tp __y, _Tp __z)
Return the Carlson elliptic function of the first kind.
template<typename _Tp >
_Tp __ellint_rg (_Tp __x, _Tp __y, _Tp __z)
Return the symmetric Carlson elliptic function of the second kind .
template<typename _Tp >
_Tp __ellint_rj (_Tp __x, _Tp __y, _Tp __z, _Tp __p)
Return the Carlson elliptic function of the third kind.
template<typename _Tp >
_Tp __ellnome (_Tp __k)
template<typename _Tp >
_Tp __ellnome_k (_Tp __k)
template<typename _Tp >
_Tp __ellnome_series (_Tp __k)
template<typename _Tp >
_Tp __euler (unsigned int __n)
This returns Euler number .
template<typename _Tp >
_Tp __euler (unsigned int __n, _Tp __x)
template<typename _Tp >
_Tp __euler_series (unsigned int __n)
template<typename _Tp >
_Tp __eulerian_1 (unsigned int __n, unsigned int __m)
template<typename _Tp >
std::vector< _Tp > __eulerian_1 (unsigned int __n)
template<typename _Tp >
_Tp __eulerian_1_recur (unsigned int __n, unsigned int __m)
template<typename _Tp >
std::vector< _Tp > __eulerian_1_recur (unsigned int __n)
template<typename _Tp >
_Tp __eulerian_2 (unsigned int __n, unsigned int __m)
template<typename _Tp >
std::vector< _Tp > __eulerian_2 (unsigned int __n)
template<typename _Tp >
_Tp __eulerian_2_recur (unsigned int __n, unsigned int __m)
template<typename _Tp >
std::vector< _Tp > __eulerian_2_recur (unsigned int __n)
template<typename _Tp >
_Tp __exp2 (_Tp __x)
template<typename _Tp >
_Tp __expint (unsigned int __n, _Tp __x)
Return the exponential integral .
template<typename _Tp >
_Tp __expint (_Tp __x)
Return the exponential integral .
template<typename _Tp >
_Tp __expint_E1 (_Tp __x)
Return the exponential integral .
template<typename _Tp >
_Tp __expint_E1_asymp (_Tp __x)
Return the exponential integral by asymptotic expansion.
template<typename _Tp >
_Tp __expint_E1_series (_Tp __x)
Return the exponential integral by series summation. This should be good for .
template<typename _Tp >
_Tp __expint_Ei (_Tp __x)
Return the exponential integral .
template<typename _Tp >
_Tp __expint_Ei_asymp (_Tp __x)
Return the exponential integral by asymptotic expansion.
template<typename _Tp >
_Tp __expint_Ei_series (_Tp __x)
Return the exponential integral by series summation.
template<typename _Tp >
_Tp __expint_En_asymp (unsigned int __n, _Tp __x)
Return the exponential integral for large argument.
template<typename _Tp >
_Tp __expint_En_cont_frac (unsigned int __n, _Tp __x)
Return the exponential integral by continued fractions.
template<typename _Tp >
_Tp __expint_En_large_n (unsigned int __n, _Tp __x)
Return the exponential integral for large order.
template<typename _Tp >
_Tp __expint_En_recursion (unsigned int __n, _Tp __x)
Return the exponential integral by recursion. Use upward recursion for and downward recursion (Miller's algorithm) otherwise.
template<typename _Tp >
_Tp __expint_En_series (unsigned int __n, _Tp __x)
Return the exponential integral by series summation.
template<typename _Tp >
_Tp __exponential_p (_Tp __lambda, _Tp __x)
Return the exponential cumulative probability density function.
template<typename _Tp >
_Tp __exponential_pdf (_Tp __lambda, _Tp __x)
Return the exponential probability density function.
template<typename _Tp >
_Tp __exponential_q (_Tp __lambda, _Tp __x)
Return the complement of the exponential cumulative probability density function.
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __factorial (unsigned int __n)
Return the factorial of the integer n.
template<typename _Tp >
_Tp __falling_factorial (_Tp __a, int __n)
Return the logarithm of the falling factorial function or the lower Pochhammer symbol for real argument and integral order . The falling factorial function is defined by
In particular, .
template<typename _Tp >
_Tp __falling_factorial (_Tp __a, _Tp __nu)
Return the logarithm of the falling factorial function or the lower Pochhammer symbol for real argument and order . The falling factorial function is defined by
.
template<typename _Sp , typename _Tp >
_Tp __fermi_dirac (_Sp __s, _Tp __x)
template<typename _Tp >
_Tp __fisher_f_p (_Tp __F, unsigned int __nu1, unsigned int __nu2)
Return the F-distribution propability function. This returns the probability that the observed chi-square for a correct model exceeds the value .
template<typename _Tp >
_Tp __fisher_f_pdf (_Tp __F, unsigned int __nu1, unsigned int __nu2)
Return the F-distribution propability function. This returns the probability that the observed chi-square for a correct model exceeds the value .
template<typename _Tp >
_Tp __fisher_f_q (_Tp __F, unsigned int __nu1, unsigned int __nu2)
Return the F-distribution propability function. This returns the probability that the observed chi-square for a correct model exceeds the value .
template<typename _Tp >
__gnu_cxx::__fock_airy_t< _Tp, std::complex< _Tp > > __fock_airy (_Tp __x)
Compute the Fock-type Airy functions and and their first derivatives and respectively.
.
template<typename _Tp >
std::complex< _Tp > __fresnel (const _Tp __x)
Return the Fresnel cosine and sine integrals as a complex number $f[ C(x) + iS(x) $f].
template<typename _Tp >
void __fresnel_cont_frac (const _Tp __ax, _Tp &_Cf, _Tp &_Sf)
This function computes the Fresnel cosine and sine integrals by continued fractions for positive argument.
template<typename _Tp >
void __fresnel_series (const _Tp __ax, _Tp &_Cf, _Tp &_Sf)
This function returns the Fresnel cosine and sine integrals as a pair by series expansion for positive argument.
template<typename _Tp >
_Tp __gamma (_Tp __a)
Return the gamma function . The gamma function is defined by:
.
template<typename _Tp >
std::pair< _Tp, _Tp > __gamma (_Tp __a, _Tp __x)
Return the incomplete gamma functions.
template<typename _Tp >
std::pair< _Tp, _Tp > __gamma_cont_frac (_Tp __a, _Tp __x)
Return the incomplete gamma function by continued fraction.
template<typename _Tp >
_Tp __gamma_p (_Tp __alpha, _Tp __beta, _Tp __x)
Return the gamma cumulative propability distribution function.
template<typename _Tp >
_Tp __gamma_p (_Tp __a, _Tp __x)
Return the regularized lower incomplete gamma function. The regularized lower incomplete gamma function is defined by
where is the gamma function and
is the lower incomplete gamma function.
template<typename _Tp >
_Tp __gamma_pdf (_Tp __alpha, _Tp __beta, _Tp __x)
Return the gamma propability distribution function.
template<typename _Tp >
_Tp __gamma_q (_Tp __alpha, _Tp __beta, _Tp __x)
Return the gamma complementary cumulative propability distribution function.
template<typename _Tp >
_Tp __gamma_q (_Tp __a, _Tp __x)
Return the regularized upper incomplete gamma function. The regularized upper incomplete gamma function is defined by
where is the gamma function and
is the upper incomplete gamma function.
template<typename _Tp >
_Tp __gamma_reciprocal (_Tp __a)
template<typename _Tp >
_Tp __gamma_reciprocal_series (_Tp __a)
template<typename _Tp >
std::pair< _Tp, _Tp > __gamma_series (_Tp __a, _Tp __x)
Return the incomplete gamma function by series summation.
.
template<typename _Tp >
__gnu_cxx::__gamma_temme_t< _Tp > __gamma_temme (_Tp __mu)
Compute the gamma functions required by the Temme series expansions of and .
and
where is and . is the nearest integer to . The values of and are returned as well.
template<typename _Tp >
_Tp __gauss (_Tp __x)
template<typename _Tp >
__gnu_cxx::__gegenbauer_t< _Tp > __gegenbauer_recur (unsigned int __n, _Tp __lambda, _Tp __x)
template<typename _Tp >
std::vector< __gnu_cxx::__quadrature_point_t< _Tp > > __gegenbauer_zeros (unsigned int __n, _Tp __lambda)
template<typename _Tp >
__gnu_cxx::__cyl_hankel_t< std::complex< _Tp >, std::complex< _Tp >, std::complex< _Tp > > __hankel (std::complex< _Tp > __nu, std::complex< _Tp > __z)
template<typename _Tp >
__gnu_cxx::__cyl_hankel_t< std::complex< _Tp >, std::complex< _Tp >, std::complex< _Tp > > __hankel_debye (std::complex< _Tp > __nu, std::complex< _Tp > __z, std::complex< _Tp > __alpha, int __indexr, char &__aorb, int &__morn)
template<typename _Tp >
void __hankel_params (std::complex< _Tp > __nu, std::complex< _Tp > __zhat, std::complex< _Tp > &__p, std::complex< _Tp > &__p2, std::complex< _Tp > &__nup2, std::complex< _Tp > &__num2, std::complex< _Tp > &__num1d3, std::complex< _Tp > &__num2d3, std::complex< _Tp > &__num4d3, std::complex< _Tp > &__zeta, std::complex< _Tp > &__zetaphf, std::complex< _Tp > &__zetamhf, std::complex< _Tp > &__zetam3hf, std::complex< _Tp > &__zetrat)
Compute parameters depending on z and nu that appear in the uniform asymptotic expansions of the Hankel functions and their derivatives, except the arguments to the Airy functions.
template<typename _Tp >
__gnu_cxx::__cyl_hankel_t< std::complex< _Tp >, std::complex< _Tp >, std::complex< _Tp > > __hankel_uniform (std::complex< _Tp > __nu, std::complex< _Tp > __z)
This routine computes the uniform asymptotic approximations of the Hankel functions and their derivatives including a patch for the case when the order equals or nearly equals the argument. At such points, Olver's expressions have zero denominators (and numerators) resulting in numerical problems. This routine averages results from four surrounding points in the complex plane to obtain the result in such cases.
template<typename _Tp >
__gnu_cxx::__cyl_hankel_t< std::complex< _Tp >, std::complex< _Tp >, std::complex< _Tp > > __hankel_uniform_olver (std::complex< _Tp > __nu, std::complex< _Tp > __z)
Compute approximate values for the Hankel functions of the first and second kinds using Olver's uniform asymptotic expansion to of order nu along with their derivatives.
template<typename _Tp >
void __hankel_uniform_outer (std::complex< _Tp > __nu, std::complex< _Tp > __z, _Tp __eps, std::complex< _Tp > &__zhat, std::complex< _Tp > &__1dnsq, std::complex< _Tp > &__num1d3, std::complex< _Tp > &__num2d3, std::complex< _Tp > &__p, std::complex< _Tp > &__p2, std::complex< _Tp > &__etm3h, std::complex< _Tp > &__etrat, std::complex< _Tp > &_Aip, std::complex< _Tp > &__o4dp, std::complex< _Tp > &_Aim, std::complex< _Tp > &__o4dm, std::complex< _Tp > &__od2p, std::complex< _Tp > &__od0dp, std::complex< _Tp > &__od2m, std::complex< _Tp > &__od0dm)
Compute outer factors and associated functions of z and nu appearing in Olver's uniform asymptotic expansions of the Hankel functions of the first and second kinds and their derivatives. The various functions of z and nu returned by hankel_uniform_outer are available for use in computing further terms in the expansions.
template<typename _Tp >
void __hankel_uniform_sum (std::complex< _Tp > __p, std::complex< _Tp > __p2, std::complex< _Tp > __num2, std::complex< _Tp > __zetam3hf, std::complex< _Tp > _Aip, std::complex< _Tp > __o4dp, std::complex< _Tp > _Aim, std::complex< _Tp > __o4dm, std::complex< _Tp > __od2p, std::complex< _Tp > __od0dp, std::complex< _Tp > __od2m, std::complex< _Tp > __od0dm, _Tp __eps, std::complex< _Tp > &_H1sum, std::complex< _Tp > &_H1psum, std::complex< _Tp > &_H2sum, std::complex< _Tp > &_H2psum)
Compute the sums in appropriate linear combinations appearing in Olver's uniform asymptotic expansions for the Hankel functions of the first and second kinds and their derivatives, using up to nterms (less than 5) to achieve relative error eps.
template<typename _Tp >
_Tp __harmonic_number (unsigned int __n)
template<typename _Tp >
_Tp __hermite (unsigned int __n, _Tp __x)
This routine returns the Hermite polynomial of order n: .
template<typename _Tp >
_Tp __hermite_asymp (unsigned int __n, _Tp __x)
This routine returns the Hermite polynomial of large order n: . We assume here that x >= 0.
template<typename _Tp >
__gnu_cxx::__hermite_t< _Tp > __hermite_recur (unsigned int __n, _Tp __x)
This routine returns the Hermite polynomial of order n: by recursion on n.
template<typename _Tp >
std::vector< __gnu_cxx::__quadrature_point_t< _Tp > > __hermite_zeros (unsigned int __n, _Tp __proto=_Tp{})
template<typename _Tp >
_Tp __heuman_lambda (_Tp __k, _Tp __phi)
template<typename _Tp >
_Tp __hurwitz_zeta (_Tp __s, _Tp __a)
Return the Hurwitz zeta function for all s != 1 and a > -1.
template<typename _Tp >
_Tp __hurwitz_zeta_euler_maclaurin (_Tp __s, _Tp __a)
Return the Hurwitz zeta function for all s != 1 and a > -1.
template<typename _Tp >
std::complex< _Tp > __hurwitz_zeta_polylog (_Tp __s, std::complex< _Tp > __a)
template<typename _Tp >
std::complex< _Tp > __hydrogen (unsigned int __n, unsigned int __l, unsigned int __m, _Tp __Z, _Tp __r, _Tp __theta, _Tp __phi)
template<typename _Tp >
_Tp __hyperg (_Tp __a, _Tp __b, _Tp __c, _Tp __x)
Return the hypergeometric function .
template<typename _Tp >
_Tp __hyperg_luke (_Tp __a, _Tp __b, _Tp __c, _Tp __xin)
Return the hypergeometric function by an iterative procedure described in Luke, Algorithms for the Computation of Mathematical Functions.
template<typename _Tp >
_Tp __hyperg_recur (int __m, _Tp __b, _Tp __c, _Tp __x)
Return the hypergeometric polynomial by Holm recursion.
template<typename _Tp >
_Tp __hyperg_reflect (_Tp __a, _Tp __b, _Tp __c, _Tp __x)
Return the hypergeometric function by the reflection formulae in Abramowitz & Stegun formula 15.3.6 for d = c - a - b not integral and formula 15.3.11 for d = c - a - b integral. This assumes a, b, c != negative integer.
template<typename _Tp >
_Tp __hyperg_series (_Tp __a, _Tp __b, _Tp __c, _Tp __x)
Return the hypergeometric function by series expansion.
template<typename _Tp >
_Tp __ibeta_cont_frac (_Tp __a, _Tp __b, _Tp __x)
template<typename _Tp >
__gnu_cxx::__jacobi_ellint_t< _Tp > __jacobi_ellint (_Tp __k, _Tp __u)
template<typename _Tp >
__gnu_cxx::__jacobi_t< _Tp > __jacobi_recur (unsigned int __n, _Tp __alpha1, _Tp __beta1, _Tp __x)
template<typename _Tp >
std::complex< _Tp > __jacobi_theta_1 (std::complex< _Tp > __q, std::complex< _Tp > __x)
template<typename _Tp >
_Tp __jacobi_theta_1 (_Tp __q, const _Tp __x)
template<typename _Tp >
_Tp __jacobi_theta_1_prod (_Tp __q, _Tp __x)
template<typename _Tp >
_Tp __jacobi_theta_1_sum (_Tp __q, _Tp __x)
template<typename _Tp >
std::complex< _Tp > __jacobi_theta_2 (std::complex< _Tp > __q, std::complex< _Tp > __x)
template<typename _Tp >
_Tp __jacobi_theta_2 (_Tp __q, const _Tp __x)
template<typename _Tp >
_Tp __jacobi_theta_2_prod (_Tp __q, _Tp __x)
template<typename _Tp >
_Tp __jacobi_theta_2_sum (_Tp __q, _Tp __x)
template<typename _Tp >
std::complex< _Tp > __jacobi_theta_3 (std::complex< _Tp > __q, std::complex< _Tp > __x)
template<typename _Tp >
_Tp __jacobi_theta_3 (_Tp __q, const _Tp __x)
template<typename _Tp >
_Tp __jacobi_theta_3_prod (_Tp __q, _Tp __x)
template<typename _Tp >
_Tp __jacobi_theta_3_sum (_Tp __q, _Tp __x)
template<typename _Tp >
std::complex< _Tp > __jacobi_theta_4 (std::complex< _Tp > __q, std::complex< _Tp > __x)
template<typename _Tp >
_Tp __jacobi_theta_4 (_Tp __q, const _Tp __x)
template<typename _Tp >
_Tp __jacobi_theta_4_prod (_Tp __q, _Tp __x)
template<typename _Tp >
_Tp __jacobi_theta_4_sum (_Tp __q, _Tp __x)
template<typename _Tp >
std::vector< __gnu_cxx::__quadrature_point_t< _Tp > > __jacobi_zeros (unsigned int __n, _Tp __alpha1, _Tp __beta1)
template<typename _Tp >
_Tp __jacobi_zeta (_Tp __k, _Tp __phi)
template<typename _Tp >
_Tp __kolmogorov_p (_Tp __a, _Tp __b, _Tp __x)
template<typename _Tpa , typename _Tp >
_Tp __laguerre (unsigned int __n, _Tpa __alpha1, _Tp __x)
This routine returns the associated Laguerre polynomial of degree n, order : .
template<typename _Tp >
_Tp __laguerre (unsigned int __n, _Tp __x)
This routine returns the Laguerre polynomial of degree n: .
template<typename _Tpa , typename _Tp >
_Tp __laguerre_hyperg (unsigned int __n, _Tpa __alpha1, _Tp __x)
Evaluate the polynomial based on the confluent hypergeometric function in a safe way, with no restriction on the arguments.
template<typename _Tpa , typename _Tp >
_Tp __laguerre_large_n (unsigned __n, _Tpa __alpha1, _Tp __x)
This routine returns the associated Laguerre polynomial of degree , order for large n. Abramowitz & Stegun, 13.5.21.
template<typename _Tpa , typename _Tp >
__gnu_cxx::__laguerre_t< _Tpa, _Tp > __laguerre_recur (unsigned int __n, _Tpa __alpha1, _Tp __x)
This routine returns the associated Laguerre polynomial of degree n, order : by recursion.
template<typename _Tp >
std::vector< __gnu_cxx::__quadrature_point_t< _Tp > > __laguerre_zeros (unsigned int __n, _Tp __alpha1)
template<typename _Tp >
_Tp __lah (unsigned int __n, unsigned int __k)
template<typename _Tp >
std::vector< _Tp > __lah (unsigned int __n)
template<typename _Tp >
_Tp __lah_recur (unsigned int __n, unsigned int __k)
template<typename _Tp >
std::vector< _Tp > __lah_recur (unsigned int __n)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __lanczos_binet1p (_Tp __z)
Return the Binet function by the Lanczos method. The Binet function is the log of the scaled Gamma function defined by
or
where is the gamma function.
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __lanczos_log_gamma1p (_Tp __z)
Return the logarithm of the gamma function by the Lanczos method.
template<typename _Tp >
__gnu_cxx::__legendre_p_t< _Tp > __legendre_p (unsigned int __l, _Tp __x)
Return the Legendre polynomial by upward recursion on degree .
template<typename _Tp >
__gnu_cxx::__legendre_q_t< _Tp > __legendre_q (unsigned int __l, _Tp __x)
Return the Legendre function of the second kind by upward recursion on degree .
template<typename _Tp >
_Tp __legendre_q_series (unsigned int __l, _Tp __x)
template<typename _Tp >
std::vector< __gnu_cxx::__quadrature_point_t< _Tp > > __legendre_zeros (unsigned int __l, _Tp proto=_Tp{})
template<typename _Tp >
_Tp __log_binomial (unsigned int __n, unsigned int __k)
Return the logarithm of the binomial coefficient. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
template<typename _Tp >
_Tp __log_binomial (_Tp __nu, unsigned int __k)
Return the logarithm of the binomial coefficient for non-integral degree. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
template<typename _Tp >
_Tp __log_binomial_sign (_Tp __nu, unsigned int __k)
Return the sign of the exponentiated logarithm of the binomial coefficient for non-integral degree. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
template<typename _Tp >
std::complex< _Tp > __log_binomial_sign (std::complex< _Tp > __nu, unsigned int __k)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __log_double_factorial (_Tp __nu)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __log_double_factorial (int __n)
Return the logarithm of the double factorial of the integer n.
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __log_factorial (unsigned int __n)
Return the logarithm of the factorial of the integer n.
template<typename _Tp >
_Tp __log_falling_factorial (_Tp __a, _Tp __nu)
Return the logarithm of the falling factorial function or the lower Pochhammer symbol. The lower Pochammer symbol is defined by
In particular, . Thus this function returns
Many notations exist for this function:
,
, and others.
template<typename _Tp >
_Tp __log_gamma (_Tp __a)
Return . This will return values even for . To recover the sign of for any argument use __log_gamma_sign.
template<typename _Tp >
std::complex< _Tp > __log_gamma (std::complex< _Tp > __a)
Return for complex argument.
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __log_gamma_bernoulli (_Tp __x)
Return by asymptotic expansion with Bernoulli number coefficients. This is like Sterling's approximation.
template<typename _Tp >
_Tp __log_gamma_sign (_Tp __a)
Return the sign of . At nonpositive integers zero is returned indicating is undefined.
template<typename _Tp >
std::complex< _Tp > __log_gamma_sign (std::complex< _Tp > __a)
template<typename _Tp >
_Tp __log_rising_factorial (_Tp __a, _Tp __nu)
Return the logarithm of the rising factorial function or the (upper) Pochhammer symbol. The Pochammer symbol is defined for integer order by
Thus this function returns
Many notations exist for this function:
(especially in the literature of special functions),
, and others.
template<typename _Tp >
_Tp __log_stirling_1 (unsigned int __n, unsigned int __m)
template<typename _Tp >
_Tp __log_stirling_1_sign (unsigned int __n, unsigned int __m)
template<typename _Tp >
_Tp __log_stirling_2 (unsigned int __n, unsigned int __m)
template<typename _Tp >
_Tp __logint (const _Tp __x)
Return the logarithmic integral .
template<typename _Tp >
_Tp __logistic_p (_Tp __a, _Tp __b, _Tp __x)
Return the logistic cumulative distribution function.
template<typename _Tp >
_Tp __logistic_pdf (_Tp __a, _Tp __b, _Tp __x)
Return the logistic probability density function.
template<typename _Tp >
_Tp __lognormal_p (_Tp __mu, _Tp __sigma, _Tp __x)
Return the lognormal cumulative probability density function.
template<typename _Tp >
_Tp __lognormal_pdf (_Tp __nu, _Tp __sigma, _Tp __x)
Return the lognormal probability density function.
template<typename _Tp >
_Tp __normal_p (_Tp __mu, _Tp __sigma, _Tp __x)
Return the normal cumulative probability density function.
template<typename _Tp >
_Tp __normal_pdf (_Tp __mu, _Tp __sigma, _Tp __x)
Return the normal probability density function.
template<typename _Tp >
_Tp __owens_t (_Tp __h, _Tp __a)
template<typename _Tp , typename _ArgType >
__gnu_cxx::fp_promote_t< std::complex< _Tp >, _ArgType > __periodic_zeta (_ArgType __z, _Tp __s)
template<typename _Tp >
std::complex< _Tp > __polar_pi (_Tp __rho, _Tp __phi_pi)
template<typename _Tp >
std::complex< _Tp > __polar_pi (_Tp __rho, const std::complex< _Tp > &__phi_pi)
template<typename _Tp >
_Tp __polygamma (unsigned int __m, _Tp __x)
Return the polygamma function .
template<typename _Tp >
_Tp __polylog (_Tp __s, _Tp __x)
template<typename _Tp >
std::complex< _Tp > __polylog (_Tp __s, std::complex< _Tp > __w)
template<typename _Tp , typename _ArgType >
__gnu_cxx::fp_promote_t< std::complex< _Tp >, _ArgType > __polylog_exp (_Tp __s, _ArgType __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_asymp (_Tp __s, std::complex< _Tp > __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_neg (_Tp __s, std::complex< _Tp > __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_neg (int __n, std::complex< _Tp > __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_neg_int (int __s, std::complex< _Tp > __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_neg_int (int __s, _Tp __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_neg_real (_Tp __s, std::complex< _Tp > __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_neg_real (_Tp __s, _Tp __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_pos (unsigned int __s, std::complex< _Tp > __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_pos (unsigned int __s, _Tp __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_pos (_Tp __s, std::complex< _Tp > __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_pos_int (unsigned int __s, std::complex< _Tp > __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_pos_int (unsigned int __s, _Tp __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_pos_real (_Tp __s, std::complex< _Tp > __w)
template<typename _Tp >
std::complex< _Tp > __polylog_exp_pos_real (_Tp __s, _Tp __w)
template<typename _PowTp , typename _Tp >
_Tp __polylog_exp_sum (_PowTp __s, _Tp __w)
template<typename _Tp >
__gnu_cxx::__hermite_he_t< _Tp > __prob_hermite_recur (unsigned int __n, _Tp __x)
This routine returns the Probabilists Hermite polynomial of order n: by recursion on n.
template<typename _Tp >
_Tp __radial_jacobi (unsigned int __n, unsigned int __m, _Tp __rho)
template<typename _Tp >
std::vector< __gnu_cxx::__quadrature_point_t< _Tp > > __radial_jacobi_zeros (unsigned int __n, unsigned int __m)
template<typename _Tp >
_Tp __rice_pdf (_Tp __nu, _Tp __sigma, _Tp __x)
Return the Rice probability density function.
template<typename _Tp >
_Tp __riemann_zeta (_Tp __s)
Return the Riemann zeta function .
template<typename _Tp >
_Tp __riemann_zeta_euler_maclaurin (_Tp __s)
Evaluate the Riemann zeta function by an alternate series for s > 0.
template<typename _Tp >
_Tp __riemann_zeta_glob (_Tp __s)
template<typename _Tp >
_Tp __riemann_zeta_laurent (_Tp __s)
Compute the Riemann zeta function by Laurent expansion about s = 1.
template<typename _Tp >
_Tp __riemann_zeta_m_1 (_Tp __s)
Return the Riemann zeta function .
template<typename _Tp >
_Tp __riemann_zeta_m_1_glob (_Tp __s)
Evaluate the Riemann zeta function by series for all s != 1. Convergence is great until largish negative numbers. Then the convergence of the > 0 sum gets better.
template<typename _Tp >
_Tp __riemann_zeta_product (_Tp __s)
Compute the Riemann zeta function using the product over prime factors.
template<typename _Tp >
_Tp __riemann_zeta_sum (_Tp __s)
Compute the Riemann zeta function by summation for s > 1.
template<typename _Tp >
_Tp __rising_factorial (_Tp __a, int __n)
Return the (upper) Pochhammer function or the rising factorial function. The Pochammer symbol is defined by
Many notations exist for this function:
, (especially in the literature of special functions),
, and others.
template<typename _Tp >
_Tp __rising_factorial (_Tp __a, _Tp __nu)
Return the rising factorial function or the (upper) Pochhammer function. The rising factorial function is defined by
Many notations exist for this function:
, (especially in the literature of special functions),
, and others.
template<typename _Tp >
_Tp __sin_pi (_Tp __x)
template<typename _Tp >
std::complex< _Tp > __sin_pi (std::complex< _Tp > __z)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __sinc (_Tp __x)
Return the sinus cardinal function
.
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __sinc_pi (_Tp __x)
Return the reperiodized sinus cardinal function
.
template<typename _Tp >
__gnu_cxx::__sincos_t< _Tp > __sincos (_Tp __x)
template<>
__gnu_cxx::__sincos_t< float > __sincos (float __x)
template<>
__gnu_cxx::__sincos_t< double > __sincos (double __x)
template<>
__gnu_cxx::__sincos_t< long double > __sincos (long double __x)
template<typename _Tp >
__gnu_cxx::__sincos_t< _Tp > __sincos_pi (_Tp __x)
template<typename _Tp >
std::pair< _Tp, _Tp > __sincosint (_Tp __x)
This function returns the sine and cosine integrals as a pair.
template<typename _Tp >
void __sincosint_asymp (_Tp __t, _Tp &_Si, _Tp &_Ci)
This function computes the sine and cosine integrals by asymptotic series summation for positive argument.
template<typename _Tp >
void __sincosint_cont_frac (_Tp __t, _Tp &_Si, _Tp &_Ci)
This function computes the sine and cosine integrals by continued fraction for positive argument.
template<typename _Tp >
void __sincosint_series (_Tp __t, _Tp &_Si, _Tp &_Ci)
This function computes the sine and cosine integrals by series summation for positive argument.
template<typename _Tp >
_Tp __sinh_pi (_Tp __x)
template<typename _Tp >
std::complex< _Tp > __sinh_pi (std::complex< _Tp > __z)
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __sinhc (_Tp __x)
Return the hyperbolic sinus cardinal function
.
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __sinhc_pi (_Tp __x)
Return the reperiodized hyperbolic sinus cardinal function
.
template<typename _Tp >
_Tp __sinhint (const _Tp __x)
Return the hyperbolic sine integral .
template<typename _Tp >
_Tp __sph_bessel (unsigned int __n, _Tp __x)
Return the spherical Bessel function of order n and non-negative real argument x.
template<typename _Tp >
std::complex< _Tp > __sph_bessel (unsigned int __n, std::complex< _Tp > __z)
Return the complex spherical Bessel function.
template<typename _Tp >
__gnu_cxx::__sph_mod_bessel_t< unsigned int, _Tp, _Tp > __sph_bessel_ik (unsigned int __n, _Tp __x)
Compute the spherical modified Bessel functions and and their first derivatives and respectively.
template<typename _Tp >
__gnu_cxx::__sph_bessel_t< unsigned int, _Tp, _Tp > __sph_bessel_jn (unsigned int __n, _Tp __x)
Compute the spherical Bessel and Neumann functions and their first derivatives and respectively.
template<typename _Tp >
__gnu_cxx::__sph_bessel_t< unsigned int, _Tp, std::complex< _Tp > > __sph_bessel_jn_neg_arg (unsigned int __n, _Tp __x)
template<typename _Tp >
__gnu_cxx::__sph_hankel_t< unsigned int, std::complex< _Tp >, std::complex< _Tp > > __sph_hankel (unsigned int __n, std::complex< _Tp > __z)
Helper to compute complex spherical Hankel functions and their derivatives.
template<typename _Tp >
std::complex< _Tp > __sph_hankel_1 (unsigned int __n, _Tp __x)
Return the spherical Hankel function of the first kind .
template<typename _Tp >
std::complex< _Tp > __sph_hankel_1 (unsigned int __n, std::complex< _Tp > __z)
Return the complex spherical Hankel function of the first kind.
template<typename _Tp >
std::complex< _Tp > __sph_hankel_2 (unsigned int __n, _Tp __x)
Return the spherical Hankel function of the second kind .
template<typename _Tp >
std::complex< _Tp > __sph_hankel_2 (unsigned int __n, std::complex< _Tp > __z)
Return the complex spherical Hankel function of the second kind.
template<typename _Tp >
std::complex< _Tp > __sph_harmonic (unsigned int __l, int __m, _Tp __theta, _Tp __phi)
Return the spherical harmonic function.
template<typename _Tp >
_Tp __sph_legendre (unsigned int __l, unsigned int __m, _Tp __theta)
Return the spherical associated Legendre function.
template<typename _Tp >
_Tp __sph_neumann (unsigned int __n, _Tp __x)
Return the spherical Neumann function of order n and non-negative real argument x.
template<typename _Tp >
std::complex< _Tp > __sph_neumann (unsigned int __n, std::complex< _Tp > __z)
Return the complex spherical Neumann function.
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __spouge_binet1p (_Tp __z)
Return the Binet function by the Spouge method. The Binet function is the log of the scaled Gamma function defined by
or
where is the gamma function.
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp __spouge_log_gamma1p (_Tp __z)
Return the logarithm of the gamma function by the Spouge algorithm:
where
and the error is bounded by
.
template<typename _Tp >
_Tp __stirling_1 (unsigned int __n, unsigned int __m)
template<typename _Tp >
std::vector< _Tp > __stirling_1 (unsigned int __n)
template<typename _Tp >
_Tp __stirling_1_recur (unsigned int __n, unsigned int __m)
template<typename _Tp >
std::vector< _Tp > __stirling_1_recur (unsigned int __n)
template<typename _Tp >
_Tp __stirling_2 (unsigned int __n, unsigned int __m)
template<typename _Tp >
std::vector< _Tp > __stirling_2 (unsigned int __n)
template<typename _Tp >
_Tp __stirling_2_recur (unsigned int __n, unsigned int __m)
template<typename _Tp >
std::vector< _Tp > __stirling_2_recur (unsigned int __n)
template<typename _Tp >
_Tp __stirling_2_series (unsigned int __n, unsigned int __m)
template<typename _Tp >
_Tp __student_t_p (_Tp __t, unsigned int __nu)
Return the Students T probability function.
template<typename _Tp >
_Tp __student_t_pdf (_Tp __t, unsigned int __nu)
Return the Students T probability density.
template<typename _Tp >
_Tp __student_t_q (_Tp __t, unsigned int __nu)
Return the complement of the Students T probability function.
template<typename _Tp >
_Tp __tan_pi (_Tp __x)
template<typename _Tp >
std::complex< _Tp > __tan_pi (std::complex< _Tp > __z)
template<typename _Tp >
_Tp __tanh_pi (_Tp __x)
template<typename _Tp >
std::complex< _Tp > __tanh_pi (std::complex< _Tp > __z)
template<typename _Tp >
_Tp __tgamma (_Tp __a, _Tp __x)
Return the upper incomplete gamma function. The lower incomplete gamma function is defined by
.
template<typename _Tp >
_Tp __tgamma_lower (_Tp __a, _Tp __x)
Return the lower incomplete gamma function. The lower incomplete gamma function is defined by
.
template<typename _Tp >
_Tp __theta_1 (_Tp __nu, _Tp __x)
template<typename _Tp >
_Tp __theta_2 (_Tp __nu, _Tp __x)
template<typename _Tp >
_Tp __theta_2_asymp (_Tp __nu, _Tp __x)
template<typename _Tp >
_Tp __theta_2_sum (_Tp __nu, _Tp __x)
template<typename _Tp >
_Tp __theta_3 (_Tp __nu, _Tp __x)
template<typename _Tp >
_Tp __theta_3_asymp (_Tp __nu, _Tp __x)
template<typename _Tp >
_Tp __theta_3_sum (_Tp __nu, _Tp __x)
template<typename _Tp >
_Tp __theta_4 (_Tp __nu, _Tp __x)
template<typename _Tp >
_Tp __theta_c (_Tp __k, _Tp __x)
template<typename _Tp >
_Tp __theta_d (_Tp __k, _Tp __x)
template<typename _Tp >
_Tp __theta_n (_Tp __k, _Tp __x)
template<typename _Tp >
_Tp __theta_s (_Tp __k, _Tp __x)
template<typename _Tp >
_Tp __tricomi_u (_Tp __a, _Tp __c, _Tp __x)
Return the Tricomi confluent hypergeometric function
.
template<typename _Tp >
_Tp __tricomi_u_naive (_Tp __a, _Tp __c, _Tp __x)
Return the Tricomi confluent hypergeometric function
.
template<typename _Tp >
_Tp __weibull_p (_Tp __a, _Tp __b, _Tp __x)
Return the Weibull cumulative probability density function.
template<typename _Tp >
_Tp __weibull_pdf (_Tp __a, _Tp __b, _Tp __x)
Return the Weibull probability density function.
template<typename _Tp >
__gnu_cxx::fp_promote_t< _Tp > __zernike (unsigned int __n, int __m, _Tp __rho, _Tp __phi)
template<typename _Tp >
_Tp __znorm1 (_Tp __x)
template<typename _Tp >
_Tp __znorm2 (_Tp __x)
Variables
template<typename _Tp >
constexpr int __max_FGH = _Airy_series<_Tp>::_N_FGH
template<>
constexpr int __max_FGH< double > = 79
template<>
constexpr int __max_FGH< float > = 15
constexpr size_t _Num_Euler_Maclaurin_zeta = 100
constexpr size_t _Num_Stieltjes = 21
constexpr _Factorial_table< long double > _S_double_factorial_table [301]
constexpr long double _S_Euler_Maclaurin_zeta [_Num_Euler_Maclaurin_zeta]
constexpr _Factorial_table< long double > _S_factorial_table [171]
constexpr unsigned long long _S_harmonic_denom [_S_num_harmonic_numer]
constexpr unsigned long long _S_harmonic_numer [_S_num_harmonic_numer]
constexpr _Factorial_table< long double > _S_neg_double_factorial_table [999]
template<typename _Tp >
constexpr std::size_t _S_num_double_factorials = 0
template<>
constexpr std::size_t _S_num_double_factorials< double > = 301
template<>
constexpr std::size_t _S_num_double_factorials< float > = 57
template<>
constexpr std::size_t _S_num_double_factorials< long double > = 301
template<typename _Tp >
constexpr std::size_t _S_num_factorials = 0
template<>
constexpr std::size_t _S_num_factorials< double > = 171
template<>
constexpr std::size_t _S_num_factorials< float > = 35
template<>
constexpr std::size_t _S_num_factorials< long double > = 171
constexpr unsigned long long _S_num_harmonic_numer = 29
template<typename _Tp >
constexpr std::size_t _S_num_neg_double_factorials = 0
template<>
constexpr std::size_t _S_num_neg_double_factorials< double > = 150
template<>
constexpr std::size_t _S_num_neg_double_factorials< float > = 27
template<>
constexpr std::size_t _S_num_neg_double_factorials< long double > = 999
constexpr size_t _S_num_zetam1 = 121
constexpr long double _S_Stieltjes [_Num_Stieltjes]
constexpr long double _S_zetam1 [_S_num_zetam1]
Detailed Description
Implementation-space details.
Function Documentation
__airy()
template<typename _Tp > __gnu_cxx::__airy_t<_Tp, _Tp> std::__detail::__airy (_Tp __z)
Compute the Airy functions and and their first derivatives and respectively.
Parameters
__z The argument of the Airy functions.
Returns
A struct containing the Airy functions of the first and second kinds and their derivatives.
Definition at line 475 of file sf_mod_bessel.tcc.
References __cyl_bessel_ik(), and __cyl_bessel_jn().
Referenced by __airy_ai(), __airy_bi(), __fock_airy(), and __hermite_asymp().
__airy_ai()
template<typename _Tp > std::complex<_Tp> std::__detail::__airy_ai (std::complex< _Tp > __z)
Return the complex Airy Ai function.
Definition at line 2629 of file sf_airy.tcc.
References __airy().
__airy_arg()
template<typename _Tp > void std::__detail::__airy_arg (std::complex< _Tp > __num2d3, std::complex< _Tp > __zeta, std::complex< _Tp > & __argp, std::complex< _Tp > & __argm)
Compute the arguments for the Airy function evaluations carefully to prevent premature overflow. Note that the major work here is in safe_div. A faster, but less safe implementation can be obtained without use of safe_div.
Parameters
[in] __num2d3 - output from hankel_params
[in] __zeta zeta in the uniform asymptotic expansions - output from hankel_params
[out] __argp
[out] __argm
Exceptions
std::runtime_error if unable to compute Airy function arguments
Definition at line 214 of file sf_hankel.tcc.
Referenced by __hankel_uniform_outer().
__airy_bi()
template<typename _Tp > std::complex<_Tp> std::__detail::__airy_bi (std::complex< _Tp > __z)
Return the complex Airy Bi function.
Definition at line 2641 of file sf_airy.tcc.
References __airy().
__assoc_laguerre()
template<typename _Tpa , typename _Tp > _Tp std::__detail::__assoc_laguerre (unsigned int __n, _Tpa __alpha, _Tp __x)
This routine returns the associated Laguerre polynomial of degree n, order m: .
The associated Laguerre polynomial is defined for integral order by:
where the Laguerre polynomial is defined by:
Template Parameters
_Tpa The type of the order.
_Tp The type of the parameter
Parameters
__n The degree
__alpha The order
__x The argument
Returns
The value of the associated Laguerre polynomial of order n, degree m, and argument x.
Definition at line 367 of file sf_laguerre.tcc.
Referenced by __hydrogen().
__assoc_legendre_p()
template<typename _Tp > __gnu_cxx::__assoc_legendre_p_t<_Tp> std::__detail::__assoc_legendre_p (unsigned int __l, unsigned int __m, _Tp __x, _Tp __phase = _Tp{+1})
Return the associated Legendre function by recursion on and downward recursion on m.
The associated Legendre function is derived from the Legendre function by the Rodrigues formula:
Note
The Condon-Shortley phase factor is absent by default.
if .
Parameters
__l The degree of the associated Legendre function. .
__m The order of the associated Legendre function.
__x The argument of the associated Legendre function.
__phase The phase of the associated Legendre function. Use -1 for the Condon-Shortley phase convention.
Definition at line 241 of file sf_legendre.tcc.
References __legendre_p().
__assoc_legendre_q()
template<typename _Tp > __gnu_cxx::__assoc_legendre_q_t<_Tp> std::__detail::__assoc_legendre_q (unsigned int __l, unsigned int __m, _Tp __x, _Tp __phase = _Tp{+1})
Definition at line 299 of file sf_legendre.tcc.
__bell() [1/2]
template<typename _Tp > std::vector<_Tp> std::__detail::__bell (unsigned int __n) inline
Return a vector of the Bell numbers.
Definition at line 509 of file sf_stirling.tcc.
Referenced by __bell(), __bell_series(), and __gnu_cxx::bell().
__bell() [2/2]
template<typename _Tp , typename _Up > _Up std::__detail::__bell (unsigned int __n, _Up __x) inline
Evaluate the Bell polynomial
where are the Stirling numbers of the second kind.
Definition at line 521 of file sf_stirling.tcc.
References __bell().
__bell_series()
template<typename _Tp > std::vector<_Tp> std::__detail::__bell_series (unsigned int __n)
Return a vector of the Bell numbers by summation.
where are the Stirling numbers of the second kind.
Todo:
Test for blowup in Bell number summation.
Definition at line 490 of file sf_stirling.tcc.
References __bell().
__bernoulli() [1/2]
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__bernoulli (unsigned int __n)
This returns Bernoulli number .
Parameters
__n the order n of the Bernoulli number.
Returns
The Bernoulli number of order n.
Definition at line 128 of file sf_bernoulli.tcc.
Referenced by __euler(), and __gnu_cxx::bernoulli().
__bernoulli() [2/2]
template<typename _Tp > _Tp std::__detail::__bernoulli (unsigned int __n, _Tp __x)
Return the Bernoulli polynomial of order n at argument x.
The values at 0 and 1 are equal to the corresponding Bernoulli number:
The derivative is proportional to the previous polynomial:
The series expansion is:
A useful argument promotion is:
Definition at line 168 of file sf_bernoulli.tcc.
References __binomial().
__bernoulli_2n()
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__bernoulli_2n (unsigned int __n)
This returns Bernoulli number at even integer arguments .
Parameters
__n the half-order n of the Bernoulli number.
Returns
The Bernoulli number of order 2n.
Definition at line 140 of file sf_bernoulli.tcc.
__bernoulli_series()
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__bernoulli_series (unsigned int __n)
This returns Bernoulli numbers from a table or by summation for larger values.
.
Note that
are small and rapidly decreasing finctions of n.
Parameters
__n the order n of the Bernoulli number.
Returns
The Bernoulli number of order n.
Definition at line 65 of file sf_bernoulli.tcc.
__beta()
template<typename _Tp > _Tp std::__detail::__beta (_Tp __a, _Tp __b)
Return the beta function .
The beta function is defined by
Parameters
__a The first argument of the beta function.
__b The second argument of the beta function.
Returns
The beta function.
Definition at line 215 of file sf_beta.tcc.
References __beta_gamma(), and __beta_lgamma().
Referenced by __fisher_f_pdf(), __gnu_cxx::gamma_pdf(), __gnu_cxx::jacobi(), __gnu_cxx::jacobif(), __gnu_cxx::jacobil(), __gnu_cxx::mittag_leffler(), and std::__detail::_Airy< _Tp >::operator()().
__beta_gamma()
template<typename _Tp > _Tp std::__detail::__beta_gamma (_Tp __a, _Tp __b)
Return the beta function: .
The beta function is defined by
Parameters
__a The first argument of the beta function.
__b The second argument of the beta function.
Returns
The beta function.
Definition at line 77 of file sf_beta.tcc.
References __gamma().
Referenced by __beta().
__beta_inc()
template<typename _Tp > _Tp std::__detail::__beta_inc (_Tp __a, _Tp __b, _Tp __x)
Return the regularized incomplete beta function, , of arguments a, b, and x.
The regularized incomplete beta function is defined by:
where
is the non-regularized beta function and is the usual beta function.
Parameters
__a The first parameter
__b The second parameter
__x The argument
Definition at line 311 of file sf_beta.tcc.
References __ibeta_cont_frac(), __log_gamma(), and __log_gamma_sign().
Referenced by __beta_p(), __binomial_p(), __binomial_q(), __fisher_f_p(), __fisher_f_q(), __student_t_p(), and __student_t_q().
__beta_lgamma()
template<typename _Tp > _Tp std::__detail::__beta_lgamma (_Tp __a, _Tp __b)
Return the beta function using the log gamma functions.
The beta function is defined by
Parameters
__a The first argument of the beta function.
__b The second argument of the beta function.
Returns
The beta function.
Definition at line 125 of file sf_beta.tcc.
References __log_gamma(), and __log_gamma_sign().
Referenced by __beta().
__beta_p()
template<typename _Tp > _Tp std::__detail::__beta_p (_Tp __a, _Tp __b, _Tp __x)
Definition at line 705 of file sf_distributions.tcc.
References __beta_inc().
__beta_product()
template<typename _Tp > _Tp std::__detail::__beta_product (_Tp __a, _Tp __b)
Return the beta function using the product form.
The beta function is defined by
Here, we employ the product form:
Parameters
__a The first argument of the beta function.
__b The second argument of the beta function.
Returns
The beta function.
Definition at line 179 of file sf_beta.tcc.
__binomial() [1/2]
template<typename _Tp > _Tp std::__detail::__binomial (unsigned int __n, unsigned int __k)
Return the binomial coefficient. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
Parameters
__n The first argument of the binomial coefficient.
__k The second argument of the binomial coefficient.
Returns
The binomial coefficient.
Definition at line 2540 of file sf_gamma.tcc.
References std::__detail::_Factorial_table< _Tp >::__n.
Referenced by __bernoulli().
__binomial() [2/2]
template<typename _Tp > _Tp std::__detail::__binomial (_Tp __nu, unsigned int __k)
Return the binomial coefficient for non-integral degree. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
Parameters
__nu The real first argument of the binomial coefficient.
__k The second argument of the binomial coefficient.
Returns
The binomial coefficient.
Definition at line 2600 of file sf_gamma.tcc.
References __gamma(), __log_binomial(), __log_binomial_sign(), and std::__detail::_Factorial_table< _Tp >::__n.
__binomial_p()
template<typename _Tp > _Tp std::__detail::__binomial_p (_Tp __p, unsigned int __n, unsigned int __k)
Return the binomial cumulative distribution function.
The binomial cumulative distribution function is related to the incomplete beta function:
Parameters
__p
__n
__k
Definition at line 614 of file sf_distributions.tcc.
References __beta_inc().
__binomial_pdf()
template<typename _Tp > _Tp std::__detail::__binomial_pdf (_Tp __p, unsigned int __n, unsigned int __k)
Return the binomial probability mass function.
The binomial cumulative distribution function is related to the incomplete beta function:
Parameters
__p
__n
__k
Definition at line 578 of file sf_distributions.tcc.
__binomial_q()
template<typename _Tp > _Tp std::__detail::__binomial_q (_Tp __p, unsigned int __n, unsigned int __k)
Return the complementary binomial cumulative distribution function.
The binomial cumulative distribution function is related to the incomplete beta function:
Parameters
__p
__n
__k
Definition at line 644 of file sf_distributions.tcc.
References __beta_inc().
__bose_einstein()
template<typename _Sp , typename _Tp > _Tp std::__detail::__bose_einstein (_Sp __s, _Tp __x)
Return the Bose-Einstein integral of integer or real order s and real argument x.
See also
https://en.wikipedia.org/wiki/Clausen_function
http://dlmf.nist.gov/25.12.16
Parameters
__s The order s >= 0.
__x The real argument.
Returns
The real Bose-Einstein integral G_s(x),
Definition at line 1493 of file sf_polylog.tcc.
References __polylog_exp().
__cauchy_p()
template<typename _Tp > _Tp std::__detail::__cauchy_p (_Tp __a, _Tp __b, _Tp __x)
Definition at line 697 of file sf_distributions.tcc.
__chebyshev_recur()
template<typename _Tp > std::tuple<_Tp, _Tp, _Tp> std::__detail::__chebyshev_recur (unsigned int __n, _Tp __x, _Tp _C0, _Tp _C1)
Return a Chebyshev polynomial of non-negative order and real argument by the recursion
Template Parameters
_Tp The real type of the argument
Parameters
__n The non-negative integral order
__x The real argument
_C0 The value of the zeroth-order Chebyshev polynomial at
_C1 The value of the first-order Chebyshev polynomial at
Definition at line 60 of file sf_chebyshev.tcc.
Referenced by __chebyshev_t(), __chebyshev_u(), __chebyshev_v(), and __chebyshev_w().
__chebyshev_t()
template<typename _Tp > __gnu_cxx::__chebyshev_t_t<_Tp> std::__detail::__chebyshev_t (unsigned int __n, _Tp __x)
Return the Chebyshev polynomial of the first kind of non-negative order and real argument .
The Chebyshev polynomial of the first kind is defined by:
where , .
Template Parameters
_Tp The real type of the argument
Parameters
__n The non-negative integral order
__x The real argument
Definition at line 88 of file sf_chebyshev.tcc.
References __chebyshev_recur().
__chebyshev_u()
template<typename _Tp > __gnu_cxx::__chebyshev_u_t<_Tp> std::__detail::__chebyshev_u (unsigned int __n, _Tp __x)
Return the Chebyshev polynomial of the second kind of non-negative order and real argument .
The Chebyshev polynomial of the second kind is defined by:
where , .
Template Parameters
_Tp The real type of the argument
Parameters
__n The non-negative integral order
__x The real argument
Definition at line 118 of file sf_chebyshev.tcc.
References __chebyshev_recur().
__chebyshev_v()
template<typename _Tp > __gnu_cxx::__chebyshev_v_t<_Tp> std::__detail::__chebyshev_v (unsigned int __n, _Tp __x)
Return the Chebyshev polynomial of the third kind of non-negative order and real argument .
The Chebyshev polynomial of the third kind is defined by:
where , .
Template Parameters
_Tp The real type of the argument
Parameters
__n The non-negative integral order
__x The real argument
Definition at line 149 of file sf_chebyshev.tcc.
References __chebyshev_recur().
__chebyshev_w()
template<typename _Tp > __gnu_cxx::__chebyshev_w_t<_Tp> std::__detail::__chebyshev_w (unsigned int __n, _Tp __x)
Return the Chebyshev polynomial of the fourth kind of non-negative order and real argument .
The Chebyshev polynomial of the fourth kind is defined by:
where , .
Template Parameters
_Tp The real type of the argument
Parameters
__n The non-negative integral order
__x The real argument
Definition at line 180 of file sf_chebyshev.tcc.
References __chebyshev_recur().
__chi_squared_pdf()
template<typename _Tp > _Tp std::__detail::__chi_squared_pdf (_Tp __chi2, unsigned int __nu)
Return the chi-squared propability function. This returns the probability that the observed chi-squared for a correct model is less than the value .
The chi-squared propability function is related to the normalized lower incomplete gamma function:
Definition at line 75 of file sf_distributions.tcc.
References __gamma_p().
__chi_squared_pdfc()
template<typename _Tp > _Tp std::__detail::__chi_squared_pdfc (_Tp __chi2, unsigned int __nu)
Return the complementary chi-squared propability function. This returns the probability that the observed chi-squared for a correct model is greater than the value .
The complementary chi-squared propability function is related to the normalized upper incomplete gamma function:
Definition at line 99 of file sf_distributions.tcc.
References __gamma_q().
__chshint()
template<typename _Tp > std::pair<_Tp, _Tp> std::__detail::__chshint (_Tp __x, _Tp & _Chi, _Tp & _Shi)
This function returns the hyperbolic cosine and hyperbolic sine integrals as a pair.
The hyperbolic cosine integral is defined by:
The hyperbolic sine integral is defined by:
Definition at line 166 of file sf_hypint.tcc.
References __chshint_cont_frac(), and __chshint_series().
__chshint_cont_frac()
template<typename _Tp > void std::__detail::__chshint_cont_frac (_Tp __t, _Tp & _Chi, _Tp & _Shi)
This function computes the hyperbolic cosine and hyperbolic sine integrals by continued fraction for positive argument.
Definition at line 53 of file sf_hypint.tcc.
Referenced by __chshint().
__chshint_series()
template<typename _Tp > void std::__detail::__chshint_series (_Tp __t, _Tp & _Chi, _Tp & _Shi)
This function computes the hyperbolic cosine and hyperbolic sine integrals by series summation for positive argument.
Definition at line 96 of file sf_hypint.tcc.
Referenced by __chshint().
__clamp_0_m2pi()
template<typename _Tp > std::complex<_Tp> std::__detail::__clamp_0_m2pi (std::complex< _Tp > __z)
Definition at line 185 of file sf_polylog.tcc.
Referenced by __polylog_exp_neg_int(), __polylog_exp_neg_real(), __polylog_exp_pos_int(), and __polylog_exp_pos_real().
__clamp_pi()
template<typename _Tp > std::complex<_Tp> std::__detail::__clamp_pi (std::complex< _Tp > __z)
Definition at line 171 of file sf_polylog.tcc.
Referenced by __polylog_exp_neg_int(), __polylog_exp_neg_real(), __polylog_exp_pos_int(), and __polylog_exp_pos_real().
__clausen() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__clausen (unsigned int __m, std::complex< _Tp > __z)
Return Clausen's function of integer order m and complex argument z. The notation and connection to polylog is from Wikipedia
Parameters
__m The non-negative integral order.
__z The complex argument.
Returns
The complex Clausen function.
Definition at line 1288 of file sf_polylog.tcc.
References __polylog_exp().
__clausen() [2/2]
template<typename _Tp > _Tp std::__detail::__clausen (unsigned int __m, _Tp __x)
Return Clausen's function of integer order m and real argument x. The notation and connection to polylog is from Wikipedia
Parameters
__m The integer order m >= 1.
__x The real argument.
Returns
The Clausen function.
Definition at line 1315 of file sf_polylog.tcc.
References __polylog_exp().
__clausen_cl() [1/2]
template<typename _Tp > _Tp std::__detail::__clausen_cl (unsigned int __m, std::complex< _Tp > __z)
Return Clausen's cosine sum Cl_m for positive integer order m and complex argument w.
See also
https://en.wikipedia.org/wiki/Clausen_function
Parameters
__m The integer order m >= 1.
__z The complex argument.
Returns
The Clausen cosine sum Cl_m(w),
Definition at line 1399 of file sf_polylog.tcc.
References __polylog_exp().
__clausen_cl() [2/2]
template<typename _Tp > _Tp std::__detail::__clausen_cl (unsigned int __m, _Tp __x)
Return Clausen's cosine sum Cl_m for positive integer order m and real argument w.
See also
https://en.wikipedia.org/wiki/Clausen_function
Parameters
__m The integer order m >= 1.
__x The real argument.
Returns
The real Clausen cosine sum Cl_m(w),
Definition at line 1427 of file sf_polylog.tcc.
References __polylog_exp().
__clausen_sl() [1/2]
template<typename _Tp > _Tp std::__detail::__clausen_sl (unsigned int __m, std::complex< _Tp > __z)
Return Clausen's sine sum Sl_m for positive integer order m and complex argument z.
See also
https://en.wikipedia.org/wiki/Clausen_function
Parameters
__m The integer order m >= 1.
__z The complex argument.
Returns
The Clausen sine sum Sl_m(w),
Definition at line 1343 of file sf_polylog.tcc.
References __polylog_exp().
__clausen_sl() [2/2]
template<typename _Tp > _Tp std::__detail::__clausen_sl (unsigned int __m, _Tp __x)
Return Clausen's sine sum Sl_m for positive integer order m and real argument x.
See also
https://en.wikipedia.org/wiki/Clausen_function
Parameters
__m The integer order m >= 1.
__x The real argument.
Returns
The Clausen sine sum Sl_m(w),
Definition at line 1371 of file sf_polylog.tcc.
References __polylog_exp().
__comp_ellint_1()
template<typename _Tp > _Tp std::__detail::__comp_ellint_1 (_Tp __k)
Return the complete elliptic integral of the first kind using the Carlson formulation.
The complete elliptic integral of the first kind is defined as
where is the incomplete elliptic integral of the first kind.
Parameters
__k The modulus of the complete elliptic function.
Returns
The complete elliptic function of the first kind.
Definition at line 592 of file sf_ellint.tcc.
References __comp_ellint_rf().
Referenced by __ellint_1(), __ellnome_k(), __heuman_lambda(), __jacobi_zeta(), __theta_c(), __theta_d(), __theta_n(), and __theta_s().
__comp_ellint_2()
template<typename _Tp > _Tp std::__detail::__comp_ellint_2 (_Tp __k)
Return the complete elliptic integral of the second kind using the Carlson formulation.
The complete elliptic integral of the second kind is defined as
Parameters
__k The modulus of the complete elliptic function.
Returns
The complete elliptic function of the second kind.
Definition at line 666 of file sf_ellint.tcc.
References __ellint_rd(), and __ellint_rf().
Referenced by __ellint_2().
__comp_ellint_3()
template<typename _Tp > _Tp std::__detail::__comp_ellint_3 (_Tp __k, _Tp __nu)
Return the complete elliptic integral of the third kind using the Carlson formulation.
The complete elliptic integral of the third kind is defined as
Parameters
__k The elliptic modulus.
__nu The characteristic.
Returns
The complete elliptic function of the third kind.
Definition at line 756 of file sf_ellint.tcc.
References __ellint_rf(), and __ellint_rj().
Referenced by __ellint_3().
__comp_ellint_d()
template<typename _Tp > _Tp std::__detail::__comp_ellint_d (_Tp __k)
Return the complete Legendre elliptic integral D.
Definition at line 862 of file sf_ellint.tcc.
References __ellint_rd().
__comp_ellint_rf()
template<typename _Tp > _Tp std::__detail::__comp_ellint_rf (_Tp __x, _Tp __y)
Definition at line 252 of file sf_ellint.tcc.
Referenced by __comp_ellint_1(), and __ellint_rf().
__comp_ellint_rg()
template<typename _Tp > _Tp std::__detail::__comp_ellint_rg (_Tp __x, _Tp __y)
Definition at line 368 of file sf_ellint.tcc.
Referenced by __ellint_rg().
__conf_hyperg()
template<typename _Tp > _Tp std::__detail::__conf_hyperg (_Tp __a, _Tp __c, _Tp __x)
Return the confluent hypergeometric function .
Parameters
__a The numerator parameter.
__c The denominator parameter.
__x The argument of the confluent hypergeometric function.
Returns
The confluent hypergeometric function.
Definition at line 337 of file sf_hyperg.tcc.
References __conf_hyperg_luke(), __conf_hyperg_series(), and __gnu_cxx::__fp_is_integer().
Referenced by __tricomi_u_naive().
__conf_hyperg_lim()
template<typename _Tp > _Tp std::__detail::__conf_hyperg_lim (_Tp __c, _Tp __x)
Return the confluent hypergeometric limit function .
Parameters
__c The denominator parameter.
__x The argument of the confluent hypergeometric limit function.
Returns
The confluent limit hypergeometric function.
Definition at line 163 of file sf_hyperg.tcc.
References __conf_hyperg_lim_series(), and __gnu_cxx::__fp_is_integer().
__conf_hyperg_lim_series()
template<typename _Tp > _Tp std::__detail::__conf_hyperg_lim_series (_Tp __c, _Tp __x)
This routine returns the confluent hypergeometric limit function by series expansion.
If a and b are integers and a < 0 and either b > 0 or b < a then the series is a polynomial with a finite number of terms.
Parameters
__c The "denominator" parameter.
__x The argument of the confluent hypergeometric limit function.
Returns
The confluent hypergeometric limit function.
Definition at line 130 of file sf_hyperg.tcc.
Referenced by __conf_hyperg_lim().
__conf_hyperg_luke()
template<typename _Tp > _Tp std::__detail::__conf_hyperg_luke (_Tp __a, _Tp __c, _Tp __xin)
Return the hypergeometric function by an iterative procedure described in Luke, Algorithms for the Computation of Mathematical Functions.
Like the case of the 2F1 rational approximations, these are probably guaranteed to converge for x < 0, barring gross numerical instability in the pre-asymptotic regime.
Definition at line 231 of file sf_hyperg.tcc.
Referenced by __conf_hyperg().
__conf_hyperg_series()
template<typename _Tp > _Tp std::__detail::__conf_hyperg_series (_Tp __a, _Tp __c, _Tp __x)
This routine returns the confluent hypergeometric function by series expansion.
Parameters
__a The "numerator" parameter.
__c The "denominator" parameter.
__x The argument of the confluent hypergeometric function.
Returns
The confluent hypergeometric function.
Definition at line 196 of file sf_hyperg.tcc.
Referenced by __conf_hyperg().
__cos_pi() [1/2]
template<typename _Tp > _Tp std::__detail::__cos_pi (_Tp __x)
Return the reperiodized cosine of argument x:
Definition at line 104 of file sf_trig.tcc.
Referenced by __cos_pi(), __cosh_pi(), __cyl_bessel_jn(), __cyl_bessel_jn_neg_arg(), __log_double_factorial(), __sin_pi(), and __sinh_pi().
__cos_pi() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__cos_pi (std::complex< _Tp > __z)
Return the reperiodized cosine of complex argument z:
Definition at line 231 of file sf_trig.tcc.
References __cos_pi(), and __sin_pi().
__cosh_pi() [1/2]
template<typename _Tp > _Tp std::__detail::__cosh_pi (_Tp __x)
Return the reperiodized hyperbolic cosine of argument x:
Definition at line 133 of file sf_trig.tcc.
__cosh_pi() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__cosh_pi (std::complex< _Tp > __z)
Return the reperiodized hyperbolic cosine of complex argument z:
Definition at line 253 of file sf_trig.tcc.
References __cos_pi(), and __sin_pi().
__coshint()
template<typename _Tp > _Tp std::__detail::__coshint (const _Tp __x)
Return the hyperbolic cosine integral .
The hyperbolic cosine integral is given by
Parameters
__x The argument of the hyperbolic cosine integral function.
Returns
The hyperbolic cosine integral.
Definition at line 561 of file sf_expint.tcc.
References __expint_E1(), and __expint_Ei().
__coulomb_CF1()
template<typename _Tp > std::pair<_Tp, _Tp> std::__detail::__coulomb_CF1 (unsigned int __l, _Tp __eta, _Tp __x)
Evaluate the first continued fraction, giving the ratio F'/F at the upper l value. We also determine the sign of F at that point, since it is the sign of the last denominator in the continued fraction.
Definition at line 146 of file sf_coulomb.tcc.
__coulomb_CF2()
template<typename _Tp > std::complex<_Tp> std::__detail::__coulomb_CF2 (unsigned int __l, _Tp __eta, _Tp __x)
Evaluate the second continued fraction to obtain the ratio
at the specified l value.
Definition at line 204 of file sf_coulomb.tcc.
__coulomb_f_recur()
template<typename _Tp > std::pair<_Tp, _Tp> std::__detail::__coulomb_f_recur (unsigned int __l_min, unsigned int __k_max, _Tp __eta, _Tp __x, _Tp _F_l_max, _Tp _Fp_l_max)
Evolve the backwards recurrence for F, F'.
where
Definition at line 77 of file sf_coulomb.tcc.
__coulomb_g_recur()
template<typename _Tp > std::pair<_Tp, _Tp> std::__detail::__coulomb_g_recur (unsigned int __l_min, unsigned int __k_max, _Tp __eta, _Tp __x, _Tp _G_l_min, _Tp _Gp_l_min)
Evolve the forward recurrence for G, G'.
where
Definition at line 115 of file sf_coulomb.tcc.
__coulomb_norm()
template<typename _Tp > _Tp std::__detail::__coulomb_norm (unsigned int __l, _Tp __eta)
Definition at line 49 of file sf_coulomb.tcc.
__cyl_bessel()
template<typename _Tp > std::complex<_Tp> std::__detail::__cyl_bessel (std::complex< _Tp > __nu, std::complex< _Tp > __z)
Return the complex cylindrical Bessel function.
Parameters
[in] __nu The order for which the cylindrical Bessel function is evaluated.
[in] __z The argument at which the cylindrical Bessel function is evaluated.
Returns
The complex cylindrical Bessel function.
Definition at line 1173 of file sf_hankel.tcc.
References __hankel().
__cyl_bessel_i()
template<typename _Tp > _Tp std::__detail::__cyl_bessel_i (_Tp __nu, _Tp __x)
Return the regular modified Bessel function of order : .
The regular modified cylindrical Bessel function is:
Parameters
__nu The order of the regular modified Bessel function.
__x The argument of the regular modified Bessel function.
Returns
The output regular modified Bessel function.
Definition at line 371 of file sf_mod_bessel.tcc.
References __cyl_bessel_ij_series(), and __cyl_bessel_ik().
Referenced by __rice_pdf().
__cyl_bessel_ij_series()
template<typename _Tp > _Tp std::__detail::__cyl_bessel_ij_series (_Tp __nu, _Tp __x, _Tp __sgn, unsigned int __max_iter)
This routine returns the cylindrical Bessel functions of order : or by series expansion.
The modified cylindrical Bessel function is:
where or for or respectively.
See Abramowitz & Stegun, 9.1.10 Abramowitz & Stegun, 9.6.7 (1) Handbook of Mathematical Functions, ed. Milton Abramowitz and Irene A. Stegun, Dover Publications, Equation 9.1.10 p. 360 and Equation 9.6.10 p. 375
Parameters
__nu The order of the Bessel function.
__x The argument of the Bessel function.
__sgn The sign of the alternate terms -1 for the Bessel function of the first kind. +1 for the modified Bessel function of the first kind.
__max_iter The maximum number of iterations for sum.
Returns
The output Bessel function.
Definition at line 434 of file sf_bessel.tcc.
References __log_gamma().
Referenced by __cyl_bessel_i(), and __cyl_bessel_j().
__cyl_bessel_ik()
template<typename _Tp > __gnu_cxx::__cyl_mod_bessel_t<_Tp, _Tp, _Tp> std::__detail::__cyl_bessel_ik (_Tp __nu, _Tp __x)
Return the modified cylindrical Bessel functions and their derivatives of order by various means.
Parameters
__nu The order of the Bessel functions.
__x The argument of the Bessel functions.
Returns
A struct containing the modified cylindrical Bessel functions of the first and second kinds and their derivatives.
Definition at line 309 of file sf_mod_bessel.tcc.
References __cyl_bessel_ik_asymp(), __cyl_bessel_ik_steed(), and __sin_pi().
Referenced by __airy(), __cyl_bessel_i(), __cyl_bessel_k(), and __sph_bessel_ik().
__cyl_bessel_ik_asymp()
template<typename _Tp > __gnu_cxx::__cyl_mod_bessel_t<_Tp, _Tp, _Tp> std::__detail::__cyl_bessel_ik_asymp (_Tp __nu, _Tp __x)
This routine computes the asymptotic modified cylindrical Bessel and functions of order nu: , . Use this for .
References: (1) Handbook of Mathematical Functions, ed. Milton Abramowitz and Irene A. Stegun, Dover Publications, Section 9 p. 364, Equations 9.2.5-9.2.10
Parameters
__nu The order of the Bessel functions.
__x The argument of the Bessel functions.
Returns
A struct containing the modified cylindrical Bessel functions of the first and second kinds and their derivatives.
Definition at line 79 of file sf_mod_bessel.tcc.
Referenced by __cyl_bessel_ik(), and __cyl_bessel_ik_steed().
__cyl_bessel_ik_steed()
template<typename _Tp > __gnu_cxx::__cyl_mod_bessel_t<_Tp, _Tp, _Tp> std::__detail::__cyl_bessel_ik_steed (_Tp __nu, _Tp __x)
Compute the modified Bessel functions and and their first derivatives and respectively. These four functions are computed together for numerical stability.
Parameters
__nu The order of the Bessel functions.
__x The argument of the Bessel functions.
Returns
A struct containing the modified cylindrical Bessel functions of the first and second kinds and their derivatives.
Definition at line 153 of file sf_mod_bessel.tcc.
References __cyl_bessel_ik_asymp(), and __gamma_temme().
Referenced by __cyl_bessel_ik().
__cyl_bessel_j()
template<typename _Tp > _Tp std::__detail::__cyl_bessel_j (_Tp __nu, _Tp __x)
Return the Bessel function of order : .
The cylindrical Bessel function is:
Parameters
__nu The order of the Bessel function.
__x The argument of the Bessel function.
Returns
The output Bessel function.
Definition at line 581 of file sf_bessel.tcc.
References __cyl_bessel_ij_series(), and __cyl_bessel_jn().
__cyl_bessel_jn()
template<typename _Tp > __gnu_cxx::__cyl_bessel_t<_Tp, _Tp, _Tp> std::__detail::__cyl_bessel_jn (_Tp __nu, _Tp __x)
Return the cylindrical Bessel functions and their derivatives of order by various means.
Definition at line 473 of file sf_bessel.tcc.
References __cos_pi(), __cyl_bessel_jn_asymp(), __cyl_bessel_jn_steed(), and __sin_pi().
Referenced by __airy(), __cyl_bessel_j(), __cyl_bessel_jn_neg_arg(), __cyl_hankel_1(), __cyl_hankel_2(), __cyl_neumann_n(), and __sph_bessel_jn().
__cyl_bessel_jn_asymp()
template<typename _Tp > __gnu_cxx::__cyl_bessel_t<_Tp, _Tp, _Tp> std::__detail::__cyl_bessel_jn_asymp (_Tp __nu, _Tp __x)
This routine computes the asymptotic cylindrical Bessel and Neumann functions of order nu: , . Use this for .
and
where and
There sums work everywhere but on the negative real axis: .
References: (1) Handbook of Mathematical Functions, ed. Milton Abramowitz and Irene A. Stegun, Dover Publications, Section 9 p. 364, Equations 9.2.5-9.2.10
Parameters
__nu The order of the Bessel functions.
__x The argument of the Bessel functions.
Returns
A struct containing the cylindrical Bessel functions of the first and second kinds and their derivatives.
Definition at line 100 of file sf_bessel.tcc.
Referenced by __cyl_bessel_jn(), and __cyl_bessel_jn_steed().
__cyl_bessel_jn_neg_arg()
template<typename _Tp > __gnu_cxx::__cyl_bessel_t<_Tp, _Tp, std::complex<_Tp> > std::__detail::__cyl_bessel_jn_neg_arg (_Tp __nu, _Tp __x)
Return the cylindrical Bessel functions and their derivatives of order and argument .
Definition at line 539 of file sf_bessel.tcc.
References __cos_pi(), __cyl_bessel_jn(), and __polar_pi().
Referenced by __cyl_hankel_1(), __cyl_hankel_2(), and __sph_bessel_jn_neg_arg().
__cyl_bessel_jn_steed()
template<typename _Tp > __gnu_cxx::__cyl_bessel_t<_Tp, _Tp, _Tp> std::__detail::__cyl_bessel_jn_steed (_Tp __nu, _Tp __x)
Compute the Bessel and Neumann functions and their first derivatives and respectively. These four functions are computed together for numerical stability.
Parameters
__nu The order of the Bessel functions.
__x The argument of the Bessel functions.
Returns
A struct containing the cylindrical Bessel functions of the first and second kinds and their derivatives.
Definition at line 229 of file sf_bessel.tcc.
References __cyl_bessel_jn_asymp(), and __gamma_temme().
Referenced by __cyl_bessel_jn().
__cyl_bessel_k()
template<typename _Tp > _Tp std::__detail::__cyl_bessel_k (_Tp __nu, _Tp __x)
Return the irregular modified Bessel function of order .
The irregular modified Bessel function is defined by:
where for integral a limit is taken: . For negative argument we have simply:
Parameters
__nu The order of the irregular modified Bessel function.
__x The argument of the irregular modified Bessel function.
Returns
The output irregular modified Bessel function.
Definition at line 405 of file sf_mod_bessel.tcc.
References __cyl_bessel_ik().
__cyl_hankel_1() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__cyl_hankel_1 (_Tp __nu, _Tp __x)
Return the cylindrical Hankel function of the first kind .
The cylindrical Hankel function of the first kind is defined by:
Parameters
__nu The order of the spherical Neumann function.
__x The argument of the spherical Neumann function.
Returns
The output spherical Neumann function.
Definition at line 638 of file sf_bessel.tcc.
References __cyl_bessel_jn(), __cyl_bessel_jn_neg_arg(), and __polar_pi().
__cyl_hankel_1() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__cyl_hankel_1 (std::complex< _Tp > __nu, std::complex< _Tp > __z)
Return the complex cylindrical Hankel function of the first kind.
Parameters
[in] __nu The order for which the cylindrical Hankel function of the first kind is evaluated.
[in] __z The argument at which the cylindrical Hankel function of the first kind is evaluated.
Returns
The complex cylindrical Hankel function of the first kind.
Definition at line 1139 of file sf_hankel.tcc.
References __hankel().
__cyl_hankel_2() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__cyl_hankel_2 (_Tp __nu, _Tp __x)
Return the cylindrical Hankel function of the second kind .
The cylindrical Hankel function of the second kind is defined by:
Parameters
__nu The order of the spherical Neumann function.
__x The argument of the spherical Neumann function.
Returns
The output spherical Neumann function.
Definition at line 677 of file sf_bessel.tcc.
References __cyl_bessel_jn(), __cyl_bessel_jn_neg_arg(), and __polar_pi().
__cyl_hankel_2() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__cyl_hankel_2 (std::complex< _Tp > __nu, std::complex< _Tp > __z)
Return the complex cylindrical Hankel function of the second kind.
Parameters
[in] __nu The order for which the cylindrical Hankel function of the second kind is evaluated.
[in] __z The argument at which the cylindrical Hankel function of the second kind is evaluated.
Returns
The complex cylindrical Hankel function of the second kind.
Definition at line 1156 of file sf_hankel.tcc.
References __hankel().
__cyl_neumann()
template<typename _Tp > std::complex<_Tp> std::__detail::__cyl_neumann (std::complex< _Tp > __nu, std::complex< _Tp > __z)
Return the complex cylindrical Neumann function.
Parameters
[in] __nu The order for which the cylindrical Neumann function is evaluated.
[in] __z The argument at which the cylindrical Neumann function is evaluated.
Returns
The complex cylindrical Neumann function.
Definition at line 1190 of file sf_hankel.tcc.
References __hankel().
__cyl_neumann_n()
template<typename _Tp > _Tp std::__detail::__cyl_neumann_n (_Tp __nu, _Tp __x)
Return the Neumann function of order : .
The Neumann function is defined by:
where for integral a limit is taken: .
Parameters
__nu The order of the Neumann function.
__x The argument of the Neumann function.
Returns
The output Neumann function.
Definition at line 612 of file sf_bessel.tcc.
References __cyl_bessel_jn().
__dawson()
template<typename _Tp > _Tp std::__detail::__dawson (_Tp __x)
Return the Dawson integral, , for real argument x.
The Dawson integral is defined by:
and it's derivative is:
Parameters
__x The argument .
Definition at line 235 of file sf_dawson.tcc.
References __dawson_cont_frac(), and __dawson_series().
__dawson_cont_frac()
template<typename _Tp > _Tp std::__detail::__dawson_cont_frac (_Tp __x)
Compute the Dawson integral using a sampling theorem representation.
This array could be built on a thread-local basis.
Definition at line 73 of file sf_dawson.tcc.
Referenced by __dawson().
__dawson_series()
template<typename _Tp > _Tp std::__detail::__dawson_series (_Tp __x)
Compute the Dawson integral using the series expansion.
Definition at line 49 of file sf_dawson.tcc.
Referenced by __dawson().
__debye()
template<typename _Tp > _Tp std::__detail::__debye (unsigned int __n, _Tp __x)
Return the Debye function. The Debye functions are related to the incomplete Riemann zeta function:
where is the incomplete gamma function ratios. The Debye function is:
Note the infinite limit:
Todo:
: We should return both the Debye function and it's complement.
Compute the Debye function:
Abramowitz & Stegun 27.1.2
Compute the Debye function:
for . Abramowitz-Stegun 27.1.1
Todo:
Find Debye for x < -2pi!
Definition at line 916 of file sf_zeta.tcc.
__debye_region()
template<typename _Tp > void std::__detail::__debye_region (std::complex< _Tp > __alpha, int & __indexr, char & __aorb)
Compute the Debye region in the complex plane.
Definition at line 53 of file sf_hankel.tcc.
Referenced by __hankel().
__digamma() [1/2]
template<typename _Tp > _Tp std::__detail::__digamma (unsigned int __n)
Return the digamma function of integral argument. The digamma or function is defined as the logarithmic derivative of the gamma function:
The digamma series for integral argument is given by:
The latter sum is called the harmonic number, .
Definition at line 3319 of file sf_gamma.tcc.
Referenced by __digamma(), __hyperg_reflect(), and __polygamma().
__digamma() [2/2]
template<typename _Tp > _Tp std::__detail::__digamma (_Tp __x)
Return the digamma function. The digamma or function is defined by
For negative argument the reflection formula is used:
.
Definition at line 3409 of file sf_gamma.tcc.
References __digamma(), __digamma_asymp(), __gnu_cxx::__fp_is_half_odd_integer(), __gnu_cxx::__fp_is_integer(), __hurwitz_zeta(), std::__detail::_Factorial_table< _Tp >::__n, and __tan_pi().
__digamma_asymp()
template<typename _Tp > _Tp std::__detail::__digamma_asymp (_Tp __x)
Return the digamma function for large argument. The digamma or function is defined by
.
The asymptotic series is given by:
Definition at line 3376 of file sf_gamma.tcc.
Referenced by __digamma().
__digamma_series()
template<typename _Tp > _Tp std::__detail::__digamma_series (_Tp __x)
Return the digamma function by series expansion. The digamma or function is defined by
.
The series is given by:
Definition at line 3344 of file sf_gamma.tcc.
__dilog()
template<typename _Tp > _Tp std::__detail::__dilog (_Tp __x)
Compute the dilogarithm function by summation for x <= 1.
The dilogarithm function is defined by:
For |x| near 1 use the reflection formulae:
For x < -1 use the reflection formula:
Definition at line 246 of file sf_zeta.tcc.
__dirichlet_beta() [1/2]
template<typename _Tp > _Tp std::__detail::__dirichlet_beta (std::complex< _Tp > __s)
Return the Dirichlet beta function. Currently, s must be real (complex type but negligible imaginary part.) Otherwise std::domain_error is thrown. The Dirichlet beta function, in terms of the polylogarithm, is
Parameters
__s The complex (but on-real-axis) argument.
Returns
The Dirichlet Beta function of real argument.
Exceptions
std::domain_error if the argument has a significant imaginary part.
Definition at line 1227 of file sf_polylog.tcc.
References __polylog().
__dirichlet_beta() [2/2]
template<typename _Tp > _Tp std::__detail::__dirichlet_beta (_Tp __s)
Return the Dirichlet beta function for real argument. The Dirichlet beta function, in terms of the polylogarithm, is
Parameters
__s The real argument.
Returns
The Dirichlet Beta function of real argument.
Definition at line 1250 of file sf_polylog.tcc.
References __polylog().
__dirichlet_eta() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__dirichlet_eta (std::complex< _Tp > __s)
Return the Dirichlet eta function. Currently, s must be real (complex type but negligible imaginary part.) Otherwise std::domain_error is thrown. The Dirichlet eta function, in terms of the polylogarithm, is
Parameters
__s The complex (but on-real-axis) argument.
Returns
The complex Dirichlet eta function.
Exceptions
std::domain_error if the argument has a significant imaginary part.
Definition at line 1167 of file sf_polylog.tcc.
References __polylog().
Referenced by __dirichlet_eta(), and __dirichlet_lambda().
__dirichlet_eta() [2/2]
template<typename _Tp > _Tp std::__detail::__dirichlet_eta (_Tp __s)
Return the Dirichlet eta function for real argument. The Dirichlet eta function, in terms of the polylogarithm, is
Parameters
__s The real argument.
Returns
The Dirichlet eta function.
Definition at line 1189 of file sf_polylog.tcc.
References __dirichlet_eta(), __gnu_cxx::__fp_is_integer(), __gamma(), __polylog(), and __sin_pi().
__dirichlet_lambda()
template<typename _Tp > _Tp std::__detail::__dirichlet_lambda (_Tp __s)
Return the Dirichlet lambda function for real argument.
Parameters
__s The real argument.
Returns
The Dirichlet lambda function.
Definition at line 1270 of file sf_polylog.tcc.
References __dirichlet_eta(), and __riemann_zeta().
__double_factorial()
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__double_factorial (int __n)
Return the double factorial of the integer n.
The double factorial is defined for integral n by:
The double factorial is defined for odd negative integers in the obvious way:
for $f[ n = -2m - 1 $f].
Definition at line 1687 of file sf_gamma.tcc.
References std::__detail::_Factorial_table< _Tp >::__factorial, __log_double_factorial(), std::__detail::_Factorial_table< _Tp >::__n, _S_double_factorial_table, and _S_neg_double_factorial_table.
__ellint_1()
template<typename _Tp > _Tp std::__detail::__ellint_1 (_Tp __k, _Tp __phi)
Return the incomplete elliptic integral of the first kind using the Carlson formulation.
The incomplete elliptic integral of the first kind is defined as
Parameters
__k The elliptic modulus.
__phi The integral limit argument of the elliptic function.
Returns
The elliptic function of the first kind.
Definition at line 621 of file sf_ellint.tcc.
References __comp_ellint_1(), and __ellint_rf().
Referenced by __heuman_lambda().
__ellint_2()
template<typename _Tp > _Tp std::__detail::__ellint_2 (_Tp __k, _Tp __phi)
Return the incomplete elliptic integral of the second kind using the Carlson formulation.
The incomplete elliptic integral of the second kind is defined as
Parameters
__k The elliptic modulus.
__phi The integral limit argument of the elliptic function.
Returns
The elliptic function of the second kind.
Definition at line 702 of file sf_ellint.tcc.
References __comp_ellint_2(), __ellint_rd(), and __ellint_rf().
__ellint_3()
template<typename _Tp > _Tp std::__detail::__ellint_3 (_Tp __k, _Tp __nu, _Tp __phi)
Return the incomplete elliptic integral of the third kind using the Carlson formulation.
The incomplete elliptic integral of the third kind is defined as
Parameters
__k The elliptic modulus.
__nu The characteristic.
__phi The integral limit argument of the elliptic function.
Returns
The elliptic function of the third kind.
Definition at line 795 of file sf_ellint.tcc.
References __comp_ellint_3(), __ellint_rf(), and __ellint_rj().
__ellint_cel()
template<typename _Tp > _Tp std::__detail::__ellint_cel (_Tp __k_c, _Tp __p, _Tp __a, _Tp __b)
Return the Bulirsch complete elliptic integrals.
Definition at line 950 of file sf_ellint.tcc.
References __ellint_rf(), and __ellint_rj().
__ellint_d()
template<typename _Tp > _Tp std::__detail::__ellint_d (_Tp __k, _Tp __phi)
Return the Legendre elliptic integral D.
Definition at line 836 of file sf_ellint.tcc.
References __ellint_rd().
__ellint_el1()
template<typename _Tp > _Tp std::__detail::__ellint_el1 (_Tp __x, _Tp __k_c)
Return the Bulirsch elliptic integrals of the first kind.
Definition at line 878 of file sf_ellint.tcc.
References __ellint_rf().
__ellint_el2()
template<typename _Tp > _Tp std::__detail::__ellint_el2 (_Tp __x, _Tp __k_c, _Tp __a, _Tp __b)
Return the Bulirsch elliptic integrals of the second kind.
Definition at line 899 of file sf_ellint.tcc.
References __ellint_rd(), and __ellint_rf().
__ellint_el3()
template<typename _Tp > _Tp std::__detail::__ellint_el3 (_Tp __x, _Tp __k_c, _Tp __p)
Return the Bulirsch elliptic integrals of the third kind.
Definition at line 924 of file sf_ellint.tcc.
References __ellint_rf(), and __ellint_rj().
__ellint_rc()
template<typename _Tp > _Tp std::__detail::__ellint_rc (_Tp __x, _Tp __y)
Return the Carlson elliptic function where is the Carlson elliptic function of the first kind.
The Carlson elliptic function is defined by:
Based on Carlson's algorithms:
B. C. Carlson Numer. Math. 33, 1 (1979)
B. C. Carlson, Special Functions of Applied Mathematics (1977)
Numerical Recipes in C, 2nd ed, pp. 261-269, by Press, Teukolsky, Vetterling, Flannery (1992)
Parameters
__x The first argument.
__y The second argument.
Returns
The Carlson elliptic function.
Definition at line 84 of file sf_ellint.tcc.
Referenced by __ellint_rf(), and __ellint_rj().
__ellint_rd()
template<typename _Tp > _Tp std::__detail::__ellint_rd (_Tp __x, _Tp __y, _Tp __z)
Return the Carlson elliptic function of the second kind where is the Carlson elliptic function of the third kind.
The Carlson elliptic function of the second kind is defined by:
Based on Carlson's algorithms:
B. C. Carlson Numer. Math. 33, 1 (1979)
B. C. Carlson, Special Functions of Applied Mathematics (1977)
Numerical Recipes in C, 2nd ed, pp. 261-269, by Press, Teukolsky, Vetterling, Flannery (1992)
Parameters
__x The first of two symmetric arguments.
__y The second of two symmetric arguments.
__z The third argument.
Returns
The Carlson elliptic function of the second kind.
Definition at line 175 of file sf_ellint.tcc.
Referenced by __comp_ellint_2(), __comp_ellint_d(), __ellint_2(), __ellint_d(), __ellint_el2(), __ellint_rg(), and __ellint_rj().
__ellint_rf()
template<typename _Tp > _Tp std::__detail::__ellint_rf (_Tp __x, _Tp __y, _Tp __z)
Return the Carlson elliptic function of the first kind.
The Carlson elliptic function of the first kind is defined by:
Parameters
__x The first of three symmetric arguments.
__y The second of three symmetric arguments.
__z The third of three symmetric arguments.
Returns
The Carlson elliptic function of the first kind.
Definition at line 294 of file sf_ellint.tcc.
References __comp_ellint_rf(), and __ellint_rc().
Referenced by __comp_ellint_2(), __comp_ellint_3(), __ellint_1(), __ellint_2(), __ellint_3(), __ellint_cel(), __ellint_el1(), __ellint_el2(), __ellint_el3(), and __heuman_lambda().
__ellint_rg()
template<typename _Tp > _Tp std::__detail::__ellint_rg (_Tp __x, _Tp __y, _Tp __z)
Return the symmetric Carlson elliptic function of the second kind .
The Carlson symmetric elliptic function of the second kind is defined by:
Based on Carlson's algorithms:
B. C. Carlson Numer. Math. 33, 1 (1979)
B. C. Carlson, Special Functions of Applied Mathematics (1977)
Numerical Recipes in C, 2nd ed, pp. 261-269, by Press, Teukolsky, Vetterling, Flannery (1992)
Parameters
__x The first of three symmetric arguments.
__y The second of three symmetric arguments.
__z The third of three symmetric arguments.
Returns
The Carlson symmetric elliptic function of the second kind.
Definition at line 430 of file sf_ellint.tcc.
References __comp_ellint_rg(), and __ellint_rd().
__ellint_rj()
template<typename _Tp > _Tp std::__detail::__ellint_rj (_Tp __x, _Tp __y, _Tp __z, _Tp __p)
Return the Carlson elliptic function of the third kind.
The Carlson elliptic function of the third kind is defined by:
Based on Carlson's algorithms:
B. C. Carlson Numer. Math. 33, 1 (1979)
B. C. Carlson, Special Functions of Applied Mathematics (1977)
Numerical Recipes in C, 2nd ed, pp. 261-269, by Press, Teukolsky, Vetterling, Flannery (1992)
Parameters
__x The first of three symmetric arguments.
__y The second of three symmetric arguments.
__z The third of three symmetric arguments.
__p The fourth argument.
Returns
The Carlson elliptic function of the fourth kind.
Definition at line 478 of file sf_ellint.tcc.
References __ellint_rc(), and __ellint_rd().
Referenced by __comp_ellint_3(), __ellint_3(), __ellint_cel(), __ellint_el3(), __heuman_lambda(), and __jacobi_zeta().
__ellnome()
template<typename _Tp > _Tp std::__detail::__ellnome (_Tp __k)
Return the elliptic nome given the modulus k.
Definition at line 329 of file sf_theta.tcc.
References __ellnome_k(), and __ellnome_series().
Referenced by __theta_c(), __theta_d(), __theta_n(), and __theta_s().
__ellnome_k()
template<typename _Tp > _Tp std::__detail::__ellnome_k (_Tp __k)
Use the arithmetic-geometric mean to calculate the elliptic nome given the elliptic argument k.
where is the complementary elliptic argument and is the Legendre elliptic integral of the first kind.
Definition at line 312 of file sf_theta.tcc.
References __comp_ellint_1().
Referenced by __ellnome().
__ellnome_series()
template<typename _Tp > _Tp std::__detail::__ellnome_series (_Tp __k)
Use MacLaurin series to calculate the elliptic nome given the elliptic argument k.
where is the complementary elliptic argument and is the Legendre elliptic integral of the first kind.
Definition at line 291 of file sf_theta.tcc.
Referenced by __ellnome().
__euler() [1/2]
template<typename _Tp > _Tp std::__detail::__euler (unsigned int __n) inline
This returns Euler number .
Parameters
__n the order n of the Euler number.
Returns
The Euler number of order n.
Definition at line 119 of file sf_euler.tcc.
__euler() [2/2]
template<typename _Tp > _Tp std::__detail::__euler (unsigned int __n, _Tp __x)
Return the Euler polynomial of order n at argument x.
The derivative is proportional to the previous polynomial:
Definition at line 137 of file sf_euler.tcc.
References __bernoulli().
__euler_series()
template<typename _Tp > _Tp std::__detail::__euler_series (unsigned int __n)
Return the Euler number from lookup or by series expansion.
The Euler numbers are given by the recursive sum:
where , ,
Todo:
Find a way to predict the maximum Euler number for a type.
Definition at line 61 of file sf_euler.tcc.
__eulerian_1() [1/2]
template<typename _Tp > _Tp std::__detail::__eulerian_1 (unsigned int __n, unsigned int __m) inline
Return the Eulerian number of the first kind. The Eulerian numbers of the first kind are defined by recursion:
Note that is a common older notation.
Definition at line 207 of file sf_euler.tcc.
__eulerian_1() [2/2]
template<typename _Tp > std::vector<_Tp> std::__detail::__eulerian_1 (unsigned int __n) inline
Return a vector Eulerian numbers of the first kind. The Eulerian numbers are defined by recursion:
Definition at line 253 of file sf_euler.tcc.
__eulerian_1_recur() [1/2]
template<typename _Tp > _Tp std::__detail::__eulerian_1_recur (unsigned int __n, unsigned int __m)
Return the Eulerian number of the first kind. The Eulerian numbers of the first kind are defined by recursion:
Note that is a common older notation.
Definition at line 166 of file sf_euler.tcc.
__eulerian_1_recur() [2/2]
template<typename _Tp > std::vector<_Tp> std::__detail::__eulerian_1_recur (unsigned int __n)
Return a vector Eulerian numbers of the first kind by recursion. The recursion is
Definition at line 219 of file sf_euler.tcc.
__eulerian_2() [1/2]
template<typename _Tp > _Tp std::__detail::__eulerian_2 (unsigned int __n, unsigned int __m) inline
Return the Eulerian number of the second kind. The Eulerian numbers of the second kind are defined by recursion:
Definition at line 309 of file sf_euler.tcc.
__eulerian_2() [2/2]
template<typename _Tp > std::vector<_Tp> std::__detail::__eulerian_2 (unsigned int __n) inline
Return a vector of Eulerian numbers of the second kind.
Definition at line 363 of file sf_euler.tcc.
__eulerian_2_recur() [1/2]
template<typename _Tp > _Tp std::__detail::__eulerian_2_recur (unsigned int __n, unsigned int __m)
Return the Eulerian number of the second kind by recursion:
Definition at line 269 of file sf_euler.tcc.
__eulerian_2_recur() [2/2]
template<typename _Tp > std::vector<_Tp> std::__detail::__eulerian_2_recur (unsigned int __n)
Return a vector of Eulerian numbers of the second kind.
Definition at line 325 of file sf_euler.tcc.
__exp2()
template<typename _Tp > _Tp std::__detail::__exp2 (_Tp __x)
Make exp2 available to complex and real types.
Definition at line 64 of file sf_zeta.tcc.
Referenced by __riemann_zeta().
__expint() [1/2]
template<typename _Tp > _Tp std::__detail::__expint (unsigned int __n, _Tp __x)
Return the exponential integral .
The exponential integral is given by
Parameters
__n The order of the exponential integral function.
__x The argument of the exponential integral function.
Returns
The exponential integral.
Todo:
Study arbitrary switch to large-n .
Todo:
Find a good asymptotic switch point in .
Definition at line 476 of file sf_expint.tcc.
References __expint_E1(), __expint_En_asymp(), __expint_En_cont_frac(), __expint_En_large_n(), and __expint_En_series().
Referenced by __logint().
__expint() [2/2]
template<typename _Tp > _Tp std::__detail::__expint (_Tp __x)
Return the exponential integral .
The exponential integral is given by
Parameters
__x The argument of the exponential integral function.
Returns
The exponential integral.
Definition at line 517 of file sf_expint.tcc.
References __expint_Ei().
__expint_E1()
template<typename _Tp > _Tp std::__detail::__expint_E1 (_Tp __x)
Return the exponential integral .
The exponential integral is given by
Parameters
__x The argument of the exponential integral function.
Returns
The exponential integral.
Todo:
Find a good asymptotic switch point in .
Todo:
Find a good asymptotic switch point in .
Definition at line 381 of file sf_expint.tcc.
References __expint_E1_asymp(), __expint_E1_series(), __expint_Ei(), and __expint_En_cont_frac().
Referenced by __coshint(), __expint(), __expint_Ei(), __expint_En_recursion(), and __sinhint().
__expint_E1_asymp()
template<typename _Tp > _Tp std::__detail::__expint_E1_asymp (_Tp __x)
Return the exponential integral by asymptotic expansion.
The exponential integral is given by
Parameters
__x The argument of the exponential integral function.
Returns
The exponential integral.
Definition at line 114 of file sf_expint.tcc.
Referenced by __expint_E1().
__expint_E1_series()
template<typename _Tp > _Tp std::__detail::__expint_E1_series (_Tp __x)
Return the exponential integral by series summation. This should be good for .
The exponential integral is given by
Parameters
__x The argument of the exponential integral function.
Returns
The exponential integral.
Definition at line 76 of file sf_expint.tcc.
Referenced by __expint_E1().
__expint_Ei()
template<typename _Tp > _Tp std::__detail::__expint_Ei (_Tp __x)
Return the exponential integral .
The exponential integral is given by
Parameters
__x The argument of the exponential integral function.
Returns
The exponential integral.
Definition at line 356 of file sf_expint.tcc.
References __expint_E1(), __expint_Ei_asymp(), and __expint_Ei_series().
Referenced by __coshint(), __expint(), __expint_E1(), and __sinhint().
__expint_Ei_asymp()
template<typename _Tp > _Tp std::__detail::__expint_Ei_asymp (_Tp __x)
Return the exponential integral by asymptotic expansion.
The exponential integral is given by
Parameters
__x The argument of the exponential integral function.
Returns
The exponential integral.
Definition at line 322 of file sf_expint.tcc.
Referenced by __expint_Ei().
__expint_Ei_series()
template<typename _Tp > _Tp std::__detail::__expint_Ei_series (_Tp __x)
Return the exponential integral by series summation.
The exponential integral is given by
Parameters
__x The argument of the exponential integral function.
Returns
The exponential integral.
Definition at line 289 of file sf_expint.tcc.
Referenced by __expint_Ei().
__expint_En_asymp()
template<typename _Tp > _Tp std::__detail::__expint_En_asymp (unsigned int __n, _Tp __x)
Return the exponential integral for large argument.
The exponential integral is given by
Parameters
__n The order of the exponential integral function.
__x The argument of the exponential integral function.
Returns
The exponential integral.
Definition at line 410 of file sf_expint.tcc.
Referenced by __expint().
__expint_En_cont_frac()
template<typename _Tp > _Tp std::__detail::__expint_En_cont_frac (unsigned int __n, _Tp __x)
Return the exponential integral by continued fractions.
The exponential integral is given by
Parameters
__n The order of the exponential integral function.
__x The argument of the exponential integral function.
Returns
The exponential integral.
Definition at line 198 of file sf_expint.tcc.
Referenced by __expint(), and __expint_E1().
__expint_En_large_n()
template<typename _Tp > _Tp std::__detail::__expint_En_large_n (unsigned int __n, _Tp __x)
Return the exponential integral for large order.
The exponential integral is given by
Parameters
__n The order of the exponential integral function.
__x The argument of the exponential integral function.
Returns
The exponential integral.
Definition at line 442 of file sf_expint.tcc.
Referenced by __expint().
__expint_En_recursion()
template<typename _Tp > _Tp std::__detail::__expint_En_recursion (unsigned int __n, _Tp __x)
Return the exponential integral by recursion. Use upward recursion for and downward recursion (Miller's algorithm) otherwise.
The exponential integral is given by
Parameters
__n The order of the exponential integral function.
__x The argument of the exponential integral function.
Returns
The exponential integral.
Todo:
Find a principled starting number for the downward recursion.
Definition at line 244 of file sf_expint.tcc.
References __expint_E1().
__expint_En_series()
template<typename _Tp > _Tp std::__detail::__expint_En_series (unsigned int __n, _Tp __x)
Return the exponential integral by series summation.
The exponential integral is given by
Parameters
__n The order of the exponential integral function.
__x The argument of the exponential integral function.
Returns
The exponential integral.
Definition at line 150 of file sf_expint.tcc.
Referenced by __expint().
__exponential_p()
template<typename _Tp > _Tp std::__detail::__exponential_p (_Tp __lambda, _Tp __x)
Return the exponential cumulative probability density function.
The formula for the exponential cumulative probability density function is
Definition at line 328 of file sf_distributions.tcc.
__exponential_pdf()
template<typename _Tp > _Tp std::__detail::__exponential_pdf (_Tp __lambda, _Tp __x)
Return the exponential probability density function.
The formula for the exponential probability density function is
Definition at line 308 of file sf_distributions.tcc.
__exponential_q()
template<typename _Tp > _Tp std::__detail::__exponential_q (_Tp __lambda, _Tp __x)
Return the complement of the exponential cumulative probability density function.
The formula for the complement of the exponential cumulative probability density function is
Definition at line 350 of file sf_distributions.tcc.
__factorial()
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__factorial (unsigned int __n)
Return the factorial of the integer n.
The factorial is:
Definition at line 1617 of file sf_gamma.tcc.
References std::__detail::_Factorial_table< _Tp >::__n, and _S_factorial_table.
__falling_factorial() [1/2]
template<typename _Tp > _Tp std::__detail::__falling_factorial (_Tp __a, int __n)
Return the logarithm of the falling factorial function or the lower Pochhammer symbol for real argument and integral order . The falling factorial function is defined by
In particular, .
Definition at line 2943 of file sf_gamma.tcc.
References __gnu_cxx::__fp_is_integer(), __log_gamma(), __log_gamma_sign(), and std::__detail::_Factorial_table< _Tp >::__n.
Referenced by __falling_factorial(), and __log_falling_factorial().
__falling_factorial() [2/2]
template<typename _Tp > _Tp std::__detail::__falling_factorial (_Tp __a, _Tp __nu)
Return the logarithm of the falling factorial function or the lower Pochhammer symbol for real argument and order . The falling factorial function is defined by
.
Definition at line 2998 of file sf_gamma.tcc.
References __falling_factorial(), __gnu_cxx::__fp_is_integer(), __log_gamma(), and __log_gamma_sign().
__fermi_dirac()
template<typename _Sp , typename _Tp > _Tp std::__detail::__fermi_dirac (_Sp __s, _Tp __x)
Return the Fermi-Dirac integral of integer or real order s and real argument x.
See also
https://en.wikipedia.org/wiki/Clausen_function
http://dlmf.nist.gov/25.12.16
Parameters
__s The order s > -1.
__x The real argument.
Returns
The real Fermi-Dirac integral F_s(x),
Definition at line 1461 of file sf_polylog.tcc.
References __polylog_exp().
__fisher_f_p()
template<typename _Tp > _Tp std::__detail::__fisher_f_p (_Tp __F, unsigned int __nu1, unsigned int __nu2)
Return the F-distribution propability function. This returns the probability that the observed chi-square for a correct model exceeds the value .
The f-distribution propability function is related to the incomplete beta function:
Parameters
__nu1 The number of degrees of freedom of sample 1
__nu2 The number of degrees of freedom of sample 2
__F The F statistic
Definition at line 523 of file sf_distributions.tcc.
References __beta_inc().
__fisher_f_pdf()
template<typename _Tp > _Tp std::__detail::__fisher_f_pdf (_Tp __F, unsigned int __nu1, unsigned int __nu2)
Return the F-distribution propability function. This returns the probability that the observed chi-square for a correct model exceeds the value .
The f-distribution propability function is related to the incomplete beta function:
Parameters
__nu1 The number of degrees of freedom of sample 1
__nu2 The number of degrees of freedom of sample 2
__F The F statistic
Definition at line 493 of file sf_distributions.tcc.
References __beta().
__fisher_f_q()
template<typename _Tp > _Tp std::__detail::__fisher_f_q (_Tp __F, unsigned int __nu1, unsigned int __nu2)
Return the F-distribution propability function. This returns the probability that the observed chi-square for a correct model exceeds the value .
The f-distribution propability function is related to the incomplete beta function:
Parameters
__F
__nu1
__nu2
Definition at line 552 of file sf_distributions.tcc.
References __beta_inc().
__fock_airy()
template<typename _Tp > __gnu_cxx::__fock_airy_t<_Tp, std::complex<_Tp> > std::__detail::__fock_airy (_Tp __x)
Compute the Fock-type Airy functions and and their first derivatives and respectively.
.
Parameters
__x The argument of the Airy functions.
Returns
A struct containing the Fock-type Airy functions of the first and second kinds and their derivatives.
Definition at line 560 of file sf_mod_bessel.tcc.
References __airy().
__fresnel()
template<typename _Tp > std::complex<_Tp> std::__detail::__fresnel (const _Tp __x)
Return the Fresnel cosine and sine integrals as a complex number $f[ C(x) + iS(x) $f].
The Fresnel cosine integral is defined by:
The Fresnel sine integral is defined by:
Parameters
__x The argument
Definition at line 170 of file sf_fresnel.tcc.
References __fresnel_cont_frac(), and __fresnel_series().
__fresnel_cont_frac()
template<typename _Tp > void std::__detail::__fresnel_cont_frac (const _Tp __ax, _Tp & _Cf, _Tp & _Sf)
This function computes the Fresnel cosine and sine integrals by continued fractions for positive argument.
Definition at line 109 of file sf_fresnel.tcc.
Referenced by __fresnel().
__fresnel_series()
template<typename _Tp > void std::__detail::__fresnel_series (const _Tp __ax, _Tp & _Cf, _Tp & _Sf)
This function returns the Fresnel cosine and sine integrals as a pair by series expansion for positive argument.
Definition at line 51 of file sf_fresnel.tcc.
Referenced by __fresnel().
__gamma() [1/2]
template<typename _Tp > _Tp std::__detail::__gamma (_Tp __a)
Return the gamma function . The gamma function is defined by:
.
Parameters
__a The argument of the gamma function.
Returns
The gamma function.
Definition at line 2641 of file sf_gamma.tcc.
References __gnu_cxx::__fp_is_integer(), __gamma_reciprocal_series(), __log_gamma(), __log_gamma_sign(), std::__detail::_Factorial_table< _Tp >::__n, and _S_factorial_table.
Referenced by __beta_gamma(), __binomial(), __dirichlet_eta(), __gamma_p(), __gamma_pdf(), __gamma_q(), __gamma_reciprocal(), __gamma_reciprocal_series(), __hurwitz_zeta_polylog(), __polylog_exp_pos(), __riemann_zeta(), __riemann_zeta_glob(), __riemann_zeta_m_1(), __riemann_zeta_sum(), __student_t_pdf(), and std::__detail::_Airy_series< _Tp >::_S_Scorer2().
__gamma() [2/2]
template<typename _Tp > std::pair<_Tp, _Tp> std::__detail::__gamma (_Tp __a, _Tp __x)
Return the incomplete gamma functions.
Definition at line 2768 of file sf_gamma.tcc.
References __gnu_cxx::__fp_is_integer(), __gamma_cont_frac(), and __gamma_series().
__gamma_cont_frac()
template<typename _Tp > std::pair<_Tp, _Tp> std::__detail::__gamma_cont_frac (_Tp __a, _Tp __x)
Return the incomplete gamma function by continued fraction.
Definition at line 2723 of file sf_gamma.tcc.
References __log_gamma(), __log_gamma_sign(), and std::__detail::_Factorial_table< _Tp >::__n.
Referenced by __gamma(), __gamma_p(), __gamma_q(), __tgamma(), and __tgamma_lower().
__gamma_p() [1/2]
template<typename _Tp > _Tp std::__detail::__gamma_p (_Tp __alpha, _Tp __beta, _Tp __x)
Return the gamma cumulative propability distribution function.
The formula for the gamma probability density function is:
Definition at line 141 of file sf_distributions.tcc.
References __gamma(), and __tgamma_lower().
Referenced by __chi_squared_pdf().
__gamma_p() [2/2]
template<typename _Tp > _Tp std::__detail::__gamma_p (_Tp __a, _Tp __x)
Return the regularized lower incomplete gamma function. The regularized lower incomplete gamma function is defined by
where is the gamma function and
is the lower incomplete gamma function.
Definition at line 2807 of file sf_gamma.tcc.
References __gnu_cxx::__fp_is_integer(), __gamma_cont_frac(), and __gamma_series().
__gamma_pdf()
template<typename _Tp > _Tp std::__detail::__gamma_pdf (_Tp __alpha, _Tp __beta, _Tp __x)
Return the gamma propability distribution function.
The formula for the gamma probability density function is:
Definition at line 121 of file sf_distributions.tcc.
References __gamma().
__gamma_q() [1/2]
template<typename _Tp > _Tp std::__detail::__gamma_q (_Tp __alpha, _Tp __beta, _Tp __x)
Return the gamma complementary cumulative propability distribution function.
The formula for the gamma probability density function is:
Definition at line 162 of file sf_distributions.tcc.
References __gamma(), and __tgamma().
Referenced by __chi_squared_pdfc().
__gamma_q() [2/2]
template<typename _Tp > _Tp std::__detail::__gamma_q (_Tp __a, _Tp __x)
Return the regularized upper incomplete gamma function. The regularized upper incomplete gamma function is defined by
where is the gamma function and
is the upper incomplete gamma function.
Definition at line 2841 of file sf_gamma.tcc.
References __gnu_cxx::__fp_is_integer(), __gamma_cont_frac(), and __gamma_series().
__gamma_reciprocal()
template<typename _Tp > _Tp std::__detail::__gamma_reciprocal (_Tp __a)
Return the reciprocal of the Gamma function:
Parameters
__a The argument of the reciprocal of the gamma function.
Returns
The reciprocal of the gamma function.
Definition at line 2271 of file sf_gamma.tcc.
References std::__detail::_Factorial_table< _Tp >::__factorial, __gnu_cxx::__fp_is_integer(), __gamma(), __gamma_reciprocal_series(), std::__detail::_Factorial_table< _Tp >::__n, __sin_pi(), and _S_factorial_table.
Referenced by __polylog_exp_asymp().
__gamma_reciprocal_series()
template<typename _Tp > _Tp std::__detail::__gamma_reciprocal_series (_Tp __a)
Return the reciprocal of the Gamma function by series. The reciprocal of the Gamma function is given by
where the coefficients are defined by recursion:
where
Parameters
__a The argument of the reciprocal of the gamma function.
Returns
The reciprocal of the gamma function.
Definition at line 2203 of file sf_gamma.tcc.
References __gamma().
Referenced by __gamma(), __gamma_reciprocal(), and __gamma_temme().
__gamma_series()
template<typename _Tp > std::pair<_Tp, _Tp> std::__detail::__gamma_series (_Tp __a, _Tp __x)
Return the incomplete gamma function by series summation.
.
Definition at line 2678 of file sf_gamma.tcc.
References __gnu_cxx::__fp_is_integer(), __log_gamma(), __log_gamma_sign(), and std::__detail::_Factorial_table< _Tp >::__n.
Referenced by __gamma(), __gamma_p(), __gamma_q(), __tgamma(), and __tgamma_lower().
__gamma_temme()
template<typename _Tp > __gnu_cxx::__gamma_temme_t<_Tp> std::__detail::__gamma_temme (_Tp __mu)
Compute the gamma functions required by the Temme series expansions of and .
and
where is and . is the nearest integer to . The values of and are returned as well.
The accuracy requirements on this are exquisite.
Parameters
__mu The input parameter of the gamma functions.
Returns
An output structure containing four gamma functions.
Definition at line 188 of file sf_bessel.tcc.
References __gamma_reciprocal_series().
Referenced by __cyl_bessel_ik_steed(), and __cyl_bessel_jn_steed().
__gauss()
template<typename _Tp > _Tp std::__detail::__gauss (_Tp __x)
The CDF of the normal distribution. i.e. the integrated lower tail of the normal PDF.
Definition at line 70 of file sf_owens_t.tcc.
__gegenbauer_recur()
template<typename _Tp > __gnu_cxx::__gegenbauer_t<_Tp> std::__detail::__gegenbauer_recur (unsigned int __n, _Tp __lambda, _Tp __x)
Return the Gegenbauer polynomial of degree n and real order and argument x.
The Gegenbauer polynomials are generated by a three-term recursion relation:
and , . This works for
Template Parameters
_Tp The real type of the argument and order
Parameters
__n The non-negative integral degree
__lambda The order of the Gegenbauer polynomial
__x The real argument
Definition at line 65 of file sf_gegenbauer.tcc.
__gegenbauer_zeros()
template<typename _Tp > std::vector<__gnu_cxx::__quadrature_point_t<_Tp> > std::__detail::__gegenbauer_zeros (unsigned int __n, _Tp __lambda)
Return a vector containing the zeros of the Gegenbauer or ultraspherical polynomial . This works for
Template Parameters
_Tp The real type of the order
Parameters
[in] __n The degree of the Gegenbauer polynomial
[in] __lambda The order of the Gegenbauer polynomial
Definition at line 104 of file sf_gegenbauer.tcc.
References __gnu_cxx::lgamma().
__hankel()
template<typename _Tp > __gnu_cxx::__cyl_hankel_t<std::complex<_Tp>, std::complex<_Tp>, std::complex<_Tp> > std::__detail::__hankel (std::complex< _Tp > __nu, std::complex< _Tp > __z)
Parameters
[in] __nu The order for which the Hankel functions are evaluated.
[in] __z The argument at which the Hankel functions are evaluated.
Returns
A struct containing the cylindrical Hankel functions of the first and second kinds and their derivatives.
Definition at line 1080 of file sf_hankel.tcc.
References __debye_region(), __hankel_debye(), and __hankel_uniform().
Referenced by __cyl_bessel(), __cyl_hankel_1(), __cyl_hankel_2(), __cyl_neumann(), and __sph_hankel().
__hankel_debye()
template<typename _Tp > __gnu_cxx::__cyl_hankel_t<std::complex<_Tp>, std::complex<_Tp>, std::complex<_Tp> > std::__detail::__hankel_debye (std::complex< _Tp > __nu, std::complex< _Tp > __z, std::complex< _Tp > __alpha, int __indexr, char & __aorb, int & __morn)
Parameters
[in] __nu The order for which the Hankel functions are evaluated.
[in] __z The argument at which the Hankel functions are evaluated.
[in] __alpha
[in] __indexr
[out] __aorb
[out] __morn
Returns
A struct containing the cylindrical Hankel functions of the first and second kinds and their derivatives.
Definition at line 913 of file sf_hankel.tcc.
References __sin_pi().
Referenced by __hankel().
__hankel_params()
template<typename _Tp > void std::__detail::__hankel_params (std::complex< _Tp > __nu, std::complex< _Tp > __zhat, std::complex< _Tp > & __p, std::complex< _Tp > & __p2, std::complex< _Tp > & __nup2, std::complex< _Tp > & __num2, std::complex< _Tp > & __num1d3, std::complex< _Tp > & __num2d3, std::complex< _Tp > & __num4d3, std::complex< _Tp > & __zeta, std::complex< _Tp > & __zetaphf, std::complex< _Tp > & __zetamhf, std::complex< _Tp > & __zetam3hf, std::complex< _Tp > & __zetrat)
Compute parameters depending on z and nu that appear in the uniform asymptotic expansions of the Hankel functions and their derivatives, except the arguments to the Airy functions.
Definition at line 108 of file sf_hankel.tcc.
Referenced by __hankel_uniform_outer().
__hankel_uniform()
template<typename _Tp > __gnu_cxx::__cyl_hankel_t<std::complex<_Tp>, std::complex<_Tp>, std::complex<_Tp> > std::__detail::__hankel_uniform (std::complex< _Tp > __nu, std::complex< _Tp > __z)
This routine computes the uniform asymptotic approximations of the Hankel functions and their derivatives including a patch for the case when the order equals or nearly equals the argument. At such points, Olver's expressions have zero denominators (and numerators) resulting in numerical problems. This routine averages results from four surrounding points in the complex plane to obtain the result in such cases.
Parameters
[in] __nu The order for which the Hankel functions are evaluated.
[in] __z The argument at which the Hankel functions are evaluated.
Returns
A struct containing the cylindrical Hankel functions of the first and second kinds and their derivatives.
Definition at line 860 of file sf_hankel.tcc.
References __hankel_uniform_olver().
Referenced by __hankel().
__hankel_uniform_olver()
template<typename _Tp > __gnu_cxx::__cyl_hankel_t<std::complex<_Tp>, std::complex<_Tp>, std::complex<_Tp> > std::__detail::__hankel_uniform_olver (std::complex< _Tp > __nu, std::complex< _Tp > __z)
Compute approximate values for the Hankel functions of the first and second kinds using Olver's uniform asymptotic expansion to of order nu along with their derivatives.
Parameters
[in] __nu The order for which the Hankel functions are evaluated.
[in] __z The argument at which the Hankel functions are evaluated.
Returns
A struct containing the cylindrical Hankel functions of the first and second kinds and their derivatives.
Definition at line 777 of file sf_hankel.tcc.
References __hankel_uniform_outer(), and __hankel_uniform_sum().
Referenced by __hankel_uniform().
__hankel_uniform_outer()
template<typename _Tp > void std::__detail::__hankel_uniform_outer (std::complex< _Tp > __nu, std::complex< _Tp > __z, _Tp __eps, std::complex< _Tp > & __zhat, std::complex< _Tp > & __1dnsq, std::complex< _Tp > & __num1d3, std::complex< _Tp > & __num2d3, std::complex< _Tp > & __p, std::complex< _Tp > & __p2, std::complex< _Tp > & __etm3h, std::complex< _Tp > & __etrat, std::complex< _Tp > & _Aip, std::complex< _Tp > & __o4dp, std::complex< _Tp > & _Aim, std::complex< _Tp > & __o4dm, std::complex< _Tp > & __od2p, std::complex< _Tp > & __od0dp, std::complex< _Tp > & __od2m, std::complex< _Tp > & __od0dm)
Compute outer factors and associated functions of z and nu appearing in Olver's uniform asymptotic expansions of the Hankel functions of the first and second kinds and their derivatives. The various functions of z and nu returned by hankel_uniform_outer are available for use in computing further terms in the expansions.
Definition at line 247 of file sf_hankel.tcc.
References __airy_arg(), and __hankel_params().
Referenced by __hankel_uniform_olver().
__hankel_uniform_sum()
template<typename _Tp > void std::__detail::__hankel_uniform_sum (std::complex< _Tp > __p, std::complex< _Tp > __p2, std::complex< _Tp > __num2, std::complex< _Tp > __zetam3hf, std::complex< _Tp > _Aip, std::complex< _Tp > __o4dp, std::complex< _Tp > _Aim, std::complex< _Tp > __o4dm, std::complex< _Tp > __od2p, std::complex< _Tp > __od0dp, std::complex< _Tp > __od2m, std::complex< _Tp > __od0dm, _Tp __eps, std::complex< _Tp > & _H1sum, std::complex< _Tp > & _H1psum, std::complex< _Tp > & _H2sum, std::complex< _Tp > & _H2psum)
Compute the sums in appropriate linear combinations appearing in Olver's uniform asymptotic expansions for the Hankel functions of the first and second kinds and their derivatives, using up to nterms (less than 5) to achieve relative error eps.
Parameters
[in] __p
[in] __p2
[in] __num2
[in] __zetam3hf
[in] _Aip The Airy function value .
[in] __o4dp
[in] _Aim The Airy function value .
[in] __o4dm
[in] __od2p
[in] __od0dp
[in] __od2m
[in] __od0dm
[in] __eps The error tolerance
[out] _H1sum The Hankel function of the first kind.
[out] _H1psum The derivative of the Hankel function of the first kind.
[out] _H2sum The Hankel function of the second kind.
[out] _H2psum The derivative of the Hankel function of the second kind.
Definition at line 324 of file sf_hankel.tcc.
Referenced by __hankel_uniform_olver().
__harmonic_number()
template<typename _Tp > _Tp std::__detail::__harmonic_number (unsigned int __n)
Definition at line 3288 of file sf_gamma.tcc.
References std::__detail::_Factorial_table< _Tp >::__n, _S_harmonic_denom, _S_harmonic_numer, and _S_num_harmonic_numer.
__hermite()
template<typename _Tp > _Tp std::__detail::__hermite (unsigned int __n, _Tp __x)
This routine returns the Hermite polynomial of order n: .
The Hermite polynomial is defined by:
An explicit series formula is:
The Hermite polynomial obeys a reflection formula:
Parameters
__n The order of the Hermite polynomial.
__x The argument of the Hermite polynomial.
Returns
The value of the Hermite polynomial of order n and argument x.
Definition at line 212 of file sf_hermite.tcc.
References __hermite_asymp(), and __hermite_recur().
__hermite_asymp()
template<typename _Tp > _Tp std::__detail::__hermite_asymp (unsigned int __n, _Tp __x)
This routine returns the Hermite polynomial of large order n: . We assume here that x >= 0.
The Hermite polynomial is defined by:
See also
"Asymptotic analysis of the Hermite polynomials from their differential-difference equation", Diego Dominici, arXiv:math/0601078v1 [math.CA] 4 Jan 2006
Parameters
__n The order of the Hermite polynomial.
__x The argument of the Hermite polynomial.
Returns
The value of the Hermite polynomial of order n and argument x.
Definition at line 143 of file sf_hermite.tcc.
References __airy().
Referenced by __hermite().
__hermite_recur()
template<typename _Tp > __gnu_cxx::__hermite_t<_Tp> std::__detail::__hermite_recur (unsigned int __n, _Tp __x)
This routine returns the Hermite polynomial of order n: by recursion on n.
The Hermite polynomial is defined by:
The Hermite polynomial has first and second derivatives:
and
The Physicists Hermite polynomials have highest-order coefficient and are orthogonal with respect to the weight function
Parameters
__n The order of the Hermite polynomial.
__x The argument of the Hermite polynomial.
Returns
The value of the Hermite polynomial of order n and argument x.
Todo:
Find the sign of Hermite blowup values.
Definition at line 86 of file sf_hermite.tcc.
Referenced by __hermite().
__hermite_zeros()
template<typename _Tp > std::vector<__gnu_cxx::__quadrature_point_t<_Tp> > std::__detail::__hermite_zeros (unsigned int __n, _Tp __proto = _Tp{})
Build a vector of the Gauss-Hermite integration rule abscissae and weights.
Definition at line 289 of file sf_hermite.tcc.
__heuman_lambda()
template<typename _Tp > _Tp std::__detail::__heuman_lambda (_Tp __k, _Tp __phi)
Return the Heuman lambda function.
Definition at line 1008 of file sf_ellint.tcc.
References __comp_ellint_1(), __ellint_1(), __ellint_rf(), __ellint_rj(), and __jacobi_zeta().
__hurwitz_zeta()
template<typename _Tp > _Tp std::__detail::__hurwitz_zeta (_Tp __s, _Tp __a)
Return the Hurwitz zeta function for all s != 1 and a > -1.
The Hurwitz zeta function is defined by:
The Riemann zeta function is a special case:
Parameters
__s The order
__a The scale parameter
Definition at line 871 of file sf_zeta.tcc.
References __hurwitz_zeta_euler_maclaurin(), and __riemann_zeta().
Referenced by __digamma(), and __polygamma().
__hurwitz_zeta_euler_maclaurin()
template<typename _Tp > _Tp std::__detail::__hurwitz_zeta_euler_maclaurin (_Tp __s, _Tp __a)
Return the Hurwitz zeta function for all s != 1 and a > -1.
See also
An efficient algorithm for accelerating the convergence of oscillatory series, useful for computing the polylogarithm and Hurwitz zeta functions, Linas Vep"0160tas
Parameters
__s The order
__a The scale parameter
Definition at line 823 of file sf_zeta.tcc.
References _S_Euler_Maclaurin_zeta.
Referenced by __hurwitz_zeta().
__hurwitz_zeta_polylog()
template<typename _Tp > std::complex<_Tp> std::__detail::__hurwitz_zeta_polylog (_Tp __s, std::complex< _Tp > __a)
Return the Hurwitz Zeta function for real s and complex a. This uses Jonquiere's identity:
Parameters
__s The real argument
__a The complex parameter
Todo:
This __hurwitz_zeta_polylog prefactor is prone to overflow. positive integer orders s?
Definition at line 1127 of file sf_polylog.tcc.
References __gamma(), and __polylog_exp().
__hydrogen()
template<typename _Tp > std::complex<_Tp> std::__detail::__hydrogen (unsigned int __n, unsigned int __l, unsigned int __m, _Tp __Z, _Tp __r, _Tp __theta, _Tp __phi)
Return the bound-state Coulomb wave-function.
Definition at line 248 of file sf_coulomb.tcc.
References __assoc_laguerre(), __log_gamma(), and __sph_legendre().
__hyperg()
template<typename _Tp > _Tp std::__detail::__hyperg (_Tp __a, _Tp __b, _Tp __c, _Tp __x)
Return the hypergeometric function .
The hypergeometric function is defined by
Parameters
__a The first numerator parameter.
__b The second numerator parameter.
__c The denominator parameter.
__x The argument of the confluent hypergeometric function.
Returns
The confluent hypergeometric function.
Definition at line 927 of file sf_hyperg.tcc.
References __gnu_cxx::__fp_is_integer(), __hyperg_luke(), __hyperg_reflect(), __hyperg_series(), __log_gamma(), and __log_gamma_sign().
Referenced by __legendre_q_series().
__hyperg_luke()
template<typename _Tp > _Tp std::__detail::__hyperg_luke (_Tp __a, _Tp __b, _Tp __c, _Tp __xin)
Return the hypergeometric function by an iterative procedure described in Luke, Algorithms for the Computation of Mathematical Functions.
Definition at line 501 of file sf_hyperg.tcc.
Referenced by __hyperg().
__hyperg_recur()
template<typename _Tp > _Tp std::__detail::__hyperg_recur (int __m, _Tp __b, _Tp __c, _Tp __x)
Return the hypergeometric polynomial by Holm recursion.
The hypergeometric function is defined by
Parameters
__m The first numerator parameter.
__b The second numerator parameter.
__c The denominator parameter.
__x The argument of the confluent hypergeometric function.
Returns
The confluent hypergeometric function.
: go recur!
Definition at line 478 of file sf_hyperg.tcc.
__hyperg_reflect()
template<typename _Tp > _Tp std::__detail::__hyperg_reflect (_Tp __a, _Tp __b, _Tp __c, _Tp __x)
Return the hypergeometric function by the reflection formulae in Abramowitz & Stegun formula 15.3.6 for d = c - a - b not integral and formula 15.3.11 for d = c - a - b integral. This assumes a, b, c != negative integer.
The hypergeometric function is defined by
The reflection formula for nonintegral is:
The reflection formula for integral is:
Definition at line 637 of file sf_hyperg.tcc.
References __digamma(), __gnu_cxx::__fp_is_integer(), __hyperg_series(), __log_gamma(), and __log_gamma_sign().
Referenced by __hyperg().
__hyperg_series()
template<typename _Tp > _Tp std::__detail::__hyperg_series (_Tp __a, _Tp __b, _Tp __c, _Tp __x)
Return the hypergeometric function by series expansion.
The hypergeometric function is defined by
This works and it's pretty fast.
Parameters
__a The first numerator parameter.
__b The second numerator parameter.
__c The denominator parameter.
__x The argument of the confluent hypergeometric function.
Returns
The confluent hypergeometric function.
Definition at line 430 of file sf_hyperg.tcc.
Referenced by __hyperg(), and __hyperg_reflect().
__ibeta_cont_frac()
template<typename _Tp > _Tp std::__detail::__ibeta_cont_frac (_Tp __a, _Tp __b, _Tp __x)
Return the regularized incomplete beta function, , of arguments a, b, and x.
Parameters
__a The first parameter
__b The second parameter
__x The argument
Definition at line 239 of file sf_beta.tcc.
Referenced by __beta_inc().
__jacobi_ellint()
template<typename _Tp > __gnu_cxx::__jacobi_ellint_t<_Tp> std::__detail::__jacobi_ellint (_Tp __k, _Tp __u)
Return a structure containing the three primary Jacobi elliptic functions: .
Parameters
__k The elliptic modulus .
__u The argument.
Returns
An object containing the three principal Jacobi elliptic functions, and the means to compute the remaining nine as well as the amplitude.
Definition at line 1649 of file sf_theta.tcc.
__jacobi_recur()
template<typename _Tp > __gnu_cxx::__jacobi_t<_Tp> std::__detail::__jacobi_recur (unsigned int __n, _Tp __alpha1, _Tp __beta1, _Tp __x)
Compute the Jacobi polynomial by recursion on n:
This works for
Template Parameters
_Tp The real type of the argument
Parameters
[in] __n The degree of the Jacobi polynomial
[in] __alpha1 The first order parameter of the Jacobi polynomial
[in] __beta1 The second order parameter of the Jacobi polynomial
[in] __x The argument
Definition at line 68 of file sf_jacobi.tcc.
Referenced by __radial_jacobi().
__jacobi_theta_1() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__jacobi_theta_1 (std::complex< _Tp > __q, std::complex< _Tp > __x)
Return the Jacobi function by summation of the series.
The Jacobi or elliptic theta function is defined by
Regarding the nome and the theta function as functions of the lattice parameter or the lattice parameter is transformed to maximize its imaginary part:
and
where the new lattice parameter is .
The argument is reduced with
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 980 of file sf_theta.tcc.
References __jacobi_theta_1_prod(), __jacobi_theta_1_sum(), __polar_pi(), std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__reduce(), std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__tau(), and std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_S_pi.
Referenced by __jacobi_theta_1().
__jacobi_theta_1() [2/2]
template<typename _Tp > _Tp std::__detail::__jacobi_theta_1 (_Tp __q, const _Tp __x)
Return the Jacobi function for real nome and argument.
The Jacobi or elliptic theta function is defined by
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1048 of file sf_theta.tcc.
References __jacobi_theta_1().
__jacobi_theta_1_prod()
template<typename _Tp > _Tp std::__detail::__jacobi_theta_1_prod (_Tp __q, _Tp __x)
Return the Jacobi function by accumulation of the product.
The Jacobi or elliptic theta-1 function is defined by
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 923 of file sf_theta.tcc.
Referenced by __jacobi_theta_1().
__jacobi_theta_1_sum()
template<typename _Tp > _Tp std::__detail::__jacobi_theta_1_sum (_Tp __q, _Tp __x)
Return the Jacobi function by summation of the series.
The Jacobi or elliptic theta-1 function is defined by
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 888 of file sf_theta.tcc.
Referenced by __jacobi_theta_1().
__jacobi_theta_2() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__jacobi_theta_2 (std::complex< _Tp > __q, std::complex< _Tp > __x)
Return the Jacobi function by summation of the series.
The Jacobi or elliptic theta function is defined by
Regarding the nome and the theta function as functions of the lattice parameter or the lattice parameter is transformed to maximize its imaginary part:
and
where the new lattice parameter is .
The argument is reduced with
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1176 of file sf_theta.tcc.
References __jacobi_theta_2_prod(), __jacobi_theta_2_sum(), __jacobi_theta_4_sum(), __polar_pi(), std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__reduce(), std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__tau(), std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_S_pi, and std::__detail::__jacobi_theta_0_t< _Tp1, _Tp3 >::th2.
Referenced by __jacobi_theta_2().
__jacobi_theta_2() [2/2]
template<typename _Tp > _Tp std::__detail::__jacobi_theta_2 (_Tp __q, const _Tp __x)
Return the Jacobi function for real nome and argument.
The Jacobi or elliptic theta function is defined by
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1249 of file sf_theta.tcc.
References __jacobi_theta_2().
__jacobi_theta_2_prod()
template<typename _Tp > _Tp std::__detail::__jacobi_theta_2_prod (_Tp __q, _Tp __x)
Return the Jacobi function by accumulation of the product.
The Jacobi or elliptic theta-2 function is defined by
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1109 of file sf_theta.tcc.
References __jacobi_theta_4_prod(), and __jacobi_theta_4_sum().
Referenced by __jacobi_theta_2().
__jacobi_theta_2_sum()
template<typename _Tp > _Tp std::__detail::__jacobi_theta_2_sum (_Tp __q, _Tp __x)
Return the Jacobi function by summation of the series.
The Jacobi or elliptic theta-2 function is defined by
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1077 of file sf_theta.tcc.
Referenced by __jacobi_theta_2(), and __jacobi_theta_4().
__jacobi_theta_3() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__jacobi_theta_3 (std::complex< _Tp > __q, std::complex< _Tp > __x)
Return the Jacobi function by summation of the series.
The Jacobi or elliptic theta function is defined by
Regarding the nome and the theta function as functions of the lattice parameter or the lattice parameter is transformed to maximize its imaginary part:
and
where the new lattice parameter is .
The argument is reduced with
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1365 of file sf_theta.tcc.
References __jacobi_theta_3_prod(), __jacobi_theta_3_sum(), std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__reduce(), std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__tau(), std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_S_pi, and std::__detail::__jacobi_theta_0_t< _Tp1, _Tp3 >::th3.
Referenced by __jacobi_theta_3().
__jacobi_theta_3() [2/2]
template<typename _Tp > _Tp std::__detail::__jacobi_theta_3 (_Tp __q, const _Tp __x)
Return the Jacobi function for real nome and argument.
The Jacobi or elliptic theta function is defined by
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1433 of file sf_theta.tcc.
References __jacobi_theta_3().
__jacobi_theta_3_prod()
template<typename _Tp > _Tp std::__detail::__jacobi_theta_3_prod (_Tp __q, _Tp __x)
Return the Jacobi function by accumulation of the product.
The Jacobi or elliptic theta-3 function is defined by
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1309 of file sf_theta.tcc.
Referenced by __jacobi_theta_3().
__jacobi_theta_3_sum()
template<typename _Tp > _Tp std::__detail::__jacobi_theta_3_sum (_Tp __q, _Tp __x)
Return the Jacobi function by summation of the series.
The Jacobi or elliptic theta-3 function is defined by
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1277 of file sf_theta.tcc.
Referenced by __jacobi_theta_3().
__jacobi_theta_4() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__jacobi_theta_4 (std::complex< _Tp > __q, std::complex< _Tp > __x)
Return the Jacobi function by summation of the series.
The Jacobi or elliptic theta-4 function is defined by
Regarding the nome and the theta function as functions of the lattice parameter or the lattice parameter is transformed to maximize its imaginary part:
and
where the new lattice parameter is .
The argument is reduced with
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1551 of file sf_theta.tcc.
References __jacobi_theta_2_sum(), __jacobi_theta_4_prod(), __jacobi_theta_4_sum(), std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__reduce(), std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__tau(), std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_S_pi, and std::__detail::__jacobi_theta_0_t< _Tp1, _Tp3 >::th4.
Referenced by __jacobi_theta_4().
__jacobi_theta_4() [2/2]
template<typename _Tp > _Tp std::__detail::__jacobi_theta_4 (_Tp __q, const _Tp __x)
Return the Jacobi function for real nome and argument.
The Jacobi or elliptic theta function is defined by
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1622 of file sf_theta.tcc.
References __jacobi_theta_4().
__jacobi_theta_4_prod()
template<typename _Tp > _Tp std::__detail::__jacobi_theta_4_prod (_Tp __q, _Tp __x)
Return the Jacobi function by accumulation of the product.
The Jacobi or elliptic theta-4 function is defined by
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1495 of file sf_theta.tcc.
Referenced by __jacobi_theta_2_prod(), and __jacobi_theta_4().
__jacobi_theta_4_sum()
template<typename _Tp > _Tp std::__detail::__jacobi_theta_4_sum (_Tp __q, _Tp __x)
Return the Jacobi function by summation of the series.
The Jacobi or elliptic theta function is defined by
Parameters
__q The elliptic nome, .
__x The argument.
Definition at line 1461 of file sf_theta.tcc.
Referenced by __jacobi_theta_2(), __jacobi_theta_2_prod(), and __jacobi_theta_4().
__jacobi_zeros()
template<typename _Tp > std::vector<__gnu_cxx::__quadrature_point_t<_Tp> > std::__detail::__jacobi_zeros (unsigned int __n, _Tp __alpha1, _Tp __beta1)
Return a vector containing the zeros of the Jacobi polynomial . Thias works for .
Template Parameters
_Tp The real type of the parameters
Parameters
[in] __n The degree of the Jacobi polynomial
[in] __alpha1 The first order parameter of the Jacobi polynomial
[in] __beta1 The second order parameter of the Jacobi polynomial
Definition at line 142 of file sf_jacobi.tcc.
References __gnu_cxx::lgamma().
Referenced by __radial_jacobi_zeros().
__jacobi_zeta()
template<typename _Tp > _Tp std::__detail::__jacobi_zeta (_Tp __k, _Tp __phi)
Return the Jacobi zeta function.
Definition at line 971 of file sf_ellint.tcc.
References __comp_ellint_1(), and __ellint_rj().
Referenced by __heuman_lambda().
__kolmogorov_p()
template<typename _Tp > _Tp std::__detail::__kolmogorov_p (_Tp __a, _Tp __b, _Tp __x)
Definition at line 723 of file sf_distributions.tcc.
__laguerre() [1/2]
template<typename _Tpa , typename _Tp > _Tp std::__detail::__laguerre (unsigned int __n, _Tpa __alpha1, _Tp __x)
This routine returns the associated Laguerre polynomial of degree n, order : .
The associated Laguerre function is defined by
where is the Pochhammer symbol and is the confluent hypergeometric function.
The associated Laguerre polynomial is defined for integral order by:
where the Laguerre polynomial is defined by:
Template Parameters
_Tpa The type of the order.
_Tp The type of the parameter.
Parameters
__n The degree of the Laguerre function.
__alpha1 The order of the Laguerre function.
__x The argument of the Laguerre function.
Returns
The value of the Laguerre function of degree n, order , and argument x.
Definition at line 316 of file sf_laguerre.tcc.
References __laguerre_hyperg(), __laguerre_large_n(), and __laguerre_recur().
__laguerre() [2/2]
template<typename _Tp > _Tp std::__detail::__laguerre (unsigned int __n, _Tp __x)
This routine returns the Laguerre polynomial of degree n: .
The Laguerre polynomial is defined by:
Parameters
__n The degree of the Laguerre polynomial.
__x The argument of the Laguerre polynomial.
Returns
The value of the Laguerre polynomial of order n and argument x.
Definition at line 387 of file sf_laguerre.tcc.
__laguerre_hyperg()
template<typename _Tpa , typename _Tp > _Tp std::__detail::__laguerre_hyperg (unsigned int __n, _Tpa __alpha1, _Tp __x)
Evaluate the polynomial based on the confluent hypergeometric function in a safe way, with no restriction on the arguments.
The associated Laguerre function is defined by
where is the Pochhammer symbol and is the confluent hypergeometric function.
This function assumes x != 0.
This is from the GNU Scientific Library.
Template Parameters
_Tpa The type of the order.
_Tp The type of the parameter.
Parameters
__n The degree of the Laguerre function.
__alpha1 The order of the Laguerre function.
__x The argument of the Laguerre function.
Returns
The value of the Laguerre function of degree n, order , and argument x.
Definition at line 131 of file sf_laguerre.tcc.
Referenced by __laguerre().
__laguerre_large_n()
template<typename _Tpa , typename _Tp > _Tp std::__detail::__laguerre_large_n (unsigned __n, _Tpa __alpha1, _Tp __x)
This routine returns the associated Laguerre polynomial of degree , order for large n. Abramowitz & Stegun, 13.5.21.
Template Parameters
_Tpa The type of the order.
_Tp The type of the parameter.
Parameters
__n The degree of the Laguerre function.
__alpha1 The order of the Laguerre function.
__x The argument of the Laguerre function.
Returns
The value of the Laguerre function of degree n, order , and argument x.
This is from the GNU Scientific Library.
Definition at line 75 of file sf_laguerre.tcc.
References __log_gamma(), and __sin_pi().
Referenced by __laguerre().
__laguerre_recur()
template<typename _Tpa , typename _Tp > __gnu_cxx::__laguerre_t<_Tpa, _Tp> std::__detail::__laguerre_recur (unsigned int __n, _Tpa __alpha1, _Tp __x)
This routine returns the associated Laguerre polynomial of degree n, order : by recursion.
The associated Laguerre function is defined by
where is the Pochhammer symbol and is the confluent hypergeometric function.
The associated Laguerre polynomial is defined for integral order by:
where the Laguerre polynomial is defined by:
Template Parameters
_Tpa The type of the order.
_Tp The type of the parameter.
Parameters
__n The degree of the Laguerre function.
__alpha1 The order of the Laguerre function.
__x The argument of the Laguerre function.
Returns
The value of the Laguerre function of order n, degree , and argument x.
Definition at line 189 of file sf_laguerre.tcc.
Referenced by __laguerre().
__laguerre_zeros()
template<typename _Tp > std::vector<__gnu_cxx::__quadrature_point_t<_Tp> > std::__detail::__laguerre_zeros (unsigned int __n, _Tp __alpha1)
Return an array of abscissae and weights for the Gauss-Laguerre rule.
Definition at line 225 of file sf_laguerre.tcc.
References __gnu_cxx::lgamma().
__lah() [1/2]
template<typename _Tp > _Tp std::__detail::__lah (unsigned int __n, unsigned int __k) inline
Return the Lah number. Lah numbers are defined by downward recurrence:
Definition at line 440 of file sf_stirling.tcc.
__lah() [2/2]
template<typename _Tp > std::vector<_Tp> std::__detail::__lah (unsigned int __n) inline
Return a vector of Lah numbers. Lah numbers are defined by downward recurrence:
Definition at line 478 of file sf_stirling.tcc.
__lah_recur() [1/2]
template<typename _Tp > _Tp std::__detail::__lah_recur (unsigned int __n, unsigned int __k)
Return the Lah number by downward recurrence:
Definition at line 416 of file sf_stirling.tcc.
__lah_recur() [2/2]
template<typename _Tp > std::vector<_Tp> std::__detail::__lah_recur (unsigned int __n)
Return a vector of Lah numbers defined by downward recurrence:
Definition at line 451 of file sf_stirling.tcc.
__lanczos_binet1p()
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__lanczos_binet1p (_Tp __z)
Return the Binet function by the Lanczos method. The Binet function is the log of the scaled Gamma function defined by
or
where is the gamma function.
Parameters
__z The argument of the log of the gamma function.
Returns
The logarithm of the gamma function.
Definition at line 2125 of file sf_gamma.tcc.
References std::__detail::_Factorial_table< _Tp >::__n.
Referenced by __lanczos_log_gamma1p().
__lanczos_log_gamma1p()
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__lanczos_log_gamma1p (_Tp __z)
Return the logarithm of the gamma function by the Lanczos method.
If the argument is real, the log of the absolute value of the Gamma function is returned. The sign to be applied to the exponential of this log Gamma can be recovered with a call to __log_gamma_sign.
For complex argument the fully complex log of the gamma function is returned.
Parameters
__z The argument of the log of the gamma function.
Returns
The logarithm of the gamma function.
Definition at line 2159 of file sf_gamma.tcc.
References __lanczos_binet1p(), and __sin_pi().
__legendre_p()
template<typename _Tp > __gnu_cxx::__legendre_p_t<_Tp> std::__detail::__legendre_p (unsigned int __l, _Tp __x)
Return the Legendre polynomial by upward recursion on degree .
The Legendre function of degree and argument , , is defined by:
This can be expressed as a series:
Parameters
__l The degree of the Legendre polynomial. .
__x The argument of the Legendre polynomial.
Definition at line 85 of file sf_legendre.tcc.
Referenced by __assoc_legendre_p(), and __sph_legendre().
__legendre_q()
template<typename _Tp > __gnu_cxx::__legendre_q_t<_Tp> std::__detail::__legendre_q (unsigned int __l, _Tp __x)
Return the Legendre function of the second kind by upward recursion on degree .
The Legendre function of the second kind of degree and argument , , is defined by:
Parameters
__l The degree of the Legendre function. .
__x The argument of the Legendre function. .
Definition at line 165 of file sf_legendre.tcc.
References __legendre_q_series().
__legendre_q_series()
template<typename _Tp > _Tp std::__detail::__legendre_q_series (unsigned int __l, _Tp __x)
Legendre q series.
Definition at line 133 of file sf_legendre.tcc.
References __hyperg().
Referenced by __legendre_q().
__legendre_zeros()
template<typename _Tp > std::vector<__gnu_cxx::__quadrature_point_t<_Tp> > std::__detail::__legendre_zeros (unsigned int __l, _Tp proto = _Tp{})
Build a list of zeros and weights for the Gauss-Legendre integration rule for the Legendre polynomial of degree l.
Definition at line 521 of file sf_legendre.tcc.
__log_binomial() [1/2]
template<typename _Tp > _Tp std::__detail::__log_binomial (unsigned int __n, unsigned int __k)
Return the logarithm of the binomial coefficient. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
Parameters
__n The first argument of the binomial coefficient.
__k The second argument of the binomial coefficient.
Returns
The logarithm of the binomial coefficient.
Definition at line 2436 of file sf_gamma.tcc.
References __log_gamma(), and std::__detail::_Factorial_table< _Tp >::__n.
Referenced by __binomial().
__log_binomial() [2/2]
template<typename _Tp > _Tp std::__detail::__log_binomial (_Tp __nu, unsigned int __k)
Return the logarithm of the binomial coefficient for non-integral degree. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
Parameters
__nu The first argument of the binomial coefficient.
__k The second argument of the binomial coefficient.
Returns
The logarithm of the binomial coefficient.
Definition at line 2473 of file sf_gamma.tcc.
References __log_gamma(), and std::__detail::_Factorial_table< _Tp >::__n.
__log_binomial_sign() [1/2]
template<typename _Tp > _Tp std::__detail::__log_binomial_sign (_Tp __nu, unsigned int __k)
Return the sign of the exponentiated logarithm of the binomial coefficient for non-integral degree. The binomial coefficient is given by:
The binomial coefficients are generated by:
.
Parameters
__nu The first argument of the binomial coefficient.
__k The second argument of the binomial coefficient.
Returns
The sign of the gamma function.
Definition at line 2504 of file sf_gamma.tcc.
References __log_gamma_sign(), and std::__detail::_Factorial_table< _Tp >::__n.
Referenced by __binomial().
__log_binomial_sign() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__log_binomial_sign (std::complex< _Tp > __nu, unsigned int __k)
Definition at line 2519 of file sf_gamma.tcc.
__log_double_factorial() [1/2]
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__log_double_factorial (_Tp __nu)
Extend double factorial to non-integer arguments. Arkken,
Definition at line 1657 of file sf_gamma.tcc.
References __cos_pi(), and __log_gamma().
Referenced by __double_factorial(), and __log_double_factorial().
__log_double_factorial() [2/2]
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__log_double_factorial (int __n)
Return the logarithm of the double factorial of the integer n.
The double factorial is defined for integral n by:
The double factorial is defined for odd negative integers in the obvious way:
for $f[ n = -2m - 1 $f].
Definition at line 1727 of file sf_gamma.tcc.
References __log_double_factorial(), std::__detail::_Factorial_table< _Tp >::__log_factorial, std::__detail::_Factorial_table< _Tp >::__n, _S_double_factorial_table, and _S_neg_double_factorial_table.
__log_factorial()
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__log_factorial (unsigned int __n)
Return the logarithm of the factorial of the integer n.
The factorial is:
Definition at line 1635 of file sf_gamma.tcc.
References __log_gamma(), std::__detail::_Factorial_table< _Tp >::__n, _S_double_factorial_table, and _S_factorial_table.
__log_falling_factorial()
template<typename _Tp > _Tp std::__detail::__log_falling_factorial (_Tp __a, _Tp __nu)
Return the logarithm of the falling factorial function or the lower Pochhammer symbol. The lower Pochammer symbol is defined by
In particular, . Thus this function returns
Many notations exist for this function:
,
, and others.
Definition at line 3052 of file sf_gamma.tcc.
References __falling_factorial(), __gnu_cxx::__fp_is_integer(), and __log_gamma().
__log_gamma() [1/2]
template<typename _Tp > _Tp std::__detail::__log_gamma (_Tp __a)
Return . This will return values even for . To recover the sign of for any argument use __log_gamma_sign.
Parameters
__a The argument of the log of the gamma function.
Returns
The logarithm of the gamma function.
Definition at line 2327 of file sf_gamma.tcc.
References __sin_pi(), and __spouge_log_gamma1p().
Referenced by __beta_inc(), __beta_lgamma(), __cyl_bessel_ij_series(), __falling_factorial(), __gamma(), __gamma_cont_frac(), __gamma_series(), __hydrogen(), __hyperg(), __hyperg_reflect(), __laguerre_large_n(), __log_binomial(), __log_double_factorial(), __log_factorial(), __log_falling_factorial(), __log_gamma(), __log_rising_factorial(), __polygamma(), __polylog_exp_neg(), __polylog_exp_pos(), __riemann_zeta(), __rising_factorial(), and __sph_legendre().
__log_gamma() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__log_gamma (std::complex< _Tp > __a)
Return for complex argument.
Parameters
__a The complex argument of the log of the gamma function.
Returns
The complex logarithm of the gamma function.
Definition at line 2362 of file sf_gamma.tcc.
References __gnu_cxx::__fp_is_integer(), std::__detail::_Factorial_table< _Tp >::__log_factorial, __log_gamma(), std::__detail::_Factorial_table< _Tp >::__n, __sin_pi(), __spouge_log_gamma1p(), and _S_factorial_table.
__log_gamma_bernoulli()
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__log_gamma_bernoulli (_Tp __x)
Return by asymptotic expansion with Bernoulli number coefficients. This is like Sterling's approximation.
Parameters
__x The argument of the log of the gamma function.
Returns
The logarithm of the gamma function.
Definition at line 1759 of file sf_gamma.tcc.
__log_gamma_sign() [1/2]
template<typename _Tp > _Tp std::__detail::__log_gamma_sign (_Tp __a)
Return the sign of . At nonpositive integers zero is returned indicating is undefined.
Parameters
__a The argument of the gamma function.
Returns
The sign of the gamma function.
Definition at line 2403 of file sf_gamma.tcc.
Referenced by __beta_inc(), __beta_lgamma(), __falling_factorial(), __gamma(), __gamma_cont_frac(), __gamma_series(), __hyperg(), __hyperg_reflect(), __log_binomial_sign(), and __rising_factorial().
__log_gamma_sign() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__log_gamma_sign (std::complex< _Tp > __a)
Definition at line 2415 of file sf_gamma.tcc.
__log_rising_factorial()
template<typename _Tp > _Tp std::__detail::__log_rising_factorial (_Tp __a, _Tp __nu)
Return the logarithm of the rising factorial function or the (upper) Pochhammer symbol. The Pochammer symbol is defined for integer order by
Thus this function returns
Many notations exist for this function:
(especially in the literature of special functions),
, and others.
Definition at line 3201 of file sf_gamma.tcc.
References __log_gamma(), and __rising_factorial().
__log_stirling_1()
template<typename _Tp > _Tp std::__detail::__log_stirling_1 (unsigned int __n, unsigned int __m)
Return the logarithm of the absolute value of Stirling number of the first kind.
Definition at line 387 of file sf_stirling.tcc.
__log_stirling_1_sign()
template<typename _Tp > _Tp std::__detail::__log_stirling_1_sign (unsigned int __n, unsigned int __m) inline
Return the sign of the exponent of the logarithm of the Stirling number of the first kind.
Definition at line 405 of file sf_stirling.tcc.
__log_stirling_2()
template<typename _Tp > _Tp std::__detail::__log_stirling_2 (unsigned int __n, unsigned int __m)
Return the Stirling number of the second kind.
Todo:
Find asymptotic expressions for the Stirling numbers.
Definition at line 234 of file sf_stirling.tcc.
__logint()
template<typename _Tp > _Tp std::__detail::__logint (const _Tp __x)
Return the logarithmic integral .
The logarithmic integral is given by
Parameters
__x The argument of the logarithmic integral function.
Returns
The logarithmic integral.
Definition at line 538 of file sf_expint.tcc.
References __expint().
__logistic_p()
template<typename _Tp > _Tp std::__detail::__logistic_p (_Tp __a, _Tp __b, _Tp __x)
Return the logistic cumulative distribution function.
The formula for the logistic probability function is
where .
Definition at line 688 of file sf_distributions.tcc.
__logistic_pdf()
template<typename _Tp > _Tp std::__detail::__logistic_pdf (_Tp __a, _Tp __b, _Tp __x)
Return the logistic probability density function.
The formula for the logistic probability density function is
where .
Definition at line 670 of file sf_distributions.tcc.
__lognormal_p()
template<typename _Tp > _Tp std::__detail::__lognormal_p (_Tp __mu, _Tp __sigma, _Tp __x)
Return the lognormal cumulative probability density function.
The formula for the lognormal cumulative probability density function is
Definition at line 287 of file sf_distributions.tcc.
__lognormal_pdf()
template<typename _Tp > _Tp std::__detail::__lognormal_pdf (_Tp __nu, _Tp __sigma, _Tp __x)
Return the lognormal probability density function.
The formula for the lognormal probability density function is
Definition at line 259 of file sf_distributions.tcc.
__normal_p()
template<typename _Tp > _Tp std::__detail::__normal_p (_Tp __mu, _Tp __sigma, _Tp __x)
Return the normal cumulative probability density function.
The formula for the normal cumulative probability density function is
Definition at line 238 of file sf_distributions.tcc.
__normal_pdf()
template<typename _Tp > _Tp std::__detail::__normal_pdf (_Tp __mu, _Tp __sigma, _Tp __x)
Return the normal probability density function.
The formula for the normal probability density function is
Definition at line 210 of file sf_distributions.tcc.
__owens_t()
template<typename _Tp > _Tp std::__detail::__owens_t (_Tp __h, _Tp __a)
Return the Owens T function:
This implementation is a translation of the Fortran implementation in
See also
Patefield, M. and Tandy, D. "Fast and accurate Calculation of Owen's T-Function", Journal of Statistical Software, 5 (5), 1 - 25 (2000)
Parameters
[in] __h The scale parameter.
[in] __a The integration limit.
Returns
The owens T function.
Definition at line 92 of file sf_owens_t.tcc.
References __znorm1(), and __znorm2().
__periodic_zeta()
template<typename _Tp , typename _ArgType > __gnu_cxx::fp_promote_t<std::complex<_Tp>, _ArgType> std::__detail::__periodic_zeta (_ArgType __z, _Tp __s)
Return the periodic zeta function F(z,s) for two real arguments.
The periodic zeta function is defined by
Parameters
__s The real order.
__z The real or complex argument.
Returns
The complex value of the periodic zeta function.
Definition at line 1102 of file sf_polylog.tcc.
References __gnu_cxx::__fp_is_zero(), __polylog_exp(), and __riemann_zeta().
__polar_pi() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polar_pi (_Tp __rho, _Tp __phi_pi) inline
Reperiodized complex constructor.
Definition at line 401 of file sf_trig.tcc.
References __gnu_cxx::__sincos_t< _Tp >::__cos_v, __gnu_cxx::__sincos_t< _Tp >::__sin_v, and __sincos_pi().
Referenced by __cyl_bessel_jn_neg_arg(), __cyl_hankel_1(), __cyl_hankel_2(), __jacobi_theta_1(), __jacobi_theta_2(), __polylog_exp_neg(), and __polylog_exp_pos().
__polar_pi() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polar_pi (_Tp __rho, const std::complex< _Tp > & __phi_pi) inline
Reperiodized complex constructor.
Definition at line 413 of file sf_trig.tcc.
References __gnu_cxx::__sincos_t< _Tp >::__cos_v, __gnu_cxx::__sincos_t< _Tp >::__sin_v, and __sincos_pi().
__polygamma()
template<typename _Tp > _Tp std::__detail::__polygamma (unsigned int __m, _Tp __x)
Return the polygamma function .
The polygamma function is related to the Hurwitz zeta function:
Definition at line 3467 of file sf_gamma.tcc.
References __digamma(), __gnu_cxx::__fp_is_integer(), __hurwitz_zeta(), __log_gamma(), and std::__detail::_Factorial_table< _Tp >::__n.
__polylog() [1/2]
template<typename _Tp > _Tp std::__detail::__polylog (_Tp __s, _Tp __x)
Return the polylog Li_s(x) for two real arguments.
The polylog is defined by
Parameters
__s The real order.
__x The real argument.
Returns
The complex value of the polylogarithm.
Definition at line 1037 of file sf_polylog.tcc.
References __gnu_cxx::__fp_is_equal(), __gnu_cxx::__fp_is_integer(), __gnu_cxx::__fp_is_zero(), and __polylog_exp().
Referenced by __dirichlet_beta(), __dirichlet_eta(), and __polylog().
__polylog() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog (_Tp __s, std::complex< _Tp > __w)
Return the polylog in those cases where we can calculate it.
Parameters
__s The real order.
__w The complex argument.
Returns
The complex value of the polylogarithm.
Definition at line 1078 of file sf_polylog.tcc.
References __polylog(), and __polylog_exp().
__polylog_exp()
template<typename _Tp , typename _ArgType > __gnu_cxx::fp_promote_t<std::complex<_Tp>, _ArgType> std::__detail::__polylog_exp (_Tp __s, _ArgType __w)
This is the frontend function which calculates First we branch into different parts depending on the properties of s. This function is the same irrespective of a real or complex w, hence the template parameter ArgType.
Note
: I really wish we could return a variant<Tp, std::complex<Tp>>.
Parameters
__s The real order.
__w The real or complex argument.
Returns
The real or complex value of Li_s(e^w).
Definition at line 996 of file sf_polylog.tcc.
References __gnu_cxx::__fp_is_integer(), __polylog_exp_neg_int(), __polylog_exp_neg_real(), __polylog_exp_pos_int(), __polylog_exp_pos_real(), and __polylog_exp_sum().
Referenced by __bose_einstein(), __clausen(), __clausen_cl(), __clausen_sl(), __fermi_dirac(), __hurwitz_zeta_polylog(), __periodic_zeta(), and __polylog().
__polylog_exp_asymp()
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_asymp (_Tp __s, std::complex< _Tp > __w)
This function implements the asymptotic series for the polylog. It is given by
for
Don't check this against Mathematica 8. For real w the imaginary part of the polylog is given by . Check this relation for any benchmark that you use.
Parameters
__s the real index s.
__w the large complex argument w.
Returns
the value of the polylogarithm.
Definition at line 603 of file sf_polylog.tcc.
References __gamma_reciprocal().
Referenced by __polylog_exp_neg_int(), __polylog_exp_neg_real(), __polylog_exp_pos_int(), and __polylog_exp_pos_real().
__polylog_exp_neg() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_neg (_Tp __s, std::complex< _Tp > __w)
This function treats the cases of negative real index s. Theoretical convergence is present for . We use an optimized version of
Parameters
__s The negative real index
__w The complex argument
Returns
The value of the polylogarithm.
Definition at line 367 of file sf_polylog.tcc.
References __log_gamma(), __polar_pi(), and __riemann_zeta_m_1().
Referenced by __polylog_exp_neg_int(), and __polylog_exp_neg_real().
__polylog_exp_neg() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_neg (int __n, std::complex< _Tp > __w)
Compute the polylogarithm for negative integer order.
where .
Parameters
__n the negative integer index .
__w the argument w.
Returns
the value of the polylogarithm.
Definition at line 453 of file sf_polylog.tcc.
References __gnu_cxx::__fp_is_equal(), __gnu_cxx::__fp_is_zero(), _Num_Euler_Maclaurin_zeta, and _S_Euler_Maclaurin_zeta.
__polylog_exp_neg_int() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_neg_int (int __s, std::complex< _Tp > __w)
This treats the case where s is a negative integer.
Parameters
__s a negative integer.
__w an arbitrary complex number
Returns
the value of the polylogarith,.
Definition at line 789 of file sf_polylog.tcc.
References __clamp_0_m2pi(), __clamp_pi(), __gnu_cxx::__fp_is_equal(), __polylog_exp_asymp(), __polylog_exp_neg(), and __polylog_exp_sum().
Referenced by __polylog_exp().
__polylog_exp_neg_int() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_neg_int (int __s, _Tp __w)
This treats the case where s is a negative integer and w is a real.
Parameters
__s a negative integer.
__w the argument.
Returns
the value of the polylogarithm.
Definition at line 835 of file sf_polylog.tcc.
References __gnu_cxx::__fp_is_zero(), __polylog_exp_asymp(), __polylog_exp_neg(), and __polylog_exp_sum().
__polylog_exp_neg_real() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_neg_real (_Tp __s, std::complex< _Tp > __w)
Return the polylog where s is a negative real value and for complex argument. Now we branch depending on the properties of w in the specific functions
Parameters
__s A negative real value that does not reduce to a negative integer.
__w The complex argument.
Returns
The value of the polylogarithm.
Definition at line 936 of file sf_polylog.tcc.
References __clamp_0_m2pi(), __clamp_pi(), __polylog_exp_asymp(), __polylog_exp_neg(), and __polylog_exp_sum().
Referenced by __polylog_exp().
__polylog_exp_neg_real() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_neg_real (_Tp __s, _Tp __w)
Return the polylog where s is a negative real value and for real argument. Now we branch depending on the properties of w in the specific functions.
Parameters
__s A negative real value.
__w A real argument.
Returns
The value of the polylogarithm.
Definition at line 967 of file sf_polylog.tcc.
References __polylog_exp_asymp(), __polylog_exp_neg(), and __polylog_exp_sum().
__polylog_exp_pos() [1/3]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_pos (unsigned int __s, std::complex< _Tp > __w)
This function treats the cases of positive integer index s for complex argument w.
The radius of convergence is . Note that this series involves a . gcc and Mathematica differ in their implementation of : gcc: whereas Mathematica doesn't preserve the sign in this case:
Parameters
__s the positive integer index.
__w the argument.
Returns
the value of the polylogarithm.
Definition at line 219 of file sf_polylog.tcc.
References __riemann_zeta().
Referenced by __polylog_exp_pos_int(), and __polylog_exp_pos_real().
__polylog_exp_pos() [2/3]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_pos (unsigned int __s, _Tp __w)
This function treats the cases of positive integer index s for real argument w.
This specialization is worthwhile to catch the differing behaviour of log(x).
The radius of convergence is . Note that this series involves a . gcc and Mathematica differ in their implementation of : gcc: whereas Mathematica doesn't preserve the sign in this case:
Parameters
__s the positive integer index.
__w the argument.
Returns
the value of the polylogarithm.
Definition at line 295 of file sf_polylog.tcc.
References __riemann_zeta().
__polylog_exp_pos() [3/3]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_pos (_Tp __s, std::complex< _Tp > __w)
This function treats the cases of positive real index s.
The defining series is
with
Parameters
__s the positive real index s.
__w The complex argument w.
Returns
the value of the polylogarithm.
Definition at line 516 of file sf_polylog.tcc.
References __gamma(), __log_gamma(), __polar_pi(), and __riemann_zeta().
__polylog_exp_pos_int() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_pos_int (unsigned int __s, std::complex< _Tp > __w)
Here s is a positive integer and the function descends into the different kernels depending on w.
Parameters
__s a positive integer.
__w an arbitrary complex number.
Returns
The value of the polylogarithm.
Definition at line 678 of file sf_polylog.tcc.
References __clamp_0_m2pi(), __clamp_pi(), __gnu_cxx::__fp_is_equal(), __gnu_cxx::__fp_is_zero(), __polylog_exp_asymp(), __polylog_exp_pos(), and __polylog_exp_sum().
Referenced by __polylog_exp().
__polylog_exp_pos_int() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_pos_int (unsigned int __s, _Tp __w)
Here s is a positive integer and the function descends into the different kernels depending on w.
Parameters
__s a positive integer
__w an arbitrary real argument w
Returns
the value of the polylogarithm.
Definition at line 739 of file sf_polylog.tcc.
References __gnu_cxx::__fp_is_zero(), __polylog_exp_asymp(), __polylog_exp_pos(), and __polylog_exp_sum().
__polylog_exp_pos_real() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_pos_real (_Tp __s, std::complex< _Tp > __w)
Return the polylog where s is a positive real value and for complex argument.
Parameters
__s A positive real number.
__w the complex argument.
Returns
The value of the polylogarithm.
Definition at line 862 of file sf_polylog.tcc.
References __clamp_0_m2pi(), __clamp_pi(), __gnu_cxx::__fp_is_equal(), __gnu_cxx::__fp_is_zero(), __polylog_exp_asymp(), __polylog_exp_pos(), __polylog_exp_sum(), and __riemann_zeta().
Referenced by __polylog_exp().
__polylog_exp_pos_real() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__polylog_exp_pos_real (_Tp __s, _Tp __w)
Return the polylog where s is a positive real value and the argument is real.
Parameters
__s A positive real number tht does not reduce to an integer.
__w The real argument w.
Returns
The value of the polylogarithm.
Definition at line 902 of file sf_polylog.tcc.
References __gnu_cxx::__fp_is_equal(), __gnu_cxx::__fp_is_zero(), __polylog_exp_asymp(), __polylog_exp_pos(), __polylog_exp_sum(), and __riemann_zeta().
__polylog_exp_sum()
template<typename _PowTp , typename _Tp > _Tp std::__detail::__polylog_exp_sum (_PowTp __s, _Tp __w)
Theoretical convergence for Re(w) < 0.
Seems to beat the other expansions for . Note that this is an implementation of the basic series:
Parameters
__s is an arbitrary type, integral or float.
__w something with a negative real part.
Returns
the value of the polylogarithm.
Definition at line 647 of file sf_polylog.tcc.
Referenced by __polylog_exp(), __polylog_exp_neg_int(), __polylog_exp_neg_real(), __polylog_exp_pos_int(), and __polylog_exp_pos_real().
__prob_hermite_recur()
template<typename _Tp > __gnu_cxx::__hermite_he_t<_Tp> std::__detail::__prob_hermite_recur (unsigned int __n, _Tp __x)
This routine returns the Probabilists Hermite polynomial of order n: by recursion on n.
The Probabilists Hermite polynomial is defined by:
or
where is the Physicists Hermite function.
The Probabilists Hermite polynomial has first and second derivatives:
and
The Probabilists Hermite polynomial are monic and are orthogonal with respect to the weight function
Parameters
__n The order of the Hermite polynomial.
__x The argument of the Hermite polynomial.
Returns
The value of the Hermite polynomial of order n and argument x.
Definition at line 260 of file sf_hermite.tcc.
__radial_jacobi()
template<typename _Tp > _Tp std::__detail::__radial_jacobi (unsigned int __n, unsigned int __m, _Tp __rho)
Return the radial polynomial for non-negative , and real radial argument is a polynomial of degree in .
The radial polynomials are defined by
for even and identically 0 for odd.
The radial polynomials are related to the Jacobi polynomials:
for
The radial polynomials can be related to the Zernike polynomials:
for non-negative .
See also
zernike for details on the Zernike polynomials.
Principals of Optics, 7th edition, Max Born and Emil Wolf, Cambridge University Press, 1999, pp 523-525 and 905-910.
Zernike Polynomials: Evaluation, Quadrature, and Interpolation Philip Greengard, Kirill Serkh, Technical Report YALEU/DCS/TR-1539, February 20, 2018
Template Parameters
_Tp The real type of the radial coordinate
Parameters
__n The non-negative degree.
__m The non-negative azimuthal order
__rho The radial argument
Definition at line 295 of file sf_jacobi.tcc.
References __jacobi_recur().
Referenced by __zernike(), __gnu_cxx::radpolyf(), and __gnu_cxx::radpolyl().
__radial_jacobi_zeros()
template<typename _Tp > std::vector<__gnu_cxx::__quadrature_point_t<_Tp> > std::__detail::__radial_jacobi_zeros (unsigned int __n, unsigned int __m)
Return a vector containing the zeros of the radial Jacobi polynomial .
Template Parameters
_Tp The real type of the radial coordinate
Parameters
[in] __n The degree of the radial Jacobi polynomial
[in] __m The order of the radial Jacobi polynomial
Definition at line 326 of file sf_jacobi.tcc.
References __jacobi_zeros().
__rice_pdf()
template<typename _Tp > _Tp std::__detail::__rice_pdf (_Tp __nu, _Tp __sigma, _Tp __x)
Return the Rice probability density function.
The formula for the Rice probability density function is
where is the modified Bessel function of the first kind of order 0 and and .
Definition at line 186 of file sf_distributions.tcc.
References __cyl_bessel_i().
__riemann_zeta()
template<typename _Tp > _Tp std::__detail::__riemann_zeta (_Tp __s)
Return the Riemann zeta function .
The Riemann zeta function is defined by:
Parameters
__s The order
Todo:
Global double sum or MacLaurin series in riemann_zeta?
Definition at line 761 of file sf_zeta.tcc.
References __exp2(), __gnu_cxx::__fp_is_integer(), __gamma(), __log_gamma(), __riemann_zeta_glob(), __riemann_zeta_m_1(), __riemann_zeta_product(), __riemann_zeta_sum(), and __sin_pi().
Referenced by __dirichlet_lambda(), __hurwitz_zeta(), __periodic_zeta(), __polylog_exp_pos(), and __polylog_exp_pos_real().
__riemann_zeta_euler_maclaurin()
template<typename _Tp > _Tp std::__detail::__riemann_zeta_euler_maclaurin (_Tp __s)
Evaluate the Riemann zeta function by an alternate series for s > 0.
This is a specialization of the code for the Hurwitz zeta function.
Definition at line 391 of file sf_zeta.tcc.
References _S_Euler_Maclaurin_zeta.
__riemann_zeta_glob()
template<typename _Tp > _Tp std::__detail::__riemann_zeta_glob (_Tp __s)
Definition at line 501 of file sf_zeta.tcc.
References __gnu_cxx::__fp_is_even_integer(), __gamma(), __riemann_zeta_m_1_glob(), and __sin_pi().
Referenced by __riemann_zeta().
__riemann_zeta_laurent()
template<typename _Tp > _Tp std::__detail::__riemann_zeta_laurent (_Tp __s)
Compute the Riemann zeta function by Laurent expansion about s = 1.
The Laurent expansion of the Riemann zeta function is given by:
Where are the Stieltjes constants, the Euler-Mascheroni constant.
The Stieltjes constants can be found from a limiting process:
Definition at line 314 of file sf_zeta.tcc.
References _Num_Stieltjes, and _S_Stieltjes.
Referenced by __riemann_zeta_m_1().
__riemann_zeta_m_1()
template<typename _Tp > _Tp std::__detail::__riemann_zeta_m_1 (_Tp __s)
Return the Riemann zeta function .
Parameters
__s The order
Definition at line 717 of file sf_zeta.tcc.
References __gnu_cxx::__fp_is_integer(), __gamma(), __riemann_zeta_laurent(), __riemann_zeta_m_1_glob(), __sin_pi(), _S_num_zetam1, and _S_zetam1.
Referenced by __polylog_exp_neg(), and __riemann_zeta().
__riemann_zeta_m_1_glob()
template<typename _Tp > _Tp std::__detail::__riemann_zeta_m_1_glob (_Tp __s)
Evaluate the Riemann zeta function by series for all s != 1. Convergence is great until largish negative numbers. Then the convergence of the > 0 sum gets better.
The series is:
Havil 2003, p. 206.
The Riemann zeta function is defined by:
For s < 1 use the reflection formula:
Definition at line 450 of file sf_zeta.tcc.
Referenced by __riemann_zeta_glob(), and __riemann_zeta_m_1().
__riemann_zeta_product()
template<typename _Tp > _Tp std::__detail::__riemann_zeta_product (_Tp __s)
Compute the Riemann zeta function using the product over prime factors.
where are the prime numbers.
The Riemann zeta function is defined by:
For (s) < 1 use the reflection formula:
Parameters
__s The order.
Definition at line 551 of file sf_zeta.tcc.
Referenced by __riemann_zeta().
__riemann_zeta_sum()
template<typename _Tp > _Tp std::__detail::__riemann_zeta_sum (_Tp __s)
Compute the Riemann zeta function by summation for s > 1.
The Riemann zeta function is defined by:
For s < 1 use the reflection formula:
Definition at line 348 of file sf_zeta.tcc.
References __gamma(), and __sin_pi().
Referenced by __riemann_zeta().
__rising_factorial() [1/2]
template<typename _Tp > _Tp std::__detail::__rising_factorial (_Tp __a, int __n)
Return the (upper) Pochhammer function or the rising factorial function. The Pochammer symbol is defined by
Many notations exist for this function:
, (especially in the literature of special functions),
, and others.
Definition at line 3102 of file sf_gamma.tcc.
References __log_gamma(), __log_gamma_sign(), and std::__detail::_Factorial_table< _Tp >::__n.
Referenced by __log_rising_factorial(), and __rising_factorial().
__rising_factorial() [2/2]
template<typename _Tp > _Tp std::__detail::__rising_factorial (_Tp __a, _Tp __nu)
Return the rising factorial function or the (upper) Pochhammer function. The rising factorial function is defined by
Many notations exist for this function:
, (especially in the literature of special functions),
, and others.
Definition at line 3157 of file sf_gamma.tcc.
References __log_gamma(), __log_gamma_sign(), std::__detail::_Factorial_table< _Tp >::__n, and __rising_factorial().
__sin_pi() [1/2]
template<typename _Tp > _Tp std::__detail::__sin_pi (_Tp __x)
Return the reperiodized sine of argument x:
Definition at line 52 of file sf_trig.tcc.
Referenced by __cos_pi(), __cosh_pi(), __cyl_bessel_ik(), __cyl_bessel_jn(), __dirichlet_eta(), __gamma_reciprocal(), __hankel_debye(), __laguerre_large_n(), __lanczos_log_gamma1p(), __log_gamma(), __riemann_zeta(), __riemann_zeta_glob(), __riemann_zeta_m_1(), __riemann_zeta_sum(), __sin_pi(), __sinc_pi(), __sinh_pi(), and __spouge_log_gamma1p().
__sin_pi() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__sin_pi (std::complex< _Tp > __z)
Return the reperiodized sine of complex argument z:
Definition at line 187 of file sf_trig.tcc.
References __cos_pi(), and __sin_pi().
__sinc()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> std::__detail::__sinc (_Tp __x)
Return the sinus cardinal function
.
Definition at line 52 of file sf_cardinal.tcc.
__sinc_pi()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> std::__detail::__sinc_pi (_Tp __x)
Return the reperiodized sinus cardinal function
.
Definition at line 72 of file sf_cardinal.tcc.
References __sin_pi().
__sincos() [1/4]
template<typename _Tp > __gnu_cxx::__sincos_t<_Tp> std::__detail::__sincos (_Tp __x) inline
Definition at line 316 of file sf_trig.tcc.
Referenced by __sincos_pi().
__sincos() [2/4]
template<> __gnu_cxx::__sincos_t<float> std::__detail::__sincos (float __x) inline
Definition at line 324 of file sf_trig.tcc.
__sincos() [3/4]
template<> __gnu_cxx::__sincos_t<double> std::__detail::__sincos (double __x) inline
Definition at line 336 of file sf_trig.tcc.
__sincos() [4/4]
template<> __gnu_cxx::__sincos_t<long double> std::__detail::__sincos (long double __x) inline
Definition at line 348 of file sf_trig.tcc.
__sincos_pi()
template<typename _Tp > __gnu_cxx::__sincos_t<_Tp> std::__detail::__sincos_pi (_Tp __x)
Reperiodized sincos.
Definition at line 360 of file sf_trig.tcc.
References __gnu_cxx::__sincos_t< _Tp >::__cos_v, __gnu_cxx::__sincos_t< _Tp >::__sin_v, and __sincos().
Referenced by __polar_pi().
__sincosint()
template<typename _Tp > std::pair<_Tp, _Tp> std::__detail::__sincosint (_Tp __x)
This function returns the sine and cosine integrals as a pair.
The sine integral is defined by:
The cosine integral is defined by:
Definition at line 226 of file sf_trigint.tcc.
References __sincosint_asymp(), __sincosint_cont_frac(), and __sincosint_series().
__sincosint_asymp()
template<typename _Tp > void std::__detail::__sincosint_asymp (_Tp __t, _Tp & _Si, _Tp & _Ci)
This function computes the sine and cosine integrals by asymptotic series summation for positive argument.
The asymptotic series is very good for x > 50.
Definition at line 159 of file sf_trigint.tcc.
Referenced by __sincosint().
__sincosint_cont_frac()
template<typename _Tp > void std::__detail::__sincosint_cont_frac (_Tp __t, _Tp & _Si, _Tp & _Ci)
This function computes the sine and cosine integrals by continued fraction for positive argument.
Definition at line 52 of file sf_trigint.tcc.
Referenced by __sincosint().
__sincosint_series()
template<typename _Tp > void std::__detail::__sincosint_series (_Tp __t, _Tp & _Si, _Tp & _Ci)
This function computes the sine and cosine integrals by series summation for positive argument.
Definition at line 95 of file sf_trigint.tcc.
Referenced by __sincosint().
__sinh_pi() [1/2]
template<typename _Tp > _Tp std::__detail::__sinh_pi (_Tp __x)
Return the reperiodized hyperbolic sine of argument x:
Definition at line 84 of file sf_trig.tcc.
Referenced by __sinhc_pi().
__sinh_pi() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__sinh_pi (std::complex< _Tp > __z)
Return the reperiodized hyperbolic sine of complex argument z:
Definition at line 209 of file sf_trig.tcc.
References __cos_pi(), and __sin_pi().
__sinhc()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> std::__detail::__sinhc (_Tp __x)
Return the hyperbolic sinus cardinal function
.
Definition at line 97 of file sf_cardinal.tcc.
__sinhc_pi()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> std::__detail::__sinhc_pi (_Tp __x)
Return the reperiodized hyperbolic sinus cardinal function
.
Definition at line 115 of file sf_cardinal.tcc.
References __sinh_pi().
__sinhint()
template<typename _Tp > _Tp std::__detail::__sinhint (const _Tp __x)
Return the hyperbolic sine integral .
The hyperbolic sine integral is given by
Parameters
__x The argument of the hyperbolic sine integral function.
Returns
The hyperbolic sine integral.
Definition at line 584 of file sf_expint.tcc.
References __expint_E1(), and __expint_Ei().
__sph_bessel() [1/2]
template<typename _Tp > _Tp std::__detail::__sph_bessel (unsigned int __n, _Tp __x)
Return the spherical Bessel function of order n and non-negative real argument x.
The spherical Bessel function is defined by:
Parameters
__n The non-negative integral order
__x The non-negative real argument
Returns
The output spherical Bessel function.
Definition at line 781 of file sf_bessel.tcc.
References __sph_bessel_jn().
__sph_bessel() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__sph_bessel (unsigned int __n, std::complex< _Tp > __z)
Return the complex spherical Bessel function.
Parameters
[in] __n The order for which the spherical Bessel function is evaluated.
[in] __z The argument at which the spherical Bessel function is evaluated.
Returns
The complex spherical Bessel function.
Definition at line 1273 of file sf_hankel.tcc.
References __sph_hankel().
__sph_bessel_ik()
template<typename _Tp > __gnu_cxx::__sph_mod_bessel_t<unsigned int, _Tp, _Tp> std::__detail::__sph_bessel_ik (unsigned int __n, _Tp __x)
Compute the spherical modified Bessel functions and and their first derivatives and respectively.
Parameters
__n The order of the modified spherical Bessel function.
__x The argument of the modified spherical Bessel function.
Returns
A struct containing the modified spherical Bessel functions of the first and second kinds and their derivatives.
Definition at line 428 of file sf_mod_bessel.tcc.
References __cyl_bessel_ik().
__sph_bessel_jn()
template<typename _Tp > __gnu_cxx::__sph_bessel_t<unsigned int, _Tp, _Tp> std::__detail::__sph_bessel_jn (unsigned int __n, _Tp __x)
Compute the spherical Bessel and Neumann functions and their first derivatives and respectively.
Parameters
__n The order of the spherical Bessel function.
__x The argument of the spherical Bessel function.
Returns
The output derivative of the spherical Neumann function.
Definition at line 713 of file sf_bessel.tcc.
References __cyl_bessel_jn().
Referenced by __sph_bessel(), __sph_hankel_1(), __sph_hankel_2(), and __sph_neumann().
__sph_bessel_jn_neg_arg()
template<typename _Tp > __gnu_cxx::__sph_bessel_t<unsigned int, _Tp, std::complex<_Tp> > std::__detail::__sph_bessel_jn_neg_arg (unsigned int __n, _Tp __x)
Return the spherical Bessel functions and their derivatives of order and argument .
Definition at line 737 of file sf_bessel.tcc.
References __cyl_bessel_jn_neg_arg().
Referenced by __sph_hankel_1(), and __sph_hankel_2().
__sph_hankel()
template<typename _Tp > __gnu_cxx::__sph_hankel_t<unsigned int, std::complex<_Tp>, std::complex<_Tp> > std::__detail::__sph_hankel (unsigned int __n, std::complex< _Tp > __z)
Helper to compute complex spherical Hankel functions and their derivatives.
Parameters
[in] __n The order for which the spherical Hankel functions are evaluated.
[in] __z The argument at which the spherical Hankel functions are evaluated.
Returns
A struct containing the spherical Hankel functions of the first and second kinds and their derivatives.
Definition at line 1209 of file sf_hankel.tcc.
References __hankel().
Referenced by __sph_bessel(), __sph_hankel_1(), __sph_hankel_2(), and __sph_neumann().
__sph_hankel_1() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__sph_hankel_1 (unsigned int __n, _Tp __x)
Return the spherical Hankel function of the first kind .
The spherical Hankel function of the first kind is defined by:
Parameters
__n The order of the spherical Neumann function.
__x The argument of the spherical Neumann function.
Returns
The output spherical Neumann function.
Definition at line 842 of file sf_bessel.tcc.
References __sph_bessel_jn(), and __sph_bessel_jn_neg_arg().
__sph_hankel_1() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__sph_hankel_1 (unsigned int __n, std::complex< _Tp > __z)
Return the complex spherical Hankel function of the first kind.
Parameters
[in] __n The order for which the spherical Hankel function of the first kind is evaluated.
[in] __z The argument at which the spherical Hankel function of the first kind is evaluated.
Returns
The complex spherical Hankel function of the first kind.
Definition at line 1239 of file sf_hankel.tcc.
References __sph_hankel().
__sph_hankel_2() [1/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__sph_hankel_2 (unsigned int __n, _Tp __x)
Return the spherical Hankel function of the second kind .
The spherical Hankel function of the second kind is defined by:
Parameters
__n The non-negative integral order
__x The non-negative real argument
Returns
The output spherical Neumann function.
Definition at line 877 of file sf_bessel.tcc.
References __sph_bessel_jn(), and __sph_bessel_jn_neg_arg().
__sph_hankel_2() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__sph_hankel_2 (unsigned int __n, std::complex< _Tp > __z)
Return the complex spherical Hankel function of the second kind.
Parameters
[in] __n The order for which the spherical Hankel function of the second kind is evaluated.
[in] __z The argument at which the spherical Hankel function of the second kind is evaluated.
Returns
The complex spherical Hankel function of the second kind.
Definition at line 1256 of file sf_hankel.tcc.
References __sph_hankel().
__sph_harmonic()
template<typename _Tp > std::complex<_Tp> std::__detail::__sph_harmonic (unsigned int __l, int __m, _Tp __theta, _Tp __phi)
Return the spherical harmonic function.
The spherical harmonic function of , , and , is defined by:
Note
if .
Parameters
__l The degree of the spherical harmonic function. .
__m The order of the spherical harmonic function.
__theta The radian polar angle argument of the spherical harmonic function.
__phi The radian azimuthal angle argument of the spherical harmonic function.
Definition at line 502 of file sf_legendre.tcc.
References __sph_legendre().
__sph_legendre()
template<typename _Tp > _Tp std::__detail::__sph_legendre (unsigned int __l, unsigned int __m, _Tp __theta)
Return the spherical associated Legendre function.
The spherical associated Legendre function of , , and is defined as where
is the spherical harmonic function and is the associated Legendre function.
This function differs from the associated Legendre function by argument () and by a normalization factor but this factor is rather large for large and and so this function is stable for larger differences of and .
Note
Unlike the case for __assoc_legendre_p the Condon-Shortley phase factor is present here.
if .
Parameters
__l The degree of the spherical associated Legendre function. .
__m The order of the spherical associated Legendre function.
__theta The radian polar angle argument of the spherical associated Legendre function.
Definition at line 409 of file sf_legendre.tcc.
References __legendre_p(), and __log_gamma().
Referenced by __hydrogen(), and __sph_harmonic().
__sph_neumann() [1/2]
template<typename _Tp > _Tp std::__detail::__sph_neumann (unsigned int __n, _Tp __x)
Return the spherical Neumann function of order n and non-negative real argument x.
The spherical Neumann function is defined by:
Parameters
__n The order of the spherical Neumann function.
__x The argument of the spherical Neumann function.
Returns
The output spherical Neumann function.
Definition at line 814 of file sf_bessel.tcc.
References __sph_bessel_jn().
__sph_neumann() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__sph_neumann (unsigned int __n, std::complex< _Tp > __z)
Return the complex spherical Neumann function.
Parameters
[in] __n The order for which the spherical Neumann function is evaluated.
[in] __z The argument at which the spherical Neumann function is evaluated.
Returns
The complex spherical Neumann function.
Definition at line 1290 of file sf_hankel.tcc.
References __sph_hankel().
__spouge_binet1p()
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__spouge_binet1p (_Tp __z)
Return the Binet function by the Spouge method. The Binet function is the log of the scaled Gamma function defined by
or
where is the gamma function.
Parameters
__z The argument of the log of the gamma function.
Returns
The logarithm of the gamma function.
Definition at line 1941 of file sf_gamma.tcc.
Referenced by __spouge_log_gamma1p().
__spouge_log_gamma1p()
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std::__detail::__spouge_log_gamma1p (_Tp __z)
Return the logarithm of the gamma function by the Spouge algorithm:
where
and the error is bounded by
.
If the argument is real, the log of the absolute value of the Gamma function is returned. The sign to be applied to the exponential of this log Gamma can be recovered with a call to __log_gamma_sign.
For complex argument the fully complex log of the gamma function is returned.
See also
Spouge, J. L., Computation of the gamma, digamma, and trigamma functions. SIAM Journal on Numerical Analysis 31, 3 (1994), pp. 931-944
Parameters
__z The argument of the gamma function.
Returns
The the gamma function.
Definition at line 1985 of file sf_gamma.tcc.
References __sin_pi(), and __spouge_binet1p().
Referenced by __log_gamma().
__stirling_1() [1/2]
template<typename _Tp > _Tp std::__detail::__stirling_1 (unsigned int __n, unsigned int __m)
Return the Stirling number of the first kind.
The Stirling numbers of the first kind are the coefficients of the Pocchammer polynomials:
The recursion is
with starting values
and
Todo:
Find asymptotic expressions for the Stirling numbers.
Definition at line 311 of file sf_stirling.tcc.
__stirling_1() [2/2]
template<typename _Tp > std::vector<_Tp> std::__detail::__stirling_1 (unsigned int __n)
Return a vector of Stirling numbers of the first kind. The recursion is
with starting values
and
Definition at line 378 of file sf_stirling.tcc.
__stirling_1_recur() [1/2]
template<typename _Tp > _Tp std::__detail::__stirling_1_recur (unsigned int __n, unsigned int __m)
Return the Stirling number of the first kind by recursion. The recursion is
with starting values
and
Definition at line 263 of file sf_stirling.tcc.
__stirling_1_recur() [2/2]
template<typename _Tp > std::vector<_Tp> std::__detail::__stirling_1_recur (unsigned int __n)
Return a vector of Stirling numbers of the first kind by recursion. The recursion is
with starting values
and
Definition at line 340 of file sf_stirling.tcc.
__stirling_2() [1/2]
template<typename _Tp > _Tp std::__detail::__stirling_2 (unsigned int __n, unsigned int __m)
Return the Stirling number of the second kind from lookup or by series expansion.
The series is:
Todo:
Find asymptotic expressions for the Stirling numbers.
Definition at line 155 of file sf_stirling.tcc.
__stirling_2() [2/2]
template<typename _Tp > std::vector<_Tp> std::__detail::__stirling_2 (unsigned int __n)
Return a vector of Stirling numbers of the second kind. or by series expansion.
The series is:
Todo:
Find asymptotic expressions for the Stirling numbers.
Definition at line 224 of file sf_stirling.tcc.
__stirling_2_recur() [1/2]
template<typename _Tp > _Tp std::__detail::__stirling_2_recur (unsigned int __n, unsigned int __m)
Return the Stirling number of the second kind by recursion. The recursion is
with starting values
and
The Stirling number of the second kind is denoted by other symbols in the literature: , and others.
Definition at line 119 of file sf_stirling.tcc.
__stirling_2_recur() [2/2]
template<typename _Tp > std::vector<_Tp> std::__detail::__stirling_2_recur (unsigned int __n)
Return a vector of Stirling numbers of the second kind by recursion. The recursion is
with starting values
and
The Stirling number of the second kind is denoted by other symbols in the literature: , and others.
Definition at line 189 of file sf_stirling.tcc.
__stirling_2_series()
template<typename _Tp > _Tp std::__detail::__stirling_2_series (unsigned int __n, unsigned int __m)
Return the Stirling number of the second kind from lookup or by series expansion.
The series is:
The Stirling number of the second kind is denoted by other symbols in the literature: , and others.
Todo:
Find a way to predict the maximum Stirling number supported for a given type.
Definition at line 66 of file sf_stirling.tcc.
__student_t_p()
template<typename _Tp > _Tp std::__detail::__student_t_p (_Tp __t, unsigned int __nu)
Return the Students T probability function.
The students T propability function is related to the incomplete beta function:
Parameters
__t
__nu
Definition at line 444 of file sf_distributions.tcc.
References __beta_inc().
__student_t_pdf()
template<typename _Tp > _Tp std::__detail::__student_t_pdf (_Tp __t, unsigned int __nu)
Return the Students T probability density.
The students T propability density is:
Parameters
__t
__nu
Definition at line 419 of file sf_distributions.tcc.
References __gamma().
__student_t_q()
template<typename _Tp > _Tp std::__detail::__student_t_q (_Tp __t, unsigned int __nu)
Return the complement of the Students T probability function.
The complement of the students T propability function is:
Parameters
__t
__nu
Definition at line 467 of file sf_distributions.tcc.
References __beta_inc().
__tan_pi() [1/2]
template<typename _Tp > _Tp std::__detail::__tan_pi (_Tp __x)
Return the reperiodized tangent of argument x:
Definition at line 153 of file sf_trig.tcc.
Referenced by __digamma(), __tan_pi(), and __tanh_pi().
__tan_pi() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__tan_pi (std::complex< _Tp > __z)
Return the reperiodized tangent of complex argument z:
Definition at line 275 of file sf_trig.tcc.
References __tan_pi().
__tanh_pi() [1/2]
template<typename _Tp > _Tp std::__detail::__tanh_pi (_Tp __x)
Return the reperiodized hyperbolic tangent of argument x:
Definition at line 169 of file sf_trig.tcc.
__tanh_pi() [2/2]
template<typename _Tp > std::complex<_Tp> std::__detail::__tanh_pi (std::complex< _Tp > __z)
Return the reperiodized hyperbolic tangent of complex argument z:
Definition at line 298 of file sf_trig.tcc.
References __tan_pi().
__tgamma()
template<typename _Tp > _Tp std::__detail::__tgamma (_Tp __a, _Tp __x)
Return the upper incomplete gamma function. The lower incomplete gamma function is defined by
.
Definition at line 2905 of file sf_gamma.tcc.
References __gnu_cxx::__fp_is_integer(), __gamma_cont_frac(), and __gamma_series().
Referenced by __gamma_q().
__tgamma_lower()
template<typename _Tp > _Tp std::__detail::__tgamma_lower (_Tp __a, _Tp __x)
Return the lower incomplete gamma function. The lower incomplete gamma function is defined by
.
Definition at line 2870 of file sf_gamma.tcc.
References __gnu_cxx::__fp_is_integer(), __gamma_cont_frac(), and __gamma_series().
Referenced by __gamma_p().
__theta_1()
template<typename _Tp > _Tp std::__detail::__theta_1 (_Tp __nu, _Tp __x)
Return the exponential theta-1 function of period nu and argument x.
The exponential theta-1 function is defined by
Parameters
__nu The periodic (period = 2) argument
__x The argument
Definition at line 212 of file sf_theta.tcc.
References __gnu_cxx::__fp_is_zero(), and __theta_2().
Referenced by __theta_s().
__theta_2()
template<typename _Tp > _Tp std::__detail::__theta_2 (_Tp __nu, _Tp __x)
Return the exponential theta-2 function of period nu and argument x.
The exponential theta-2 function is defined by
Parameters
__nu The periodic (period = 2) argument
__x The argument
Definition at line 184 of file sf_theta.tcc.
References __theta_2_asymp(), and __theta_2_sum().
Referenced by __theta_1(), and __theta_c().
__theta_2_asymp()
template<typename _Tp > _Tp std::__detail::__theta_2_asymp (_Tp __nu, _Tp __x)
Compute and return the exponential function by asymptotic series expansion:
Definition at line 120 of file sf_theta.tcc.
Referenced by __theta_2().
__theta_2_sum()
template<typename _Tp > _Tp std::__detail::__theta_2_sum (_Tp __nu, _Tp __x)
Compute and return the exponential function by series expansion:
Definition at line 56 of file sf_theta.tcc.
Referenced by __theta_2().
__theta_3()
template<typename _Tp > _Tp std::__detail::__theta_3 (_Tp __nu, _Tp __x)
Return the exponential theta-3 function of period nu and argument x.
The exponential theta-3 function is defined by
Parameters
__nu The periodic (period = 1) argument
__x The argument
Definition at line 240 of file sf_theta.tcc.
References __theta_3_asymp(), and __theta_3_sum().
Referenced by __theta_4(), and __theta_d().
__theta_3_asymp()
template<typename _Tp > _Tp std::__detail::__theta_3_asymp (_Tp __nu, _Tp __x)
Compute and return the exponential function by asymptotic series expansion:
Definition at line 150 of file sf_theta.tcc.
Referenced by __theta_3().
__theta_3_sum()
template<typename _Tp > _Tp std::__detail::__theta_3_sum (_Tp __nu, _Tp __x)
Compute and return the exponential function by series expansion:
Definition at line 89 of file sf_theta.tcc.
Referenced by __theta_3().
__theta_4()
template<typename _Tp > _Tp std::__detail::__theta_4 (_Tp __nu, _Tp __x)
Return the exponential theta-4 function of period nu and argument x.
The exponential theta-4 function is defined by
Parameters
__nu The periodic (period = 2) argument
__x The argument
Definition at line 268 of file sf_theta.tcc.
References __theta_3().
Referenced by __theta_n().
__theta_c()
template<typename _Tp > _Tp std::__detail::__theta_c (_Tp __k, _Tp __x)
Return the Neville function
Definition at line 382 of file sf_theta.tcc.
References __comp_ellint_1(), __ellnome(), and __theta_2().
__theta_d()
template<typename _Tp > _Tp std::__detail::__theta_d (_Tp __k, _Tp __x)
Return the Neville function
Definition at line 411 of file sf_theta.tcc.
References __comp_ellint_1(), __ellnome(), and __theta_3().
__theta_n()
template<typename _Tp > _Tp std::__detail::__theta_n (_Tp __k, _Tp __x)
Return the Neville function
The Neville theta-n function is defined by
Definition at line 442 of file sf_theta.tcc.
References __comp_ellint_1(), __ellnome(), and __theta_4().
__theta_s()
template<typename _Tp > _Tp std::__detail::__theta_s (_Tp __k, _Tp __x)
Return the Neville function
Definition at line 352 of file sf_theta.tcc.
References __comp_ellint_1(), __ellnome(), and __theta_1().
__tricomi_u()
template<typename _Tp > _Tp std::__detail::__tricomi_u (_Tp __a, _Tp __c, _Tp __x)
Return the Tricomi confluent hypergeometric function
.
Parameters
__a The numerator parameter.
__c The denominator parameter.
__x The argument of the confluent hypergeometric function.
Returns
The Tricomi confluent hypergeometric function.
Definition at line 402 of file sf_hyperg.tcc.
References __tricomi_u_naive().
__tricomi_u_naive()
template<typename _Tp > _Tp std::__detail::__tricomi_u_naive (_Tp __a, _Tp __c, _Tp __x)
Return the Tricomi confluent hypergeometric function
.
Parameters
__a The numerator parameter.
__c The denominator parameter.
__x The argument of the confluent hypergeometric function.
Returns
The Tricomi confluent hypergeometric function.
Definition at line 368 of file sf_hyperg.tcc.
References __conf_hyperg(), __gnu_cxx::__fp_is_integer(), and __gnu_cxx::tgamma().
Referenced by __tricomi_u().
__weibull_p()
template<typename _Tp > _Tp std::__detail::__weibull_p (_Tp __a, _Tp __b, _Tp __x)
Return the Weibull cumulative probability density function.
The formula for the Weibull cumulative probability density function is
Definition at line 395 of file sf_distributions.tcc.
__weibull_pdf()
template<typename _Tp > _Tp std::__detail::__weibull_pdf (_Tp __a, _Tp __b, _Tp __x)
Return the Weibull probability density function.
The formula for the Weibull probability density function is
Definition at line 374 of file sf_distributions.tcc.
__zernike()
template<typename _Tp > __gnu_cxx::fp_promote_t<_Tp> std::__detail::__zernike (unsigned int __n, int __m, _Tp __rho, _Tp __phi)
Return the Zernicke polynomial for non-negative integral degree , signed integral order , and real radial argument and azimuthal angle .
The even Zernicke polynomials are defined by:
and the odd Zernicke polynomials are defined by:
for non-negative degree and and where is the radial polynomial (
See also
__radial_jacobi).
Principals of Optics, 7th edition, Max Born and Emil Wolf, Cambridge University Press, 1999, pp 523-525 and 905-910.
Template Parameters
_Tp The real type of the radial coordinate and azimuthal angle
Parameters
__n The non-negative integral degree.
__m The integral azimuthal order
__rho The radial coordinate
__phi The azimuthal angle
Definition at line 373 of file sf_jacobi.tcc.
References __radial_jacobi().
__znorm1()
template<typename _Tp > _Tp std::__detail::__znorm1 (_Tp __x)
Definition at line 58 of file sf_owens_t.tcc.
Referenced by __owens_t().
__znorm2()
template<typename _Tp > _Tp std::__detail::__znorm2 (_Tp __x)
Definition at line 47 of file sf_owens_t.tcc.
Referenced by __owens_t().
Variable Documentation
__max_FGH
template<typename _Tp > constexpr int std::__detail::__max_FGH = _Airy_series<_Tp>::_N_FGH
Definition at line 178 of file sf_airy.tcc.
__max_FGH< double >
template<> constexpr int std::__detail::__max_FGH< double > = 79
Definition at line 184 of file sf_airy.tcc.
__max_FGH< float >
template<> constexpr int std::__detail::__max_FGH< float > = 15
Definition at line 181 of file sf_airy.tcc.
_Num_Euler_Maclaurin_zeta
constexpr size_t std::__detail::_Num_Euler_Maclaurin_zeta = 100
Coefficients for Euler-Maclaurin summation of zeta functions.
where are the Bernoulli numbers.
Definition at line 117 of file sf_zeta.tcc.
Referenced by __polylog_exp_neg().
_Num_Stieltjes
constexpr size_t std::__detail::_Num_Stieltjes = 21
Coefficients for the expansion of the Riemann zeta function:
the Euler-Masceroni constant.
http://www.plouffe.fr/simon/constants/stieltjesgamma.txt
Definition at line 83 of file sf_zeta.tcc.
Referenced by __riemann_zeta_laurent().
_S_double_factorial_table
constexpr _Factorial_table<long double> std::__detail::_S_double_factorial_table[301]
Definition at line 280 of file sf_gamma.tcc.
Referenced by __double_factorial(), __log_double_factorial(), and __log_factorial().
_S_Euler_Maclaurin_zeta
constexpr long double std::__detail::_S_Euler_Maclaurin_zeta[_Num_Euler_Maclaurin_zeta]
Definition at line 120 of file sf_zeta.tcc.
Referenced by __hurwitz_zeta_euler_maclaurin(), __polylog_exp_neg(), and __riemann_zeta_euler_maclaurin().
_S_factorial_table
constexpr _Factorial_table<long double> std::__detail::_S_factorial_table[171]
Definition at line 90 of file sf_gamma.tcc.
Referenced by __factorial(), __gamma(), __gamma_reciprocal(), __log_factorial(), and __log_gamma().
_S_harmonic_denom
constexpr unsigned long long std::__detail::_S_harmonic_denom[_S_num_harmonic_numer]
Definition at line 3254 of file sf_gamma.tcc.
Referenced by __harmonic_number().
_S_harmonic_numer
constexpr unsigned long long std::__detail::_S_harmonic_numer[_S_num_harmonic_numer]
Definition at line 3221 of file sf_gamma.tcc.
Referenced by __harmonic_number().
_S_neg_double_factorial_table
constexpr _Factorial_table<long double> std::__detail::_S_neg_double_factorial_table[999]
Definition at line 601 of file sf_gamma.tcc.
Referenced by __double_factorial(), and __log_double_factorial().
_S_num_double_factorials
template<typename _Tp > constexpr std::size_t std::__detail::_S_num_double_factorials = 0
Definition at line 265 of file sf_gamma.tcc.
_S_num_double_factorials< double >
template<> constexpr std::size_t std::__detail::_S_num_double_factorials< double > = 301
Definition at line 270 of file sf_gamma.tcc.
_S_num_double_factorials< float >
template<> constexpr std::size_t std::__detail::_S_num_double_factorials< float > = 57
Definition at line 268 of file sf_gamma.tcc.
_S_num_double_factorials< long double >
template<> constexpr std::size_t std::__detail::_S_num_double_factorials< long double > = 301
Definition at line 272 of file sf_gamma.tcc.
_S_num_factorials
template<typename _Tp > constexpr std::size_t std::__detail::_S_num_factorials = 0
Definition at line 75 of file sf_gamma.tcc.
_S_num_factorials< double >
template<> constexpr std::size_t std::__detail::_S_num_factorials< double > = 171
Definition at line 80 of file sf_gamma.tcc.
_S_num_factorials< float >
template<> constexpr std::size_t std::__detail::_S_num_factorials< float > = 35
Definition at line 78 of file sf_gamma.tcc.
_S_num_factorials< long double >
template<> constexpr std::size_t std::__detail::_S_num_factorials< long double > = 171
Definition at line 82 of file sf_gamma.tcc.
_S_num_harmonic_numer
constexpr unsigned long long std::__detail::_S_num_harmonic_numer = 29
Definition at line 3218 of file sf_gamma.tcc.
Referenced by __harmonic_number().
_S_num_neg_double_factorials
template<typename _Tp > constexpr std::size_t std::__detail::_S_num_neg_double_factorials = 0
Definition at line 585 of file sf_gamma.tcc.
_S_num_neg_double_factorials< double >
template<> constexpr std::size_t std::__detail::_S_num_neg_double_factorials< double > = 150
Definition at line 590 of file sf_gamma.tcc.
_S_num_neg_double_factorials< float >
template<> constexpr std::size_t std::__detail::_S_num_neg_double_factorials< float > = 27
Definition at line 588 of file sf_gamma.tcc.
_S_num_neg_double_factorials< long double >
template<> constexpr std::size_t std::__detail::_S_num_neg_double_factorials< long double > = 999
Definition at line 592 of file sf_gamma.tcc.
_S_num_zetam1
constexpr size_t std::__detail::_S_num_zetam1 = 121
Table of zeta(n) - 1 from 0 - 120. MPFR @ 128 bits precision.
Definition at line 580 of file sf_zeta.tcc.
Referenced by __riemann_zeta_m_1().
_S_Stieltjes
constexpr long double std::__detail::_S_Stieltjes[_Num_Stieltjes]
Initial value:
{
    +0.5772156649015328606065120900824024310421593359L,
    -0.0728158454836767248605863758749013191377363383L,
    -0.0096903631928723184845303860352125293590658061L,
    +0.0020538344203033458661600465427533842857158044L,
    +0.0023253700654673000574681701775260680009044694L,
    +0.0007933238173010627017533348774444448307315394L,
    -0.0002387693454301996098724218419080042777837151L,
    -0.0005272895670577510460740975054788582819962534L,
    -0.0003521233538030395096020521650012087417291805L,
    -0.0000343947744180880481779146237982273906207895L,
    +0.0002053328149090647946837222892370653029598537L,
    +0.0002701844395439035266729020820679556738278420L,
    +0.0001672729121051401933535015433411834466078066L,
    -0.0000274638066037601588600076036933551815267853L,
    -0.0002092092620592999458371396973445849578315442L,
    -0.0002834686553202414466429344749971269770687029L,
    -0.0001996968583089697747077845632032403919157649L,
    +0.0000262770371099183366994665976305101228160786L,
    +0.0003073684081492528265927547519486256455238112L,
    +0.0005036054530473556290555964377171600353212698L,
    +0.0004663435615115594494005948244335505251131434L,
  }
Definition at line 86 of file sf_zeta.tcc.
Referenced by __riemann_zeta_laurent().
_S_zetam1
constexpr long double std::__detail::_S_zetam1[_S_num_zetam1]
Definition at line 584 of file sf_zeta.tcc.
Referenced by __riemann_zeta_m_1().