C++ Special Math Functions: std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 > Struct Template Reference
std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 > Struct Template Reference
Public Types
using _Cmplx = std::complex< _Real >
using _Real = __num_traits_t< _Type >
using _Type = typename __jacobi_lattice_t< _Tp1, _Tp3 >::_Tp_Nome
Public Member Functions
__weierstrass_roots_t (const __jacobi_lattice_t< _Tp1, _Tp3 > &__lattice)
__weierstrass_roots_t (const __jacobi_theta_0_t< _Tp1, _Tp3 > &__theta0, _Tp1 __omega1)
_Type __delta () const
Return the discriminant .
Public Attributes
_Type __e1
_Type __e2
_Type __e3
Detailed Description
template<typename _Tp1, typename _Tp3 = std::complex<_Tp1>>
struct std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >
A struct of the Weierstrass elliptic function roots.
Note that
Definition at line 747 of file sf_theta.tcc.
Member Typedef Documentation
_Cmplx
template<typename _Tp1, typename _Tp3 = std::complex<_Tp1>> using std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::_Cmplx = std::complex<_Real>
Definition at line 751 of file sf_theta.tcc.
_Real
template<typename _Tp1, typename _Tp3 = std::complex<_Tp1>> using std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::_Real = __num_traits_t<_Type>
Definition at line 750 of file sf_theta.tcc.
_Type
template<typename _Tp1, typename _Tp3 = std::complex<_Tp1>> using std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::_Type = typename __jacobi_lattice_t<_Tp1, _Tp3>::_Tp_Nome
Definition at line 749 of file sf_theta.tcc.
Constructor & Destructor Documentation
__weierstrass_roots_t() [1/2]
template<typename _Tp1 , typename _Tp3 > std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::__weierstrass_roots_t (const __jacobi_lattice_t< _Tp1, _Tp3 > & __lattice) explicit
Constructor for the Weierstrass roots.
Parameters
__lattice The Jacobi latticce.
Definition at line 781 of file sf_theta.tcc.
Referenced by std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::__delta().
__weierstrass_roots_t() [2/2]
template<typename _Tp1 , typename _Tp3 > std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::__weierstrass_roots_t (const __jacobi_theta_0_t< _Tp1, _Tp3 > & __theta0, _Tp1 __omega_1)
Constructor for the Weierstrass roots.
Parameters
__lattice The Jacobi latticce.
Definition at line 799 of file sf_theta.tcc.
References std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__omega_1(), std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_S_pi, std::__detail::__jacobi_theta_0_t< _Tp1, _Tp3 >::th2, and std::__detail::__jacobi_theta_0_t< _Tp1, _Tp3 >::th4.
Member Function Documentation
__delta()
template<typename _Tp1, typename _Tp3 = std::complex<_Tp1>> _Type std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::__delta () const inline
Return the discriminant .
Definition at line 764 of file sf_theta.tcc.
References std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::__weierstrass_roots_t().
Member Data Documentation
__e1
template<typename _Tp1, typename _Tp3 = std::complex<_Tp1>> _Type std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::__e1
Definition at line 753 of file sf_theta.tcc.
Referenced by std::__detail::__weierstrass_invariants_t< _Tp1, _Tp3 >::__weierstrass_invariants_t().
__e2
template<typename _Tp1, typename _Tp3 = std::complex<_Tp1>> _Type std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::__e2
Definition at line 753 of file sf_theta.tcc.
__e3
template<typename _Tp1, typename _Tp3 = std::complex<_Tp1>> _Type std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::__e3
Definition at line 753 of file sf_theta.tcc.
The documentation for this struct was generated from the following file:
include/bits/sf_theta.tcc