C++ Special Math Functions: std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 > Struct Template Reference
std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 > Struct Template Reference
Classes
struct __arg_t
struct __tau_t
Public Types
using _Cmplx = std::complex< _Real >
using _Real = __gnu_cxx::fp_promote_t< _Real_Omega1, _Real_Omega3 >
using _Real_Omega1 = __num_traits_t< _Tp_Omega1 >
using _Real_Omega3 = __num_traits_t< _Tp_Omega3 >
using _Tp_Nome = std::conditional_t< __gnu_cxx::is_complex_v< _Tp_Omega1 > &&__gnu_cxx::is_complex_v< _Tp_Omega3 >, _Cmplx, _Real >
Public Member Functions
__jacobi_lattice_t (const _Tp_Omega1 &__omega1, const _Tp_Omega3 &__omega3)
Construct the lattice from two complex lattice frequencies.
__jacobi_lattice_t (const __tau_t &__tau)
Construct the lattice from a single complex lattice parameter or half period ratio.
__jacobi_lattice_t (_Tp_Nome __q)
Construct the lattice from a single scalar elliptic nome.
_Tp_Nome __ellnome () const
_Tp_Omega1 __omega_1 () const
Return the first lattice frequency.
_Cmplx __omega_2 () const
Return the second lattice frequency.
_Tp_Omega3 __omega_3 () const
Return the third lattice frequency.
__arg_t __reduce (const _Cmplx &__z) const
__tau_t __tau () const
Return the acalar lattice parameter or half period ratio.
Public Attributes
_Tp_Omega1 _M_omega_1
_Tp_Omega3 _M_omega_3
Static Public Attributes
static constexpr auto _S_pi = __gnu_cxx::__const_pi<_Real>()
Detailed Description
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>>
struct std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >
A struct representing the Jacobi and Weierstrass lattice. The two types for the frequencies and the subsequent type calculus allow us to treat the rectangulr lattice (real nome, pure imaginary lattice parameter) specially.
Definition at line 470 of file sf_theta.tcc.
Member Typedef Documentation
_Cmplx
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> using std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_Cmplx = std::complex<_Real>
Definition at line 478 of file sf_theta.tcc.
_Real
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> using std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_Real = __gnu_cxx::fp_promote_t<_Real_Omega1, _Real_Omega3>
Definition at line 477 of file sf_theta.tcc.
_Real_Omega1
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> using std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_Real_Omega1 = __num_traits_t<_Tp_Omega1>
Definition at line 475 of file sf_theta.tcc.
_Real_Omega3
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> using std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_Real_Omega3 = __num_traits_t<_Tp_Omega3>
Definition at line 476 of file sf_theta.tcc.
_Tp_Nome
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> using std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_Tp_Nome = std::conditional_t<__gnu_cxx::is_complex_v<_Tp_Omega1> && __gnu_cxx::is_complex_v<_Tp_Omega3>, _Cmplx, _Real>
Definition at line 481 of file sf_theta.tcc.
Constructor & Destructor Documentation
__jacobi_lattice_t() [1/3]
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__jacobi_lattice_t (const _Tp_Omega1 & __omega1, const _Tp_Omega3 & __omega3) inline
Construct the lattice from two complex lattice frequencies.
Definition at line 508 of file sf_theta.tcc.
__jacobi_lattice_t() [2/3]
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__jacobi_lattice_t (const __tau_t & __tau) inline explicit
Construct the lattice from a single complex lattice parameter or half period ratio.
Definition at line 530 of file sf_theta.tcc.
__jacobi_lattice_t() [3/3]
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__jacobi_lattice_t (_Tp_Nome __q) inline explicit
Construct the lattice from a single scalar elliptic nome.
Definition at line 549 of file sf_theta.tcc.
Member Function Documentation
__ellnome()
template<typename _Tp_Omega1 , typename _Tp_Omega3 > __jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_Tp_Nome std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__ellnome () const
Return the elliptic nome corresponding to the lattice parameter.
Definition at line 593 of file sf_theta.tcc.
Referenced by std::__detail::__jacobi_theta_0_t< _Tp1, _Tp3 >::__jacobi_theta_0_t(), and std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__omega_3().
__omega_1()
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> _Tp_Omega1 std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__omega_1 () const inline
Return the first lattice frequency.
Definition at line 564 of file sf_theta.tcc.
Referenced by std::__detail::__jacobi_theta_0_t< _Tp1, _Tp3 >::__jacobi_theta_0_t(), and std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::__weierstrass_roots_t().
__omega_2()
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> _Cmplx std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__omega_2 () const inline
Return the second lattice frequency.
Definition at line 569 of file sf_theta.tcc.
Referenced by std::__detail::__jacobi_theta_0_t< _Tp1, _Tp3 >::__jacobi_theta_0_t().
__omega_3()
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> _Tp_Omega3 std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__omega_3 () const inline
Return the third lattice frequency.
Definition at line 574 of file sf_theta.tcc.
Referenced by std::__detail::__jacobi_theta_0_t< _Tp1, _Tp3 >::__jacobi_theta_0_t().
__reduce()
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> __jacobi_lattice_t< _Tp1, _Tp3 >::__arg_t std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__reduce (const _Cmplx & __z) const
Reduce the argument to the fundamental lattice parallelogram . This is sort of like a 2D lattice remquo.
Parameters
__z The argument to be reduced.
Returns
A struct containing the argument reduced to the interior of the fundamental parallelogram and two integers indicating the number of periods in the 'real' and 'tau' directions.
Definition at line 616 of file sf_theta.tcc.
Referenced by std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__ellnome(), std::__detail::__jacobi_theta_1(), std::__detail::__jacobi_theta_2(), std::__detail::__jacobi_theta_3(), std::__detail::__jacobi_theta_4(), and std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__omega_3().
__tau()
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> __tau_t std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::__tau () const inline
Return the acalar lattice parameter or half period ratio.
Definition at line 559 of file sf_theta.tcc.
Referenced by std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__ellnome(), std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__jacobi_lattice_t(), std::__detail::__jacobi_theta_1(), std::__detail::__jacobi_theta_2(), std::__detail::__jacobi_theta_3(), std::__detail::__jacobi_theta_4(), and std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__reduce().
Member Data Documentation
_M_omega_1
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> _Tp_Omega1 std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_M_omega_1
Definition at line 584 of file sf_theta.tcc.
Referenced by std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__jacobi_lattice_t(), std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__omega_1(), std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__omega_2(), and std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__tau().
_M_omega_3
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> _Tp_Omega3 std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_M_omega_3
Definition at line 585 of file sf_theta.tcc.
Referenced by std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__jacobi_lattice_t(), std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__omega_2(), std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__omega_3(), and std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__tau().
_S_pi
template<typename _Tp_Omega1, typename _Tp_Omega3 = std::complex<_Tp_Omega1>> constexpr auto std::__detail::__jacobi_lattice_t< _Tp_Omega1, _Tp_Omega3 >::_S_pi = __gnu_cxx::__const_pi<_Real>() static
Definition at line 583 of file sf_theta.tcc.
Referenced by std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__ellnome(), std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__jacobi_lattice_t(), std::__detail::__jacobi_theta_0_t< _Tp1, _Tp3 >::__jacobi_theta_0_t(), std::__detail::__jacobi_theta_1(), std::__detail::__jacobi_theta_2(), std::__detail::__jacobi_theta_3(), std::__detail::__jacobi_theta_4(), std::__detail::__jacobi_lattice_t< _Tp1, _Tp3 >::__reduce(), and std::__detail::__weierstrass_roots_t< _Tp1, _Tp3 >::__weierstrass_roots_t().
The documentation for this struct was generated from the following file:
include/bits/sf_theta.tcc