TR29124 C++ Special Math Functions: std::__detail::_Airy< _Tp > Class Template Reference
std::__detail::_Airy< _Tp > Class Template Reference
Public Types
using scalar_type = std::__detail::__num_traits_t< value_type >
using value_type = _Tp
Public Member Functions
constexpr _Airy ()=default
_Airy (const _Airy &)=default
_Airy (_Airy &&)=default
constexpr _AiryState< value_type > operator() (value_type __y) const
Public Attributes
scalar_type inner_radius {_Airy_default_radii<scalar_type>::inner_radius}
scalar_type outer_radius {_Airy_default_radii<scalar_type>::outer_radius}
Static Public Attributes
static constexpr scalar_type _S_2pi_3 = scalar_type{2} * _S_pi_3
static constexpr scalar_type _S_5pi_6 = scalar_type{5} * _S_pi_6
static constexpr auto _S_cNaN = value_type(_S_NaN, _S_NaN)
static constexpr value_type _S_i = value_type{0, 1}
static constexpr auto _S_NaN = __gnu_cxx::__quiet_NaN<scalar_type>()
static constexpr scalar_type _S_pi = __gnu_cxx::__math_constants<scalar_type>::__pi
static constexpr scalar_type _S_pi_3 = __gnu_cxx::__math_constants<scalar_type>::__pi_third
static constexpr scalar_type _S_pi_6 = _S_pi_3 / scalar_type{2}
static constexpr scalar_type _S_sqrt_pi = __gnu_cxx::__math_constants<scalar_type>::__root_pi
Detailed Description
template<typename _Tp>
class std::__detail::_Airy< _Tp >
Class to manage the asymptotic expansions for Airy functions. The parameters describing the various regions are adjustable.
Definition at line 2498 of file sf_airy.tcc.
Member Typedef Documentation
template<typename _Tp> using std::__detail::_Airy< _Tp >::scalar_type = std::__detail::__num_traits_t<value_type>
Definition at line 2503 of file sf_airy.tcc.
template<typename _Tp> using std::__detail::_Airy< _Tp >::value_type = _Tp
Definition at line 2502 of file sf_airy.tcc.
Constructor & Destructor Documentation
template<typename _Tp> constexpr std::__detail::_Airy< _Tp >::_Airy () default
template<typename _Tp> std::__detail::_Airy< _Tp >::_Airy (const _Airy< _Tp > &) default
template<typename _Tp> std::__detail::_Airy< _Tp >::_Airy (_Airy< _Tp > &&) default
Member Function Documentation
template<typename _Tp> constexpr _AiryState< _Tp > std::__detail::_Airy< _Tp >::operator() (value_type __y) const
Return the Airy functions for complex argument.
Definition at line 2550 of file sf_airy.tcc.
References std::__detail::__beta(), std::__detail::_Airy_series< _Tp >::_S_Ai(), and std::__detail::_Airy_series< _Tp >::_S_Bi().
Member Data Documentation
template<typename _Tp> constexpr scalar_type std::__detail::_Airy< _Tp >::_S_2pi_3 = scalar_type{2} * _S_pi_3 static
Definition at line 2510 of file sf_airy.tcc.
template<typename _Tp> constexpr scalar_type std::__detail::_Airy< _Tp >::_S_5pi_6 = scalar_type{5} * _S_pi_6 static
Definition at line 2512 of file sf_airy.tcc.
template<typename _Tp> constexpr auto std::__detail::_Airy< _Tp >::_S_cNaN = value_type(_S_NaN, _S_NaN) static
Definition at line 2516 of file sf_airy.tcc.
template<typename _Tp> constexpr _Airy< _Tp >::value_type std::__detail::_Airy< _Tp >::_S_i = value_type{0, 1} static
Definition at line 2513 of file sf_airy.tcc.
template<typename _Tp> constexpr auto std::__detail::_Airy< _Tp >::_S_NaN = __gnu_cxx::__quiet_NaN<scalar_type>() static
Definition at line 2515 of file sf_airy.tcc.
template<typename _Tp> constexpr scalar_type std::__detail::_Airy< _Tp >::_S_pi = __gnu_cxx::__math_constants<scalar_type>::__pi static
Definition at line 2505 of file sf_airy.tcc.
template<typename _Tp> constexpr _Airy< _Tp >::scalar_type std::__detail::_Airy< _Tp >::_S_pi_3 = __gnu_cxx::__math_constants<scalar_type>::__pi_third static
Definition at line 2509 of file sf_airy.tcc.
template<typename _Tp> constexpr _Airy< _Tp >::scalar_type std::__detail::_Airy< _Tp >::_S_pi_6 = _S_pi_3 / scalar_type{2} static
Definition at line 2511 of file sf_airy.tcc.
template<typename _Tp> constexpr _Airy< _Tp >::scalar_type std::__detail::_Airy< _Tp >::_S_sqrt_pi = __gnu_cxx::__math_constants<scalar_type>::__root_pi static
Definition at line 2507 of file sf_airy.tcc.
template<typename _Tp> scalar_type std::__detail::_Airy< _Tp >::inner_radius {_Airy_default_radii<scalar_type>::inner_radius}
Definition at line 2525 of file sf_airy.tcc.
template<typename _Tp> scalar_type std::__detail::_Airy< _Tp >::outer_radius {_Airy_default_radii<scalar_type>::outer_radius}
Definition at line 2526 of file sf_airy.tcc.
The documentation for this class was generated from the following file:
bits/sf_airy.tcc