C++ Special Math Functions: std::__detail::_Airy_series< _Tp > Class Template Reference
std::__detail::_Airy_series< _Tp > Class Template Reference
Public Types
using _Cmplx = std::complex< _Tp >
Static Public Member Functions
static std::pair< _Cmplx, _Cmplx > _S_Ai (_Cmplx __t)
static _AiryState< _Cmplx > _S_Airy (_Cmplx __t)
static std::pair< _Cmplx, _Cmplx > _S_Bi (_Cmplx __t)
static _AiryAuxilliaryState< _Cmplx > _S_FGH (_Cmplx __t)
static _AiryState< _Cmplx > _S_Fock (_Cmplx __t)
static _AiryState< _Cmplx > _S_Scorer (_Cmplx __t)
static _AiryState< _Cmplx > _S_Scorer2 (_Cmplx __t)
Static Public Attributes
static constexpr int _N_FGH = 200
static constexpr _Tp _S_Ai0 = _Tp{3.550280538878172392600631860041831763980e-1L}
static constexpr _Tp _S_Aip0 = _Tp{-2.588194037928067984051835601892039634793e-1L}
static constexpr _Tp _S_Bi0 = _Tp{6.149266274460007351509223690936135535960e-1L}
static constexpr _Tp _S_Bip0 = _Tp{4.482883573538263579148237103988283908668e-1L}
static constexpr _Tp _S_eps = __gnu_cxx::__epsilon(_Tp{})
static constexpr _Tp _S_Gi0 = _Tp{2.049755424820002450503074563645378511979e-1L}
static constexpr _Tp _S_Gip0 = _Tp{1.494294524512754526382745701329427969551e-1L}
static constexpr _Tp _S_Hi0 = _Tp{4.099510849640004901006149127290757023959e-1L}
static constexpr _Tp _S_Hip0 = _Tp{2.988589049025509052765491402658855939102e-1L}
static constexpr _Cmplx _S_i {_Tp{0}, _Tp{1}}
static constexpr _Tp _S_pi = __gnu_cxx::__const_pi(_Tp{})
static constexpr _Tp _S_sqrt_pi = __gnu_cxx::__const_root_pi(_Tp{})
Detailed Description
template<typename _Tp>
class std::__detail::_Airy_series< _Tp >
This class orgianizes series solutions of the Airy function.
This class contains tabulations of the factors appearing in the sums above.
Definition at line 108 of file sf_airy.tcc.
Member Typedef Documentation
template<typename _Tp > using std::__detail::_Airy_series< _Tp >::_Cmplx = std::complex<_Tp>
Definition at line 112 of file sf_airy.tcc.
Member Function Documentation
template<typename _Tp > std::pair< std::complex< _Tp >, std::complex< _Tp > > std::__detail::_Airy_series< _Tp >::_S_Ai (_Cmplx __t) static
Return the Airy function of the first kind and its derivative by using the series expansions of the auxilliary Airy functions:
The Airy function of the first kind is then defined by:
where , and ,
Template Parameters
_Tp A real type
Definition at line 341 of file sf_airy.tcc.
Referenced by std::__detail::_Airy< _Tp >::operator()().
template<typename _Tp > _AiryState< std::complex< _Tp > > std::__detail::_Airy_series< _Tp >::_S_Airy (_Cmplx __t) static
Return the Fock-type Airy functions , and and their derivatives of complex argument.
Template Parameters
_Tp A real type
Parameters
__t The complex argument
Definition at line 609 of file sf_airy.tcc.
template<typename _Tp > std::pair< std::complex< _Tp >, std::complex< _Tp > > std::__detail::_Airy_series< _Tp >::_S_Bi (_Cmplx __t) static
Return the Airy function of the second kind and its derivative by using the series expansions of the auxilliary Airy functions:
The Airy function of the second kind is then defined by:
where , and ,
Template Parameters
_Tp A real type
Definition at line 364 of file sf_airy.tcc.
Referenced by std::__detail::_Airy< _Tp >::operator()().
template<typename _Tp > _AiryAuxilliaryState< std::complex< _Tp > > std::__detail::_Airy_series< _Tp >::_S_FGH (_Cmplx __t) static
Return the auxilliary Airy functions:
Template Parameters
_Tp A real type
Definition at line 383 of file sf_airy.tcc.
template<typename _Tp > _AiryState< std::complex< _Tp > > std::__detail::_Airy_series< _Tp >::_S_Fock (_Cmplx __t) static
Return the Fock-type Airy functions , and and their derivatives of complex argument.
Template Parameters
_Tp A real type
Parameters
__t The complex argument
Definition at line 621 of file sf_airy.tcc.
template<typename _Tp > _AiryState< std::complex< _Tp > > std::__detail::_Airy_series< _Tp >::_S_Scorer (_Cmplx __t) static
Return the Scorer functions by using the series expansions of the auxilliary Airy functions:
The Scorer function is then defined by:
where and . The other Scorer function is found from the identity
Todo:
Find out what is wrong with the Hi = fai + gai + hai scorer function.
Template Parameters
_Tp A real type
Definition at line 464 of file sf_airy.tcc.
template<typename _Tp > _AiryState< std::complex< _Tp > > std::__detail::_Airy_series< _Tp >::_S_Scorer2 (_Cmplx __t) static
Return the Scorer functions by using the series expansions:
Definition at line 501 of file sf_airy.tcc.
References std::__detail::__gamma().
Member Data Documentation
template<typename _Tp > constexpr int std::__detail::_Airy_series< _Tp >::_N_FGH = 200 static
Definition at line 114 of file sf_airy.tcc.
template<typename _Tp > constexpr _Tp std::__detail::_Airy_series< _Tp >::_S_Ai0 = _Tp{3.550280538878172392600631860041831763980e-1L} static
Definition at line 130 of file sf_airy.tcc.
template<typename _Tp > constexpr _Tp std::__detail::_Airy_series< _Tp >::_S_Aip0 = _Tp{-2.588194037928067984051835601892039634793e-1L} static
Definition at line 132 of file sf_airy.tcc.
template<typename _Tp > constexpr _Tp std::__detail::_Airy_series< _Tp >::_S_Bi0 = _Tp{6.149266274460007351509223690936135535960e-1L} static
Definition at line 134 of file sf_airy.tcc.
template<typename _Tp > constexpr _Tp std::__detail::_Airy_series< _Tp >::_S_Bip0 = _Tp{4.482883573538263579148237103988283908668e-1L} static
Definition at line 136 of file sf_airy.tcc.
template<typename _Tp > constexpr _Tp std::__detail::_Airy_series< _Tp >::_S_eps = __gnu_cxx::__epsilon(_Tp{}) static
Definition at line 125 of file sf_airy.tcc.
template<typename _Tp > constexpr _Tp std::__detail::_Airy_series< _Tp >::_S_Gi0 = _Tp{2.049755424820002450503074563645378511979e-1L} static
Definition at line 142 of file sf_airy.tcc.
template<typename _Tp > constexpr _Tp std::__detail::_Airy_series< _Tp >::_S_Gip0 = _Tp{1.494294524512754526382745701329427969551e-1L} static
Definition at line 144 of file sf_airy.tcc.
template<typename _Tp > constexpr _Tp std::__detail::_Airy_series< _Tp >::_S_Hi0 = _Tp{4.099510849640004901006149127290757023959e-1L} static
Definition at line 138 of file sf_airy.tcc.
template<typename _Tp > constexpr _Tp std::__detail::_Airy_series< _Tp >::_S_Hip0 = _Tp{2.988589049025509052765491402658855939102e-1L} static
Definition at line 140 of file sf_airy.tcc.
template<typename _Tp > constexpr std::complex< _Tp > std::__detail::_Airy_series< _Tp >::_S_i {_Tp{0}, _Tp{1}} static
Definition at line 145 of file sf_airy.tcc.
template<typename _Tp > constexpr _Tp std::__detail::_Airy_series< _Tp >::_S_pi = __gnu_cxx::__const_pi(_Tp{}) static
Definition at line 126 of file sf_airy.tcc.
template<typename _Tp > constexpr _Tp std::__detail::_Airy_series< _Tp >::_S_sqrt_pi = __gnu_cxx::__const_root_pi(_Tp{}) static
Definition at line 128 of file sf_airy.tcc.
The documentation for this class was generated from the following file:
bits/sf_airy.tcc