TR29124 C++ Special Math Functions: __gnu_cxx Namespace Reference
__gnu_cxx Namespace Reference
Enumerations
enum { _GLIBCXX_JACOBI_SN, _GLIBCXX_JACOBI_CN, _GLIBCXX_JACOBI_DN }
Functions
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > airy_ai (_Tp __x)
float airy_aif (float __x)
long double airy_ail (long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > airy_bi (_Tp __x)
float airy_bif (float __x)
long double airy_bil (long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > bernoulli (unsigned int __n)
float bernoullif (unsigned int __n)
long double bernoullil (unsigned int __n)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > bincoef (unsigned int __n, unsigned int __k)
float bincoeff (unsigned int __n, unsigned int __k)
long double bincoefl (unsigned int __n, unsigned int __k)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > chebyshev_t (unsigned int __n, _Tp __x)
float chebyshev_tf (unsigned int __n, float __x)
long double chebyshev_tl (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > chebyshev_u (unsigned int __n, _Tp __x)
float chebyshev_uf (unsigned int __n, float __x)
long double chebyshev_ul (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > chebyshev_v (unsigned int __n, _Tp __x)
float chebyshev_vf (unsigned int __n, float __x)
long double chebyshev_vl (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > chebyshev_w (unsigned int __n, _Tp __x)
float chebyshev_wf (unsigned int __n, float __x)
long double chebyshev_wl (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > clausen (unsigned int __m, _Tp __w)
template<typename _Tp >
std::complex< __gnu_cxx::__promote_num_t< _Tp > > clausen (unsigned int __m, std::complex< _Tp > __w)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > clausen_c (unsigned int __m, _Tp __w)
float clausen_cf (unsigned int __m, float __w)
long double clausen_cl (unsigned int __m, long double __w)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > clausen_s (unsigned int __m, _Tp __w)
float clausen_sf (unsigned int __m, float __w)
long double clausen_sl (unsigned int __m, long double __w)
float clausenf (unsigned int __m, float __w)
std::complex< float > clausenf (unsigned int __m, std::complex< float > __w)
long double clausenl (unsigned int __m, long double __w)
std::complex< long double > clausenl (unsigned int __m, std::complex< long double > __w)
template<typename _Tk >
__gnu_cxx::__promote_num_t< _Tk > comp_ellint_d (_Tk __k)
float comp_ellint_df (float __k)
long double comp_ellint_dl (long double __k)
float comp_ellint_rf (float __x, float __y)
long double comp_ellint_rf (long double __x, long double __y)
template<typename _Tx , typename _Ty >
__gnu_cxx::__promote_num_t< _Tx, _Ty > comp_ellint_rf (_Tx __x, _Ty __y)
float comp_ellint_rg (float __x, float __y)
long double comp_ellint_rg (long double __x, long double __y)
template<typename _Tx , typename _Ty >
__gnu_cxx::__promote_num_t< _Tx, _Ty > comp_ellint_rg (_Tx __x, _Ty __y)
template<typename _Tpa , typename _Tpc , typename _Tp >
__gnu_cxx::__promote_3< _Tpa, _Tpc, _Tp >::__type conf_hyperg (_Tpa __a, _Tpc __c, _Tp __x)
template<typename _Tpc , typename _Tp >
__gnu_cxx::__promote_2< _Tpc, _Tp >::__type conf_hyperg_lim (_Tpc __c, _Tp __x)
float conf_hyperg_limf (float __c, float __x)
long double conf_hyperg_liml (long double __c, long double __x)
float conf_hypergf (float __a, float __c, float __x)
long double conf_hypergl (long double __a, long double __c, long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > coshint (_Tp __x)
float coshintf (float __x)
long double coshintl (long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > cosint (_Tp __x)
float cosintf (float __x)
long double cosintl (long double __x)
template<typename _Tpnu , typename _Tp >
std::complex< __gnu_cxx::__promote_num_t< _Tpnu, _Tp > > cyl_hankel_1 (_Tpnu __nu, _Tp __z)
template<typename _Tpnu , typename _Tp >
std::complex< __gnu_cxx::__promote_num_t< _Tpnu, _Tp > > cyl_hankel_1 (std::complex< _Tpnu > __nu, std::complex< _Tp > __x)
std::complex< float > cyl_hankel_1f (float __nu, float __z)
std::complex< float > cyl_hankel_1f (std::complex< float > __nu, std::complex< float > __x)
std::complex< long double > cyl_hankel_1l (long double __nu, long double __z)
std::complex< long double > cyl_hankel_1l (std::complex< long double > __nu, std::complex< long double > __x)
template<typename _Tpnu , typename _Tp >
std::complex< __gnu_cxx::__promote_num_t< _Tpnu, _Tp > > cyl_hankel_2 (_Tpnu __nu, _Tp __z)
template<typename _Tpnu , typename _Tp >
std::complex< __gnu_cxx::__promote_num_t< _Tpnu, _Tp > > cyl_hankel_2 (std::complex< _Tpnu > __nu, std::complex< _Tp > __x)
std::complex< float > cyl_hankel_2f (float __nu, float __z)
std::complex< float > cyl_hankel_2f (std::complex< float > __nu, std::complex< float > __x)
std::complex< long double > cyl_hankel_2l (long double __nu, long double __z)
std::complex< long double > cyl_hankel_2l (std::complex< long double > __nu, std::complex< long double > __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > dawson (_Tp __x)
float dawsonf (float __x)
long double dawsonl (long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > digamma (_Tp __z)
float digammaf (float __z)
long double digammal (long double __z)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > dilog (_Tp __x)
float dilogf (float __x)
long double dilogl (long double __x)
template<typename _Tp >
_Tp dirichlet_beta (_Tp __x)
float dirichlet_betaf (float __x)
long double dirichlet_betal (long double __x)
template<typename _Tp >
_Tp dirichlet_eta (_Tp __x)
float dirichlet_etaf (float __x)
long double dirichlet_etal (long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > double_factorial (int __n)
float double_factorialf (int __n)
long double double_factoriall (int __n)
template<typename _Tk , typename _Tp , typename _Ta , typename _Tb >
__gnu_cxx::__promote_num_t< _Tk, _Tp, _Ta, _Tb > ellint_cel (_Tk __k_c, _Tp __p, _Ta __a, _Tb __b)
float ellint_celf (float __k_c, float __p, float __a, float __b)
long double ellint_cell (long double __k_c, long double __p, long double __a, long double __b)
template<typename _Tk , typename _Tphi >
__gnu_cxx::__promote_num_t< _Tk, _Tphi > ellint_d (_Tk __k, _Tphi __phi)
float ellint_df (float __k, float __phi)
long double ellint_dl (long double __k, long double __phi)
template<typename _Tp , typename _Tk >
__gnu_cxx::__promote_num_t< _Tp, _Tk > ellint_el1 (_Tp __x, _Tk __k_c)
float ellint_el1f (float __x, float __k_c)
long double ellint_el1l (long double __x, long double __k_c)
template<typename _Tp , typename _Tk , typename _Ta , typename _Tb >
__gnu_cxx::__promote_num_t< _Tp, _Tk, _Ta, _Tb > ellint_el2 (_Tp __x, _Tk __k_c, _Ta __a, _Tb __b)
float ellint_el2f (float __x, float __k_c, float __a, float __b)
long double ellint_el2l (long double __x, long double __k_c, long double __a, long double __b)
template<typename _Tx , typename _Tk , typename _Tp >
__gnu_cxx::__promote_num_t< _Tx, _Tk, _Tp > ellint_el3 (_Tx __x, _Tk __k_c, _Tp __p)
float ellint_el3f (float __x, float __k_c, float __p)
long double ellint_el3l (long double __x, long double __k_c, long double __p)
template<typename _Tp , typename _Up >
__gnu_cxx::__promote_num_t< _Tp, _Up > ellint_rc (_Tp __x, _Up __y)
float ellint_rcf (float __x, float __y)
long double ellint_rcl (long double __x, long double __y)
template<typename _Tp , typename _Up , typename _Vp >
__gnu_cxx::__promote_num_t< _Tp, _Up, _Vp > ellint_rd (_Tp __x, _Up __y, _Vp __z)
float ellint_rdf (float __x, float __y, float __z)
long double ellint_rdl (long double __x, long double __y, long double __z)
template<typename _Tp , typename _Up , typename _Vp >
__gnu_cxx::__promote_num_t< _Tp, _Up, _Vp > ellint_rf (_Tp __x, _Up __y, _Vp __z)
float ellint_rff (float __x, float __y, float __z)
long double ellint_rfl (long double __x, long double __y, long double __z)
template<typename _Tp , typename _Up , typename _Vp >
__gnu_cxx::__promote_num_t< _Tp, _Up, _Vp > ellint_rg (_Tp __x, _Up __y, _Vp __z)
float ellint_rgf (float __x, float __y, float __z)
long double ellint_rgl (long double __x, long double __y, long double __z)
template<typename _Tp , typename _Up , typename _Vp , typename _Wp >
__gnu_cxx::__promote_num_t< _Tp, _Up, _Vp, _Wp > ellint_rj (_Tp __x, _Up __y, _Vp __z, _Wp __p)
float ellint_rjf (float __x, float __y, float __z, float __p)
long double ellint_rjl (long double __x, long double __y, long double __z, long double __p)
template<typename _Tp >
_Tp ellnome (_Tp __k)
float ellnomef (float __k)
long double ellnomel (long double __k)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > expint_e1 (_Tp __x)
float expint_e1f (float __x)
long double expint_e1l (long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > expint_en (unsigned int __n, _Tp __x)
float expint_enf (unsigned int __n, float __x)
long double expint_enl (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > factorial (unsigned int __n)
float factorialf (unsigned int __n)
long double factoriall (unsigned int __n)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > fresnel_c (_Tp __x)
float fresnel_cf (float __x)
long double fresnel_cl (long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > fresnel_s (_Tp __x)
float fresnel_sf (float __x)
long double fresnel_sl (long double __x)
template<typename _Tn , typename _Tp >
__gnu_cxx::__promote_num_t< _Tn, _Tp > gamma_l (_Tn __n, _Tp __x)
float gamma_lf (float __n, float __x)
long double gamma_ll (long double __n, long double __x)
template<typename _Ta , typename _Tp >
__gnu_cxx::__promote_num_t< _Ta, _Tp > gamma_p (_Ta __a, _Tp __x)
float gamma_pf (float __a, float __x)
long double gamma_pl (long double __a, long double __x)
template<typename _Ta , typename _Tp >
__gnu_cxx::__promote_num_t< _Ta, _Tp > gamma_q (_Ta __a, _Tp __x)
float gamma_qf (float __a, float __x)
long double gamma_ql (long double __a, long double __x)
template<typename _Tn , typename _Tp >
__gnu_cxx::__promote_num_t< _Tn, _Tp > gamma_u (_Tn __n, _Tp __x)
float gamma_uf (float __n, float __x)
long double gamma_ul (long double __n, long double __x)
template<typename _Talpha , typename _Tp >
__gnu_cxx::__promote_num_t< _Talpha, _Tp > gegenbauer (unsigned int __n, _Talpha __alpha, _Tp __x)
float gegenbauerf (unsigned int __n, float __alpha, float __x)
long double gegenbauerl (unsigned int __n, long double __alpha, long double __x)
template<typename _Tk , typename _Tphi >
__gnu_cxx::__promote_num_t< _Tk, _Tphi > heuman_lambda (_Tk __k, _Tphi __phi)
float heuman_lambdaf (float __k, float __phi)
long double heuman_lambdal (long double __k, long double __phi)
template<typename _Tp , typename _Up >
__gnu_cxx::__promote_num_t< _Tp, _Up > hurwitz_zeta (_Tp __s, _Up __a)
float hurwitz_zetaf (float __s, float __a)
long double hurwitz_zetal (long double __s, long double __a)
template<typename _Tpa , typename _Tpb , typename _Tpc , typename _Tp >
__gnu_cxx::__promote_4< _Tpa, _Tpb, _Tpc, _Tp >::__type hyperg (_Tpa __a, _Tpb __b, _Tpc __c, _Tp __x)
float hypergf (float __a, float __b, float __c, float __x)
long double hypergl (long double __a, long double __b, long double __c, long double __x)
template<typename _Ta , typename _Tb , typename _Tp >
__gnu_cxx::__promote_num_t< _Ta, _Tb, _Tp > ibeta (_Ta __a, _Tb __b, _Tp __x)
template<typename _Ta , typename _Tb , typename _Tp >
__gnu_cxx::__promote_num_t< _Ta, _Tb, _Tp > ibetac (_Ta __a, _Tb __b, _Tp __x)
float ibetacf (float __a, float __b, float __x)
long double ibetacl (long double __a, long double __b, long double __x)
float ibetaf (float __a, float __b, float __x)
long double ibetal (long double __a, long double __b, long double __x)
template<typename _Talpha , typename _Tbeta , typename _Tp >
__gnu_cxx::__promote_num_t< _Talpha, _Tbeta, _Tp > jacobi (unsigned __n, _Talpha __alpha, _Tbeta __beta, _Tp __x)
template<typename _Kp , typename _Up >
__gnu_cxx::__promote_num_t< _Kp, _Up > jacobi_cn (_Kp __k, _Up __u)
float jacobi_cnf (float __k, float __u)
long double jacobi_cnl (long double __k, long double __u)
template<typename _Kp , typename _Up >
__gnu_cxx::__promote_num_t< _Kp, _Up > jacobi_dn (_Kp __k, _Up __u)
float jacobi_dnf (float __k, float __u)
long double jacobi_dnl (long double __k, long double __u)
template<typename _Kp , typename _Up >
__gnu_cxx::__promote_num_t< _Kp, _Up > jacobi_sn (_Kp __k, _Up __u)
float jacobi_snf (float __k, float __u)
long double jacobi_snl (long double __k, long double __u)
template<typename _Tk , typename _Tphi >
__gnu_cxx::__promote_num_t< _Tk, _Tphi > jacobi_zeta (_Tk __k, _Tphi __phi)
float jacobi_zetaf (float __k, float __phi)
long double jacobi_zetal (long double __k, long double __phi)
float jacobif (unsigned __n, float __alpha, float __beta, float __x)
long double jacobil (unsigned __n, long double __alpha, long double __beta, long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > lbincoef (unsigned int __n, unsigned int __k)
float lbincoeff (unsigned int __n, unsigned int __k)
long double lbincoefl (unsigned int __n, unsigned int __k)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > ldouble_factorial (int __n)
float ldouble_factorialf (int __n)
long double ldouble_factoriall (int __n)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > legendre_q (unsigned int __n, _Tp __x)
float legendre_qf (unsigned int __n, float __x)
long double legendre_ql (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > lfactorial (unsigned int __n)
float lfactorialf (unsigned int __n)
long double lfactoriall (unsigned int __n)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > logint (_Tp __x)
float logintf (float __x)
long double logintl (long double __x)
template<typename _Tp , typename _Tn >
__gnu_cxx::__promote_num_t< _Tp, _Tn > lpochhammer_l (_Tp __a, _Tn __n)
float lpochhammer_lf (float __a, float __n)
long double lpochhammer_ll (long double __a, long double __n)
template<typename _Tp , typename _Tn >
__gnu_cxx::__promote_num_t< _Tp, _Tn > lpochhammer_u (_Tp __a, _Tn __n)
float lpochhammer_uf (float __a, float __n)
long double lpochhammer_ul (long double __a, long double __n)
template<typename _Tph , typename _Tpa >
__gnu_cxx::__promote_num_t< _Tph, _Tpa > owens_t (_Tph __h, _Tpa __a)
float owens_tf (float __h, float __a)
long double owens_tl (long double __h, long double __a)
template<typename _Tp , typename _Tn >
__gnu_cxx::__promote_num_t< _Tp, _Tn > pochhammer_l (_Tp __a, _Tn __n)
float pochhammer_lf (float __a, float __n)
long double pochhammer_ll (long double __a, long double __n)
template<typename _Tp , typename _Tn >
__gnu_cxx::__promote_num_t< _Tp, _Tn > pochhammer_u (_Tp __a, _Tn __n)
float pochhammer_uf (float __a, float __n)
long double pochhammer_ul (long double __a, long double __n)
template<typename _Tp >
std::complex< __gnu_cxx::__promote_num_t< _Tp > > polylog (_Tp __s, std::complex< _Tp > __w)
std::complex< float > polylogf (float __s, std::complex< float > __w)
std::complex< long double > polylogl (long double __s, std::complex< long double > __w)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > psi (_Tp __x)
float psif (float __x)
long double psil (long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > radpoly (unsigned int __n, unsigned int __m, _Tp __rho)
float radpolyf (unsigned int __n, unsigned int __m, float __rho)
long double radpolyl (unsigned int __n, unsigned int __m, long double __rho)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > sinc (_Tp __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > sinc_pi (_Tp __x)
float sinc_pif (float __x)
long double sinc_pil (long double __x)
float sincf (float __x)
long double sincl (long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > sinhc (_Tp __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > sinhc_pi (_Tp __x)
float sinhc_pif (float __x)
long double sinhc_pil (long double __x)
float sinhcf (float __x)
long double sinhcl (long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > sinhint (_Tp __x)
float sinhintf (float __x)
long double sinhintl (long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > sinint (_Tp __x)
float sinintf (float __x)
long double sinintl (long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > sph_bessel_i (unsigned int __n, _Tp __x)
float sph_bessel_if (unsigned int __n, float __x)
long double sph_bessel_il (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::__promote_num_t< _Tp > sph_bessel_k (unsigned int __n, _Tp __x)
float sph_bessel_kf (unsigned int __n, float __x)
long double sph_bessel_kl (unsigned int __n, long double __x)
template<typename _Tp >
std::complex< __gnu_cxx::__promote_num_t< _Tp > > sph_hankel_1 (unsigned int __n, _Tp __z)
template<typename _Tp >
std::complex< __gnu_cxx::__promote_num_t< _Tp > > sph_hankel_1 (unsigned int __n, std::complex< _Tp > __x)
std::complex< float > sph_hankel_1f (unsigned int __n, float __z)
std::complex< float > sph_hankel_1f (unsigned int __n, std::complex< float > __x)
std::complex< long double > sph_hankel_1l (unsigned int __n, long double __z)
std::complex< long double > sph_hankel_1l (unsigned int __n, std::complex< long double > __x)
template<typename _Tp >
std::complex< __gnu_cxx::__promote_num_t< _Tp > > sph_hankel_2 (unsigned int __n, _Tp __z)
template<typename _Tp >
std::complex< __gnu_cxx::__promote_num_t< _Tp > > sph_hankel_2 (unsigned int __n, std::complex< _Tp > __x)
std::complex< float > sph_hankel_2f (unsigned int __n, float __z)
std::complex< float > sph_hankel_2f (unsigned int __n, std::complex< float > __x)
std::complex< long double > sph_hankel_2l (unsigned int __n, long double __z)
std::complex< long double > sph_hankel_2l (unsigned int __n, std::complex< long double > __x)
template<typename _Ttheta , typename _Tphi >
std::complex< __gnu_cxx::__promote_num_t< _Ttheta, _Tphi > > sph_harmonic (unsigned int __l, int __m, _Ttheta __theta, _Tphi __phi)
std::complex< float > sph_harmonicf (unsigned int __l, int __m, float __theta, float __phi)
std::complex< long double > sph_harmonicl (unsigned int __l, int __m, long double __theta, long double __phi)
template<typename _Tpnu , typename _Tp >
__gnu_cxx::__promote_num_t< _Tpnu, _Tp > theta_1 (_Tpnu __nu, _Tp __x)
float theta_1f (float __nu, float __x)
long double theta_1l (long double __nu, long double __x)
template<typename _Tpnu , typename _Tp >
__gnu_cxx::__promote_num_t< _Tpnu, _Tp > theta_2 (_Tpnu __nu, _Tp __x)
float theta_2f (float __nu, float __x)
long double theta_2l (long double __nu, long double __x)
template<typename _Tpnu , typename _Tp >
__gnu_cxx::__promote_num_t< _Tpnu, _Tp > theta_3 (_Tpnu __nu, _Tp __x)
float theta_3f (float __nu, float __x)
long double theta_3l (long double __nu, long double __x)
template<typename _Tpnu , typename _Tp >
__gnu_cxx::__promote_num_t< _Tpnu, _Tp > theta_4 (_Tpnu __nu, _Tp __x)
float theta_4f (float __nu, float __x)
long double theta_4l (long double __nu, long double __x)
template<typename _Tpk , typename _Tp >
__gnu_cxx::__promote_num_t< _Tpk, _Tp > theta_c (_Tpk __k, _Tp __x)
float theta_cf (float __k, float __x)
long double theta_cl (long double __k, long double __x)
template<typename _Tpk , typename _Tp >
__gnu_cxx::__promote_num_t< _Tpk, _Tp > theta_d (_Tpk __k, _Tp __x)
float theta_df (float __k, float __x)
long double theta_dl (long double __k, long double __x)
template<typename _Tpk , typename _Tp >
__gnu_cxx::__promote_num_t< _Tpk, _Tp > theta_n (_Tpk __k, _Tp __x)
float theta_nf (float __k, float __x)
long double theta_nl (long double __k, long double __x)
template<typename _Tpk , typename _Tp >
__gnu_cxx::__promote_num_t< _Tpk, _Tp > theta_s (_Tpk __k, _Tp __x)
float theta_sf (float __k, float __x)
long double theta_sl (long double __k, long double __x)
template<typename _Trho , typename _Tphi >
__gnu_cxx::__promote_num_t< _Trho, _Tphi > zernike (unsigned int __n, int __m, _Trho __rho, _Tphi __phi)
float zernikef (unsigned int __n, int __m, float __rho, float __phi)
long double zernikel (unsigned int __n, int __m, long double __rho, long double __phi)
Enumeration Type Documentation
anonymous enum
Enumerator
_GLIBCXX_JACOBI_SN
_GLIBCXX_JACOBI_CN
_GLIBCXX_JACOBI_DN
Definition at line 1205 of file specfun.h.
Function Documentation
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::airy_ai (_Tp __x) inline
Definition at line 1819 of file specfun.h.
float __gnu_cxx::airy_aif (float __x) inline
Definition at line 1799 of file specfun.h.
long double __gnu_cxx::airy_ail (long double __x) inline
Definition at line 1807 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::airy_bi (_Tp __x) inline
Definition at line 1850 of file specfun.h.
float __gnu_cxx::airy_bif (float __x) inline
Definition at line 1830 of file specfun.h.
long double __gnu_cxx::airy_bil (long double __x) inline
Definition at line 1838 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::bernoulli (unsigned int __n) inline
Return the Bernoulli number of integer order n.
The Bernoulli numbers are defined by
Parameters
__n The order.
Definition at line 2564 of file specfun.h.
float __gnu_cxx::bernoullif (unsigned int __n) inline
Definition at line 2545 of file specfun.h.
long double __gnu_cxx::bernoullil (unsigned int __n) inline
Definition at line 2549 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::bincoef (unsigned int __n, unsigned int __k) inline
Definition at line 2515 of file specfun.h.
float __gnu_cxx::bincoeff (unsigned int __n, unsigned int __k) inline
Definition at line 2503 of file specfun.h.
long double __gnu_cxx::bincoefl (unsigned int __n, unsigned int __k) inline
Definition at line 2507 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::chebyshev_t (unsigned int __n, _Tp __x) inline
Return the Chebyshev polynomials of the first kind of order n and argument x.
The Chebyshev polynomials of the first kind is defined by
Parameters
__n
__x
Definition at line 1386 of file specfun.h.
float __gnu_cxx::chebyshev_tf (unsigned int __n, float __x) inline
Return the Chebyshev polynomials of the first kind of order n and argument x.
See also
chebyshev_t for details.
Definition at line 1359 of file specfun.h.
long double __gnu_cxx::chebyshev_tl (unsigned int __n, long double __x) inline
Return the Chebyshev polynomials of the first kind of order n and argument x.
See also
chebyshev_t for details.
Definition at line 1369 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::chebyshev_u (unsigned int __n, _Tp __x) inline
Return the Chebyshev polynomials of the second kind of order n and argument x.
The Chebyshev polynomials of the second kind is defined by
Parameters
__n
__x
Definition at line 1428 of file specfun.h.
float __gnu_cxx::chebyshev_uf (unsigned int __n, float __x) inline
Return the Chebyshev polynomials of the second kind of order n and argument x.
See also
chebyshev_u for details.
Definition at line 1401 of file specfun.h.
long double __gnu_cxx::chebyshev_ul (unsigned int __n, long double __x) inline
Return the Chebyshev polynomials of the second kind of order n and argument x.
See also
chebyshev_u for details.
Definition at line 1411 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::chebyshev_v (unsigned int __n, _Tp __x) inline
Return the Chebyshev polynomials of the third kind of order n and argument x.
The Chebyshev polynomials of the third kind is defined by
Parameters
__n
__x
Definition at line 1470 of file specfun.h.
float __gnu_cxx::chebyshev_vf (unsigned int __n, float __x) inline
Return the Chebyshev polynomials of the third kind of order n and argument x.
See also
chebyshev_v for details.
Definition at line 1443 of file specfun.h.
long double __gnu_cxx::chebyshev_vl (unsigned int __n, long double __x) inline
Return the Chebyshev polynomials of the third kind of order n and argument x.
See also
chebyshev_v for details.
Definition at line 1453 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::chebyshev_w (unsigned int __n, _Tp __x) inline
Return the Chebyshev polynomials of the fourth kind of order n and argument x.
The Chebyshev polynomials of the fourth kind is defined by
Parameters
__n
__x
Definition at line 1512 of file specfun.h.
float __gnu_cxx::chebyshev_wf (unsigned int __n, float __x) inline
Return the Chebyshev polynomials of the fourth kind of order n and argument x.
See also
chebyshev_w for details.
Definition at line 1485 of file specfun.h.
long double __gnu_cxx::chebyshev_wl (unsigned int __n, long double __x) inline
Return the Chebyshev polynomials of the fourth kind of order n and argument x.
See also
chebyshev_w for details.
Definition at line 1495 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::clausen (unsigned int __m, _Tp __w) inline
Return the Clausen function of integer order m and complex argument w.
The Clausen function is defined by
Parameters
__m
__w The complex argument
Definition at line 3284 of file specfun.h.
template<typename _Tp > std::complex<__gnu_cxx::__promote_num_t<_Tp> > __gnu_cxx::clausen (unsigned int __m, std::complex< _Tp > __w) inline
Definition at line 3305 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::clausen_c (unsigned int __m, _Tp __w) inline
Return the Clausen cosine function of order m and real argument x.
The Clausen cosine function is defined by
Parameters
__m
__w
Definition at line 3245 of file specfun.h.
float __gnu_cxx::clausen_cf (unsigned int __m, float __w) inline
Return the Clausen cosine function of order m and real argument x.
See also
clausen_c for details.
Definition at line 3220 of file specfun.h.
long double __gnu_cxx::clausen_cl (unsigned int __m, long double __w) inline
Return the Clausen cosine function of order m and real argument x.
See also
clausen_c for details.
Definition at line 3229 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::clausen_s (unsigned int __m, _Tp __w) inline
Return the Clausen sine function of order m and real argument x.
The Clausen sine function is defined by
Parameters
__m
__w
Definition at line 3206 of file specfun.h.
float __gnu_cxx::clausen_sf (unsigned int __m, float __w) inline
Return the Clausen sine function of order m and real argument x.
See also
clausen_s for details.
Definition at line 3181 of file specfun.h.
long double __gnu_cxx::clausen_sl (unsigned int __m, long double __w) inline
Return the Clausen sine function of order m and real argument x.
See also
clausen_s for details.
Definition at line 3190 of file specfun.h.
float __gnu_cxx::clausenf (unsigned int __m, float __w) inline
Return the Clausen function of integer order m and complex argument w.
See also
clausen for details.
Definition at line 3259 of file specfun.h.
std::complex<float> __gnu_cxx::clausenf (unsigned int __m, std::complex< float > __w) inline
Definition at line 3293 of file specfun.h.
long double __gnu_cxx::clausenl (unsigned int __m, long double __w) inline
Return the Clausen function of integer order m and complex argument w.
See also
clausen for details.
Definition at line 3268 of file specfun.h.
std::complex<long double> __gnu_cxx::clausenl (unsigned int __m, std::complex< long double > __w) inline
Definition at line 3297 of file specfun.h.
template<typename _Tk > __gnu_cxx::__promote_num_t<_Tk> __gnu_cxx::comp_ellint_d (_Tk __k) inline
Return the complete Legendre elliptic integral D of k and .
The complete Legendre elliptic integral D is defined by
Parameters
__k The
__phi The
Definition at line 2713 of file specfun.h.
float __gnu_cxx::comp_ellint_df (float __k) inline
Definition at line 2693 of file specfun.h.
long double __gnu_cxx::comp_ellint_dl (long double __k) inline
Definition at line 2697 of file specfun.h.
float __gnu_cxx::comp_ellint_rf (float __x, float __y) inline
Definition at line 1945 of file specfun.h.
long double __gnu_cxx::comp_ellint_rf (long double __x, long double __y) inline
Definition at line 1949 of file specfun.h.
template<typename _Tx , typename _Ty > __gnu_cxx::__promote_num_t<_Tx, _Ty> __gnu_cxx::comp_ellint_rf (_Tx __x, _Ty __y) inline
Definition at line 1957 of file specfun.h.
float __gnu_cxx::comp_ellint_rg (float __x, float __y) inline
Definition at line 2050 of file specfun.h.
long double __gnu_cxx::comp_ellint_rg (long double __x, long double __y) inline
Definition at line 2054 of file specfun.h.
template<typename _Tx , typename _Ty > __gnu_cxx::__promote_num_t<_Tx, _Ty> __gnu_cxx::comp_ellint_rg (_Tx __x, _Ty __y) inline
Definition at line 2062 of file specfun.h.
template<typename _Tpa , typename _Tpc , typename _Tp > __gnu_cxx::__promote_3<_Tpa, _Tpc, _Tp>::__type __gnu_cxx::conf_hyperg (_Tpa __a, _Tpc __c, _Tp __x) inline
Return the confluent hypergeometric function of numeratorial parameter a, denominatorial parameter c, and argument x.
The confluent hypergeometric function is defined by
Parameters
__a
__c
__x
Definition at line 885 of file specfun.h.
template<typename _Tpc , typename _Tp > __gnu_cxx::__promote_2<_Tpc, _Tp>::__type __gnu_cxx::conf_hyperg_lim (_Tpc __c, _Tp __x) inline
Return the confluent hypergeometric limit function of numeratorial parameter a and argument x.
The confluent hypergeometric limit function is defined by
Parameters
__c
__x
Definition at line 974 of file specfun.h.
float __gnu_cxx::conf_hyperg_limf (float __c, float __x) inline
Return the confluent hypergeometric limit function of numeratorial parameter a and argument x.
See also
conf_hyperg_lim for details.
Definition at line 947 of file specfun.h.
long double __gnu_cxx::conf_hyperg_liml (long double __c, long double __x) inline
Return the confluent hypergeometric limit function of numeratorial parameter a and argument x.
See also
conf_hyperg_lim for details.
Definition at line 957 of file specfun.h.
float __gnu_cxx::conf_hypergf (float __a, float __c, float __x) inline
Return the confluent hypergeometric function of numeratorial parameter a, denominatorial parameter c, and argument x.
See also
conf_hyperg for details.
Definition at line 857 of file specfun.h.
long double __gnu_cxx::conf_hypergl (long double __a, long double __c, long double __x) inline
Return the confluent hypergeometric function of numeratorial parameter a, denominatorial parameter c, and argument x.
See also
conf_hyperg for details.
Definition at line 867 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::coshint (_Tp __x) inline
Return the hyperbolic cosine integral of argument x.
The hyperbolic cosine integral is defined by
Parameters
__x
Definition at line 1198 of file specfun.h.
float __gnu_cxx::coshintf (float __x) inline
Definition at line 1174 of file specfun.h.
long double __gnu_cxx::coshintl (long double __x) inline
Return the hyperbolic cosine integral of argument x.
See also
coshint for details.
Definition at line 1183 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::cosint (_Tp __x) inline
Return the cosine integral of argument x.
The cosine integral is defined by
Parameters
__x
Definition at line 1127 of file specfun.h.
float __gnu_cxx::cosintf (float __x) inline
Return the cosine integral of argument x.
See also
cosint for details.
Definition at line 1103 of file specfun.h.
long double __gnu_cxx::cosintl (long double __x) inline
Return the cosine integral of argument x.
See also
cosint for details.
Definition at line 1112 of file specfun.h.
template<typename _Tpnu , typename _Tp > std::complex<__gnu_cxx::__promote_num_t<_Tpnu, _Tp> > __gnu_cxx::cyl_hankel_1 (_Tpnu __nu, _Tp __z) inline
Definition at line 1659 of file specfun.h.
template<typename _Tpnu , typename _Tp > std::complex<__gnu_cxx::__promote_num_t<_Tpnu, _Tp> > __gnu_cxx::cyl_hankel_1 (std::complex< _Tpnu > __nu, std::complex< _Tp > __x) inline
Return the complex cylindrical Hankel function of the first kind of complex order and complex argument x.
The cylindrical Hankel function of the first kind is defined by
Parameters
__nu The complex order
__x The complex argument
Definition at line 2907 of file specfun.h.
std::complex<float> __gnu_cxx::cyl_hankel_1f (float __nu, float __z) inline
Definition at line 1647 of file specfun.h.
std::complex<float> __gnu_cxx::cyl_hankel_1f (std::complex< float > __nu, std::complex< float > __x) inline
Return the complex cylindrical Hankel function of the first kind of complex order and complex argument x.
See also
cyl_hankel_1 for more details.
Definition at line 2880 of file specfun.h.
std::complex<long double> __gnu_cxx::cyl_hankel_1l (long double __nu, long double __z) inline
Definition at line 1651 of file specfun.h.
std::complex<long double> __gnu_cxx::cyl_hankel_1l (std::complex< long double > __nu, std::complex< long double > __x) inline
Return the complex cylindrical Hankel function of the first kind of complex order and complex argument x.
See also
cyl_hankel_1 for more details.
Definition at line 2890 of file specfun.h.
template<typename _Tpnu , typename _Tp > std::complex<__gnu_cxx::__promote_num_t<_Tpnu, _Tp> > __gnu_cxx::cyl_hankel_2 (_Tpnu __nu, _Tp __z) inline
Definition at line 1680 of file specfun.h.
template<typename _Tpnu , typename _Tp > std::complex<__gnu_cxx::__promote_num_t<_Tpnu, _Tp> > __gnu_cxx::cyl_hankel_2 (std::complex< _Tpnu > __nu, std::complex< _Tp > __x) inline
Return the complex cylindrical Hankel function of the second kind of complex order and complex argument x.
The cylindrical Hankel function of the second kind is defined by
Parameters
__nu The complex order
__x The complex argument
Definition at line 2949 of file specfun.h.
std::complex<float> __gnu_cxx::cyl_hankel_2f (float __nu, float __z) inline
Definition at line 1668 of file specfun.h.
std::complex<float> __gnu_cxx::cyl_hankel_2f (std::complex< float > __nu, std::complex< float > __x) inline
Return the complex cylindrical Hankel function of the second kind of complex order and complex argument x.
See also
cyl_hankel_2 for more details.
Definition at line 2922 of file specfun.h.
std::complex<long double> __gnu_cxx::cyl_hankel_2l (long double __nu, long double __z) inline
Definition at line 1672 of file specfun.h.
std::complex<long double> __gnu_cxx::cyl_hankel_2l (std::complex< long double > __nu, std::complex< long double > __x) inline
Return the complex cylindrical Hankel function of the second kind of complex order and complex argument x.
See also
cyl_hankel_2 for more details.
Definition at line 2932 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::dawson (_Tp __x) inline
Definition at line 2291 of file specfun.h.
float __gnu_cxx::dawsonf (float __x) inline
Definition at line 2279 of file specfun.h.
long double __gnu_cxx::dawsonl (long double __x) inline
Definition at line 2283 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::digamma (_Tp __z) inline
Definition at line 1915 of file specfun.h.
float __gnu_cxx::digammaf (float __z) inline
Definition at line 1903 of file specfun.h.
long double __gnu_cxx::digammal (long double __z) inline
Definition at line 1907 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::dilog (_Tp __x) inline
Definition at line 1936 of file specfun.h.
float __gnu_cxx::dilogf (float __x) inline
Definition at line 1924 of file specfun.h.
long double __gnu_cxx::dilogl (long double __x) inline
Definition at line 1928 of file specfun.h.
template<typename _Tp > _Tp __gnu_cxx::dirichlet_beta (_Tp __x) inline
Return the Dirichlet beta function of real argument x.
The Dirichlet beta function is defined by
Parameters
__x
Definition at line 3167 of file specfun.h.
float __gnu_cxx::dirichlet_betaf (float __x) inline
Definition at line 3148 of file specfun.h.
long double __gnu_cxx::dirichlet_betal (long double __x) inline
Definition at line 3152 of file specfun.h.
template<typename _Tp > _Tp __gnu_cxx::dirichlet_eta (_Tp __x) inline
Return the Dirichlet eta function of real argument x.
The Dirichlet eta function is defined by
Parameters
__x
Definition at line 3139 of file specfun.h.
float __gnu_cxx::dirichlet_etaf (float __x) inline
Return the Dirichlet eta function of real argument x.
See also
dirichlet_eta for details.
Definition at line 3115 of file specfun.h.
long double __gnu_cxx::dirichlet_etal (long double __x) inline
Return the Dirichlet eta function of real argument x.
See also
dirichlet_eta for details.
Definition at line 3124 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::double_factorial (int __n) inline
Definition at line 2452 of file specfun.h.
float __gnu_cxx::double_factorialf (int __n) inline
Definition at line 2440 of file specfun.h.
long double __gnu_cxx::double_factoriall (int __n) inline
Definition at line 2444 of file specfun.h.
template<typename _Tk , typename _Tp , typename _Ta , typename _Tb > __gnu_cxx::__promote_num_t<_Tk, _Tp, _Ta, _Tb> __gnu_cxx::ellint_cel (_Tk __k_c, _Tp __p, _Ta __a, _Tb __b) inline
Return the Bulirsch complete elliptic integral of ...
The Bulirsch complete elliptic integral is defined by
Parameters
__k_c The
__p The
__a The
__b The
Definition at line 2865 of file specfun.h.
float __gnu_cxx::ellint_celf (float __k_c, float __p, float __a, float __b) inline
Definition at line 2842 of file specfun.h.
long double __gnu_cxx::ellint_cell (long double __k_c, long double __p, long double __a, long double __b) inline
Definition at line 2846 of file specfun.h.
template<typename _Tk , typename _Tphi > __gnu_cxx::__promote_num_t<_Tk, _Tphi> __gnu_cxx::ellint_d (_Tk __k, _Tphi __phi) inline
Return the Legendre elliptic integral D of k and .
The Legendre elliptic integral D is defined by
Parameters
__k The
__phi The
Definition at line 2742 of file specfun.h.
float __gnu_cxx::ellint_df (float __k, float __phi) inline
Definition at line 2722 of file specfun.h.
long double __gnu_cxx::ellint_dl (long double __k, long double __phi) inline
Definition at line 2726 of file specfun.h.
template<typename _Tp , typename _Tk > __gnu_cxx::__promote_num_t<_Tp, _Tk> __gnu_cxx::ellint_el1 (_Tp __x, _Tk __k_c) inline
Return the Bulirsch elliptic integral of the first kind of ...
The Bulirsch elliptic integral of the first kind is defined by
Parameters
__x The
__k_c The
Definition at line 2771 of file specfun.h.
float __gnu_cxx::ellint_el1f (float __x, float __k_c) inline
Definition at line 2751 of file specfun.h.
long double __gnu_cxx::ellint_el1l (long double __x, long double __k_c) inline
Definition at line 2755 of file specfun.h.
template<typename _Tp , typename _Tk , typename _Ta , typename _Tb > __gnu_cxx::__promote_num_t<_Tp, _Tk, _Ta, _Tb> __gnu_cxx::ellint_el2 (_Tp __x, _Tk __k_c, _Ta __a, _Tb __b) inline
Return the Bulirsch elliptic integral of the second kind of ...
The Bulirsch elliptic integral of the second kind is defined by
Parameters
__x The
__k_c The
__a The
__b The
Definition at line 2803 of file specfun.h.
float __gnu_cxx::ellint_el2f (float __x, float __k_c, float __a, float __b) inline
Definition at line 2780 of file specfun.h.
long double __gnu_cxx::ellint_el2l (long double __x, long double __k_c, long double __a, long double __b) inline
Definition at line 2784 of file specfun.h.
template<typename _Tx , typename _Tk , typename _Tp > __gnu_cxx::__promote_num_t<_Tx, _Tk, _Tp> __gnu_cxx::ellint_el3 (_Tx __x, _Tk __k_c, _Tp __p) inline
Return the Bulirsch elliptic integral of the third kind of ...
The Bulirsch elliptic integral of the third kind is defined by
Parameters
__x The
__k_c The
__p The
Definition at line 2833 of file specfun.h.
float __gnu_cxx::ellint_el3f (float __x, float __k_c, float __p) inline
Definition at line 2812 of file specfun.h.
long double __gnu_cxx::ellint_el3l (long double __x, long double __k_c, long double __p) inline
Definition at line 2816 of file specfun.h.
template<typename _Tp , typename _Up > __gnu_cxx::__promote_num_t<_Tp, _Up> __gnu_cxx::ellint_rc (_Tp __x, _Up __y) inline
Definition at line 1999 of file specfun.h.
float __gnu_cxx::ellint_rcf (float __x, float __y) inline
Definition at line 1987 of file specfun.h.
long double __gnu_cxx::ellint_rcl (long double __x, long double __y) inline
Definition at line 1991 of file specfun.h.
template<typename _Tp , typename _Up , typename _Vp > __gnu_cxx::__promote_num_t<_Tp, _Up, _Vp> __gnu_cxx::ellint_rd (_Tp __x, _Up __y, _Vp __z) inline
Definition at line 2041 of file specfun.h.
float __gnu_cxx::ellint_rdf (float __x, float __y, float __z) inline
Definition at line 2029 of file specfun.h.
long double __gnu_cxx::ellint_rdl (long double __x, long double __y, long double __z) inline
Definition at line 2033 of file specfun.h.
template<typename _Tp , typename _Up , typename _Vp > __gnu_cxx::__promote_num_t<_Tp, _Up, _Vp> __gnu_cxx::ellint_rf (_Tp __x, _Up __y, _Vp __z) inline
Definition at line 1978 of file specfun.h.
float __gnu_cxx::ellint_rff (float __x, float __y, float __z) inline
Definition at line 1966 of file specfun.h.
long double __gnu_cxx::ellint_rfl (long double __x, long double __y, long double __z) inline
Definition at line 1970 of file specfun.h.
template<typename _Tp , typename _Up , typename _Vp > __gnu_cxx::__promote_num_t<_Tp, _Up, _Vp> __gnu_cxx::ellint_rg (_Tp __x, _Up __y, _Vp __z) inline
Definition at line 2083 of file specfun.h.
float __gnu_cxx::ellint_rgf (float __x, float __y, float __z) inline
Definition at line 2071 of file specfun.h.
long double __gnu_cxx::ellint_rgl (long double __x, long double __y, long double __z) inline
Definition at line 2075 of file specfun.h.
template<typename _Tp , typename _Up , typename _Vp , typename _Wp > __gnu_cxx::__promote_num_t<_Tp, _Up, _Vp, _Wp> __gnu_cxx::ellint_rj (_Tp __x, _Up __y, _Vp __z, _Wp __p) inline
Definition at line 2020 of file specfun.h.
float __gnu_cxx::ellint_rjf (float __x, float __y, float __z, float __p) inline
Definition at line 2008 of file specfun.h.
long double __gnu_cxx::ellint_rjl (long double __x, long double __y, long double __z, long double __p) inline
Definition at line 2012 of file specfun.h.
template<typename _Tp > _Tp __gnu_cxx::ellnome (_Tp __k) inline
Return the elliptic nome function of thing k.
The elliptic nome function is defined by
Parameters
__k
Definition at line 3489 of file specfun.h.
float __gnu_cxx::ellnomef (float __k) inline
Definition at line 3470 of file specfun.h.
long double __gnu_cxx::ellnomel (long double __k) inline
Definition at line 3474 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::expint_e1 (_Tp __x) inline
Definition at line 2307 of file specfun.h.
float __gnu_cxx::expint_e1f (float __x) inline
Definition at line 2298 of file specfun.h.
long double __gnu_cxx::expint_e1l (long double __x) inline
Definition at line 2302 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::expint_en (unsigned int __n, _Tp __x) inline
Definition at line 2326 of file specfun.h.
float __gnu_cxx::expint_enf (unsigned int __n, float __x) inline
Definition at line 2314 of file specfun.h.
long double __gnu_cxx::expint_enl (unsigned int __n, long double __x) inline
Definition at line 2318 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::factorial (unsigned int __n) inline
Definition at line 2431 of file specfun.h.
float __gnu_cxx::factorialf (unsigned int __n) inline
Definition at line 2419 of file specfun.h.
long double __gnu_cxx::factoriall (unsigned int __n) inline
Definition at line 2423 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::fresnel_c (_Tp __x) inline
Return the Fresnel cosine integral of argument x.
The Fresnel cosine integral is defined by
Parameters
__x The argument
Definition at line 2270 of file specfun.h.
float __gnu_cxx::fresnel_cf (float __x) inline
Definition at line 2251 of file specfun.h.
long double __gnu_cxx::fresnel_cl (long double __x) inline
Definition at line 2255 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::fresnel_s (_Tp __x) inline
Return the Fresnel sine integral of argument x.
The Fresnel sine integral is defined by
Parameters
__x The argument
Definition at line 2242 of file specfun.h.
float __gnu_cxx::fresnel_sf (float __x) inline
Definition at line 2223 of file specfun.h.
long double __gnu_cxx::fresnel_sl (long double __x) inline
Definition at line 2227 of file specfun.h.
template<typename _Tn , typename _Tp > __gnu_cxx::__promote_num_t<_Tn, _Tp> __gnu_cxx::gamma_l (_Tn __n, _Tp __x) inline
Definition at line 1894 of file specfun.h.
float __gnu_cxx::gamma_lf (float __n, float __x) inline
Definition at line 1882 of file specfun.h.
long double __gnu_cxx::gamma_ll (long double __n, long double __x) inline
Definition at line 1886 of file specfun.h.
template<typename _Ta , typename _Tp > __gnu_cxx::__promote_num_t<_Ta, _Tp> __gnu_cxx::gamma_p (_Ta __a, _Tp __x) inline
Definition at line 2606 of file specfun.h.
float __gnu_cxx::gamma_pf (float __a, float __x) inline
Definition at line 2594 of file specfun.h.
long double __gnu_cxx::gamma_pl (long double __a, long double __x) inline
Definition at line 2598 of file specfun.h.
template<typename _Ta , typename _Tp > __gnu_cxx::__promote_num_t<_Ta, _Tp> __gnu_cxx::gamma_q (_Ta __a, _Tp __x) inline
Definition at line 2627 of file specfun.h.
float __gnu_cxx::gamma_qf (float __a, float __x) inline
Definition at line 2615 of file specfun.h.
long double __gnu_cxx::gamma_ql (long double __a, long double __x) inline
Definition at line 2619 of file specfun.h.
template<typename _Tn , typename _Tp > __gnu_cxx::__promote_num_t<_Tn, _Tp> __gnu_cxx::gamma_u (_Tn __n, _Tp __x) inline
Definition at line 1873 of file specfun.h.
float __gnu_cxx::gamma_uf (float __n, float __x) inline
Definition at line 1861 of file specfun.h.
long double __gnu_cxx::gamma_ul (long double __n, long double __x) inline
Definition at line 1865 of file specfun.h.
template<typename _Talpha , typename _Tp > __gnu_cxx::__promote_num_t<_Talpha, _Tp> __gnu_cxx::gegenbauer (unsigned int __n, _Talpha __alpha, _Tp __x) inline
Definition at line 1554 of file specfun.h.
float __gnu_cxx::gegenbauerf (unsigned int __n, float __alpha, float __x) inline
Definition at line 1542 of file specfun.h.
long double __gnu_cxx::gegenbauerl (unsigned int __n, long double __alpha, long double __x) inline
Definition at line 1546 of file specfun.h.
template<typename _Tk , typename _Tphi > __gnu_cxx::__promote_num_t<_Tk, _Tphi> __gnu_cxx::heuman_lambda (_Tk __k, _Tphi __phi) inline
Return the Heuman lambda function of k and .
The complete Heuman lambda function is defined by
Parameters
__k The
Definition at line 2684 of file specfun.h.
float __gnu_cxx::heuman_lambdaf (float __k, float __phi) inline
Definition at line 2665 of file specfun.h.
long double __gnu_cxx::heuman_lambdal (long double __k, long double __phi) inline
Definition at line 2669 of file specfun.h.
template<typename _Tp , typename _Up > __gnu_cxx::__promote_num_t<_Tp, _Up> __gnu_cxx::hurwitz_zeta (_Tp __s, _Up __a) inline
Return the Hurwitz zeta function of argument s, and parameter a.
The the Hurwitz zeta function is defined by
Parameters
__s The argument
__a The parameter
Definition at line 2112 of file specfun.h.
float __gnu_cxx::hurwitz_zetaf (float __s, float __a) inline
Definition at line 2092 of file specfun.h.
long double __gnu_cxx::hurwitz_zetal (long double __s, long double __a) inline
Definition at line 2096 of file specfun.h.
template<typename _Tpa , typename _Tpb , typename _Tpc , typename _Tp > __gnu_cxx::__promote_4<_Tpa, _Tpb, _Tpc, _Tp>::__type __gnu_cxx::hyperg (_Tpa __a, _Tpb __b, _Tpc __c, _Tp __x) inline
Return the hypergeometric function of numeratorial parameters a, and b, denominatorial parameter c, and argument x.
The hypergeometric function is defined by
Parameters
__a
__b
__c
__x
Definition at line 929 of file specfun.h.
float __gnu_cxx::hypergf (float __a, float __b, float __c, float __x) inline
Return the hypergeometric function of numeratorial parameters a, and b, denominatorial parameter c, and argument x.
See also
hyperg for details.
Definition at line 900 of file specfun.h.
long double __gnu_cxx::hypergl (long double __a, long double __b, long double __c, long double __x) inline
Return the hypergeometric function of numeratorial parameters a, and b, denominatorial parameter c, and argument x.
See also
hyperg for details.
Definition at line 910 of file specfun.h.
template<typename _Ta , typename _Tb , typename _Tp > __gnu_cxx::__promote_num_t<_Ta, _Tb, _Tp> __gnu_cxx::ibeta (_Ta __a, _Tb __b, _Tp __x) inline
Return the regularized incomplete beta function of parameters a, b, and argument x.
The regularized incomplete beta function is defined by
Parameters
__a The parameter
__b The parameter
__x The argument
Definition at line 2183 of file specfun.h.
template<typename _Ta , typename _Tb , typename _Tp > __gnu_cxx::__promote_num_t<_Ta, _Tb, _Tp> __gnu_cxx::ibetac (_Ta __a, _Tb __b, _Tp __x) inline
Return the regularized complementary incomplete beta function of parameters a, b, and argument x.
The regularized incomplete beta function is defined by
Parameters
__a The parameter
__b The parameter
__x The argument
Definition at line 2214 of file specfun.h.
float __gnu_cxx::ibetacf (float __a, float __b, float __x) inline
Definition at line 2192 of file specfun.h.
References ibetaf().
long double __gnu_cxx::ibetacl (long double __a, long double __b, long double __x) inline
Definition at line 2196 of file specfun.h.
References ibetal().
float __gnu_cxx::ibetaf (float __a, float __b, float __x) inline
Return the regularized incomplete beta function of parameters a, b, and argument x.
See ibeta for details.
Definition at line 2155 of file specfun.h.
Referenced by ibetacf().
long double __gnu_cxx::ibetal (long double __a, long double __b, long double __x) inline
Return the regularized incomplete beta function of parameters a, b, and argument x.
See ibeta for details.
Definition at line 2165 of file specfun.h.
Referenced by ibetacl().
template<typename _Talpha , typename _Tbeta , typename _Tp > __gnu_cxx::__promote_num_t<_Talpha, _Tbeta, _Tp> __gnu_cxx::jacobi (unsigned __n, _Talpha __alpha, _Tbeta __beta, _Tp __x) inline
Definition at line 1533 of file specfun.h.
References std::__detail::__beta().
template<typename _Kp , typename _Up > __gnu_cxx::__promote_num_t<_Kp, _Up> __gnu_cxx::jacobi_cn (_Kp __k, _Up __u) inline
Return the Jacobi elliptic cn integral of argument k and thing u.
The Jacobi elliptic cn integral is defined by
Parameters
__k
__u
Definition at line 1297 of file specfun.h.
float __gnu_cxx::jacobi_cnf (float __k, float __u) inline
Return the Jacobi elliptic cn integral of argument k and thing u.
See also
jacobi_cn for details.
Definition at line 1266 of file specfun.h.
long double __gnu_cxx::jacobi_cnl (long double __k, long double __u) inline
Return the Jacobi elliptic cn integral of argument k and thing u.
See also
jacobi_cn for details.
Definition at line 1278 of file specfun.h.
template<typename _Kp , typename _Up > __gnu_cxx::__promote_num_t<_Kp, _Up> __gnu_cxx::jacobi_dn (_Kp __k, _Up __u) inline
Return the Jacobi elliptic dn integral of argument k and thing u.
The Jacobi elliptic dn integral is defined by
Parameters
__k
__u
Definition at line 1343 of file specfun.h.
float __gnu_cxx::jacobi_dnf (float __k, float __u) inline
Return the Jacobi elliptic dn integral of argument k and thing u.
See also
jacobi_dn for details.
Definition at line 1312 of file specfun.h.
long double __gnu_cxx::jacobi_dnl (long double __k, long double __u) inline
Return the Jacobi elliptic dn integral of argument k and thing u.
See also
jacobi_dn for details.
Definition at line 1324 of file specfun.h.
template<typename _Kp , typename _Up > __gnu_cxx::__promote_num_t<_Kp, _Up> __gnu_cxx::jacobi_sn (_Kp __k, _Up __u) inline
Return the Jacobi elliptic sn integral of argument k and thing u.
The Jacobi elliptic sn integral is defined by
Parameters
__k
__u
Definition at line 1251 of file specfun.h.
float __gnu_cxx::jacobi_snf (float __k, float __u) inline
Return the Jacobi elliptic sn integral of argument k and thing u.
See also
jacobi_sn for details.
Definition at line 1220 of file specfun.h.
long double __gnu_cxx::jacobi_snl (long double __k, long double __u) inline
Return the Jacobi elliptic sn integral of argument k and thing u.
See also
jacobi_sn for details.
Definition at line 1232 of file specfun.h.
template<typename _Tk , typename _Tphi > __gnu_cxx::__promote_num_t<_Tk, _Tphi> __gnu_cxx::jacobi_zeta (_Tk __k, _Tphi __phi) inline
Return the Jacobi zeta function of k and .
The Jacobi zeta function is defined by
Parameters
__k The
__phi The
Definition at line 2656 of file specfun.h.
float __gnu_cxx::jacobi_zetaf (float __k, float __phi) inline
Definition at line 2636 of file specfun.h.
long double __gnu_cxx::jacobi_zetal (long double __k, long double __phi) inline
Definition at line 2640 of file specfun.h.
float __gnu_cxx::jacobif (unsigned __n, float __alpha, float __beta, float __x) inline
Definition at line 1521 of file specfun.h.
References std::__detail::__beta().
long double __gnu_cxx::jacobil (unsigned __n, long double __alpha, long double __beta, long double __x) inline
Definition at line 1525 of file specfun.h.
References std::__detail::__beta().
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::lbincoef (unsigned int __n, unsigned int __k) inline
Definition at line 2536 of file specfun.h.
float __gnu_cxx::lbincoeff (unsigned int __n, unsigned int __k) inline
Definition at line 2524 of file specfun.h.
long double __gnu_cxx::lbincoefl (unsigned int __n, unsigned int __k) inline
Definition at line 2528 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::ldouble_factorial (int __n) inline
Definition at line 2494 of file specfun.h.
float __gnu_cxx::ldouble_factorialf (int __n) inline
Definition at line 2482 of file specfun.h.
long double __gnu_cxx::ldouble_factoriall (int __n) inline
Definition at line 2486 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::legendre_q (unsigned int __n, _Tp __x) inline
Definition at line 2585 of file specfun.h.
float __gnu_cxx::legendre_qf (unsigned int __n, float __x) inline
Definition at line 2573 of file specfun.h.
long double __gnu_cxx::legendre_ql (unsigned int __n, long double __x) inline
Definition at line 2577 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::lfactorial (unsigned int __n) inline
Definition at line 2473 of file specfun.h.
float __gnu_cxx::lfactorialf (unsigned int __n) inline
Definition at line 2461 of file specfun.h.
long double __gnu_cxx::lfactoriall (unsigned int __n) inline
Definition at line 2465 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::logint (_Tp __x) inline
Return the logarithmic integral of argument x.
The logarithmic integral is defined by
Parameters
__x
Definition at line 1051 of file specfun.h.
float __gnu_cxx::logintf (float __x) inline
Return the logarithmic integral of argument x.
See also
logint for details.
Definition at line 1027 of file specfun.h.
long double __gnu_cxx::logintl (long double __x) inline
Return the logarithmic integral of argument x.
See also
logint for details.
Definition at line 1036 of file specfun.h.
template<typename _Tp , typename _Tn > __gnu_cxx::__promote_num_t<_Tp, _Tn> __gnu_cxx::lpochhammer_l (_Tp __a, _Tn __n) inline
Definition at line 2368 of file specfun.h.
float __gnu_cxx::lpochhammer_lf (float __a, float __n) inline
Definition at line 2356 of file specfun.h.
long double __gnu_cxx::lpochhammer_ll (long double __a, long double __n) inline
Definition at line 2360 of file specfun.h.
template<typename _Tp , typename _Tn > __gnu_cxx::__promote_num_t<_Tp, _Tn> __gnu_cxx::lpochhammer_u (_Tp __a, _Tn __n) inline
Definition at line 2347 of file specfun.h.
float __gnu_cxx::lpochhammer_uf (float __a, float __n) inline
Definition at line 2335 of file specfun.h.
long double __gnu_cxx::lpochhammer_ul (long double __a, long double __n) inline
Definition at line 2339 of file specfun.h.
template<typename _Tph , typename _Tpa > __gnu_cxx::__promote_num_t<_Tph, _Tpa> __gnu_cxx::owens_t (_Tph __h, _Tpa __a) inline
Return the Owens T function of thing1 h and thing2 a.
The Owens T function is defined by
Parameters
__h
__a
Definition at line 3684 of file specfun.h.
float __gnu_cxx::owens_tf (float __h, float __a) inline
Return the Owens T function function of thing h and argument a.
See also
owens_t for details.
Definition at line 3659 of file specfun.h.
long double __gnu_cxx::owens_tl (long double __h, long double __a) inline
Return the Owens T function function of thing h and argument a.
See also
owens_t for details.
Definition at line 3668 of file specfun.h.
template<typename _Tp , typename _Tn > __gnu_cxx::__promote_num_t<_Tp, _Tn> __gnu_cxx::pochhammer_l (_Tp __a, _Tn __n) inline
Definition at line 2410 of file specfun.h.
float __gnu_cxx::pochhammer_lf (float __a, float __n) inline
Definition at line 2398 of file specfun.h.
long double __gnu_cxx::pochhammer_ll (long double __a, long double __n) inline
Definition at line 2402 of file specfun.h.
template<typename _Tp , typename _Tn > __gnu_cxx::__promote_num_t<_Tp, _Tn> __gnu_cxx::pochhammer_u (_Tp __a, _Tn __n) inline
Definition at line 2389 of file specfun.h.
float __gnu_cxx::pochhammer_uf (float __a, float __n) inline
Definition at line 2377 of file specfun.h.
long double __gnu_cxx::pochhammer_ul (long double __a, long double __n) inline
Definition at line 2381 of file specfun.h.
template<typename _Tp > std::complex<__gnu_cxx::__promote_num_t<_Tp> > __gnu_cxx::polylog (_Tp __s, std::complex< _Tp > __w) inline
Return the complex polylogarithm function of real thing s and complex argument w.
The polylogarithm function is defined by
Parameters
__s
__w
Definition at line 3101 of file specfun.h.
std::complex<float> __gnu_cxx::polylogf (float __s, std::complex< float > __w) inline
Return the complex polylogarithm function of real thing s and complex argument w.
See also
polylog for details.
Definition at line 3074 of file specfun.h.
std::complex<long double> __gnu_cxx::polylogl (long double __s, std::complex< long double > __w) inline
Return the complex polylogarithm function of real thing s and complex argument w.
See also
polylog for details.
Definition at line 3084 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::psi (_Tp __x) inline
Return the psi or digamma function of argument x.
The the psi or digamma function is defined by
Parameters
__x The parameter
Definition at line 2140 of file specfun.h.
float __gnu_cxx::psif (float __x) inline
Definition at line 2121 of file specfun.h.
long double __gnu_cxx::psil (long double __x) inline
Definition at line 2125 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::radpoly (unsigned int __n, unsigned int __m, _Tp __rho) inline
Definition at line 1596 of file specfun.h.
float __gnu_cxx::radpolyf (unsigned int __n, unsigned int __m, float __rho) inline
Definition at line 1584 of file specfun.h.
References std::__detail::__poly_radial_jacobi().
long double __gnu_cxx::radpolyl (unsigned int __n, unsigned int __m, long double __rho) inline
Definition at line 1588 of file specfun.h.
References std::__detail::__poly_radial_jacobi().
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::sinc (_Tp __x) inline
Definition at line 1013 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::sinc_pi (_Tp __x) inline
Definition at line 995 of file specfun.h.
float __gnu_cxx::sinc_pif (float __x) inline
Definition at line 983 of file specfun.h.
long double __gnu_cxx::sinc_pil (long double __x) inline
Definition at line 987 of file specfun.h.
float __gnu_cxx::sincf (float __x) inline
Definition at line 1004 of file specfun.h.
long double __gnu_cxx::sincl (long double __x) inline
Definition at line 1008 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::sinhc (_Tp __x) inline
Definition at line 1638 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::sinhc_pi (_Tp __x) inline
Definition at line 1617 of file specfun.h.
float __gnu_cxx::sinhc_pif (float __x) inline
Definition at line 1605 of file specfun.h.
long double __gnu_cxx::sinhc_pil (long double __x) inline
Definition at line 1609 of file specfun.h.
float __gnu_cxx::sinhcf (float __x) inline
Definition at line 1626 of file specfun.h.
long double __gnu_cxx::sinhcl (long double __x) inline
Definition at line 1630 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::sinhint (_Tp __x) inline
Return the hyperbolic sine integral of argument x.
The sine hyperbolic integral is defined by
Parameters
__x
Definition at line 1165 of file specfun.h.
float __gnu_cxx::sinhintf (float __x) inline
Return the hyperbolic sine integral of argument x.
See also
sinhint for details.
Definition at line 1141 of file specfun.h.
long double __gnu_cxx::sinhintl (long double __x) inline
Return the hyperbolic sine integral of argument x.
See also
sinhint for details.
Definition at line 1150 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::sinint (_Tp __x) inline
Return the sine integral of argument x.
The sine integral is defined by
Parameters
__x
Definition at line 1089 of file specfun.h.
float __gnu_cxx::sinintf (float __x) inline
Return the sine integral of argument x.
See also
sinint for details.
Definition at line 1065 of file specfun.h.
long double __gnu_cxx::sinintl (long double __x) inline
Return the sine integral of argument x.
See also
sinint for details.
Definition at line 1074 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::sph_bessel_i (unsigned int __n, _Tp __x) inline
Definition at line 1753 of file specfun.h.
float __gnu_cxx::sph_bessel_if (unsigned int __n, float __x) inline
Definition at line 1731 of file specfun.h.
long double __gnu_cxx::sph_bessel_il (unsigned int __n, long double __x) inline
Definition at line 1740 of file specfun.h.
template<typename _Tp > __gnu_cxx::__promote_num_t<_Tp> __gnu_cxx::sph_bessel_k (unsigned int __n, _Tp __x) inline
Definition at line 1787 of file specfun.h.
float __gnu_cxx::sph_bessel_kf (unsigned int __n, float __x) inline
Definition at line 1765 of file specfun.h.
long double __gnu_cxx::sph_bessel_kl (unsigned int __n, long double __x) inline
Definition at line 1774 of file specfun.h.
template<typename _Tp > std::complex<__gnu_cxx::__promote_num_t<_Tp> > __gnu_cxx::sph_hankel_1 (unsigned int __n, _Tp __z) inline
Definition at line 1701 of file specfun.h.
template<typename _Tp > std::complex<__gnu_cxx::__promote_num_t<_Tp> > __gnu_cxx::sph_hankel_1 (unsigned int __n, std::complex< _Tp > __x) inline
Return the complex spherical Hankel function of the first kind of non-negative order n and complex argument x.
The spherical Hankel function of the first kind is defined by
Parameters
__n The integral order >= 0
__x The complex argument
Definition at line 2979 of file specfun.h.
std::complex<float> __gnu_cxx::sph_hankel_1f (unsigned int __n, float __z) inline
Definition at line 1689 of file specfun.h.
std::complex<float> __gnu_cxx::sph_hankel_1f (unsigned int __n, std::complex< float > __x) inline
Definition at line 2958 of file specfun.h.
std::complex<long double> __gnu_cxx::sph_hankel_1l (unsigned int __n, long double __z) inline
Definition at line 1693 of file specfun.h.
std::complex<long double> __gnu_cxx::sph_hankel_1l (unsigned int __n, std::complex< long double > __x) inline
Definition at line 2962 of file specfun.h.
template<typename _Tp > std::complex<__gnu_cxx::__promote_num_t<_Tp> > __gnu_cxx::sph_hankel_2 (unsigned int __n, _Tp __z) inline
Definition at line 1722 of file specfun.h.
template<typename _Tp > std::complex<__gnu_cxx::__promote_num_t<_Tp> > __gnu_cxx::sph_hankel_2 (unsigned int __n, std::complex< _Tp > __x) inline
Return the complex spherical Hankel function of the second kind of non-negative order n and complex argument x.
The spherical Hankel function of the second kind is defined by
Parameters
__n The integral order >= 0
__x The complex argument
Definition at line 3009 of file specfun.h.
std::complex<float> __gnu_cxx::sph_hankel_2f (unsigned int __n, float __z) inline
Definition at line 1710 of file specfun.h.
std::complex<float> __gnu_cxx::sph_hankel_2f (unsigned int __n, std::complex< float > __x) inline
Definition at line 2988 of file specfun.h.
std::complex<long double> __gnu_cxx::sph_hankel_2l (unsigned int __n, long double __z) inline
Definition at line 1714 of file specfun.h.
std::complex<long double> __gnu_cxx::sph_hankel_2l (unsigned int __n, std::complex< long double > __x) inline
Definition at line 2992 of file specfun.h.
template<typename _Ttheta , typename _Tphi > std::complex<__gnu_cxx::__promote_num_t<_Ttheta, _Tphi> > __gnu_cxx::sph_harmonic (unsigned int __l, int __m, _Ttheta __theta, _Tphi __phi) inline
Return the complex spherical harmonic function of degree l, order m, and real zenith angle , and real azimuth angle .
The spherical harmonic function is defined by:
Parameters
__l The order
__m The degree
__theta The zenith angle in radians
__theta The zenith angle in radians
Definition at line 3059 of file specfun.h.
std::complex<float> __gnu_cxx::sph_harmonicf (unsigned int __l, int __m, float __theta, float __phi) inline
Return the complex spherical harmonic function of degree l, order m, and real zenith angle , and real azimuth angle .
See also
sph_harmonic for details.
Definition at line 3024 of file specfun.h.
std::complex<long double> __gnu_cxx::sph_harmonicl (unsigned int __l, int __m, long double __theta, long double __phi) inline
Return the complex spherical harmonic function of degree l, order m, and real zenith angle , and real azimuth angle .
See also
sph_harmonic for details.
Definition at line 3035 of file specfun.h.
template<typename _Tpnu , typename _Tp > __gnu_cxx::__promote_num_t<_Tpnu, _Tp> __gnu_cxx::theta_1 (_Tpnu __nu, _Tp __x) inline
Return the exponential theta-1 function of thing nu and argument x.
The Neville theta-1 function is defined by
Parameters
__nu
__x The argument
Definition at line 3344 of file specfun.h.
float __gnu_cxx::theta_1f (float __nu, float __x) inline
Return the exponential theta-1 function of thing nu and argument x.
See also
theta_1 for details.
Definition at line 3319 of file specfun.h.
long double __gnu_cxx::theta_1l (long double __nu, long double __x) inline
Return the exponential theta-1 function of thing nu and argument x.
See also
theta_1 for details.
Definition at line 3328 of file specfun.h.
template<typename _Tpnu , typename _Tp > __gnu_cxx::__promote_num_t<_Tpnu, _Tp> __gnu_cxx::theta_2 (_Tpnu __nu, _Tp __x) inline
Return the exponential theta-2 function of thing nu and argument x.
The Neville theta-2 function is defined by
Parameters
__nu
__x The argument
Definition at line 3383 of file specfun.h.
float __gnu_cxx::theta_2f (float __nu, float __x) inline
Return the exponential theta-2 function of thing nu and argument x.
See also
theta_2 for details.
Definition at line 3358 of file specfun.h.
long double __gnu_cxx::theta_2l (long double __nu, long double __x) inline
Return the exponential theta-2 function of thing nu and argument x.
See also
theta_2 for details.
Definition at line 3367 of file specfun.h.
template<typename _Tpnu , typename _Tp > __gnu_cxx::__promote_num_t<_Tpnu, _Tp> __gnu_cxx::theta_3 (_Tpnu __nu, _Tp __x) inline
Return the exponential theta-3 function of thing nu and argument x.
The Neville theta-3 function is defined by
Parameters
__nu
__x The argument
Definition at line 3422 of file specfun.h.
float __gnu_cxx::theta_3f (float __nu, float __x) inline
Return the exponential theta-3 function of thing nu and argument x.
See also
theta_3 for details.
Definition at line 3397 of file specfun.h.
long double __gnu_cxx::theta_3l (long double __nu, long double __x) inline
Return the exponential theta-3 function of thing nu and argument x.
See also
theta_3 for details.
Definition at line 3406 of file specfun.h.
template<typename _Tpnu , typename _Tp > __gnu_cxx::__promote_num_t<_Tpnu, _Tp> __gnu_cxx::theta_4 (_Tpnu __nu, _Tp __x) inline
Return the exponential theta-4 function of thing nu and argument x.
The Neville theta-4 function is defined by
Parameters
__nu
__x The argument
Definition at line 3461 of file specfun.h.
float __gnu_cxx::theta_4f (float __nu, float __x) inline
Return the exponential theta-4 function of thing nu and argument x.
See also
theta_4 for details.
Definition at line 3436 of file specfun.h.
long double __gnu_cxx::theta_4l (long double __nu, long double __x) inline
Return the exponential theta-4 function of thing nu and argument x.
See also
theta_4 for details.
Definition at line 3445 of file specfun.h.
template<typename _Tpk , typename _Tp > __gnu_cxx::__promote_num_t<_Tpk, _Tp> __gnu_cxx::theta_c (_Tpk __k, _Tp __x) inline
Return the Neville theta-c function of thing k and argument x.
The Neville theta-c function is defined by
Parameters
__k
__x The argument
Definition at line 3567 of file specfun.h.
float __gnu_cxx::theta_cf (float __k, float __x) inline
Return the exponential theta-c function of thing nu and argument x.
See also
theta_c for details.
Definition at line 3542 of file specfun.h.
long double __gnu_cxx::theta_cl (long double __k, long double __x) inline
Return the exponential theta-c function of thing nu and argument x.
See also
theta_c for details.
Definition at line 3551 of file specfun.h.
template<typename _Tpk , typename _Tp > __gnu_cxx::__promote_num_t<_Tpk, _Tp> __gnu_cxx::theta_d (_Tpk __k, _Tp __x) inline
Return the Neville theta-d function of thing k and argument x.
The Neville theta-d function is defined by
Parameters
__k
__x The argument
Definition at line 3606 of file specfun.h.
float __gnu_cxx::theta_df (float __k, float __x) inline
Return the exponential theta-d function of thing nu and argument x.
See also
theta_d for details.
Definition at line 3581 of file specfun.h.
long double __gnu_cxx::theta_dl (long double __k, long double __x) inline
Return the exponential theta-d function of thing nu and argument x.
See also
theta_d for details.
Definition at line 3590 of file specfun.h.
template<typename _Tpk , typename _Tp > __gnu_cxx::__promote_num_t<_Tpk, _Tp> __gnu_cxx::theta_n (_Tpk __k, _Tp __x) inline
Return the Neville theta-n function of thing k and argument x.
The Neville theta-n function is defined by
Parameters
__k
__x The argument
Definition at line 3645 of file specfun.h.
float __gnu_cxx::theta_nf (float __k, float __x) inline
Return the exponential theta-n function of thing nu and argument x.
See also
theta_n for details.
Definition at line 3620 of file specfun.h.
long double __gnu_cxx::theta_nl (long double __k, long double __x) inline
Return the exponential theta-n function of thing nu and argument x.
See also
theta_n for details.
Definition at line 3629 of file specfun.h.
template<typename _Tpk , typename _Tp > __gnu_cxx::__promote_num_t<_Tpk, _Tp> __gnu_cxx::theta_s (_Tpk __k, _Tp __x) inline
Return the Neville theta-s function of thing k and argument x.
The Neville theta-s function is defined by
Parameters
__k
__x The argument
Definition at line 3528 of file specfun.h.
float __gnu_cxx::theta_sf (float __k, float __x) inline
Return the exponential theta-s function of thing nu and argument x.
See also
theta_s for details.
Definition at line 3503 of file specfun.h.
long double __gnu_cxx::theta_sl (long double __k, long double __x) inline
Return the exponential theta-s function of thing nu and argument x.
See also
theta_s for details.
Definition at line 3512 of file specfun.h.
template<typename _Trho , typename _Tphi > __gnu_cxx::__promote_num_t<_Trho, _Tphi> __gnu_cxx::zernike (unsigned int __n, int __m, _Trho __rho, _Tphi __phi) inline
Definition at line 1575 of file specfun.h.
float __gnu_cxx::zernikef (unsigned int __n, int __m, float __rho, float __phi) inline
Definition at line 1563 of file specfun.h.
long double __gnu_cxx::zernikel (unsigned int __n, int __m, long double __rho, long double __phi) inline
Definition at line 1567 of file specfun.h.