//  Compare against values generated by the GNU Scientific Library.
//  The GSL can be found on the web: http://www.gnu.org/software/gsl/
#include <limits>
#include <emsr/special_functions.h>

#include <iostream>
#define VERIFY(A) \
  if (!(A)) \
    { \
      ++num_errors; \
      std::cout << "ERROR: line " << __LINE__ \
	<< "  max_abs_frac = " << max_abs_frac \
	<< '\n'; \
    }

#include <specfun_testcase.h>
