CC = g++
CFLAGS = -pedantic -Wall 
all: res1 res2 res3 res4 res5 res6 res7 res8 res9 res10
res1: driver1.o Bernstein.o
	$(CC) $(CFLAGS) driver1.o Bernstein.o -lm
	a.out > res1
res2: driver2.o Bernstein.o
	$(CC) $(CFLAGS) driver2.o Bernstein.o -lm
	a.out > res2
res3: driver3.o Bernstein.o
	$(CC) $(CFLAGS) driver3.o Bernstein.o -lm
	a.out > res3
res4: driver4.o Bernstein.o
	$(CC) $(CFLAGS) driver4.o Bernstein.o -lm
	a.out > res4
res5: driver5.o Bernstein.o
	$(CC) $(CFLAGS) driver5.o Bernstein.o -lm
	a.out > res5
res6: driver6.o Bernstein.o
	$(CC) $(CFLAGS) driver6.o Bernstein.o -lm
	a.out > res6
res7: driver7.o Bernstein.o
	$(CC) $(CFLAGS) driver7.o Bernstein.o -lm
	a.out > res7
res8: driver8.o Bernstein.o
	$(CC) $(CFLAGS) driver8.o Bernstein.o -lm
	a.out > res8
res9: driver9.o Bernstein.o
	$(CC) $(CFLAGS) driver9.o Bernstein.o -lm
	a.out > res9
res10: driver10.o Bernstein.o
	$(CC) $(CFLAGS) driver10.o Bernstein.o -lm
	a.out > res10
